var ExplicitModjson= [

{"en":/Adds (\d+) to (\d+) Cold Damage to Attacks/g,"cn":"附加 # - # 冰冷伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Fire Damage to Attacks/g,"cn":"附加 # - # 火焰伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Lightning Damage to Attacks/g,"cn":"附加 # - # 闪电伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Physical Damage to Attacks/g,"cn":"附加 # - # 物理伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Chaos Damage to Attacks/g,"cn":"附加 # - # 混沌伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Cold Damage to Spells/g,"cn":"附加 # - # 冰冷伤害到法术"},
{"en":/Adds (\d+) to (\d+) Fire Damage to Spells/g,"cn":"附加 # - # 火焰伤害到法术"},
{"en":/Adds (\d+) to (\d+) Lightning Damage to Spells/g,"cn":"附加 # - # 闪电伤害到法术"},
{"en":/Adds (\d+) to (\d+) Cold Damage/g,"cn":"附加 # - # 冰冷伤害"},
{"en":/Adds (\d+) to (\d+) Fire Damage/g,"cn":"附加 # - # 火焰伤害"},
{"en":/Adds (\d+) to (\d+) Lightning Damage/g,"cn":"附加 # - # 闪电伤害"},
{"en":/Adds (\d+) to (\d+) Physical Damage/g,"cn":"附加 # - # 物理伤害"},

{"en":/(\d+)% increased Armour and Energy Shield/g,"cn":"增加 #% 护甲和能量护盾"},
{"en":/(\d+)% increased Armour and Evasion/g,"cn":"增加 #% 护甲和闪避"},
{"en":/(\d+)% increased Evasion and Energy Shield/g,"cn":"增加 #% 闪避和能量护盾"},
{"en":/(\d+)% increased Armour, Evasion and Energy Shield/g,"cn":"增加 #% 护甲，闪避和能量护盾"},
{"en":/Item drops on Death if equipped by an Animated Guardian/g,"cn":"本物品在幻化守卫死亡后掉落"},
{"en":/to maximum number of Skeletons/g,"cn":"最大幽魂数量"},
{"en":/(\d+)% increased Ignite Duration on Enemies/g,"cn":"增加 #% 敌人身上的点燃持续时间"},
{"en":/(\d+)% increased Freeze Duration on Enemies/g,"cn":"增加 #% 敌人身上的冰冻持续时间"},
{"en":/(\d+)% increased Shock Duration on Enemies/g,"cn":"增加 #% 敌人身上的感电持续时间"},

{"en":/(\d+) to Level of Socketed Gems/g,"cn":"# 此物品上宝石等级"},
{"en":/(\d+) to Level of Socketed Melee Gems/g,"cn":"# 此物品上近战宝石等级"},
{"en":/(\d+) to Level of Socketed Bow Gems/g,"cn":"# 此物品上弓宝石等级"},
{"en":/(\d+) to Level of Socketed Chaos Gems/g,"cn":"# 此物品上混沌宝石等级"},
{"en":/(\d+) to Level of Socketed Cold Gems/g,"cn":"# 此物品上冰冷等级"},
{"en":/(\d+) to Level of Socketed Fire Gems/g,"cn":"# 此物品上火焰等级"},
{"en":/(\d+) to Level of Socketed Lightning Gems/g,"cn":"# 此物品上闪电等级"},
{"en":/(\d+)% increased Elemental Damage with Weapons/g,"cn":"增加 #% 武器元素伤害"},
{"en":/(\d+)% increased Elemental Damage/g,"cn":"增加 #% 元素伤害"},
{"en":/(\d+)% of Physical Attack Damage Leeched as Life/g,"cn":"#% 物理攻击伤害偷取生命"},
{"en":/(\d+)% increased Physical Damage/g,"cn":"增加 #% 物理伤害"},
{"en":/(\d+)% of Physical Attack Damage Leeched as Mana/g,"cn":"#% 物理攻击伤害偷取魔力"},
{"en":/(\d+)% increased Spell Damage/g,"cn":"增加 #% 法术伤害"},
{"en":/(\d+) to maximum Mana/g,"cn":"# 最大魔力"},
{"en":/(\d+)% to Chaos Resistance/g,"cn":"#% 混沌抗性"},
{"en":/(\d+)% to Cold Resistance/g,"cn":"#% 冰冷抗性"},
{"en":/(\d+)% to Fire Resistance/g,"cn":"#% 火焰抗性"},
{"en":/(\d+)% to Lightning Resistance/g,"cn":"#% 闪电抗性"},
{"en":/(\d+)% increased Critical Strike Chance for Spells/g,"cn":"增加 #% 法术暴击率"},
{"en":/(\d+)% increased Critical Strike Chance/g,"cn":"增加 #% 暴击率"},
{"en":/to Global Critical Strike Multiplier/g,"cn":"全域暴击加成"},
{"en":/(\d+) to Accuracy Rating/g,"cn":"# 命中"},
{"en":/(\d+)% increased Attack Speed/g,"cn":"增加 #% 攻击速度"},
{"en":/(\d+) Life gained for each Enemy hit by Attacks/g,"cn":"# 攻击击中回复生命"},
{"en":/(\d+) Life gained on Kill/g,"cn":"# 击杀回复生命"},
{"en":/(\d+)% reduced Attribute Requirements/g,"cn":"减少 #% 能力需求"},
{"en":/(\d+) Mana gained on Kill/g,"cn":"# 击杀回复魔力"},
{"en":/(\d+) to Strength/g,"cn":"# 力量"},
{"en":/(\d+) to Intelligence/g,"cn":"# 智慧"},
{"en":/(\d+) to Dexterity/g,"cn":"# 敏捷"},
{"en":/(\d+)% increased Projectile Speed/g,"cn":"增加 #% 投射物速度"},
{"en":/(\d+)% increased Stun Duration on Enemies/g,"cn":"增加 #% 眩晕持续时间"},
{"en":/(\d+)% reduced Enemy Stun Threshold/g,"cn":"减少 #% 眩晕门槛"},
{"en":/Reflects (\d+) Physical Damage to Melee Attackers/g,"cn":"反射 # 点物理伤害给近战攻击者"},
{"en":/(\d+)% increased Armour/g,"cn":"增加 #% 护甲"},
{"en":/(\d+) to Armour/g,"cn":"# 护甲"},
{"en":/(\d+)% increased Evasion Rating/g,"cn":"增加 #% 闪避"},
{"en":/(\d+) to Evasion Rating/g,"cn":"# 闪避"},
{"en":/(\d+)% increased Energy Shield/g,"cn":"增加 #% 能量护盾"},
{"en":/(\d+)% increased maximum Energy Shield/gi,"cn":"增加 #% 最大能量护盾"},
{"en":/(\d+)% increased Stun and Block Recovery/gi,"cn":"增加 #% 格挡和晕眩回复"},
{"en":/(\d+) to maximum Energy Shield/gi,"cn":"# 最大能量护盾"},
{"en":/(\d+) to maximum Life/g,"cn":"# 最大生命"},
{"en":/(\d+) to maximum Mana/gi,"cn":"# 最大魔力"},
{"en":/(\d+) Life Regenerated per second/g,"cn":"# 每秒生命回复"},
{"en":/to all Attributes/g,"cn":"全能力"},
{"en":/to all Elemental Resistances/g,"cn":"全部元素抗性"},
{"en":/(\d+)% increased Cast Speed/g,"cn":"增加 #% 施放速度"},
{"en":/(\d+)% increased Cold Damage/g,"cn":"增加 #% 冰冷伤害"},
{"en":/(\d+)% increased Fire Damage/g,"cn":"增加 #% 火焰伤害"},
{"en":/(\d+)% increased Lightning Damage/g,"cn":"增加 #% 闪电伤害"},
{"en":/(\d+)% increased Chaos Damage/g,"cn":"增加 #% 混沌伤害"},
{"en":/(\d+)% increased Rarity of Items found/g,"cn":"增加 #% 物品稀有度"},
{"en":/Chance to Block/g,"cn":"格挡率"},
{"en":/(\d+)% increased Mana Regeneration Rate/g,"cn":"增加 #% 每秒魔力回复"},
{"en":/to Fire and Cold Resistances/g,"cn":"火焰和冰冷抗性"},
{"en":/to Cold and Lightning Resistances/g,"cn":"冰冷和闪电抗性"},
{"en":/to Fire and Lightning Resistances/g,"cn":"火焰和闪电抗性"},
{"en":/(\d+)% increased Global Critical Strike Chance/g,"cn":"增加 #% 全域暴击几率"},
{"en":/(\d+)% increased Flask Life Recovery rate/g,"cn":"增加 #% 药剂生命回复速度"},
{"en":/(\d+)% increased Flask Mana Recovery rate/g,"cn":"增加 #% 药剂魔力回复速度"},
{"en":/(\d+)% increased Movement Speed/g,"cn":"增加 #% 移动速度"},
{"en":/(\d+)% chance for Flasks to gain Charges when you take a Critical Strike/g,"cn":"当你收到暴击时有 #% 几率获得药剂充能"},
{"en":/(\d+)% increased Flask Charges gained/g,"cn":"增加 #% 药剂充能获取"},
{"en":/(\d+)% reduced Flask Charges used/g,"cn":"减少 #% 药剂充能消耗"},
{"en":/(\d+)% increased Flask effect duration/g,"cn":"增加 #% 药剂持续时间"},
{"en":/(\d+)% increased Trap Damage/g,"cn":"增加 #% 陷阱伤害"},
{"en":/(\d+)% increased Mine Damage/g,"cn":"增加 #% 地雷伤害"},
{"en":/(\d+)% increased Trap Throwing Speed/g,"cn":"增加 #% 陷阱投掷速度"},
{"en":/(\d+)% increased Mine Laying Speed/g,"cn":"增加 #% 地雷放置速度"},


{"en":/增加 (\d+)% 元素伤害 with Weapons/gi,"cn":"增加 #% 武器元素伤害"}
];