var ExplicitModjson= [

{"en":/to Quality of Socketed Support Gems/gi,"cn":"装备上辅助宝石品质"},
{"en":/to Mana Cost of Skills/gi,"cn":"技能施放消耗"},
{"en":/to Level of Socketed Support Gems/gi,"cn":"装备上辅助宝石等级"},
{"en":/Causes Bleeding on Hit/gi,"cn":"击中时造成流血效果"},
{"en":/Hits can't be Evaded/gi,"cn":"攻击无法被闪避"},
{"en":/Your Hits inflict Decay, dealing (\d+) Chaos Damage per second for 10 seconds/gi,"cn":"击中时造成10秒内 # 混沌伤害的持续伤害"},
{"en":/Socketed Gems deal (\d+)% more Damage over Time/gi,"cn":"该物品上宝石造成 #% 更多持续伤害"},
{"en":/Cannot be Poisoned/gi,"cn":"不会中毒"},
{"en":/(\d+)% reduced Chaos Damage taken over time/gi,"cn":"减少 #% 受到的持续性混沌伤害"},
{"en":/to Level of Socketed Aura Gems/gi,"cn":"此物品上光环宝石等级"},
{"en":/Recover (\d+)% of your maximum Mana when you Block/gi,"cn":"格挡时回复 #% 魔力"},
{"en":/(\d+)% increased Damage with Poison/gi,"cn":"增加 #% 中毒伤害"},
{"en":/of Chaos Damage Leeched as Life/gi,"cn":"混沌伤害偷取生命"},
{"en":/to Chaos Resistance while using a Flask/gi,"cn":"混沌抗性在药剂作用期间"},
{"en":/(\d+)% chance to gain a Power, Frenzy or Endurance Charge on Kill/gi,"cn":"击杀时有 #%机率获得随机一个充能球"},
{"en":/Socketed Gems have +3% Critical Strike Chance/gi,"cn":"该物品上宝石 +3% 基础暴击率"},
{"en":/Socketed Gems have +3.5% Critical Strike Chance/gi,"cn":"该物品上宝石 +3.5% 基础暴击率"},
{"en":/(\d+)% reduced elemental Damage Taken while not moving/gi,"cn":"静止时减少 #% 所受的元素伤害"},
{"en":/(\d+)% of Physical Damage taken as Cold Damage/gi,"cn":"#% 承受的物理伤害转化为冰冷伤害"},
{"en":/Socketed Gems deal (\d+)% more Elemental Damage/gi,"cn":"该物品上宝石造成 #% 更多元素伤害"},
{"en":/Chill nearby Enemies for (\d+) second on Block/gi,"cn":"格挡时冰缓周围敌人 # 秒"},
{"en":/Adds (\d+) to (\d+) Cold Damage per Frenzy Charge/gi,"cn":"每个狂怒球附加 # to # 冰冷伤害"},
{"en":/(\d+)% increased effect of Fortify on You/gi,"cn":"增加 #% 你身上护体效果"},
{"en":/(\d+)% additional Physical Damage Reduction while using a Flask/gi,"cn":"药剂作用期间获得 #% 额外物理伤害减免"},
{"en":/(\d+)% chance to Cast Level (\d+) Fire Burst on Hit/gi,"cn":"击中时有 #%机率施展 # 级【火焰爆破】"},
{"en":/Socketed Gems deal (\d+) to (\d+) additional Fire Damage/gi,"cn":"该物品上宝石造成额外 # to # 火焰伤害"},
{"en":/Drops Burning Ground while moving, dealing (\d+) Fire Damage per second/gi,"cn":"移动时产生火焰地面，造成 # 每秒火焰伤害"},
{"en":/(\d+)% increased Radius of Area Skills/gi,"cn":"增加 #% 范围技能的半径"},
{"en":/Socketed Gems have (\d+)% chance to Ignite/gi,"cn":"该物品上宝石有 #% 机率点燃"},
{"en":/Adds (\d+) to (\d+) Fire Damage if you've Blocked Recently/gi,"cn":"格挡后短时间内附加 # to # 火焰伤害"},
{"en":/Gain (\d+)% of Physical Damage as Extra Fire Damage/gi,"cn":"获得 #% 物理伤害的额外火焰伤害"},
{"en":/(\d+)% increased Life Leeched per second/gi,"cn":"增加 #% 每秒生命偷取"},
{"en":/(\d+)% of Physical Damage as Extra Fire Damage/gi,"cn":"获得 #% 物理伤害的额外火焰伤害"},
{"en":/Damage Penetrates (\d+)% Elemental Resistances while using a Flask/gi,"cn":"药剂作用期间伤害穿透 #% 元素抗性"},
{"en":/Casts level (\d+) Spectral Spirits when equipped/gi,"cn":"装备时施放等级 # 的【幽魂之灵】"},
{"en":/Socketed Gems have (\d+)% more Attack and Cast Speed/gi,"cn":"该物品上宝石增加 #% 更多攻击与施放速度"},
{"en":/(\d+)% increased Movement speed while on Burning, Chilled or Shocked ground/gi,"cn":"站在燃烧、冰缓、感电地面时增加 #% 移动速度"},
{"en":/Gain Onslaught for (\d+) seconds when Hit/gi,"cn":"被击中时获得 #秒 猛攻"},
{"en":/Socketed Gems gain (\d+)% of Physical Damage as extra Lightning Damage/gi,"cn":"该物品上宝石获得 #% 物理伤害的额外闪电伤害"},
{"en":/(\d+)% chance to gain a Power Charge on Block/gi,"cn":"格挡时有 #% 机率获得暴击球"},
{"en":/(\d+)% reduced Reflected Damage taken/gi,"cn":"减少 #% 受到的反射伤害"},
{"en":/(\d+)% chance to Recover (\d+)% of Maximum Mana when you use a Skill/gi,"cn":"使用技能时有 #% 机率回复 #% 最大魔力"},
{"en":/(\d+)% increased Movement Speed while using a Flask/gi,"cn":"药剂作用期间增加 #% 移动速度"},
{"en":/chance to Avoid being Ignited/gi,"cn":"机率避免被点燃"},
{"en":/chance to Avoid Fire Damage when Hit/gi,"cn":"机率被击中时避免火焰伤害"},
{"en":/to Weapon range/gi,"cn":"武器攻击半径"},
{"en":/Minions have (\d+)% increased Movement Speed/gi,"cn":"召唤物增加 #% 移动速度"},
{"en":/(\d+)% reduced Mana Reserved/gi,"cn":"减少 #% 魔力保留"},
{"en":/chance to Avoid Cold Damage when Hit/gi,"cn":"机率被击中时避免冰冷伤害"},
{"en":/chance to Avoid being Frozen/gi,"cn":"机率避免被冰冻"},
{"en":/chance to Avoid Lightning Damage when Hit/gi,"cn":"机率被击中时避免闪电伤害"},
{"en":/chance to Avoid being Shocked/gi,"cn":"机率避免被感电"},
{"en":/Adds (\d+) to (\d+) Cold Damage to your Attacks/g,"cn":"附加 # - # 冰冷伤害到你的攻击"},
{"en":/Adds (\d+) to (\d+) Fire Damage to your Attacks/g,"cn":"附加 # - # 火焰伤害到你的攻击"},
{"en":/Adds (\d+) to (\d+) Lightning Damage to your Attacks/g,"cn":"附加 # - # 闪电伤害到你的攻击"},
{"en":/Adds (\d+) to (\d+) Physical Damage to your Attacks/g,"cn":"附加 # - # 物理伤害到你的攻击"},
{"en":/Adds (\d+) to (\d+) Chaos Damage to your Attacks/g,"cn":"附加 # - # 混沌伤害到你的攻击"},
{"en":/Adds (\d+) to (\d+) Cold Damage to Attacks/g,"cn":"附加 # - # 冰冷伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Fire Damage to Attacks/g,"cn":"附加 # - # 火焰伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Lightning Damage to Attacks/g,"cn":"附加 # - # 闪电伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Physical Damage to Attacks/g,"cn":"附加 # - # 物理伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Chaos Damage to Attacks/g,"cn":"附加 # - # 混沌伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Cold Damage to your Spells/gi,"cn":"附加 # - # 冰冷伤害到你的法术"},
{"en":/Adds (\d+) to (\d+) Fire Damage to your Spells/gi,"cn":"附加 # - # 火焰伤害到你的法术"},
{"en":/Adds (\d+) to (\d+) Lightning Damage to your Spells/gi,"cn":"附加 # - # 闪电伤害到你的法术"},
{"en":/Adds (\d+) to (\d+) Cold Damage to Spells/g,"cn":"附加 # - # 冰冷伤害到法术"},
{"en":/Adds (\d+) to (\d+) Fire Damage to Spells/g,"cn":"附加 # - # 火焰伤害到法术"},
{"en":/Adds (\d+) to (\d+) Lightning Damage to Spells/g,"cn":"附加 # - # 闪电伤害到法术"},
{"en":/Adds (\d+) to (\d+) Cold Damage/g,"cn":"附加 # - # 冰冷伤害"},
{"en":/Adds (\d+) to (\d+) Fire Damage/g,"cn":"附加 # - # 火焰伤害"},
{"en":/Adds (\d+) to (\d+) Lightning Damage/g,"cn":"附加 # - # 闪电伤害"},
{"en":/Adds (\d+) to (\d+) Physical Damage/g,"cn":"附加 # - # 物理伤害"},

{"en":/(\d+)% increased Armour and Energy Shield/g,"cn":"增加 #% 护甲和能量护盾"},
{"en":/(\d+)% increased Armour and Evasion/g,"cn":"增加 #% 护甲和闪避"},
{"en":/(\d+)% increased Evasion and Energy Shield/g,"cn":"增加 #% 闪避和能量护盾"},
{"en":/(\d+)% increased Armour, Evasion and Energy Shield/g,"cn":"增加 #% 护甲，闪避和能量护盾"},
{"en":/Item drops on Death if equipped by an Animated Guardian/g,"cn":"本物品在幻化守卫死亡后掉落"},
{"en":/to maximum number of Skeletons/g,"cn":"最大幽魂数量"},
{"en":/(\d+)% increased Ignite Duration on Enemies/g,"cn":"增加 #% 敌人身上的点燃持续时间"},
{"en":/(\d+)% increased Freeze Duration on Enemies/g,"cn":"增加 #% 敌人身上的冰冻持续时间"},
{"en":/(\d+)% increased Shock Duration on Enemies/g,"cn":"增加 #% 敌人身上的感电持续时间"},

{"en":/(\d+) to Level of Socketed Gems/g,"cn":"# 此物品上宝石等级"},
{"en":/(\d+) to Level of Socketed Melee Gems/g,"cn":"# 此物品上近战宝石等级"},
{"en":/(\d+) to Level of Socketed Bow Gems/g,"cn":"# 此物品上弓宝石等级"},
{"en":/(\d+) to Level of Socketed Chaos Gems/g,"cn":"# 此物品上混沌宝石等级"},
{"en":/(\d+) to Level of Socketed Cold Gems/g,"cn":"# 此物品上冰冷等级"},
{"en":/(\d+) to Level of Socketed Fire Gems/g,"cn":"# 此物品上火焰等级"},
{"en":/(\d+) to Level of Socketed Lightning Gems/g,"cn":"# 此物品上闪电等级"},
{"en":/(\d+)% increased Elemental Damage with Weapons/g,"cn":"增加 #% 武器元素伤害"},
{"en":/(\d+)% increased Elemental Damage/g,"cn":"增加 #% 元素伤害"},
{"en":/of Physical Attack Damage Leeched as Life/g,"cn":"物理攻击伤害偷取生命"},
{"en":/(\d+)% increased Physical Damage/g,"cn":"增加 #% 物理伤害"},
{"en":/of Physical Attack Damage Leeched as Mana/g,"cn":"物理攻击伤害偷取魔力"},
{"en":/(\d+)% increased Spell Damage/g,"cn":"增加 #% 法术伤害"},
{"en":/(\d+) to maximum Mana/g,"cn":"# 最大魔力"},
{"en":/(\d+)% to Chaos Resistance/g,"cn":"#% 混沌抗性"},
{"en":/(\d+)% to Cold Resistance/g,"cn":"#% 冰冷抗性"},
{"en":/(\d+)% to Fire Resistance/g,"cn":"#% 火焰抗性"},
{"en":/(\d+)% to Lightning Resistance/g,"cn":"#% 闪电抗性"},
{"en":/(\d+)% increased Critical Strike Chance for Spells/g,"cn":"增加 #% 法术暴击率"},
{"en":/(\d+)% increased Critical Strike Chance/g,"cn":"增加 #% 暴击率"},
{"en":/to Global Critical Strike Multiplier/g,"cn":"全域暴击加成"},
{"en":/(\d+) to Accuracy Rating/g,"cn":"# 命中"},
{"en":/(\d+)% increased Attack Speed/g,"cn":"增加 #% 攻击速度"},
{"en":/(\d+) Life gained for each Enemy hit by your Attacks/g,"cn":"# 你的攻击击中回复生命"},
{"en":/(\d+) Life gained for each Enemy hit by Attacks/g,"cn":"# 攻击击中回复生命"},
{"en":/(\d+) Life gained on Kill/g,"cn":"# 击杀回复生命"},
{"en":/(\d+)% reduced Attribute Requirements/g,"cn":"减少 #% 能力需求"},
{"en":/(\d+) Mana gained on Kill/g,"cn":"# 击杀回复魔力"},
{"en":/(\d+) to Strength/g,"cn":"# 力量"},
{"en":/(\d+) to Intelligence/g,"cn":"# 智慧"},
{"en":/(\d+) to Dexterity/g,"cn":"# 敏捷"},
{"en":/(\d+)% increased Projectile Speed/g,"cn":"增加 #% 投射物速度"},
{"en":/(\d+)% increased Stun Duration on Enemies/g,"cn":"增加 #% 眩晕持续时间"},
{"en":/(\d+)% reduced Enemy Stun Threshold/g,"cn":"减少 #% 眩晕门槛"},
{"en":/Reflects (\d+) Physical Damage to Melee Attackers/g,"cn":"反射 # 点物理伤害给近战攻击者"},
{"en":/(\d+)% increased Armour/g,"cn":"增加 #% 护甲"},
{"en":/(\d+) to Armour/g,"cn":"# 护甲"},
{"en":/(\d+)% increased Evasion Rating/g,"cn":"增加 #% 闪避"},
{"en":/(\d+) to Evasion Rating/g,"cn":"# 闪避"},
{"en":/(\d+)% increased Energy Shield/g,"cn":"增加 #% 能量护盾"},
{"en":/(\d+)% increased maximum Energy Shield/gi,"cn":"增加 #% 最大能量护盾"},
{"en":/(\d+)% increased Stun and Block Recovery/gi,"cn":"增加 #% 格挡和晕眩回复"},
{"en":/(\d+) to maximum Energy Shield/gi,"cn":"# 最大能量护盾"},
{"en":/(\d+) to maximum Life/gi,"cn":"# 最大生命"},
{"en":/(\d+)% increased maximum Life/gi,"cn":"增加 #% 最大生命"},
{"en":/(\d+) to maximum Mana/gi,"cn":"# 最大魔力"},
{"en":/(\d+)% increased maximum Mana/gi,"cn":"增加 #% 最大魔力"},
{"en":/(\d+) Life Regenerated per second/g,"cn":"# 每秒生命回复"},
{"en":/to all Attributes/g,"cn":"全能力"},
{"en":/to all Elemental Resistances/g,"cn":"全部元素抗性"},
{"en":/(\d+)% increased Cast Speed/g,"cn":"增加 #% 施放速度"},
{"en":/(\d+)% increased Cold Damage/g,"cn":"增加 #% 冰冷伤害"},
{"en":/(\d+)% increased Fire Damage/g,"cn":"增加 #% 火焰伤害"},
{"en":/(\d+)% increased Lightning Damage/g,"cn":"增加 #% 闪电伤害"},
{"en":/(\d+)% increased Chaos Damage/g,"cn":"增加 #% 混沌伤害"},
{"en":/(\d+)% increased Rarity of Items found/g,"cn":"增加 #% 物品稀有度"},
{"en":/Chance to Block/g,"cn":"格挡率"},
{"en":/(\d+)% increased Mana Regeneration Rate/g,"cn":"增加 #% 每秒魔力回复"},
{"en":/to Fire and Cold Resistances/g,"cn":"火焰和冰冷抗性"},
{"en":/to Cold and Lightning Resistances/g,"cn":"冰冷和闪电抗性"},
{"en":/to Fire and Lightning Resistances/g,"cn":"火焰和闪电抗性"},
{"en":/(\d+)% increased Global Critical Strike Chance/g,"cn":"增加 #% 全域暴击几率"},
{"en":/(\d+)% increased Flask Life Recovery rate/g,"cn":"增加 #% 药剂生命回复速度"},
{"en":/(\d+)% increased Flask Mana Recovery rate/g,"cn":"增加 #% 药剂魔力回复速度"},
{"en":/(\d+)% increased Movement Speed/g,"cn":"增加 #% 移动速度"},
{"en":/(\d+)% chance for Flasks to gain Charges when you take a Critical Strike/g,"cn":"当你收到暴击时有 #% 几率获得药剂充能"},
{"en":/(\d+)% increased Flask Charges gained/g,"cn":"增加 #% 药剂充能获取"},
{"en":/(\d+)% reduced Flask Charges used/g,"cn":"减少 #% 药剂充能消耗"},
{"en":/(\d+)% increased Flask effect duration/g,"cn":"增加 #% 药剂持续时间"},
{"en":/(\d+)% increased Trap Damage/g,"cn":"增加 #% 陷阱伤害"},
{"en":/(\d+)% increased Mine Damage/g,"cn":"增加 #% 地雷伤害"},
{"en":/(\d+)% increased Trap Throwing Speed/g,"cn":"增加 #% 陷阱投掷速度"},
{"en":/(\d+)% increased Mine Laying Speed/g,"cn":"增加 #% 地雷放置速度"},

{"en":/additional Global Block chance/gi,"cn":"额外格挡率"},
{"en":/additional Shield Block chance/gi,"cn":"额外盾牌格挡率"}, 
{"en":/Equipped Animated Guardian drops item on death/gi,"cn":"幻化守卫死亡后掉落本物品"},	
{"en":/Prefixes Cannot Be Changed/gi,"cn":"前缀无法被改变"},
{"en":/(\d+)% increased Chance to Shock/gi,"cn":"增加 #% 机率对敌人造成感电"},
{"en":/(\d+)% increased Chance to Freeze/gi,"cn":"增加 #% 机率对敌人造成冰冻"},
{"en":/(\d+)% increased Chance to Ignite/gi,"cn":"增加 #% 机率对敌人造成点燃"},
{"en":/Cannot roll Attack Mods/gi,"cn":"无法骰出攻击属性"},
{"en":/Cannot roll Caster Mods/gi,"cn":"无法骰出法术属性"},
{"en":/Can have multiple Crafted Mods/gi,"cn":"可以拥有复数工艺属性"},
{"en":/(\d+)% increased Trap and Mine damage/gi,"cn":"增加 #% 陷阱和地雷伤害"},
{"en":/(\d+)% increased Flask effect duration/gi,"cn":"增加 #% 药剂效果持续时间"},
{"en":/Attack Projectiles Return to You after hitting targets/gi,"cn":"攻击投射物会返还到自身"},
{"en":/(\d+)% increased Trap Throwing and Mine Laying Speed/gi,"cn":"增加 #% 陷阱投掷和地雷设置速度"},
{"en":/Suffixes Cannot Be Changed/gi,"cn":"后缀无法被变更"},
{"en":/(\d+)% reduced Enemy Block Chance/gi,"cn":"减少敌人 #% 格挡率"},
{"en":/(\d+)% increased Damage over Time/gi,"cn":"增加 #% 持续伤害"},
{"en":/Reflects (\d+) to (\d+) Physical Damage to Attackers on Block/gi,"cn":"格挡时反射 # 至 # 物理伤害至攻击者"},
{"en":/(\d+)% faster start of Energy Shield Recharge/gi,"cn":"增加 #% 能量护盾开始充能速度"},
{"en":/(\d+)% chance for Flasks to gain a Charge when you take a Critical Strike/gi,"cn":"有 #% 机率在受到暴击时回复 1 药剂充能数"},
{"en":/(\d+)% reduced Damage taken from Damage Over Time/gi,"cn":"减少 #% 受到的持续伤害"},
{"en":/(\d+)% chance to Avoid being Stunned/gi,"cn":"有 #% 机率避免被晕眩"},
{"en":/(\d+)% chance to Avoid being Knocked Back/gi,"cn":"有 #% 机率避免被击退"},
{"en":/Cannot roll Mods with Required Level above (\d+)/gi,"cn":"不能附加需求等级高于 # 的属性"},


{"en":/Adds an additional Arrow/gi,"cn":"附加1个额外箭矢"},
{"en":/Enemies can have (\d+) additional Curse/gi,"cn":"可以对敌人施放 # 个额外诅咒"},
{"en":/Can have up to (\d+) additional Trap placed at a time/gi,"cn":"可以设置 # 个额外陷阱"},
{"en":/Grants level (\d+) Anger Skill/gi,"cn":"获得等级 # 的【愤怒】技能"},
{"en":/You can catch Corrupted Fish/gi,"cn":"你可以捕获已污染的鱼"},
{"en":/Cannot be Knocked Back/gi,"cn":"免疫击退"},
{"en":/Enemies Cannot LeechLife From You/gi,"cn":"敌人不能偷取你的生命"},
{"en":/(\d+)% additional Chance to receive a Critical Strike/gi,"cn":"#% 额外几率受到暴击"},
{"en":/(\d+)% chance to Dodge Attacks/gi,"cn":"#% 几率躲避"},
{"en":/(\d+)% chance to Cause Monsters to Flee/gi,"cn":"#% 几率使敌人逃跑"},
{"en":/(\d+)% increased Chaos Damage per equipped Corrupted Item/gi,"cn":"装备每个已污染的物品时增加 #% 混沌伤害"},
{"en":/Grants level (\d+) Clarity Skill/gi,"cn":"获得等级 # 的【清晰】技能"},
{"en":/Grants level (\d+) Conductivity Skill/gi,"cn":"获得等级 # 的【导电】技能"},
{"en":/Grants level (\d+) Assassin's Mark Skill/gi,"cn":"获得等级 # 的【刺客印记】技能"},
{"en":/Culling Strike/gi,"cn":"扑杀"},
{"en":/Curse Enemies with level (\d+) Elemental Weakness on Hit/gi,"cn":"击中附加等级 # 的【元素要害】诅咒"},
{"en":/Curse Enemies with level (\d+) Temporal Chains on Hit/gi,"cn":"击中附加等级 # 的【时空锁链】诅咒"},
{"en":/Curse Enemies with level (\d+) Vulnerability on Hit/gi,"cn":"击中附加等级 # 的【脆弱】诅咒"},
{"en":/(\d+)% of Physical Damage Converted to Cold Damage/gi,"cn":"#% 物理伤害转化为冰冷伤害"},
{"en":/(\d+)% of Physical Damage Converted to Fire Damage/gi,"cn":"#% 物理伤害转化为火焰伤害"},
{"en":/(\d+)% of Physical Damage Converted to Lightning Damage/gi,"cn":"#% 物理伤害转化为闪电伤害"},
{"en":/Physical Damage taken from Attacks/gi,"cn":"受到的来自攻击的物理伤害"},
{"en":/When Hit, (\d+)% of Damage is taken from Mana before Life/gi,"cn":"被击中时，#% 伤害优先从魔力扣除"},
{"en":/(\d+)% increased Damage while Dead/gi,"cn":"死亡时增加 #% 伤害"},
{"en":/Grants level (\d+) Determination Skill/gi,"cn":"获得等级 # 的【坚定】技能"},
{"en":/Grants level (\d+) Discipline Skill/gi,"cn":"获得等级 # 的【纪律】技能"},
{"en":/(\d+)% additional Block Chance while Dual Wielding/gi,"cn":"双持时有 #% 额外格挡率"},
{"en":/Grants level (\d+) Elemental Weakness Skill /gi,"cn":"获得等级 # 的【元素要害】技能"},
{"en":/(\d+)% increased Quantity of Fish Caught/gi,"cn":"增加 #% 捕获鱼的数量"},
{"en":/(\d+)% increased Rarity of Fish Caught/gi,"cn":"增加 #% 捕获鱼的稀有度"},
{"en":/Grants level (\d+) Flammability Skill/gi,"cn":"获得等级 # 的【易燃】技能"},
{"en":/Grants level (\d+) Frostbite Skill/gi,"cn":"获得等级 # 的【冻伤】技能"},
{"en":/(\d+)% chance of Projectiles Piercing/gi,"cn":"#% 投射物穿透几率"},
{"en":/Grants level (\d+) Grace Skill/gi,"cn":"获得等级 # 的【优雅】技能"},
{"en":/Grants level (\d+) Haste Skill/gi,"cn":"获得等级 # 的【迅捷】技能"},
{"en":/Grants level (\d+) Hatred Skill/gi,"cn":"获得等级 # 的【憎恨】技能"},
{"en":/(\d+)% increased Endurance, Frenzy and Power Charge Duration/gi,"cn":"增加 #% 耐力球、狂怒球和暴击球持续时间"},
{"en":/(\d+)% increased Skill Effect Duration/gi,"cn":"增加 #% 技能效果持续时间"},
{"en":/(\d+)% increased Life Leeched per second per equipped Corrupted Item/gi,"cn":"装备每个已污染的物品时增加 #% 生命偷取速度"},
{"en":/Adds (\d+) to (\d+) Chaos Damage to Attacks/gi,"cn":"附加 # - # 混沌伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Chaos Damage/gi,"cn":"附加 # - # 混沌伤害"},
{"en":/(\d+)% increased Mana Leeched per second per equipped Corrupted Item/gi,"cn":"备每个已污染的物品时增加 #% 魔力偷取速度"},
{"en":/Mana gained for each Enemy hit by your Attacks/gi,"cn":"你的攻击击中回复魔力"},
{"en":/(\d+)% of Damage taken gained as Mana when Hit/gi,"cn":"被击中时，获得 #% 所受伤害的魔力"},
{"en":/to Maximum Frenzy Charges/gi,"cn":"最大狂怒球"},
{"en":/to Maximum Power Charges/gi,"cn":"最大暴击球"},
{"en":/to Maximum Endurance Charges/gi,"cn":"最大耐力球"},
{"en":/to all maximum Resistances/gi,"cn":"最大全部抗性"},
{"en":/(\d+)% chance of Arrows Piercing/gi,"cn":"#% 箭矢穿透几率"},
{"en":/Grants level (\d+) Projectile Weakness Skill/gi,"cn":"获得等级 # 的【投射物要害】技能"},
{"en":/Grants level (\d+) Purity of Ice Skill/gi,"cn":"获得等级 # 的【冰霜净化】技能"},
{"en":/Grants level (\d+) Purity of Fire Skill/gi,"cn":"获得等级 # 的【火焰净化】技能"},
{"en":/Grants level (\d+) Purity of Lightning Skill/gi,"cn":"获得等级 # 的【闪电净化】技能"},
{"en":/Grants level (\d+) Purity of Elements Skill/gi,"cn":"获得等级 # 的【元素净化】技能"},
{"en":/(\d+)% reduced Character Size/gi,"cn":"减少 #% 角色体型"},
{"en":/(\d+)% reduced Chill Duration on You/gi,"cn":"减少 #% 你冰缓的持续时间"},
{"en":/(\d+)% reduced Freeze Duration on You/gi,"cn":"减少 #% 你冰冻的持续时间"},
{"en":/(\d+)% reduced Ignite Duration on You/gi,"cn":"减少 #% 你点燃的持续时间"},
{"en":/(\d+)% reduced Shock Duration on You/gi,"cn":"减少 #% 你感电的持续时间"},
{"en":/SocketedSkill Gems get a (\d+)% Mana Multiplier/gi,"cn":"此物品上技能宝石有 #% 魔力消耗倍率"},
{"en":/to Level of Socketed Vaal Gems/gi,"cn":"此物品上瓦尔宝石等级"},
{"en":/(\d+)% Chance to Block Spells/gi,"cn":"#% 法术格挡率"},
{"en":/Socketed Gems are supported by level (\d+) Additional Accuracy/gi,"cn":"此物品上宝石受到等级 # 的【额外命中】辅助"},
{"en":/Socketed Gems are Supported by level (\d+) Added Fire Damage/gi,"cn":"此物品上宝石受到等级 # 的【附加火焰伤害】辅助"},
{"en":/Socketed Gems are Supported by level (\d+) Increased Area of Effect/gi,"cn":"此物品上宝石受到等级 # 的【增大范围】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Cast On Crit/gi,"cn":"此物品上宝石受到等级 # 的【暴击时施放】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Cast when Stunned/gi,"cn":"此物品上宝石受到等级 # 的【晕眩时施放】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Increased Critical Damage/gi,"cn":"此物品上宝石受到等级 # 的【增加暴击伤害】辅助"},
{"en":/Socketed Gems are Supported by level (\d+) Elemental Proliferation/gi,"cn":"此物品上宝石受到等级 # 的【元素扩散】辅助"},
{"en":/Socketed Gems are Supported by Level (\d+) Faster Casting/gi,"cn":"此物品上宝石受到等级 # 的【快速施放】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Fork/gi,"cn":"此物品上宝石受到等级 # 的【分裂】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Life Leech/gi,"cn":"此物品上宝石受到等级 # 的【生命偷取】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Melee Splash/gi,"cn":"此物品上宝石受到等级 # 的【近战伤害扩散】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Multistrike/gi,"cn":"此物品上宝石受到等级 # 的【多重打击】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Stun/gi,"cn":"此物品上宝石受到等级 # 的【击晕】辅助"},
{"en":/Socketed Gems are supported by level (\d+) Weapon Elemental Damage/gi,"cn":"此物品上宝石受到等级 # 的【武器元素伤害】辅助"},
{"en":/Grants level (\d+) Temporal ChainsSkill/gi,"cn":"获得等级 # 的【时空锁链】技能"},
{"en":/(\d+)% increased Vaal Skill Damage/gi,"cn":"增加 #% 瓦尔技能伤害"},
{"en":/Grants level (\d+) Vitality Skill/gi,"cn":"获得等级 # 的【活力】技能"},
{"en":/Grants level (\d+) Vulnerability Skill/gi,"cn":"获得等级 # 的【脆弱】技能"},
{"en":/Grants level (\d+) Wrath Skill/gi,"cn":"获得等级 # 的【雷霆】技能"},
{"en":/You cannot be Cursed with Silence/gi,"cn":"免疫沉默"},

{"en":/增加 (\d+)% 元素伤害 with Weapons/gi,"cn":"增加 #% 武器元素伤害"},
{"en":/力量 and Intelligence/gi,"cn":"力量和智慧"}


];