var ExplicitModjson= [

{"en":/to Quality of Socketed Support Gems/gi,"cn":"装备上辅助宝石品质"},
{"en":/to Mana Cost of Skills/gi,"cn":"技能施放消耗"},
{"en":/to Level of Socketed Support Gems/gi,"cn":"装备上辅助宝石等级"},
{"en":/Causes Bleeding on Hit/gi,"cn":"击中时造成流血效果"},
{"en":/Hits can't be Evaded/gi,"cn":"攻击无法被闪避"},
{"en":/Your Hits inflict Decay, dealing (\d+) Chaos Damage per second for 10 seconds/gi,"cn":"击中时造成10秒内 # 混沌伤害的持续伤害"},
{"en":/Socketed Gems deal (\d+)% more Damage over Time/gi,"cn":"该物品上宝石造成 #% 更多持续伤害"},
{"en":/Cannot be Poisoned/gi,"cn":"不会中毒"},
{"en":/(\d+)% reduced Chaos Damage taken over time/gi,"cn":"减少 #% 受到的持续性混沌伤害"},
{"en":/to Level of Socketed Aura Gems/gi,"cn":"此物品上光环宝石等级"},
{"en":/Recover (\d+)% of your maximum Mana when you Block/gi,"cn":"格挡时回复 #% 魔力"},
{"en":/(\d+)% increased Damage with Poison/gi,"cn":"增加 #% 中毒伤害"},
{"en":/of Chaos Damage Leeched as Life/gi,"cn":"混沌伤害偷取生命"},
{"en":/to Chaos Resistance while using a Flask/gi,"cn":"混沌抗性在药剂作用期间"},
{"en":/(\d+)% chance to gain a Power, Frenzy or Endurance Charge on Kill/gi,"cn":"击杀时有 #%机率获得随机一个充能球"},
{"en":/Socketed Gems have +3% Critical Strike Chance/gi,"cn":"该物品上宝石 +3% 基础暴击率"},
{"en":/Socketed Gems have +3.5% Critical Strike Chance/gi,"cn":"该物品上宝石 +3.5% 基础暴击率"},
{"en":/(\d+)% reduced elemental Damage Taken while not moving/gi,"cn":"静止时减少 #% 所受的元素伤害"},
{"en":/(\d+)% of Physical Damage taken as Cold Damage/gi,"cn":"#% 承受的物理伤害转化为冰冷伤害"},
{"en":/Socketed Gems deal (\d+)% more Elemental Damage/gi,"cn":"该物品上宝石造成 #% 更多元素伤害"},
{"en":/Chill nearby Enemies for (\d+) second on Block/gi,"cn":"格挡时冰缓周围敌人 # 秒"},
{"en":/Adds (\d+) to (\d+) Cold Damage per Frenzy Charge/gi,"cn":"每个狂怒球附加 # to # 冰冷伤害"},
{"en":/(\d+)% increased effect of Fortify on You/gi,"cn":"增加 #% 你身上护体效果"},
{"en":/(\d+)% additional Physical Damage Reduction while using a Flask/gi,"cn":"药剂作用期间获得 #% 额外物理伤害减免"},
{"en":/(\d+)% chance to Cast Level (\d+) Fire Burst on Hit/gi,"cn":"击中时有 #%机率施展 # 级【火焰爆破】"},
{"en":/Socketed Gems deal (\d+) to (\d+) additional Fire Damage/gi,"cn":"该物品上宝石造成额外 # to # 火焰伤害"},
{"en":/Drops Burning Ground while moving, dealing (\d+) Fire Damage per second/gi,"cn":"移动时产生火焰地面，造成 # 每秒火焰伤害"},
{"en":/(\d+)% increased Radius of Area Skills/gi,"cn":"增加 #% 范围技能的半径"},
{"en":/Socketed Gems have (\d+)% chance to Ignite/gi,"cn":"该物品上宝石有 #% 机率点燃"},
{"en":/Adds (\d+) to (\d+) Fire Damage if you've Blocked Recently/gi,"cn":"格挡后短时间内附加 # to # 火焰伤害"},
{"en":/Gain (\d+)% of Physical Damage as Extra Fire Damage/gi,"cn":"获得 #% 物理伤害的额外火焰伤害"},
{"en":/(\d+)% increased Life Leeched per second/gi,"cn":"增加 #% 每秒生命偷取"},
{"en":/(\d+)% of Physical Damage as Extra Fire Damage/gi,"cn":"获得 #% 物理伤害的额外火焰伤害"},
{"en":/Damage Penetrates (\d+)% Elemental Resistances while using a Flask/gi,"cn":"药剂作用期间伤害穿透 #% 元素抗性"},
{"en":/Casts level (\d+) Spectral Spirits when equipped/gi,"cn":"装备时施放等级 # 的【幽魂之灵】"},
{"en":/Socketed Gems have (\d+)% more Attack and Cast Speed/gi,"cn":"该物品上宝石增加 #% 更多攻击与施放速度"},
{"en":/(\d+)% increased Movement speed while on Burning, Chilled or Shocked ground/gi,"cn":"站在燃烧、冰缓、感电地面时增加 #% 移动速度"},
{"en":/Gain Onslaught for (\d+) seconds when Hit/gi,"cn":"被击中时获得 #秒 猛攻"},
{"en":/Socketed Gems gain (\d+)% of Physical Damage as extra Lightning Damage/gi,"cn":"该物品上宝石获得 #% 物理伤害的额外闪电伤害"},
{"en":/(\d+)% chance to gain a Power Charge on Block/gi,"cn":"格挡时有 #% 机率获得暴击球"},
{"en":/(\d+)% reduced Reflected Damage taken/gi,"cn":"减少 #% 受到的反射伤害"},
{"en":/(\d+)% chance to Recover (\d+)% of Maximum Mana when you use a Skill/gi,"cn":"使用技能时有 #% 机率回复 #% 最大魔力"},
{"en":/(\d+)% increased Movement Speed while using a Flask/gi,"cn":"药剂作用期间增加 #% 移动速度"},
{"en":/chance to Avoid being Ignited/gi,"cn":"机率避免被点燃"},
{"en":/chance to Avoid Fire Damage when Hit/gi,"cn":"机率被击中时避免火焰伤害"},
{"en":/to Weapon range/gi,"cn":"武器攻击半径"},
{"en":/Minions have (\d+)% increased Movement Speed/gi,"cn":"召唤物增加 #% 移动速度"},
{"en":/(\d+)% reduced Mana Reserved/gi,"cn":"减少 #% 魔力保留"},
{"en":/chance to Avoid Cold Damage when Hit/gi,"cn":"机率被击中时避免冰冷伤害"},
{"en":/chance to Avoid being Frozen/gi,"cn":"机率避免被冰冻"},
{"en":/chance to Avoid Lightning Damage when Hit/gi,"cn":"机率被击中时避免闪电伤害"},
{"en":/chance to Avoid being Shocked/gi,"cn":"机率避免被感电"},
{"en":/Adds (\d+) to (\d+) Cold Damage to Attacks/g,"cn":"附加 # - # 冰冷伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Fire Damage to Attacks/g,"cn":"附加 # - # 火焰伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Lightning Damage to Attacks/g,"cn":"附加 # - # 闪电伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Physical Damage to Attacks/g,"cn":"附加 # - # 物理伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Chaos Damage to Attacks/g,"cn":"附加 # - # 混沌伤害到攻击"},
{"en":/Adds (\d+) to (\d+) Cold Damage to Spells/g,"cn":"附加 # - # 冰冷伤害到法术"},
{"en":/Adds (\d+) to (\d+) Fire Damage to Spells/g,"cn":"附加 # - # 火焰伤害到法术"},
{"en":/Adds (\d+) to (\d+) Lightning Damage to Spells/g,"cn":"附加 # - # 闪电伤害到法术"},
{"en":/Adds (\d+) to (\d+) Cold Damage/g,"cn":"附加 # - # 冰冷伤害"},
{"en":/Adds (\d+) to (\d+) Fire Damage/g,"cn":"附加 # - # 火焰伤害"},
{"en":/Adds (\d+) to (\d+) Lightning Damage/g,"cn":"附加 # - # 闪电伤害"},
{"en":/Adds (\d+) to (\d+) Physical Damage/g,"cn":"附加 # - # 物理伤害"},

{"en":/(\d+)% increased Armour and Energy Shield/g,"cn":"增加 #% 护甲和能量护盾"},
{"en":/(\d+)% increased Armour and Evasion/g,"cn":"增加 #% 护甲和闪避"},
{"en":/(\d+)% increased Evasion and Energy Shield/g,"cn":"增加 #% 闪避和能量护盾"},
{"en":/(\d+)% increased Armour, Evasion and Energy Shield/g,"cn":"增加 #% 护甲，闪避和能量护盾"},
{"en":/Item drops on Death if equipped by an Animated Guardian/g,"cn":"本物品在幻化守卫死亡后掉落"},
{"en":/to maximum number of Skeletons/g,"cn":"最大幽魂数量"},
{"en":/(\d+)% increased Ignite Duration on Enemies/g,"cn":"增加 #% 敌人身上的点燃持续时间"},
{"en":/(\d+)% increased Freeze Duration on Enemies/g,"cn":"增加 #% 敌人身上的冰冻持续时间"},
{"en":/(\d+)% increased Shock Duration on Enemies/g,"cn":"增加 #% 敌人身上的感电持续时间"},

{"en":/(\d+) to Level of Socketed Gems/g,"cn":"# 此物品上宝石等级"},
{"en":/(\d+) to Level of Socketed Melee Gems/g,"cn":"# 此物品上近战宝石等级"},
{"en":/(\d+) to Level of Socketed Bow Gems/g,"cn":"# 此物品上弓宝石等级"},
{"en":/(\d+) to Level of Socketed Chaos Gems/g,"cn":"# 此物品上混沌宝石等级"},
{"en":/(\d+) to Level of Socketed Cold Gems/g,"cn":"# 此物品上冰冷等级"},
{"en":/(\d+) to Level of Socketed Fire Gems/g,"cn":"# 此物品上火焰等级"},
{"en":/(\d+) to Level of Socketed Lightning Gems/g,"cn":"# 此物品上闪电等级"},
{"en":/(\d+)% increased Elemental Damage with Weapons/g,"cn":"增加 #% 武器元素伤害"},
{"en":/(\d+)% increased Elemental Damage/g,"cn":"增加 #% 元素伤害"},
{"en":/of Physical Attack Damage Leeched as Life/g,"cn":"物理攻击伤害偷取生命"},
{"en":/(\d+)% increased Physical Damage/g,"cn":"增加 #% 物理伤害"},
{"en":/of Physical Attack Damage Leeched as Mana/g,"cn":"物理攻击伤害偷取魔力"},
{"en":/(\d+)% increased Spell Damage/g,"cn":"增加 #% 法术伤害"},
{"en":/(\d+) to maximum Mana/g,"cn":"# 最大魔力"},
{"en":/(\d+)% to Chaos Resistance/g,"cn":"#% 混沌抗性"},
{"en":/(\d+)% to Cold Resistance/g,"cn":"#% 冰冷抗性"},
{"en":/(\d+)% to Fire Resistance/g,"cn":"#% 火焰抗性"},
{"en":/(\d+)% to Lightning Resistance/g,"cn":"#% 闪电抗性"},
{"en":/(\d+)% increased Critical Strike Chance for Spells/g,"cn":"增加 #% 法术暴击率"},
{"en":/(\d+)% increased Critical Strike Chance/g,"cn":"增加 #% 暴击率"},
{"en":/to Global Critical Strike Multiplier/g,"cn":"全域暴击加成"},
{"en":/(\d+) to Accuracy Rating/g,"cn":"# 命中"},
{"en":/(\d+)% increased Attack Speed/g,"cn":"增加 #% 攻击速度"},
{"en":/(\d+) Life gained for each Enemy hit by Attacks/g,"cn":"# 攻击击中回复生命"},
{"en":/(\d+) Life gained on Kill/g,"cn":"# 击杀回复生命"},
{"en":/(\d+)% reduced Attribute Requirements/g,"cn":"减少 #% 能力需求"},
{"en":/(\d+) Mana gained on Kill/g,"cn":"# 击杀回复魔力"},
{"en":/(\d+) to Strength/g,"cn":"# 力量"},
{"en":/(\d+) to Intelligence/g,"cn":"# 智慧"},
{"en":/(\d+) to Dexterity/g,"cn":"# 敏捷"},
{"en":/(\d+)% increased Projectile Speed/g,"cn":"增加 #% 投射物速度"},
{"en":/(\d+)% increased Stun Duration on Enemies/g,"cn":"增加 #% 眩晕持续时间"},
{"en":/(\d+)% reduced Enemy Stun Threshold/g,"cn":"减少 #% 眩晕门槛"},
{"en":/Reflects (\d+) Physical Damage to Melee Attackers/g,"cn":"反射 # 点物理伤害给近战攻击者"},
{"en":/(\d+)% increased Armour/g,"cn":"增加 #% 护甲"},
{"en":/(\d+) to Armour/g,"cn":"# 护甲"},
{"en":/(\d+)% increased Evasion Rating/g,"cn":"增加 #% 闪避"},
{"en":/(\d+) to Evasion Rating/g,"cn":"# 闪避"},
{"en":/(\d+)% increased Energy Shield/g,"cn":"增加 #% 能量护盾"},
{"en":/(\d+)% increased maximum Energy Shield/gi,"cn":"增加 #% 最大能量护盾"},
{"en":/(\d+)% increased Stun and Block Recovery/gi,"cn":"增加 #% 格挡和晕眩回复"},
{"en":/(\d+) to maximum Energy Shield/gi,"cn":"# 最大能量护盾"},
{"en":/(\d+) to maximum Life/gi,"cn":"# 最大生命"},
{"en":/(\d+)% increased maximum Life/gi,"cn":"增加 #% 最大生命"},
{"en":/(\d+) to maximum Mana/gi,"cn":"# 最大魔力"},
{"en":/(\d+)% increased maximum Mana/gi,"cn":"增加 #% 最大魔力"},
{"en":/(\d+) Life Regenerated per second/g,"cn":"# 每秒生命回复"},
{"en":/to all Attributes/g,"cn":"全能力"},
{"en":/to all Elemental Resistances/g,"cn":"全部元素抗性"},
{"en":/(\d+)% increased Cast Speed/g,"cn":"增加 #% 施放速度"},
{"en":/(\d+)% increased Cold Damage/g,"cn":"增加 #% 冰冷伤害"},
{"en":/(\d+)% increased Fire Damage/g,"cn":"增加 #% 火焰伤害"},
{"en":/(\d+)% increased Lightning Damage/g,"cn":"增加 #% 闪电伤害"},
{"en":/(\d+)% increased Chaos Damage/g,"cn":"增加 #% 混沌伤害"},
{"en":/(\d+)% increased Rarity of Items found/g,"cn":"增加 #% 物品稀有度"},
{"en":/Chance to Block/g,"cn":"格挡率"},
{"en":/(\d+)% increased Mana Regeneration Rate/g,"cn":"增加 #% 每秒魔力回复"},
{"en":/to Fire and Cold Resistances/g,"cn":"火焰和冰冷抗性"},
{"en":/to Cold and Lightning Resistances/g,"cn":"冰冷和闪电抗性"},
{"en":/to Fire and Lightning Resistances/g,"cn":"火焰和闪电抗性"},
{"en":/(\d+)% increased Global Critical Strike Chance/g,"cn":"增加 #% 全域暴击几率"},
{"en":/(\d+)% increased Flask Life Recovery rate/g,"cn":"增加 #% 药剂生命回复速度"},
{"en":/(\d+)% increased Flask Mana Recovery rate/g,"cn":"增加 #% 药剂魔力回复速度"},
{"en":/(\d+)% increased Movement Speed/g,"cn":"增加 #% 移动速度"},
{"en":/(\d+)% chance for Flasks to gain Charges when you take a Critical Strike/g,"cn":"当你收到暴击时有 #% 几率获得药剂充能"},
{"en":/(\d+)% increased Flask Charges gained/g,"cn":"增加 #% 药剂充能获取"},
{"en":/(\d+)% reduced Flask Charges used/g,"cn":"减少 #% 药剂充能消耗"},
{"en":/(\d+)% increased Flask effect duration/g,"cn":"增加 #% 药剂持续时间"},
{"en":/(\d+)% increased Trap Damage/g,"cn":"增加 #% 陷阱伤害"},
{"en":/(\d+)% increased Mine Damage/g,"cn":"增加 #% 地雷伤害"},
{"en":/(\d+)% increased Trap Throwing Speed/g,"cn":"增加 #% 陷阱投掷速度"},
{"en":/(\d+)% increased Mine Laying Speed/g,"cn":"增加 #% 地雷放置速度"},


{"en":/增加 (\d+)% 元素伤害 with Weapons/gi,"cn":"增加 #% 武器元素伤害"}
];