var gemJson=[
{"en":/Glimpse of Eternity/g,"cn":"永恒窥视"},
{"en":/Lightning Aegis/g,"cn":"闪电圣盾"},
{"en":/Precision/g,"cn":"精准"},
{"en":/Bane/g,"cn":"混沌之毒"},
{"en":/Divine Ire/g,"cn":"神圣寒冰"},
{"en":/Energy Leech Support/g,"cn":"能量偷取（辅）"},
{"en":/Infused Channelling Support/g,"cn":"灌能吟唱(辅)"},
{"en":/Intensify Support/g,"cn":"法术凝聚（辅）"},
{"en":/Malevolence/g,"cn":"怨毒光环"},
{"en":/Purifying Flame/g,"cn":"净化烈焰"},
{"en":/Soulrend/g,"cn":"裂魂术"},
{"en":/Unleash Support/g,"cn":"释出（辅）"},
{"en":/Wave of Conviction/g,"cn":"定罪波"},
{"en":/Zealotry/g,"cn":"奋锐光环"},
{"en":/Holy Flame Totem/g,"cn":"圣焰图腾"},
{"en":/Arcane Wake/g,"cn":"秘术苏醒"},
{"en":/Feast of Flesh/g,"cn":"血肉盛宴"},
{"en":/Armageddon Brand/g,"cn":"末日烙印"},
{"en":/Bonechill Support/g,"cn":"彻骨（辅）"},
{"en":/Brand Recall/g,"cn":"烙印召回"},
{"en":/Storm Brand/g,"cn":"风暴烙印"},
{"en":/Winter Orb/g,"cn":"寒冬宝珠"},
{"en":/Dread Banner/g,"cn":"恐怖之旗"},
{"en":/Multiple Totems Support/g,"cn":"多重图腾（辅）"},
{"en":/War Banner/g,"cn":"战旗"},
{"en":/Lancing Steel/g,"cn":"断金之刃"},
{"en":/Shattering Steel/g,"cn":"破碎铁刃"},
{"en":/Vicious Projectiles Support/g,"cn":"邪恶投掷(辅)"},
{"en":/Envy/g,"cn":"嫉妒"},
{"en":/Summon Doedre's Effigy/g,"cn":"召唤德瑞的雕像"},
{"en":/Aspect of the Crab/g,"cn":"蟹之势"},
{"en":/Aspect of the Spider/g,"cn":"蛛之势"},
{"en":/Aspect of the Avian/g,"cn":"鸟之势"},
{"en":/Aspect of the Cat/g,"cn":"猫之势"},
{"en":/Petrification Statue/g,"cn":"召唤石化雕像"},
{"en":/Herald of Agony/g,"cn":"苦痛之捷"},
{"en":/Scourge Arrow/g,"cn":"灾厄之箭"},
{"en":/Toxic Rain/g,"cn":"腐蚀毒雨"},
{"en":/Withering Touch Support /g,"cn":"凋零之触(辅)"},
{"en":/Consecrated Path/g,"cn":"奉献之路"},
{"en":/Herald of Purity/g,"cn":"纯净之捷"},
{"en":/Smite/g,"cn":"雷鸣重击"},
{"en":/Vaal Ancestral Warchief/g,"cn":"瓦尔.先祖战士长"},
{"en":/Summon Holy Relic/g,"cn":"召唤圣物"},
{"en":/Advanced Traps Support/g,"cn":"陷阱冷却(辅)"},
{"en":/Elemental Penetration Support/g,"cn":"元素穿透(辅)"},
{"en":/Doryani's Touch/g,"cn":"多里亚尼之触"},
{"en":/Summon Bestial Rhoa/g,"cn":"召唤兽化恐喙鸟"},
{"en":/Summon Bestial Snake/g,"cn":"召唤兽化巨蛇"},
{"en":/Summon Bestial Ursa/g,"cn":"召唤兽化之爪"},
{"en":/Blood Offering/g,"cn":"血脉奉献"},
{"en":/Icestorm/g,"cn":"冰风暴"},
{"en":/Death Aura/g,"cn":"死神光环"},
{"en":/Molten Burst/g,"cn":"熔岩爆破"},
{"en":/Charged Traps Support/g,"cn":"充能陷阱(辅)"},
{"en":/Explosive Trap/g,"cn":"爆炸陷阱"},
{"en":/Flamethrower Trap/g,"cn":"掷火陷阱"},
{"en":/Seismic Trap/g,"cn":"震波陷阱"},
{"en":/Vaal Blade Vortex/g,"cn":"瓦尔．飞刃风暴"},
{"en":/Vaal Impurity of Ice/g,"cn":"瓦尔．不净之冰"},
{"en":/Lightning Spire Trap/g,"cn":"电塔陷阱"},
{"en":/Siphoning Trap/g,"cn":"虹吸陷阱"},
{"en":/Vaal Blight/g,"cn":"瓦尔．枯萎"},
{"en":/Vaal Impurity of Lightning/g,"cn":"瓦尔．不净之雷"},
{"en":/Vaal Earthquake/g,"cn":"瓦尔．震地"},
{"en":/Vaal Impurity of Fire/g,"cn":"瓦尔．不净之火"},
{"en":/Combustion Support/g,"cn":"燃烧(辅)"},
{"en":/Minion and Totem Elemental Resistance Support/g,"cn":"召唤生物与图腾元素抗性(辅)"},
{"en":/Summon Phantasm on Kill Support/g,"cn":"击败召唤幻影(辅)"},
{"en":/Summon Skeletons Channelled/g,"cn":"召唤魔侍(吟唱)"},
{"en":/Minion Damage Support/g,"cn":"召唤生物伤害(辅)"},
{"en":/Minion Speed Support/g,"cn":"召唤生物速度(辅)"},
{"en":/Vaal Summon Skeletons/g,"cn":"瓦尔.召唤魔侍"},
{"en":/Summon Lightning Golem/g,"cn":"召唤闪电魔像"},
{"en":/Minion Life Support/g,"cn":"召唤生物生命(辅)"},
{"en":/Summon Raging Spirit/g,"cn":"召唤愤怒狂灵"},
{"en":/Summon Chaos Golem/g,"cn":"召唤混沌魔像"},
{"en":/Summon Flame Golem/g,"cn":"召唤烈焰魔像"},
{"en":/Summon Stone Golem/g,"cn":"召唤巨石魔像"},
{"en":/Summon Ice Golem/g,"cn":"召唤寒冰魔像"},
{"en":/Summon Skeleton/g,"cn":"召唤魔侍"},
{"en":/Raise Spectre/g,"cn":"召唤灵体"},
{"en":/Physical Projectile Attack Damage Support/g,"cn":"物理投射物攻击伤害(辅)"},
{"en":/Endurance Charge on Melee Stun Support/g,"cn":"近战击晕获得耐力球(辅)"},
{"en":/Elemental Damage with Attacks Support/g,"cn":"武器元素伤害(辅)"},
{"en":/Greater Multiple Projectiles Support/g,"cn":"高阶多重投射(辅)"},
{"en":/Lesser Multiple Projectiles Support/g,"cn":"低阶多重投射(辅)"},
{"en":/Increased Critical Strikes Support/g,"cn":"增加暴击几率(辅)"},
{"en":/Lesser Reduced Mana Cost Support/g,"cn":"低阶减小魔力消耗(辅)"},
{"en":/Increased Critical Damage Support/g,"cn":"增加暴击伤害(辅)"},
{"en":/Power Charge On Critical Support/g,"cn":"暴击获得暴击球(辅)"},
{"en":/Increased Area of Effect Support/g,"cn":"增大范围(辅)"},
{"en":/Added Lightning Damage Support/g,"cn":"附加闪电伤害(辅)"},
{"en":/Cast On Critical Strike Support/g,"cn":"暴击时施放(辅)"},
{"en":/Block Chance Reduction Support/g,"cn":"减少格挡几率(辅)"},
{"en":/Melee Physical Damage Support/g,"cn":"近战物理伤害(辅)"},
{"en":/Elemental Proliferation Support/g,"cn":"元素扩散(辅)"},
{"en":/Damage on Full Life Support/g,"cn":"满血攻击物理伤害(辅)"},
{"en":/Cast when Damage Taken Support/g,"cn":"受伤时施放(辅)"},
{"en":/Trap and Mine Damage Support/g,"cn":"陷阱及地雷伤害(辅)"},
{"en":/Cast while Channelling Support/g,"cn":"吟唱时施放(辅)"},
{"en":/Ranged Attack Totem Support/g,"cn":"远距离攻击图腾(辅)"},
{"en":/Physical to Lightning Support/g,"cn":"物理转闪电(辅)"},
{"en":/Controlled Destruction Support/g,"cn":"精准破坏(辅)"},
{"en":/Lightning Penetration Support/g,"cn":"闪电穿透(辅)"},
{"en":/Cast on Melee Kill Support/g,"cn":"近战击败时施放(辅)"},
{"en":/Added Chaos Damage Support/g,"cn":"附加混沌伤害(辅)"},
{"en":/Increased Duration Support/g,"cn":"持续时间延长(辅)"},
{"en":/Ignite Proliferation Support/g,"cn":"点燃扩散(辅)"},
{"en":/Old Arctic Armour/g,"cn":"Old Arctic Armour"},
{"en":/Added Fire Damage Support/g,"cn":"附加火焰伤害(辅)"},
{"en":/Added Cold Damage Support/g,"cn":"附加冰霜伤害(辅)"},
{"en":/Additional Accuracy Support/g,"cn":"额外命中(辅)"},
{"en":/Concentrated Effect Support/g,"cn":"集中效应(辅)"},
{"en":/Return Projectiles Support/g,"cn":"投射物归返(辅)"},
{"en":/Slower Projectiles Support/g,"cn":"投射物减速(辅)"},
{"en":/Faster Projectiles Support/g,"cn":"快速投射(辅)"},
{"en":/Life Gain on Hit Support/g,"cn":"击中生命回复(辅)"},
{"en":/Split Projectiles Support/g,"cn":"投射物分裂(辅)"},
{"en":/Cast when Stunned Support/g,"cn":"晕眩时施放(辅)"},
{"en":/Void Manipulation Support/g,"cn":"虚空操纵(辅)"},
{"en":/Deadly Ailments Support/g,"cn":"致命异常状态(辅)"},
{"en":/Chance to Ignite Support/g,"cn":"几率点燃(辅)"},
{"en":/Fire Penetration Support/g,"cn":"火焰穿透(辅)"},
{"en":/Cold Penetration Support/g,"cn":"冰霜穿透(辅)"},
{"en":/Burning Damage Support/g,"cn":"增加燃烧伤害(辅)"},
{"en":/Swift Affliction Support/g,"cn":"极速腐化(辅)"},
{"en":/Unbound Ailments Support/g,"cn":"异常爆发(辅)"},
{"en":/Item Quantity Support/g,"cn":"物品数量增幅(辅)"},
{"en":/Less Duration Support/g,"cn":"持续时间缩短(辅)"},
{"en":/Elemental Focus Support/g,"cn":"元素集中(辅)"},
{"en":/Chance to Bleed Support/g,"cn":"几率流血(辅)"},
{"en":/Spell Cascade Support/g,"cn":"多重范围施法(辅)"},
{"en":/Faster Attacks Support/g,"cn":"快速攻击(辅)"},
{"en":/Item Rarity Support/g,"cn":"物品稀有度增幅(辅)"},
{"en":/Faster Casting Support/g,"cn":"快速施法(辅)"},
{"en":/Chance to Flee Support/g,"cn":"几率逃跑(辅)"},
{"en":/Melee Splash Support/g,"cn":"近战伤害扩散(辅)"},
{"en":/Curse On Hit Support/g,"cn":"击中附加诅咒(辅)"},
{"en":/Multiple Traps Support/g,"cn":"多重陷阱(辅)"},
{"en":/Cast on Death Support/g,"cn":"死亡时施放(辅)"},
{"en":/Ancestral Call Support/g,"cn":"先祖呼唤(辅)"},
{"en":/Vaal Lightning Strike/g,"cn":"瓦尔.闪电打击"},
{"en":/Cold to Fire Support/g,"cn":"寒冰转烈焰(辅)"},
{"en":/Cluster Traps Support/g,"cn":"散弹陷阱(辅)"},
{"en":/Trap Cooldown Support/g,"cn":"陷阱冷却(辅)"},
{"en":/Lesser Poison Support/g,"cn":"低阶毒化(辅)"},
{"en":/Mirage Archer Support/g,"cn":"幻影射手(辅)"},
{"en":/Reduced Mana Support/g,"cn":"魔力减免(辅)"},
{"en":/Culling Strike Support/g,"cn":"终结(辅)"},
{"en":/Vaal Soul Harvesting/g,"cn":"瓦尔.灵魂收割"},
{"en":/Arcane Surge Support/g,"cn":"秘术增强(辅)"},
{"en":/Vaal Righteous Fire/g,"cn":"瓦尔.正义之火"},
{"en":/Vaal Glacial Hammer/g,"cn":"瓦尔.冰霜之锤"},
{"en":/Old Phase Run/g,"cn":"Old Phase Run"},
{"en":/Vaal Lightning Warp/g,"cn":"瓦尔.闪电传送"},
{"en":/Vaal Lightning Trap/g,"cn":"瓦尔.闪电陷阱"},
{"en":/Vaal Spectral Throw/g,"cn":"瓦尔.灵体投掷"},
{"en":/Ancestral Blademaster/g,"cn":"先祖大剑师"},
{"en":/Elemental Projectiles/g,"cn":"元素投掷物"},
{"en":/Point Blank Support/g,"cn":"零点射击(辅)"},
{"en":/Spell Totem Support/g,"cn":"法术图腾(辅)"},
{"en":/Remote Mine Support/g,"cn":"遥控地雷(辅)"},
{"en":/Multistrike Support/g,"cn":"多重打击(辅)"},
{"en":/Spectral Shield Throw/g,"cn":"灵盾投掷"},
{"en":/Vaal Double Strike/g,"cn":"瓦尔.双重打击"},
{"en":/Vaal Immortal Call/g,"cn":"瓦尔.不朽怒嚎"},
{"en":/Vaal Burning Arrow/g,"cn":"瓦尔.燃烧箭矢"},
{"en":/Life Leech Support/g,"cn":"生命偷取(辅)"},
{"en":/Mana Leech Support/g,"cn":"魔力偷取(辅)"},
{"en":/Blood Magic Support/g,"cn":"血魔法(辅)"},
{"en":/Spell Echo Support/g,"cn":"施法回响(辅)"},
{"en":/Storm Barrier Support/g,"cn":"风暴屏障"},
{"en":/Vaal Detonate Dead/g,"cn":"瓦尔.爆灵术"},
{"en":/Projectile Weakness/g,"cn":"投射物要害"},
{"en":/Vaal Rain of Arrows/g,"cn":"瓦尔.箭雨"},
{"en":/Vaal Molten Shell/g,"cn":"瓦尔.熔岩护盾"},
{"en":/Vaal Power Siphon/g,"cn":"瓦尔.力量抽取"},
{"en":/Iron Grip Support/g,"cn":"钢铁之握(辅)"},
{"en":/Iron Will Support/g,"cn":"钢铁意志(辅)"},
{"en":/Blasphemy Support/g,"cn":"诅咒光环(辅)"},
{"en":/Hypothermia Support/g,"cn":"急冻(辅)"},
{"en":/Vile Toxins Support/g,"cn":"猛毒(辅)"},
{"en":/Vaal Ground Slam/g,"cn":"瓦尔.裂地之击"},
{"en":/Purity of Lightning/g,"cn":"闪电净化"},
{"en":/Righteous Lightning/g,"cn":"正义怒雷"},
{"en":/Ancestral Protector/g,"cn":"先祖卫士"},
{"en":/Ancestral Warchief/g,"cn":"先祖战士长"},
{"en":/Generosity Support/g,"cn":"和善(辅)"},
{"en":/Minefield Support/g,"cn":"地雷网(辅)"},
{"en":/Elemental Weakness/g,"cn":"元素要害"},
{"en":/Vaal Heavy Strike/g,"cn":"瓦尔.重击"},
{"en":/Purity of Elements/g,"cn":"元素净化"},
{"en":/Rejuvenation Totem/g,"cn":"回春图腾"},
{"en":/Vaal Storm Call/g,"cn":"瓦尔.风暴呼唤"},
{"en":/Vaal Flameblast/g,"cn":"瓦尔.烈焰爆破"},
{"en":/Lightning Tendrils/g,"cn":"电能释放"},
{"en":/Knockback Support/g,"cn":"击退(辅)"},
{"en":/Bloodlust Support/g,"cn":"嗜血(辅)"},
{"en":/WIP Support/g,"cn":"WIP Support"},
{"en":/Enlighten Support/g,"cn":"启蒙(辅)"},
{"en":/Innervate Support/g,"cn":"闪电支配(辅)"},
{"en":/Brutality Support/g,"cn":"残暴(辅)"},
{"en":/Onslaught Support/g,"cn":"猛攻(辅)"},
{"en":/Herald of Thunder/g,"cn":"闪电之捷"},
{"en":/Lightning Channel/g,"cn":"闪电链结"},
{"en":/New Blade Vortex/g,"cn":"新飞刃风暴"},
{"en":/Ice Bite Support/g,"cn":"霜咬(辅)"},
{"en":/Efficacy Support/g,"cn":"效能(辅)"},
{"en":/Immolate Support/g,"cn":"献祭(辅)"},
{"en":/Ruthless Support/g,"cn":"无情(辅)"},
{"en":/Vaal Ice Nova/g,"cn":"瓦尔.冰霜新星"},
{"en":/New Shock Nova/g,"cn":"新式闪电新星"},
{"en":/Lightning Strike/g,"cn":"闪电打击"},
{"en":/Vaal Discipline/g,"cn":"瓦尔.纪律"},
{"en":/Vaal FireTrap/g,"cn":"瓦尔.火焰陷阱"},
{"en":/Animate Guardian/g,"cn":"幻化守卫"},
{"en":/Fire Nova Mine/g,"cn":"火焰新星地雷"},
{"en":/Lightning Circle/g,"cn":"雷霆之环"},
{"en":/Empower Support/g,"cn":"赋予(辅)"},
{"en":/Enhance Support/g,"cn":"增幅(辅)"},
{"en":/Fortify Support/g,"cn":"护体(辅)"},
{"en":/Whirling Blades/g,"cn":"回旋之刃"},
{"en":/Vaal Cold Snap/g,"cn":"瓦尔.霜暴"},
{"en":/Damage Infusion/g,"cn":"伤害灌注"},
{"en":/Explosive Arrow/g,"cn":"爆炸箭矢"},
{"en":/Temporal Chains/g,"cn":"时空锁链"},
{"en":/Assassin's Mark/g,"cn":"暗影印记"},
{"en":/Dominating Blow/g,"cn":"霸气之击"},
{"en":/Lightning Arrow/g,"cn":"闪电箭矢"},
{"en":/Shockwave Totem/g,"cn":"震波图腾"},
{"en":/Conversion Trap/g,"cn":"迷魅陷阱"},
{"en":/Devouring Totem/g,"cn":"吞噬图腾"},
{"en":/Ethereal Knives/g,"cn":"虚空匕首"},
{"en":/Spirit Offering/g,"cn":"灵魂奉献"},
{"en":/Glacial Cascade/g,"cn":"冰川之刺"},
{"en":/Herald of Blood/g,"cn":"赤血之捷"},
{"en":/Poacher's Mark/g,"cn":"盗猎者印记"},
{"en":/Vigilant Strike/g,"cn":"戒备打击"},
{"en":/Pierce Support/g,"cn":"穿透(辅)"},
{"en":/Poison Support/g,"cn":"毒化(辅)"},
{"en":/Volley Support/g,"cn":"齐射(辅)"},
{"en":/Vaal Fireball/g,"cn":"瓦尔.火球"},
{"en":/Righteous Fire/g,"cn":"正义之火"},
{"en":/Flicker Strike/g,"cn":"闪现打击"},
{"en":/Glacial Hammer/g,"cn":"冰霜之锤"},
{"en":/Freezing Pulse/g,"cn":"冰霜脉冲"},
{"en":/Warlord's Mark/g,"cn":"督军印记"},
{"en":/Lightning Warp/g,"cn":"闪电传送"},
{"en":/Tempest Shield/g,"cn":"暴风之盾"},
{"en":/Detonate Mines/g,"cn":"引爆地雷"},
{"en":/Vaal Cyclone/g,"cn":"瓦尔.旋风斩"},
{"en":/Lightning Trap/g,"cn":"闪电陷阱"},
{"en":/Spectral Throw/g,"cn":"灵体投掷"},
{"en":/Animate Weapon/g,"cn":"幻化武器"},
{"en":/Purity of Fire/g,"cn":"火焰净化"},
{"en":/Ball Lightning/g,"cn":"天雷之珠"},
{"en":/Flesh Offering/g,"cn":"血肉奉献"},
{"en":/Siege Ballista/g,"cn":"攻城炮台"},
{"en":/Blind Support/g,"cn":"致盲(辅)"},
{"en":/Chain Support/g,"cn":"连锁(辅)"},
{"en":/Decay Support/g,"cn":"腐蚀(辅)"},
{"en":/Tectonic Slam/g,"cn":"破釜一击"},
{"en":/Charged Dash/g,"cn":"蓄力疾风闪"},
{"en":/Wand Teleport/g,"cn":"法杖传送"},
{"en":/Shield Charge/g,"cn":"重盾冲锋"},
{"en":/Double Strike/g,"cn":"双重打击"},
{"en":/Elemental Hit/g,"cn":"元素打击"},
{"en":/Immortal Call/g,"cn":"不朽怒嚎"},
{"en":/Caustic Arrow/g,"cn":"腐蚀箭矢"},
{"en":/Infernal Blow/g,"cn":"炼狱之击"},
{"en":/Burning Arrow/g,"cn":"燃烧箭矢"},
{"en":/Vaal Clarity/g,"cn":"瓦尔.清晰"},
{"en":/Arctic Breath/g,"cn":"极地吐息"},
{"en":/Arctic Armour/g,"cn":"极地装甲"},
{"en":/Purity of Ice/g,"cn":"冰霜净化"},
{"en":/Bone Offering/g,"cn":"骸骨奉献"},
{"en":/Molten Strike/g,"cn":"熔岩之击"},
{"en":/Herald of Ash/g,"cn":"灰烬之捷"},
{"en":/Herald of Ice/g,"cn":"寒冰之捷"},
{"en":/Kinetic Blast/g,"cn":"力量爆破"},
{"en":/Static Strike/g,"cn":"充能打击"},
{"en":/Shrapnel Shot/g,"cn":"流星射击"},
{"en":/Static Tether/g,"cn":"静电锁链"},
{"en":/Orb of Storms/g,"cn":"风暴漩涡"},
{"en":/Essence Drain/g,"cn":"灵魂吸取"},
{"en":/Shadow Blades/g,"cn":"幻影之刃"},
{"en":/Scorching Ray/g,"cn":"灼热光线"},
{"en":/Stun Support/g,"cn":"击晕(辅)"},
{"en":/Trap Support/g,"cn":"陷阱(辅)"},
{"en":/Fork Support/g,"cn":"分裂(辅)"},
{"en":/Maim Support/g,"cn":"瘫痪(辅)"},
{"en":/Volatile Dead/g,"cn":"灵体火球"},
{"en":/Blade Flurry/g,"cn":"刀刃乱舞"},
{"en":/Enduring Cry/g,"cn":"坚决战吼"},
{"en":/Detonate Dead/g,"cn":"爆灵术"},
{"en":/Raise Zombie/g,"cn":"魔卫复苏"},
{"en":/Vaal Breach/g,"cn":"瓦尔.裂隙"},
{"en":/Viper Strike/g,"cn":"毒蛇打击"},
{"en":/NewPunishment/g,"cn":"新惩戒"},
{"en":/Rain of Arrows/g,"cn":"箭雨"},
{"en":/Molten Shell/g,"cn":"熔岩护盾"},
{"en":/Power Siphon/g,"cn":"力量抽取"},
{"en":/Searing Bond/g,"cn":"灼热连接"},
{"en":/Vaal Reave/g,"cn":"瓦尔.冲击波"},
{"en":/Tornado Shot/g,"cn":"龙卷射击"},
{"en":/Touch of God/g,"cn":"天谴之拳"},
{"en":/Mirror Arrow/g,"cn":"魅影射击"},
{"en":/Rallying Cry/g,"cn":"激励战吼"},
{"en":/Frost Blades/g,"cn":"冰霜之刃"},
{"en":/Blade Vortex/g,"cn":"飞刃风暴"},
{"en":/Vaal Sweep/g,"cn":"瓦尔.横扫"},
{"en":/Ground Slam/g,"cn":"裂地之击"},
{"en":/Dual Strike/g,"cn":"双持打击"},
{"en":/Split Arrow/g,"cn":"分裂箭矢"},
{"en":/Fire Weapon/g,"cn":"烈焰武器"},
{"en":/Vaal Spark/g,"cn":"瓦尔.电球"},
{"en":/Vulnerability/g,"cn":"脆弱"},
{"en":/Vaal Haste/g,"cn":"瓦尔.迅捷"},
{"en":/Vaal Grace/g,"cn":"瓦尔.优雅"},
{"en":/Determination/g,"cn":"坚定"},
{"en":/Freeze Mine/g,"cn":"冰冻地雷"},
{"en":/Decoy Totem/g,"cn":"诱饵图腾"},
{"en":/Flame Totem/g,"cn":"火舌图腾"},
{"en":/Storm Burst/g,"cn":"裂风雷球"},
{"en":/Vortex Mine/g,"cn":"漩涡地雷"},
{"en":/Flame Surge/g,"cn":"怒焰奔腾"},
{"en":/Blink Arrow/g,"cn":"闪现射击"},
{"en":/Abyssal Cry/g,"cn":"深渊战吼"},
{"en":/Wild Strike/g,"cn":"野性打击"},
{"en":/Blood Rage/g,"cn":"鲜血狂怒"},
{"en":/Shock Nova/g,"cn":"闪电新星"},
{"en":/Heavy Strike/g,"cn":"重击"},
{"en":/Blade Trap/g,"cn":"利刃陷阱"},
{"en":/Flammability/g,"cn":"易燃"},
{"en":/Conductivity/g,"cn":"导电"},
{"en":/Smoke Mine/g,"cn":"烟雾地雷"},
{"en":/Storm Call/g,"cn":"风暴呼唤"},
{"en":/Flameblast/g,"cn":"烈焰爆破"},
{"en":/Flame Dash/g,"cn":"烈焰冲刺"},
{"en":/Blast Rain/g,"cn":"爆裂箭雨"},
{"en":/Phase Run/g,"cn":"暗影迷踪"},
{"en":/Firestorm/g,"cn":"烈炎风暴"},
{"en":/Bear Trap/g,"cn":"捕熊陷阱"},
{"en":/Fire Trap/g,"cn":"火焰陷阱"},
{"en":/Vaal Arc/g,"cn":"瓦尔.电弧"},
{"en":/Convocation/g,"cn":"号召"},
{"en":/Ice Crash/g,"cn":"寒冰冲击"},
{"en":/Magma Orb/g,"cn":"熔岩之核"},
{"en":/Bladefall/g,"cn":"虚空刀雨"},
{"en":/Frost Bomb/g,"cn":"寒霜爆"},
{"en":/Dark Pact/g,"cn":"暗夜血契"},
{"en":/Ice Nova/g,"cn":"冰霜新星"},
{"en":/Frost Wall/g,"cn":"冰墙"},
{"en":/Punishment/g,"cn":"惩戒"},
{"en":/Discipline/g,"cn":"纪律"},
{"en":/Ice Shot/g,"cn":"冰霜射击"},
{"en":/Incinerate/g,"cn":"烧毁"},
{"en":/Wildfire/g,"cn":"地狱火群"},
{"en":/Ice Trap/g,"cn":"冰冻陷阱"},
{"en":/Earthquake/g,"cn":"震地"},
{"en":/Frostbolt/g,"cn":"寒冰弹"},
{"en":/Bodyswap/g,"cn":"灵体转换"},
{"en":/Leap Slam/g,"cn":"跃击"},
{"en":/Lacerate/g,"cn":"破空斩"},
{"en":/Cold Snap/g,"cn":"霜暴"},
{"en":/Discharge/g,"cn":"解放"},
{"en":/Ice Spear/g,"cn":"冰矛"},
{"en":/Frostbite/g,"cn":"冻伤"},
{"en":/Desecrate/g,"cn":"亵渎"},
{"en":/Reckoning/g,"cn":"清算"},
{"en":/Vengeance/g,"cn":"复仇"},
{"en":/Contagion/g,"cn":"瘟疫"},
{"en":/Unearth/g,"cn":"亵渎之矛"},
{"en":/Cremation/g,"cn":"火葬"},
{"en":/Fireball/g,"cn":"火球"},
{"en":/Portal/g,"cn":"时空之门"},
{"en":/Backstab/g,"cn":"背刺"},
{"en":/Enfeeble/g,"cn":"衰弱"},
{"en":/Puncture/g,"cn":"放血"},
{"en":/Vitality/g,"cn":"活力"},
{"en":/Cyclone/g,"cn":"旋风斩"},
{"en":/Wither/g,"cn":"死亡凋零"},
{"en":/Sunder/g,"cn":"大地震击"},
{"en":/Despair/g,"cn":"绝望"},
{"en":/Icefire/g,"cn":"霜火"},
{"en":/Riptide/g,"cn":"激流"},
{"en":/Clarity/g,"cn":"清晰"},
{"en":/Barrage/g,"cn":"弹幕"},
{"en":/Riposte/g,"cn":"击刃"},
{"en":/Cleave/g,"cn":"劈砍"},
{"en":/Frenzy/g,"cn":"狂怒"},
{"en":/Ignite/g,"cn":"点燃"},
{"en":/Hatred/g,"cn":"憎恨"},
{"en":/Reave/g,"cn":"冲击波"},
{"en":/Blight/g,"cn":"枯萎"},
{"en":/Vortex/g,"cn":"漩涡"},
{"en":/Sweep/g,"cn":"横扫"},
{"en":/Snipe/g,"cn":"狙击"},
{"en":/Spark/g,"cn":"电球"},
{"en":/Haste/g,"cn":"迅捷"},
{"en":/Grace/g,"cn":"优雅"},
{"en":/Anger/g,"cn":"愤怒"},
{"en":/Wrath/g,"cn":"雷霆"},
{"en":/WIP/g,"cn":"WIP"},
{"en":/Arc/g,"cn":"电弧"},
];