var gemJson=[
{"en":/Added Fire Damage Support/g,"cn":"附加火焰伤害辅助"},
{"en":/Knockback Support/g,"cn":"击退辅助"},
{"en":/Stun Support/g,"cn":"击晕辅助"},
{"en":/Life Gain on Hit Support/g,"cn":"击中生命回复辅助"},
{"en":/Spell Totem Support/g,"cn":"法术图腾辅助"},
{"en":/Ranged Attack Totem Support/g,"cn":"远距离攻击图腾辅助"},
{"en":/Melee Splash Support/g,"cn":"近战伤害扩散辅助"},
{"en":/Melee Physical Damage Support/g,"cn":"近战物理伤害辅助"},
{"en":/Cold to Fire Support/g,"cn":"寒冰转烈焰辅助"},
{"en":/Weapon Elemental Damage Support/g,"cn":"武器元素伤害辅助"},
{"en":/Iron Grip Support/g,"cn":"钢铁之握辅助"},
{"en":/Iron Will Support/g,"cn":"钢铁意志辅助"},
{"en":/Melee Damage on Full Life Support/g,"cn":"满血近战物理伤害辅助"},
{"en":/Endurance Charge on Melee Stun Support/g,"cn":"近战击晕获得耐力球辅助"},
{"en":/Bloodlust Support/g,"cn":"嗜血辅助"},
{"en":/Item Quantity Support/g,"cn":"物品数量增幅辅助"},
{"en":/Reduced Mana Support/g,"cn":"魔力减免辅助"},
{"en":/Life Leech Support/g,"cn":"生命偷取辅助"},
{"en":/Increased Duration Support/g,"cn":"持续时间延长辅助"},
{"en":/Blood Magic Support/g,"cn":"血魔法辅助"},
{"en":/Fire Penetration Support/g,"cn":"火焰穿透辅助"},
{"en":/Increased Burning Damage Support/g,"cn":"增加燃烧伤害辅助"},
{"en":/Less Duration Support/g,"cn":"持续时间缩短辅助"},
{"en":/Generosity Support/g,"cn":"和善辅助"},
{"en":/Fortify Support/g,"cn":"护体辅助"},
{"en":/Multistrike Support/g,"cn":"多重打击辅助"},
{"en":/Cast on Melee Kill Support/g,"cn":"近战击杀时施放辅助"},
{"en":/Cast when Damage Taken Support/g,"cn":"受伤时施放辅助"},
{"en":/Empower Support/g,"cn":"赋予辅助"},
{"en":/Lesser Multiple Projectiles Support/g,"cn":"低阶多重投射辅助"},
{"en":/Added Cold Damage Support/g,"cn":"附加冰冷伤害辅助"},
{"en":/Additional Accuracy Support/g,"cn":"额外命中辅助"},
{"en":/Trap Support/g,"cn":"陷阱辅助"},
{"en":/Chance to Flee Support/g,"cn":"机率逃跑辅助"},
{"en":/Blind Support/g,"cn":"致盲辅助"},
{"en":/Multiple Traps Support/g,"cn":"多重陷阱辅助"},
{"en":/Void Manipulation Support/g,"cn":"虚空操纵辅助"},
{"en":/Faster Attacks Support/g,"cn":"快速攻击辅助"},
{"en":/Culling Strike Support/g,"cn":"扑杀辅助"},
{"en":/Point Blank Support/g,"cn":"零点射击辅助"},
{"en":/Physical Projectile Attack Damage Support/g,"cn":"物理投射物攻击伤害辅助"},
{"en":/Block Chance Reduction Support/g,"cn":"减少格挡率辅助"},
{"en":/Trap and Mine Damage Support/g,"cn":"陷阱及地雷伤害辅助"},
{"en":/Faster Projectiles Support/g,"cn":"快速投射辅助"},
{"en":/Mana Leech Support/g,"cn":"魔力偷取辅助"},
{"en":/Pierce Support/g,"cn":"穿透辅助"},
{"en":/Cold Penetration Support/g,"cn":"冰冷穿透辅助"},
{"en":/Fork Support/g,"cn":"分裂辅助"},
{"en":/Slower Projectiles Support/g,"cn":"投射物减速辅助"},
{"en":/Ice Bite Support/g,"cn":"霜咬辅助"},
{"en":/Hypothermia Support/g,"cn":"急冻辅助"},
{"en":/Poison Support/g,"cn":"毒化辅助"},
{"en":/Rapid Decay Support/g,"cn":"极速腐化辅助"},
{"en":/Trap Cooldown Support/g,"cn":"陷阱冷却辅助"},
{"en":/Greater Multiple Projectiles Support/g,"cn":"高阶多重投射辅助"},
{"en":/Chain Support/g,"cn":"连锁辅助"},
{"en":/Cast On Critical Strike Support/g,"cn":"暴击时施放辅助"},
{"en":/Cast on Death Support/g,"cn":"死亡时施放辅助"},
{"en":/Cluster Traps Support/g,"cn":"散弹陷阱辅助"},
{"en":/Enhance Support/g,"cn":"增幅辅助"},
{"en":/Added Lightning Damage Support/g,"cn":"附加闪电伤害辅助"},
{"en":/Increased Critical Strikes Support/g,"cn":"增加暴击机率辅助"},
{"en":/Minion Damage Support/g,"cn":"召唤物伤害辅助"},
{"en":/Remote Mine Support/g,"cn":"遥控地雷辅助"},
{"en":/Minefield Support/g,"cn":"地雷网辅助"},
{"en":/Increased Critical Damage Support/g,"cn":"增加暴击伤害辅助"},
{"en":/Faster Casting Support/g,"cn":"快速施法辅助"},
{"en":/Concentrated Effect Support/g,"cn":"集中效应辅助"},
{"en":/Minion Speed Support/g,"cn":"召唤物速度辅助"},
{"en":/Minion Life Support/g,"cn":"召唤物生命辅助"},
{"en":/Power Charge On Critical Support/g,"cn":"暴击获得暴击球辅助"},
{"en":/Physical to Lightning Support/g,"cn":"物理转闪电辅助"},
{"en":/Controlled Destruction Support/g,"cn":"精准破坏辅助"},
{"en":/Elemental Focus Support/g,"cn":"元素集中辅助"},
{"en":/Added Chaos Damage Support/g,"cn":"附加混沌伤害辅助"},
{"en":/Item Rarity Support/g,"cn":"物品希有度增幅辅助"},
{"en":/Chance to Ignite Support/g,"cn":"机率点燃辅助"},
{"en":/Lightning Penetration Support/g,"cn":"闪电穿透辅助"},
{"en":/Minion and Totem Elemental Resistance Support/g,"cn":"召唤物与图腾元素抗性辅助"},
{"en":/Innervate Support/g,"cn":"亢奋辅助"},
{"en":/Blasphemy Support/g,"cn":"诅咒光环辅助"},
{"en":/Increased Area of Effect Support/g,"cn":"增大范围辅助"},
{"en":/Elemental Proliferation Support/g,"cn":"元素扩散辅助"},
{"en":/Spell Echo Support/g,"cn":"施法回响辅助"},
{"en":/Curse On Hit Support/g,"cn":"击中附加诅咒辅助"},
{"en":/Cast when Stunned Support/g,"cn":"晕眩时施放辅助"},
{"en":/Cast while Channelling Support/g,"cn":"引导时施放辅助"},
{"en":/Enlighten Support/g,"cn":"启蒙辅助"},

{"en":/Vaal Ground Slam/g,"cn":"瓦尔.裂地之击"},
{"en":/Vaal Glacial Hammer/g,"cn":"瓦尔.冰霜之锤"},
{"en":/Vaal Molten Shell/g,"cn":"瓦尔.熔岩护盾"},
{"en":/Vaal Lightning Strike/g,"cn":"瓦尔.闪电打击"},
{"en":/Vaal Immortal Call/g,"cn":"瓦尔.不朽怒嚎"},
{"en":/Vaal Burning Arrow/g,"cn":"瓦尔.燃烧箭矢"},
{"en":/Vaal Spectral Throw/g,"cn":"瓦尔.灵体投掷"},
{"en":/Vaal Double Strike/g,"cn":"瓦尔.双重打击"},
{"en":/Vaal Detonate Dead/g,"cn":"瓦尔.尸体爆破"},
{"en":/Vaal Rain of Arrows/g,"cn":"瓦尔.箭雨"},
{"en":/Vaal Reave/g,"cn":"瓦尔.冲击波"},
{"en":/Vaal Grace/g,"cn":"瓦尔.优雅"},
{"en":/Vaal Haste/g,"cn":"瓦尔.迅捷"},
{"en":/Vaal Cyclone/g,"cn":"瓦尔.旋风斩"},
{"en":/Vaal Fireball/g,"cn":"瓦尔.火球"},
{"en":/Vaal Spark/g,"cn":"瓦尔.电球"},
{"en":/Vaal Cold Snap/g,"cn":"瓦尔.霜暴"},
{"en":/Vaal Lightning Warp/g,"cn":"瓦尔.闪电传送"},
{"en":/Vaal Summon Skeletons/g,"cn":"瓦尔.召唤骷髅"},
{"en":/Vaal Clarity/g,"cn":"瓦尔.清晰"},
{"en":/Vaal Arc/g,"cn":"瓦尔.电弧"},
{"en":/Vaal Power Siphon/g,"cn":"瓦尔.力量抽取"},
{"en":/Vaal Ice Nova/g,"cn":"瓦尔.冰霜新星"},
{"en":/Vaal Storm Call/g,"cn":"瓦尔.风暴呼唤"},
{"en":/Vaal Lightning Trap/g,"cn":"瓦尔.闪电陷阱"},
{"en":/Vaal Righteous Fire/g,"cn":"瓦尔.正义之火"},
{"en":/Vaal Discipline/g,"cn":"瓦尔.纪律"},
{"en":/Vaal Flameblast/g,"cn":"瓦尔.烈焰爆破"},
{"en":/Detonate Mines/g,"cn":"引爆地雷"},
{"en":/Portal/g,"cn":"时空之门"},
{"en":/Vaal Breach/g,"cn":"瓦尔.裂痕"},
{"en":/Cleave/g,"cn":"劈砍"},
{"en":/Infernal Blow/g,"cn":"炼狱之击"},
{"en":/Glacial Hammer/g,"cn":"冰霜之锤"},
{"en":/Heavy Strike/g,"cn":"重击"},
{"en":/Molten Strike/g,"cn":"熔岩之击"},
{"en":/Molten Shell/g,"cn":"熔岩护盾"},
{"en":/Rejuvenation Totem/g,"cn":"回春图腾"},
{"en":/Decoy Totem/g,"cn":"诱饵图腾"},
{"en":/Devouring Totem/g,"cn":"吞噬图腾"},
{"en":/Flame Totem/g,"cn":"火舌图腾"},
{"en":/Reckoning/g,"cn":"清算"},
{"en":/Vigilant Strike/g,"cn":"戒备打击"},
{"en":/Ancestral Protector/g,"cn":"先祖卫士"},
{"en":/Leap Slam/g,"cn":"跃击"},
{"en":/Shield Charge/g,"cn":"重盾冲锋"},
{"en":/Rallying Cry/g,"cn":"激励战吼"},
{"en":/Sweep/g,"cn":"横扫"},
{"en":/Searing Bond/g,"cn":"灼热连接"},
{"en":/Static Strike/g,"cn":"充能打击"},
{"en":/Sunder/g,"cn":"大地震击"},
{"en":/Enduring Cry/g,"cn":"坚决战吼"},
{"en":/Herald Of Ash/g,"cn":"灰烬之捷"},
{"en":/Warlord's Mark/g,"cn":"督军印记"},
{"en":/Punishment/g,"cn":"惩戒"},
{"en":/Vitality/g,"cn":"活力"},
{"en":/Determination/g,"cn":"坚定"},
{"en":/Anger/g,"cn":"愤怒"},
{"en":/Purity of Fire/g,"cn":"火焰净化"},
{"en":/Vengeance/g,"cn":"复仇"},
{"en":/Dominating Blow/g,"cn":"霸气之击"},
{"en":/Shockwave Totem/g,"cn":"震波图腾"},
{"en":/Animate Guardian/g,"cn":"幻化守卫"},
{"en":/Ice Crash/g,"cn":"寒冰冲击"},
{"en":/Earthquake/g,"cn":"震地"},
{"en":/Ancestral Warchief/g,"cn":"先祖战士长"},
{"en":/Immortal Call/g,"cn":"不朽怒嚎"},
{"en":/Summon Flame Golem/g,"cn":"召唤烈焰魔像"},
{"en":/Abyssal Cry/g,"cn":"深渊战吼"},
{"en":/Summon Stone Golem/g,"cn":"召唤巨石魔像"},
{"en":/Double Strike/g,"cn":"双重打击"},
{"en":/Elemental Hit/g,"cn":"元素打击"},
{"en":/Dual Strike/g,"cn":"双持打击"},
{"en":/Ice Shot/g,"cn":"冰霜射击"},
{"en":/Split Arrow/g,"cn":"分裂箭矢"},
{"en":/Viper Strike/g,"cn":"毒蛇打击"},
{"en":/Burning Arrow/g,"cn":"燃烧箭矢"},
{"en":/Fire Trap/g,"cn":"火焰陷阱"},
{"en":/Ethereal Knives/g,"cn":"虚空匕首"},
{"en":/Spectral Throw/g,"cn":"灵体投掷"},
{"en":/Frost Blades/g,"cn":"冰霜之刃"},
{"en":/Shrapnel Shot/g,"cn":"流星射击"},
{"en":/Detonate Dead/g,"cn":"尸体爆破"},
{"en":/Caustic Arrow/g,"cn":"腐蚀箭矢"},
{"en":/Puncture/g,"cn":"放血"},
{"en":/Bear Trap/g,"cn":"捕熊陷阱"},
{"en":/Animate Weapon/g,"cn":"幻化武器"},
{"en":/Riposte/g,"cn":"击刃"},
{"en":/Siege Ballista/g,"cn":"攻城炮台"},
{"en":/Whirling Blades/g,"cn":"回旋之刃"},
{"en":/Flicker Strike/g,"cn":"闪现打击"},
{"en":/Freeze Mine/g,"cn":"冰冻地雷"},
{"en":/Smoke Mine/g,"cn":"烟雾地雷"},
{"en":/Blink Arrow/g,"cn":"闪现射击"},
{"en":/Mirror Arrow/g,"cn":"魅影射击"},
{"en":/Rain of Arrows/g,"cn":"箭雨"},
{"en":/Lightning Strike/g,"cn":"闪电打击"},
{"en":/Lightning Arrow/g,"cn":"闪电箭矢"},
{"en":/Reave/g,"cn":"冲击波"},
{"en":/Barrage/g,"cn":"弹幕"},
{"en":/Blade Vortex/g,"cn":"飞刃风暴"},
{"en":/Lacerate/g,"cn":"破空斩"},
{"en":/Frenzy/g,"cn":"狂怒"},
{"en":/Blood Rage/g,"cn":"鲜血狂怒"},
{"en":/Arctic Armour/g,"cn":"极地装甲"},
{"en":/Desecrate/g,"cn":"亵渎"},
{"en":/Herald Of Ice/g,"cn":"冰霜之捷"},
{"en":/Temporal Chains/g,"cn":"时空锁链"},
{"en":/Projectile Weakness/g,"cn":"投射物要害"},
{"en":/Haste/g,"cn":"迅捷"},
{"en":/Grace/g,"cn":"优雅"},
{"en":/Hatred/g,"cn":"憎恨"},
{"en":/Purity of Ice/g,"cn":"冰霜净化"},
{"en":/Poacher's Mark/g,"cn":"盗猎者印记"},
{"en":/Explosive Arrow/g,"cn":"爆炸箭矢"},
{"en":/Cyclone/g,"cn":"旋风斩"},
{"en":/Tornado Shot/g,"cn":"龙卷射击"},
{"en":/Wild Strike/g,"cn":"野性打击"},
{"en":/Bladefall/g,"cn":"虚空刀雨"},
{"en":/Blast Rain/g,"cn":"爆裂箭雨"},
{"en":/Ice Trap/g,"cn":"冰冻陷阱"},
{"en":/Blade Flurry/g,"cn":"刀锋乱舞"},
{"en":/Phase Run/g,"cn":"暗影迷踪"},
{"en":/Summon Ice Golem/g,"cn":"召唤寒冰魔像"},
{"en":/Fireball/g,"cn":"火球"},
{"en":/Raise Zombie/g,"cn":"僵尸复苏"},
{"en":/Spark/g,"cn":"电球"},
{"en":/Freezing Pulse/g,"cn":"冰霜脉冲"},
{"en":/Lightning Tendrils/g,"cn":"电能释放"},
{"en":/Magma Orb/g,"cn":"熔岩之核"},
{"en":/Frostbolt/g,"cn":"寒冰弹"},
{"en":/Blight/g,"cn":"萎灭"},
{"en":/Cold Snap/g,"cn":"霜暴"},
{"en":/Frost Wall/g,"cn":"冰墙"},
{"en":/Conversion Trap/g,"cn":"迷魅陷阱"},
{"en":/Summon Raging Spirit/g,"cn":"召唤愤怒狂灵"},
{"en":/Contagion/g,"cn":"瘟疫"},
{"en":/Frost Bomb/g,"cn":"寒霜爆"},
{"en":/Orb of Storms/g,"cn":"风暴漩涡"},
{"en":/Lightning Warp/g,"cn":"闪电传送"},
{"en":/Summon Skeletons/g,"cn":"召唤骷髅"},
{"en":/Clarity/g,"cn":"清晰"},
{"en":/Flame Dash/g,"cn":"烈焰冲刺"},
{"en":/Wither/g,"cn":"死亡凋零"},
{"en":/Ice Nova/g,"cn":"冰霜新星"},
{"en":/Ice Spear/g,"cn":"冰矛"},
{"en":/Firestorm/g,"cn":"烈炎风暴"},
{"en":/Power Siphon/g,"cn":"力量抽取"},
{"en":/Arc/g,"cn":"电弧"},
{"en":/Incinerate/g,"cn":"烧毁"},
{"en":/Lightning Trap/g,"cn":"闪电陷阱"},
{"en":/Storm Call/g,"cn":"风暴呼唤"},
{"en":/Flame Surge/g,"cn":"怒焰奔腾"},
{"en":/Flesh Offering/g,"cn":"血肉奉献"},
{"en":/Bone Offering/g,"cn":"骸骨奉献"},
{"en":/Fire Nova Mine/g,"cn":"火焰新星地雷"},
{"en":/Essence Drain/g,"cn":"灵魂吸取"},
{"en":/Spirit Offering/g,"cn":"灵魂奉献"},
{"en":/Scorching Ray/g,"cn":"炽灼奔流"},
{"en":/Righteous Fire/g,"cn":"正义之火"},
{"en":/Tempest Shield/g,"cn":"暴风之盾"},
{"en":/Herald of Thunder/g,"cn":"闪电之捷"},
{"en":/Elemental Weakness/g,"cn":"元素要害"},
{"en":/Enfeeble/g,"cn":"衰弱"},
{"en":/Vulnerability/g,"cn":"脆弱"},
{"en":/Purity of Elements/g,"cn":"元素净化"},
{"en":/Discipline/g,"cn":"纪律"},
{"en":/Wrath/g,"cn":"雷霆"},
{"en":/Flammability/g,"cn":"易燃"},
{"en":/Frostbite/g,"cn":"冻伤"},
{"en":/Conductivity/g,"cn":"导电"},
{"en":/Purity of Lightning/g,"cn":"闪电净化"},
{"en":/Convocation/g,"cn":"号召"},
{"en":/Assassin's Mark/g,"cn":"刺客印记"},
{"en":/Arctic Breath/g,"cn":"极地吐息"},
{"en":/Discharge/g,"cn":"解放"},
{"en":/Raise Spectre/g,"cn":"唤醒幽魂"},
{"en":/Shock Nova/g,"cn":"闪电新星"},
{"en":/Flameblast/g,"cn":"烈焰爆破"},
{"en":/Ball Lightning/g,"cn":"天雷之珠"},
{"en":/Glacial Cascade/g,"cn":"冰川之刺"},
{"en":/Kinetic Blast/g,"cn":"力量爆破"},
{"en":/Vortex/g,"cn":"旋涡"},
{"en":/Summon Chaos Golem/g,"cn":"召唤混沌魔像"},
{"en":/Summon Lightning Golem/g,"cn":"召唤闪电魔像"}

];