 
 var keyStonesJson= [ 

{"en":/Radiant Crusade/g,"cn":"光明圣战"},
{"en":/Unwavering Crusade/g,"cn":"坚定圣战"},
{"en":/Nature's Reprisal/g,"cn":"大自然的报仇"},
{"en":/Master Toxicist/g,"cn":"毒物大师"},
{"en":/Templar Ascendancy/g,"cn":"圣堂武僧升华职业"},
{"en":/Witch Ascendancy/g,"cn":"女巫升华职业"},
{"en":/Path of the Witch/g,"cn":"女巫之道"},
{"en":/Guardian/g,"cn":"守护者"},
{"en":/Necromancer/g,"cn":"召唤师"},
{"en":/Path of the Ranger/g,"cn":"侠客之道"},
{"en":/Ranger Ascendancy/g,"cn":"游侠升华职业"},
{"en":/Pathfinder/g,"cn":"追猎者"},
{"en":/Elementalist/g,"cn":"元素使"},
{"en":/Path of the Templar/g,"cn":"圣堂武僧之道"},
{"en":/Raider/g,"cn":"侠客"},
{"en":/Path of the Duelist/g,"cn":"决斗者之道"},
{"en":/Duelist Ascendancy/g,"cn":"决斗者升华职业"},
{"en":/Slayer/g,"cn":"处刑"},
{"en":/Shadow Ascendancy/g,"cn":"暗影升华职业"},
{"en":/Assassin/g,"cn":"暗影"},
{"en":/Inquisitor/g,"cn":"判官"},
{"en":/Occultist/g,"cn":"秘术家"},
{"en":/Path of the Shadow/g,"cn":"暗影之道"},
{"en":/Marauder Ascendancy/g,"cn":"野蛮人升华职业"},
{"en":/Path of the Marauder/g,"cn":"野蛮人之道"},
{"en":/Juggernaut/g,"cn":"勇士"},
{"en":/Chieftain/g,"cn":"酋长"},
{"en":/Deadeye/g,"cn":"锐眼"},
{"en":/Saboteur/g,"cn":"破坏者"},
{"en":/Trickster/g,"cn":"欺诈师"},
{"en":/Gladiator/g,"cn":"卫士"},
{"en":/Champion/g,"cn":"冠军"},
{"en":/Hierophant/g,"cn":"圣宗"},
{"en":/Berserker/g,"cn":"暴徒"},
{"en":/Unrelenting/g,"cn":"灭无赦"},
{"en":/Unflinching/g,"cn":"永不动摇"},
{"en":/Undeniable/g,"cn":"不可置疑"},
{"en":/Unbreakable/g,"cn":"坚不可破"},
{"en":/Unstoppable/g,"cn":"势不可挡"},
{"en":/Unyielding/g,"cn":"屹立不摇"},
{"en":/Aspect of Carnage/g,"cn":"血肉之章"},
{"en":/Cloaked in Savagery/g,"cn":"残暴之风"},
{"en":/Pain Reaver/g,"cn":"苦痛劫掠"},
{"en":/Crave the Slaughter/g,"cn":"屠戮之欲"},
{"en":/Rite of Ruin/g,"cn":"毁灭仪式"},
{"en":/War Bringer/g,"cn":"战争使者"},
{"en":/Ramako, Sun's Light/g,"cn":"日光.雷默科"},
{"en":/Hinekora, Death's Fury/g,"cn":"死之狂怒.辛格拉"},
{"en":/Ngamahu, Flame's Advance/g,"cn":"火徒.努葛玛呼"},
{"en":/Tawhoa, Forest's Strength/g,"cn":"森林之力.塔赫亚"},
{"en":/Arohongui, Moon's Presence/g,"cn":"月使.亚欧红古"},
{"en":/Tukohama, War's Herald/g,"cn":"战争使者.图克哈玛"},
{"en":/Way of the Poacher/g,"cn":"盗猎者之途"},
{"en":/Avatar of the Chase/g,"cn":"追猎使徒"},
{"en":/Avatar of the Slaughter/g,"cn":"冷酷使徒"},
{"en":/Rapid Assault/g,"cn":"极速进攻"},
{"en":/Quartz Infusion/g,"cn":"石英化身"},
{"en":/Avatar of the Veil/g,"cn":"面纱女神"},
{"en":/Gathering Winds/g,"cn":"聚风"},
{"en":/Endless Munitions/g,"cn":"无限弹药"},
{"en":/Powerful Precision/g,"cn":"极致准心"},
{"en":/Far Shot/g,"cn":"狙击"},
{"en":/Fast and Deadly/g,"cn":"致命速度"},
{"en":/Ricochet/g,"cn":"弹射"},
{"en":/Rupture/g,"cn":"断裂"},
{"en":/Nature's Adrenaline/g,"cn":"大自然的肾上腺素"},
{"en":/Nature's Boon/g,"cn":"自然的恩赐"},
{"en":/Master Alchemist/g,"cn":"炼金术大师"},
{"en":/Veteran Bowyer/g,"cn":"制箭大师"},
{"en":/Master Surgeon/g,"cn":"手术大师"},
{"en":/Vile Bastion/g,"cn":"残劣壁垒"},
{"en":/Wicked Ward/g,"cn":"恶毒牢房"},
{"en":/Profane Bloom/g,"cn":"秽言亡语"},
{"en":/Malediction/g,"cn":"恶语术"},
{"en":/Void Beacon/g,"cn":"虚无之塔"},
{"en":/Forbidden Power/g,"cn":"禁忌力量"},
{"en":/Beacon of Ruin/g,"cn":"毁灭光炮塔"},
{"en":/Shaper of Desolation/g,"cn":"悲伤织者"},
{"en":/Mastermind of Discord/g,"cn":"混沌天才"},
{"en":/Pendulum of Destruction/g,"cn":"毁灭之钟"},
{"en":/Paragon of Calamity/g,"cn":"模范灾难"},
{"en":/Liege of the Primordial/g,"cn":"先祖诸王"},
{"en":/Elemancer/g,"cn":"魔像使"},
{"en":/Commander of Darkness/g,"cn":"黑暗统御者"},
{"en":/Mistress of Sacrifice/g,"cn":"奉献女魔"},
{"en":/Invoker/g,"cn":"腐化之塔"},
{"en":/Soul Weaver/g,"cn":"灵魂织者"},
{"en":/Puppet Master/g,"cn":"亡灵之使"},
{"en":/Bone Sculptor/g,"cn":"灵魂嗜者"},
{"en":/Flesh Binder/g,"cn":"血肉画师"},
{"en":/Headsman/g,"cn":"猎头者"},
{"en":/Endless Hunger/g,"cn":"无尽饥饿"},
{"en":/Brutal Fervour/g,"cn":"残暴热情"},
{"en":/Bane of Legends/g,"cn":"冷血传奇"},
{"en":/Impact/g,"cn":"影响"},
{"en":/Overwhelm/g,"cn":"镇压"},
{"en":/Gratuitous Violence/g,"cn":"免费力量"},
{"en":/Outmatch and Outlast/g,"cn":"完美胜出"},
{"en":/Blood in the Eyes/g,"cn":"血之眼"},
{"en":/Painforged/g,"cn":"痛苦铸造"},
{"en":/Versatile Combatant/g,"cn":"全方位斗士"},
{"en":/Violent Retaliation/g,"cn":"强力复仇"},
{"en":/Unstoppable Hero/g,"cn":"不败英雄"},
{"en":/Fortitude/g,"cn":"坚毅"},
{"en":/Worthy Foe/g,"cn":"可敬的对手"},
{"en":/Conqueror/g,"cn":"征服者"},
{"en":/First to Strike, Last to Fall/g,"cn":"嗜战如命"},
{"en":/Inspirational/g,"cn":"启发"},
{"en":/Pious Path/g,"cn":"廉简之途"},
{"en":/Instruments of Virtue/g,"cn":"公正之仪"},
{"en":/Augury of Penitence/g,"cn":"忏悔之兆"},
{"en":/Sanctify/g,"cn":"圣化"},
{"en":/Inevitable Judgement/g,"cn":"命运审判"},
{"en":/Righteous Providence/g,"cn":"正义之庭"},
{"en":/Conviction of Power/g,"cn":"力量定罪"},
{"en":/Divine Guidance/g,"cn":"神圣指引"},
{"en":/Ritual of Awakening/g,"cn":"升华仪式"},
{"en":/Pursuit of Faith/g,"cn":"信念之诉"},
{"en":/Illuminated Devotion/g,"cn":"无上奉献"},
{"en":/Sanctuary of Thought/g,"cn":"意识圣殿"},
{"en":/Arcane Blessing/g,"cn":"秘术保佑"},
{"en":/Unwavering Faith/g,"cn":"不动信念"},
{"en":/Radiant Faith/g,"cn":"信念之辉"},
{"en":/Time of Need/g,"cn":"紧急时刻"},
{"en":/Harmony of Purpose/g,"cn":"和谐之源"},
{"en":/Prayer of Glory/g,"cn":"神圣祷言"},
{"en":/Bastion of Hope/g,"cn":"希望壁垒"},
{"en":/Toxic Delivery/g,"cn":"毒物走私"},
{"en":/Unstable Infusion/g,"cn":"不稳定化身"},
{"en":/Opportunistic/g,"cn":"暗影"},
{"en":/Noxious Strike/g,"cn":"淬毒打击"},
{"en":/Ambush and Assassinate/g,"cn":"伏击"},
{"en":/Deadly Infusion/g,"cn":"致命专注"},
{"en":/Patient Reaper/g,"cn":"有耐心的死神"},
{"en":/Weave the Arcane/g,"cn":"奇异织者"},
{"en":/Swift Killer/g,"cn":"敏捷克星"},
{"en":/Harness the Void/g,"cn":"虚空掌控"},
{"en":/Prolonged Pain/g,"cn":"以太行者"},
{"en":/Escape Artist/g,"cn":"逃脱艺术"},
{"en":/Ghost Dance/g,"cn":"幽灵舞步"},
{"en":/Chain Reaction/g,"cn":"连锁反应"},
{"en":/Born in the Shadows/g,"cn":"生在影中"},
{"en":/Perfect Crime/g,"cn":"完美犯罪"},
{"en":/Pyromaniac/g,"cn":"纵火"},
{"en":/Bomb Specialist/g,"cn":"炸弹专家"},
{"en":/Demolitions Specialist/g,"cn":"爆破天才"},
{"en":/Explosives Expert/g,"cn":"爆破专家"},
{"en":/Acrobatics/g,"cn":"移形换影"},
{"en":/Ancestral Bond/g,"cn":"先祖魂约"},
{"en":/Arrow Dancing/g,"cn":"箭矢闪跃"},
{"en":/Avatar of Fire/g,"cn":"火之化身"},
{"en":/Blood Magic/g,"cn":"祭血术"},
{"en":/Chaos Inoculation/g,"cn":"异灵之体"},
{"en":/Conduit/g,"cn":"能量连接"},
{"en":/Crimson Dance/g,"cn":"玫红之舞"},
{"en":/Eldritch Battery/g,"cn":"异能魔力"},
{"en":/Elemental Equilibrium/g,"cn":"元素之相"},
{"en":/Elemental Overload/g,"cn":"元素超载"},
{"en":/Ghost Reaver/g,"cn":"灵能护体"},
{"en":/Iron Grip/g,"cn":"钢铁之握"},
{"en":/Iron Reflexes/g,"cn":"霸体"},
{"en":/Mind Over Matter/g,"cn":"心灵升华"},
{"en":/Minion Instability/g,"cn":"复仇之灵"},
{"en":/Necromantic Aegis/g,"cn":"灵能神盾"},
{"en":/Pain Attunement/g,"cn":"苦痛灵曲"},
{"en":/Perfect Agony/g,"cn":"完美苦痛"},
{"en":/Phase Acrobatics/g,"cn":"移灵换影"},
{"en":/Point Blank/g,"cn":"零点射击"},
{"en":/Resolute Technique/g,"cn":"坚毅之心"},
{"en":/Unwavering Stance/g,"cn":"烈士意志"},
{"en":/Vaal Pact/g,"cn":"瓦尔冥约"},
{"en":/Zealot's Oath/g,"cn":"狂热誓言"},

 ];
 var itemjson= [
{"en":/<span>Quality/g,"cn":"<span>品质"},
{"en":/<span>Physical Damage/g,"cn":"<span>物理伤害"},
{"en":/<span>Critical Strike Chance/g,"cn":"<span>暴击率"},
{"en":/<span>Attacks per Second/g,"cn":"<span>攻击速度"},
{"en":/<span>Weapon Range/g,"cn":"<span>武器范围"},
{"en":/<span>Mana Cost/g,"cn":"<span>魔力消耗"},
{"en":/<span>Mana Multiplier/g,"cn":"<span>魔力倍率"},
{"en":/<span>Elemental Damage/g,"cn":"<span>元素伤害"},
{"en":/<span>Limited to/g,"cn":"<span>数量上限"},
{"en":/<span>Radius</g,"cn":"<span>影响范围<"},
{"en":/<span>Support</g,"cn":"<span>辅助<"},
{"en":/>Small</g,"cn":">小<"},
{"en":/>Medium</g,"cn":">中<"},
{"en":/>Large</g,"cn":">大<"},
{"en":/                    Requires/g,"cn":"                    需求"},
{"en":/<span>Level/g,"cn":"<span>等级"},
{"en":/<span>Str/g,"cn":"<span>力量"},
{"en":/<span>Dex/g,"cn":"<span>敏捷"},
{"en":/<span>Int/g,"cn":"<span>智慧"},
{"en":/<span>Energy Shield/g,"cn":"<span>能量护盾"},
{"en":/<span>Evasion Rating/g,"cn":"<span>闪避"},
{"en":/<span>Armour/g,"cn":"<span>护甲"},
{"en":/<span class="lc">Mirrored/g,"cn":"<span class=\"lc\">已复制"},
{"en":/<span class="lc">Corrupted/g,"cn":"<span class=\"lc\">已污染"},
{"en":/<span>This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Active Skill Gem you wish to augment. Right click to remove from a socket./g,"cn":"<span>这是一颗辅助宝石. 它并不会为你的角色增加能力数值, 但会强化与其连接的技能宝石. 将其放置于物品上同样颜色的插槽并连接想要强化的技能宝石. 点击右键从插槽中移除. "},


];

 var propertiesJson= [
{"en":/Radius/g,"cn":"范围"},	 
{"en":/Quality/g,"cn":"品质"},
 {"en":/Armour/g,"cn":"护甲"},
 {"en":/Level/g,"cn":"等级"},
 {"en":/Str/g,"cn":"力量"},
 {"en":/Int/g,"cn":"智慧"},
 {"en":/Dex/g,"cn":"敏捷"},
 {"en":/Mana Cost/g,"cn":"魔力消耗"},
 {"en":/Effectiveness of Added Damage/g,"cn":"品质"},
 {"en":/Mana Multiplier/g,"cn":"魔力消耗倍率"},
 {"en":/Evasion Rating/g,"cn":"闪避"},
 {"en":/Support/g,"cn":"辅助"},
 {"en":/Physical Damage/g,"cn":"物理伤害"},
 {"en":/Elemental Damage/g,"cn":"元素伤害"},
 {"en":/Chaos Damage/g,"cn":"混沌伤害"},
 {"en":/Critical Strike Chance/g,"cn":"攻击暴击率"},
 {"en":/Attacks per Second/g,"cn":"每秒攻击次数"},
  {"en":/Weapon Range/g,"cn":"武器范围"},
 {"en":/Energy Shield/g,"cn":"能量护盾"},
{"en":/Limited to/g,"cn":"仅限"},
{"en":/Abyss/g,"cn":"深渊"},
 {"en":/Lasts %0 Seconds/g,"cn":"持续 %0 秒"},
 {"en":/Consumes %0 of %1 Charges on use/g,"cn":"每次使用会从 %1 充能次数中消耗 %0 次"},
  {"en":/Currently has %0 Charges/g,"cn":"目前有 %0 充能次数"},
   {"en":/Recovers %0 Life over %1 Seconds/g,"cn":"%1 秒内回复 %0 生命"},
    {"en":/Recovers %0 Mana over %1 Seconds/g,"cn":"%1 秒内回复 %0 魔力"},
	 {"en":/Chance to Block/g,"cn":"攻击格挡率"},
];



var baseItemJson=[
{"en":/Nailed Fist/g,"cn":"拳钉"},
{"en":/Sharktooth Claw/g,"cn":"鲨颚爪"},
{"en":/Awl/g,"cn":"凿钉"},
{"en":/Cat's Paw/g,"cn":"猫爪刃"},
{"en":/Blinder/g,"cn":"袭眼钩"},
{"en":/Timeworn Claw/g,"cn":"远古战爪"},
{"en":/Sparkling Claw/g,"cn":"眩目爪刃"},
{"en":/Fright Claw/g,"cn":"恐惧之爪"},
{"en":/Double Claw/g,"cn":"双刃爪"},
{"en":/Thresher Claw/g,"cn":"撕裂尖爪"},
{"en":/Gouger/g,"cn":"穿体凿"},
{"en":/Tiger's Paw/g,"cn":"虎爪刃"},
{"en":/Gut Ripper/g,"cn":"裂脏钩"},
{"en":/Prehistoric Claw/g,"cn":"史前战爪"},
{"en":/Noble Claw/g,"cn":"贵族战爪"},
{"en":/Eagle Claw/g,"cn":"鹰爪刃"},
{"en":/Twin Claw/g,"cn":"重刃爪"},
{"en":/Great White Claw/g,"cn":"白灵之爪"},
{"en":/Throat Stabber/g,"cn":"刺喉刃"},
{"en":/Hellion's Paw/g,"cn":"魔爪刃"},
{"en":/Eye Gouger/g,"cn":"刺眼钩"},
{"en":/Vaal Claw/g,"cn":"瓦尔战爪"},
{"en":/Imperial Claw/g,"cn":"帝国战爪"},
{"en":/Terror Claw/g,"cn":"恐惧之牙"},
{"en":/Gemini Claw/g,"cn":"双子战爪"},
{"en":/Glass Shank/g,"cn":"玻璃利片"},
{"en":/Skinning Knife/g,"cn":"剥皮刀"},
{"en":/Carving Knife/g,"cn":"刻骨刀"},
{"en":/Stiletto/g,"cn":"锐利刺匕"},
{"en":/Boot Knife/g,"cn":"窃者短刃"},
{"en":/Copper Kris/g,"cn":"铜锻波刃"},
{"en":/Skean/g,"cn":"双刃匕"},
{"en":/Imp Dagger/g,"cn":"魔性之刃"},
{"en":/Prong Dagger/g,"cn":"尖耙短匕"},
{"en":/Flaying Knife/g,"cn":"残体利刃"},
{"en":/Butcher Knife/g,"cn":"屠兽利刃"},
{"en":/Poignard/g,"cn":"夺命刺"},
{"en":/Boot Blade/g,"cn":"窃者短匕"},
{"en":/Golden Kris/g,"cn":"金光波刃"},
{"en":/Royal Skean/g,"cn":"皇家短匕"},
{"en":/Fiend Dagger/g,"cn":"兽血短匕"},
{"en":/Trisula/g,"cn":"三叉短匕"},
{"en":/Gutting Knife/g,"cn":"重伤短刀"},
{"en":/Slaughter Knife/g,"cn":"猎者之刃"},
{"en":/Ambusher/g,"cn":"伏击刺刃"},
{"en":/Ezomyte Dagger/g,"cn":"艾兹麦之匕"},
{"en":/Platinum Kris/g,"cn":"白金波刃"},
{"en":/Imperial Skean/g,"cn":"帝国短匕"},
{"en":/Demon Dagger/g,"cn":"魔灵短匕"},
{"en":/Sai/g,"cn":"战叉"},
{"en":/Driftwood Wand/g,"cn":"朽木法杖"},
{"en":/Goat's Horn/g,"cn":"羊角法杖"},
{"en":/Carved Wand/g,"cn":"粗纹法杖"},
{"en":/Quartz Wand/g,"cn":"石英法杖"},
{"en":/Spiraled Wand/g,"cn":"螺纹法杖"},
{"en":/Sage Wand/g,"cn":"贤者法杖"},
{"en":/Pagan Wand/g,"cn":"异教法杖"},
{"en":/Faun's Horn/g,"cn":"兽角法杖"},
{"en":/Engraved Wand/g,"cn":"符文法杖"},
{"en":/Crystal Wand/g,"cn":"水晶法杖"},
{"en":/Serpent Wand/g,"cn":"蛇眼法杖"},
{"en":/Omen Wand/g,"cn":"灵兆法杖"},
{"en":/Heathen Wand/g,"cn":"异徒法杖"},
{"en":/Demon's Horn/g,"cn":"魔角法杖"},
{"en":/Imbued Wand/g,"cn":"魔性法杖"},
{"en":/Opal Wand/g,"cn":"灵石法杖"},
{"en":/Tornado Wand/g,"cn":"狂风法杖"},
{"en":/Prophecy Wand/g,"cn":"箴言法杖"},
{"en":/Profane Wand/g,"cn":"亵渎法杖"},
{"en":/Rusted Sword/g,"cn":"锈剑"},
{"en":/Copper Sword/g,"cn":"青铜短剑"},
{"en":/Sabre/g,"cn":"旧军刀"},
{"en":/Broad Sword/g,"cn":"阔剑"},
{"en":/War Sword/g,"cn":"征战之剑"},
{"en":/Ancient Sword/g,"cn":"远古之剑"},
{"en":/Elegant Sword/g,"cn":"贵族之剑"},
{"en":/Dusk Blade/g,"cn":"暮色之刃"},
{"en":/Hook Sword/g,"cn":"钩爪剑"},
{"en":/Variscite Blade/g,"cn":"碧铜短剑"},
{"en":/Cutlass/g,"cn":"军用长刃"},
{"en":/Baselard/g,"cn":"冷光长剑"},
{"en":/Battle Sword/g,"cn":"士兵长剑"},
{"en":/Elder Sword/g,"cn":"智者长剑"},
{"en":/Graceful Sword/g,"cn":"权贵之剑"},
{"en":/Twilight Blade/g,"cn":"暮光长剑"},
{"en":/Grappler/g,"cn":"捕捉者"},
{"en":/Gemstone Sword/g,"cn":"宝石之剑"},
{"en":/Corsair Sword/g,"cn":"海贼长刀"},
{"en":/Gladius/g,"cn":"斗士长剑"},
{"en":/Legion Sword/g,"cn":"军团长剑"},
{"en":/Vaal Blade/g,"cn":"瓦尔军刃"},
{"en":/Eternal Sword/g,"cn":"永恒之剑"},
{"en":/Midnight Blade/g,"cn":"夜语长剑"},
{"en":/Tiger Hook/g,"cn":"虎钩"},
{"en":/Rusted Spike/g,"cn":"锈刺剑"},
{"en":/Whalebone Rapier/g,"cn":"鲸骨细刃"},
{"en":/Battered Foil/g,"cn":"钝刃细剑"},
{"en":/Basket Rapier/g,"cn":"练武者细剑"},
{"en":/Jagged Foil/g,"cn":"锯状薄刃"},
{"en":/Antique Rapier/g,"cn":"古代细剑"},
{"en":/Elegant Foil/g,"cn":"贵族细剑"},
{"en":/Thorn Rapier/g,"cn":"棘刺细剑"},
{"en":/Smallsword/g,"cn":"小剑"},
{"en":/Wyrmbone Rapier/g,"cn":"龙骨细剑"},
{"en":/Burnished Foil/g,"cn":"冷芒刺剑"},
{"en":/Estoc/g,"cn":"穿甲刺剑"},
{"en":/Serrated Foil/g,"cn":"锯齿细剑"},
{"en":/Primeval Rapier/g,"cn":"古典刺剑"},
{"en":/Fancy Foil/g,"cn":"华丽细剑"},
{"en":/Apex Rapier/g,"cn":"锐锋细剑"},
{"en":/Courtesan Sword/g,"cn":"花魁之剑"},
{"en":/Dragonbone Rapier/g,"cn":"龙骨细剑"},
{"en":/Tempered Foil/g,"cn":"强化细剑"},
{"en":/Pecoraro/g,"cn":"寒光刺剑"},
{"en":/Spiraled Foil/g,"cn":"螺纹细剑"},
{"en":/Vaal Rapier/g,"cn":"瓦尔细剑"},
{"en":/Jewelled Foil/g,"cn":"宝饰细剑"},
{"en":/Harpy Rapier/g,"cn":"魔喙细剑"},
{"en":/Dragoon Sword/g,"cn":"骑兵军刀"},
{"en":/Rusted Hatchet/g,"cn":"锈斧"},
{"en":/Jade Hatchet/g,"cn":"碎玉斧"},
{"en":/Boarding Axe/g,"cn":"万用手斧"},
{"en":/Cleaver/g,"cn":"切割者"},
{"en":/Broad Axe/g,"cn":"阔斧"},
{"en":/Arming Axe/g,"cn":"长柄斧"},
{"en":/Decorative Axe/g,"cn":"富贵之斧"},
{"en":/Spectral Axe/g,"cn":"幽魂之斧"},
{"en":/Etched Hatchet/g,"cn":"蚀刻战斧"},
{"en":/Jasper Axe/g,"cn":"灵玉斧"},
{"en":/Tomahawk/g,"cn":"征战之斧"},
{"en":/Wrist Chopper/g,"cn":"断腕之刃"},
{"en":/War Axe/g,"cn":"行军斧"},
{"en":/Chest Splitter/g,"cn":"开膛利刃"},
{"en":/Ceremonial Axe/g,"cn":"血仪之斧"},
{"en":/Wraith Axe/g,"cn":"凶灵之斧"},
{"en":/Engraved Hatchet/g,"cn":"雕文战斧"},
{"en":/Karui Axe/g,"cn":"卡鲁古斧"},
{"en":/Siege Axe/g,"cn":"破城斧"},
{"en":/Reaver Axe/g,"cn":"残暴之斧"},
{"en":/Butcher Axe/g,"cn":"屠戮之斧"},
{"en":/Vaal Hatchet/g,"cn":"瓦尔战斧"},
{"en":/Royal Axe/g,"cn":"皇家之斧"},
{"en":/Infernal Axe/g,"cn":"狱火之刃"},
{"en":/Runic Hatchet/g,"cn":"密文之斧"},
{"en":/Driftwood Club/g,"cn":"朽木之棒"},
{"en":/Tribal Club/g,"cn":"祭仪之杵"},
{"en":/Spiked Club/g,"cn":"钝钉木棒"},
{"en":/Stone Hammer/g,"cn":"石锤"},
{"en":/War Hammer/g,"cn":"战锤"},
{"en":/Bladed Mace/g,"cn":"多刃锤"},
{"en":/Ceremonial Mace/g,"cn":"祭礼之锤"},
{"en":/Dream Mace/g,"cn":"梦境之锤"},
{"en":/Wyrm Mace/g,"cn":"古龙之锤"},
{"en":/Petrified Club/g,"cn":"坚石木棒"},
{"en":/Barbed Club/g,"cn":"锐刺木棒"},
{"en":/Rock Breaker/g,"cn":"破岩锤"},
{"en":/Battle Hammer/g,"cn":"强化战锤"},
{"en":/Flanged Mace/g,"cn":"护体之锤"},
{"en":/Ornate Mace/g,"cn":"华丽之锤"},
{"en":/Phantom Mace/g,"cn":"幻象之锤"},
{"en":/Dragon Mace/g,"cn":"龙之锤"},
{"en":/Ancestral Club/g,"cn":"祖灵之杵"},
{"en":/Tenderizer/g,"cn":"裂肉之锤"},
{"en":/Gavel/g,"cn":"坚锤"},
{"en":/Legion Hammer/g,"cn":"军团之锤"},
{"en":/Pernarch/g,"cn":"锋刃重锤"},
{"en":/Auric Mace/g,"cn":"圣约之锤"},
{"en":/Nightmare Mace/g,"cn":"梦魇之锤"},
{"en":/Behemoth Mace/g,"cn":"巴哈姆特"},
{"en":/Driftwood Sceptre/g,"cn":"朽木权杖"},
{"en":/Darkwood Sceptre/g,"cn":"乌木权杖"},
{"en":/Bronze Sceptre/g,"cn":"铜锻权杖"},
{"en":/Quartz Sceptre/g,"cn":"石英权杖"},
{"en":/Iron Sceptre/g,"cn":"冷铁权杖"},
{"en":/Ochre Sceptre/g,"cn":"赤色权杖"},
{"en":/Ritual Sceptre/g,"cn":"祭仪权杖"},
{"en":/Shadow Sceptre/g,"cn":"影语权杖"},
{"en":/Horned Sceptre/g,"cn":"犄角权杖"},
{"en":/Grinning Fetish/g,"cn":"远古之祭"},
{"en":/Sekhem/g,"cn":"威能权杖"},
{"en":/Crystal Sceptre/g,"cn":"水晶权杖"},
{"en":/Lead Sceptre/g,"cn":"铅铸权杖"},
{"en":/Blood Sceptre/g,"cn":"血色权杖"},
{"en":/Royal Sceptre/g,"cn":"皇家权杖"},
{"en":/Abyssal Sceptre/g,"cn":"深渊权杖"},
{"en":/Stag Sceptre/g,"cn":"灵鹿权杖"},
{"en":/Karui Sceptre/g,"cn":"卡鲁权杖"},
{"en":/Tyrant's Sekhem/g,"cn":"暴君之统"},
{"en":/Opal Sceptre/g,"cn":"灵石权杖"},
{"en":/Platinum Sceptre/g,"cn":"白金权杖"},
{"en":/Vaal Sceptre/g,"cn":"瓦尔权杖"},
{"en":/Carnal Sceptre/g,"cn":"禁礼权杖"},
{"en":/Void Sceptre/g,"cn":"虚影权杖"},
{"en":/Sambar Sceptre/g,"cn":"恶魔权杖"},
{"en":/Crude Bow/g,"cn":"粗制弓"},
{"en":/Short Bow/g,"cn":"短弓"},
{"en":/Long Bow/g,"cn":"长弓"},
{"en":/Composite Bow/g,"cn":"合成弓"},
{"en":/Recurve Bow/g,"cn":"反曲弓"},
{"en":/Bone Bow/g,"cn":"骨制弓"},
{"en":/Royal Bow/g,"cn":"皇家猎弓"},
{"en":/Death Bow/g,"cn":"死亡之弓"},
{"en":/Reflex Bow/g,"cn":"反射弓"},
{"en":/Grove Bow/g,"cn":"丛林猎弓"},
{"en":/Decurve Bow/g,"cn":"直弓"},
{"en":/Compound Bow/g,"cn":"复合弓"},
{"en":/Sniper Bow/g,"cn":"狙杀弓"},
{"en":/Ivory Bow/g,"cn":"象牙弓"},
{"en":/Highborn Bow/g,"cn":"贵族之弓"},
{"en":/Decimation Bow/g,"cn":"猎魂之弓"},
{"en":/Steelwood Bow/g,"cn":"钢木之弓"},
{"en":/Thicket Bow/g,"cn":"林野猎弓"},
{"en":/Citadel Bow/g,"cn":"城塞战弓"},
{"en":/Ranger Bow/g,"cn":"漫游之弓"},
{"en":/Assassin Bow/g,"cn":"暗杀弓"},
{"en":/Spine Bow/g,"cn":"脊弓"},
{"en":/Imperial Bow/g,"cn":"帝国之弓"},
{"en":/Harbinger Bow/g,"cn":"先驱者之弓"},
{"en":/Maraketh Bow/g,"cn":"马拉克斯弓"},
{"en":/Gnarled Branch/g,"cn":"朽木之干"},
{"en":/Primitive Staff/g,"cn":"粗制长杖"},
{"en":/Long Staff/g,"cn":"长杖"},
{"en":/Iron Staff/g,"cn":"铁锻长杖"},
{"en":/Coiled Staff/g,"cn":"强化长杖"},
{"en":/Royal Staff/g,"cn":"皇家长杖"},
{"en":/Vile Staff/g,"cn":"毒牙长杖"},
{"en":/Crescent Staff/g,"cn":"新月长杖"},
{"en":/Woodful Staff/g,"cn":"坚木长杖"},
{"en":/Quarterstaff/g,"cn":"细柄长杖"},
{"en":/Military Staff/g,"cn":"军用长杖"},
{"en":/Serpentine Staff/g,"cn":"蛇纹长杖"},
{"en":/Highborn Staff/g,"cn":"贵族长杖"},
{"en":/Foul Staff/g,"cn":"恶灵长杖"},
{"en":/Moon Staff/g,"cn":"月神长杖"},
{"en":/Primordial Staff/g,"cn":"史典长杖"},
{"en":/Lathi/g,"cn":"武术长杖"},
{"en":/Ezomyte Staff/g,"cn":"艾兹麦长杖"},
{"en":/Maelstr%C3%B6m Staff/g,"cn":"风暴长杖"},
{"en":/Imperial Staff/g,"cn":"帝国长杖"},
{"en":/Judgement Staff/g,"cn":"审判长杖"},
{"en":/Eclipse Staff/g,"cn":"月蚀长杖"},
{"en":/Corroded Blade/g,"cn":"锈斑巨剑"},
{"en":/Longsword/g,"cn":"大剑"},
{"en":/Bastard Sword/g,"cn":"重剑"},
{"en":/Two-Handed Sword/g,"cn":"双手剑"},
{"en":/Etched Greatsword/g,"cn":"术雕巨剑"},
{"en":/Ornate Sword/g,"cn":"名贵巨剑"},
{"en":/Spectral Sword/g,"cn":"幽魂巨剑"},
{"en":/Curved Blade/g,"cn":"弯刃"},
{"en":/Butcher Sword/g,"cn":"杀戮巨剑"},
{"en":/Footman Sword/g,"cn":"士兵巨剑"},
{"en":/Highland Blade/g,"cn":"高山重刃"},
{"en":/Engraved Greatsword/g,"cn":"符文巨剑"},
{"en":/Tiger Sword/g,"cn":"虎牙巨剑"},
{"en":/Wraith Sword/g,"cn":"凶灵巨剑"},
{"en":/Lithe Blade/g,"cn":"细刃"},
{"en":/Headman's Sword/g,"cn":"行刑巨剑"},
{"en":/Reaver Sword/g,"cn":"残暴巨剑"},
{"en":/Ezomyte Blade/g,"cn":"艾兹麦巨剑"},
{"en":/Vaal Greatsword/g,"cn":"瓦尔巨剑"},
{"en":/Lion Sword/g,"cn":"狮爪巨剑"},
{"en":/Infernal Sword/g,"cn":"狱炎重剑"},
{"en":/Exquisite Blade/g,"cn":"精致之刃"},
{"en":/Stone Axe/g,"cn":"石斧"},
{"en":/Jade Chopper/g,"cn":"碎玉大斧"},
{"en":/Woodsplitter/g,"cn":"柴斧"},
{"en":/Poleaxe/g,"cn":"巨战斧"},
{"en":/Double Axe/g,"cn":"双刃巨斧"},
{"en":/Gilded Axe/g,"cn":"金柄之斧"},
{"en":/Shadow Axe/g,"cn":"幽影巨斧"},
{"en":/Jasper Chopper/g,"cn":"灵玉巨斧"},
{"en":/Dagger Axe/g,"cn":"匕斧"},
{"en":/Timber Axe/g,"cn":"裂木巨斧"},
{"en":/Headsman Axe/g,"cn":"行刑巨斧"},
{"en":/Labrys/g,"cn":"双影巨斧"},
{"en":/Noble Axe/g,"cn":"权贵巨斧"},
{"en":/Abyssal Axe/g,"cn":"深渊巨斧"},
{"en":/Talon Axe/g,"cn":"猛禽爪斧"},
{"en":/Karui Chopper/g,"cn":"卡鲁巨斧"},
{"en":/Sundering Axe/g,"cn":"裂甲巨斧"},
{"en":/Ezomyte Axe/g,"cn":"艾兹麦巨斧"},
{"en":/Vaal Axe/g,"cn":"瓦尔巨斧"},
{"en":/Despot Axe/g,"cn":"霸主巨斧"},
{"en":/Void Axe/g,"cn":"虚影巨斧"},
{"en":/Fleshripper/g,"cn":"裂肉者"},
{"en":/Driftwood Maul/g,"cn":"朽木巨锤"},
{"en":/Tribal Maul/g,"cn":"祭仪巨锤"},
{"en":/Mallet/g,"cn":"千斤锤"},
{"en":/Sledgehammer/g,"cn":"冷铁重锤"},
{"en":/Jagged Maul/g,"cn":"狼牙重锤"},
{"en":/Brass Maul/g,"cn":"铜影巨锤"},
{"en":/Fright Maul/g,"cn":"恐惧重锤"},
{"en":/Morning Star/g,"cn":"晨星"},
{"en":/Totemic Maul/g,"cn":"图腾巨锤"},
{"en":/Great Mallet/g,"cn":"刚猛巨锤"},
{"en":/Steelhead/g,"cn":"沉钢重锤"},
{"en":/Spiny Maul/g,"cn":"凶刺巨锤"},
{"en":/Plated Maul/g,"cn":"华丽重锤"},
{"en":/Dread Maul/g,"cn":"威权巨锤"},
{"en":/Solar Maul/g,"cn":"日光锤"},
{"en":/Karui Maul/g,"cn":"卡鲁重锤"},
{"en":/Colossus Mallet/g,"cn":"巨型重锤"},
{"en":/Piledriver/g,"cn":"扫荡者"},
{"en":/Meatgrinder/g,"cn":"戮魂重锤"},
{"en":/Imperial Maul/g,"cn":"帝国重锤"},
{"en":/Terror Maul/g,"cn":"惧灵重锤"},
{"en":/Coronal Maul/g,"cn":"花冠重锤"},
{"en":/Iron Gauntlets/g,"cn":"铁锻护手"},
{"en":/Plated Gauntlets/g,"cn":"坚铁护手"},
{"en":/Bronze Gauntlets/g,"cn":"青铜护手"},
{"en":/Steel Gauntlets/g,"cn":"冷钢护手"},
{"en":/Antique Gauntlets/g,"cn":"古钢护手"},
{"en":/Ancient Gauntlets/g,"cn":"远古护手"},
{"en":/Goliath Gauntlets/g,"cn":"巨灵护手"},
{"en":/Vaal Gauntlets/g,"cn":"瓦尔护手"},
{"en":/Titan Gauntlets/g,"cn":"巨人护手"},
{"en":/Rawhide Gloves/g,"cn":"生皮手套"},
{"en":/Goathide Gloves/g,"cn":"羊皮手套"},
{"en":/Deerskin Gloves/g,"cn":"鹿皮手套"},
{"en":/Nubuck Gloves/g,"cn":"砂影手套"},
{"en":/Eelskin Gloves/g,"cn":"鳗皮手套"},
{"en":/Sharkskin Gloves/g,"cn":"鲨皮手套"},
{"en":/Shagreen Gloves/g,"cn":"粗革手套"},
{"en":/Stealth Gloves/g,"cn":"匿踪手套"},
{"en":/Slink Gloves/g,"cn":"迷踪手套"},
{"en":/Wool Gloves/g,"cn":"羊毛手套"},
{"en":/Velvet Gloves/g,"cn":"丝绒手套"},
{"en":/Silk Gloves/g,"cn":"丝绸手套"},
{"en":/Embroidered Gloves/g,"cn":"刺绣手套"},
{"en":/Satin Gloves/g,"cn":"缎布手套"},
{"en":/Samite Gloves/g,"cn":"绣布手套"},
{"en":/Conjurer Gloves/g,"cn":"咒者手套"},
{"en":/Arcanist Gloves/g,"cn":"秘术手套"},
{"en":/Sorcerer Gloves/g,"cn":"术士手套"},
{"en":/Fishscale Gauntlets/g,"cn":"鱼鳞手套"},
{"en":/Ironscale Gauntlets/g,"cn":"铁影手套"},
{"en":/Bronzescale Gauntlets/g,"cn":"铜影手套"},
{"en":/Steelscale Gauntlets/g,"cn":"钢影护手"},
{"en":/Serpentscale Gauntlets/g,"cn":"蛇鳞手套"},
{"en":/Wyrmscale Gauntlets/g,"cn":"蝮鳞手套"},
{"en":/Hydrascale Gauntlets/g,"cn":"火蝮鳞手套"},
{"en":/Dragonscale Gauntlets/g,"cn":"龙鳞手套"},
{"en":/Chain Gloves/g,"cn":"链甲手套"},
{"en":/Ringmail Gloves/g,"cn":"环甲手套"},
{"en":/Mesh Gloves/g,"cn":"网眼手套"},
{"en":/Riveted Gloves/g,"cn":"仪式手套"},
{"en":/Zealot Gloves/g,"cn":"狂热者手套"},
{"en":/Soldier Gloves/g,"cn":"战士手套"},
{"en":/Legion Gloves/g,"cn":"军团手套"},
{"en":/Crusader Gloves/g,"cn":"圣战手套"},
{"en":/Wrapped Mitts/g,"cn":"裹趾护手"},
{"en":/Strapped Mitts/g,"cn":"扣环护手"},
{"en":/Clasped Mitts/g,"cn":"环带护手"},
{"en":/Trapper Mitts/g,"cn":"猎人护手"},
{"en":/Ambush Mitts/g,"cn":"伏击护手"},
{"en":/Carnal Mitts/g,"cn":"禁礼护手"},
{"en":/Assassin's Mitts/g,"cn":"刺杀者护手"},
{"en":/Murder Mitts/g,"cn":"暗杀者护手"},
{"en":/Golden Bracers/g,"cn":"黄金臂甲"},
{"en":/Spiked Gloves/g,"cn":"釦钉手套"},
{"en":/Gripped Gloves/g,"cn":"擒拿手套"},
{"en":/Fingerless Silk Gloves/g,"cn":"魔指手套"},
{"en":/Iron Greaves/g,"cn":"铁锻胫甲"},
{"en":/Steel Greaves/g,"cn":"冷钢胫甲"},
{"en":/Plated Greaves/g,"cn":"坚铁胫甲"},
{"en":/Reinforced Greaves/g,"cn":"强化胫甲"},
{"en":/Antique Greaves/g,"cn":"古钢胫甲"},
{"en":/Ancient Greaves/g,"cn":"远古胫甲"},
{"en":/Goliath Greaves/g,"cn":"巨灵胫甲"},
{"en":/Vaal Greaves/g,"cn":"瓦尔胫甲"},
{"en":/Titan Greaves/g,"cn":"巨人胫甲"},
{"en":/Kaom's Greaves/g,"cn":"冈姆胫甲"},
{"en":/Rawhide Boots/g,"cn":"生皮短靴"},
{"en":/Goathide Boots/g,"cn":"羊皮短靴"},
{"en":/Deerskin Boots/g,"cn":"鹿皮短靴"},
{"en":/Nubuck Boots/g,"cn":"砂影短靴"},
{"en":/Eelskin Boots/g,"cn":"鳗皮短靴"},
{"en":/Sharkskin Boots/g,"cn":"鲨皮短靴"},
{"en":/Shagreen Boots/g,"cn":"粗革短靴"},
{"en":/Stealth Boots/g,"cn":"匿踪短靴"},
{"en":/Slink Boots/g,"cn":"迷踪短靴"},
{"en":/Wool Shoes/g,"cn":"羊毛之鞋"},
{"en":/Velvet Slippers/g,"cn":"丝绒便鞋"},
{"en":/Silk Slippers/g,"cn":"丝绸便鞋"},
{"en":/Scholar Boots/g,"cn":"学者长靴"},
{"en":/Satin Slippers/g,"cn":"缎布便鞋"},
{"en":/Samite Slippers/g,"cn":"绣布便鞋"},
{"en":/Conjurer Boots/g,"cn":"咒者长靴"},
{"en":/Arcanist Slippers/g,"cn":"秘术便鞋"},
{"en":/Sorcerer Boots/g,"cn":"术士长靴"},
{"en":/Leatherscale Boots/g,"cn":"粗鳞皮靴"},
{"en":/Ironscale Boots/g,"cn":"铁影长靴"},
{"en":/Bronzescale Boots/g,"cn":"铜影长靴"},
{"en":/Steelscale Boots/g,"cn":"钢影长靴"},
{"en":/Serpentscale Boots/g,"cn":"蛇鳞长靴"},
{"en":/Wyrmscale Boots/g,"cn":"地蝮鳞长靴"},
{"en":/Hydrascale Boots/g,"cn":"火蝮鳞长靴"},
{"en":/Dragonscale Boots/g,"cn":"龙鳞长靴"},
{"en":/Chain Boots/g,"cn":"链甲长靴 "},
{"en":/Ringmail Boots/g,"cn":"环甲筒靴"},
{"en":/Mesh Boots/g,"cn":"网眼长靴"},
{"en":/Riveted Boots/g,"cn":"仪式短靴 "},
{"en":/Zealot Boots/g,"cn":"狂热者长靴"},
{"en":/Soldier Boots/g,"cn":"战士之靴"},
{"en":/Legion Boots/g,"cn":"军团长靴"},
{"en":/Crusader Boots/g,"cn":"圣战长靴 "},
{"en":/Wrapped Boots/g,"cn":"裹趾凉鞋 "},
{"en":/Strapped Boots/g,"cn":"扣环短靴"},
{"en":/Clasped Boots/g,"cn":"环带长靴"},
{"en":/Shackled Boots/g,"cn":"缚足长靴"},
{"en":/Trapper Boots/g,"cn":"猎人之靴"},
{"en":/Ambush Boots/g,"cn":"伏击之靴"},
{"en":/Carnal Boots/g,"cn":"禁礼之靴"},
{"en":/Assassin's Boots/g,"cn":"刺杀者之靴"},
{"en":/Murder Boots/g,"cn":"暗杀者长靴"},
{"en":/Golden Caligae/g,"cn":"黄金缠鞋"},
{"en":/Avian Slippers/g,"cn":"飞羽便鞋"},
{"en":/Two-Toned Boots/g,"cn":"异色鞋"},
{"en":/Plate Vest/g,"cn":"铁制背心"},
{"en":/Chestplate/g,"cn":"胸甲"},
{"en":/Copper Plate/g,"cn":"铜锻板甲"},
{"en":/War Plate/g,"cn":"战争之铠"},
{"en":/Full Plate/g,"cn":"连身铠甲"},
{"en":/Arena Plate/g,"cn":"斗者之铠"},
{"en":/Lordly Plate/g,"cn":"领主护铠"},
{"en":/Bronze Plate/g,"cn":"青铜铠甲"},
{"en":/Battle Plate/g,"cn":"战铠"},
{"en":/Sun Plate/g,"cn":"日光之铠"},
{"en":/Colosseum Plate/g,"cn":"决斗之铠"},
{"en":/Majestic Plate/g,"cn":"庄严之铠"},
{"en":/Golden Plate/g,"cn":"金耀之铠"},
{"en":/Crusader Plate/g,"cn":"征战重铠"},
{"en":/Astral Plate/g,"cn":"星芒战铠"},
{"en":/Gladiator Plate/g,"cn":"角斗重铠"},
{"en":/Glorious Plate/g,"cn":"荣耀战铠"},
{"en":/Kaom's Plate/g,"cn":"冈姆的重铠"},
{"en":/Shabby Jerkin/g,"cn":"破旧外套"},
{"en":/Strapped Leather/g,"cn":"扣环皮甲"},
{"en":/Buckskin Tunic/g,"cn":"鹿皮外套"},
{"en":/Wild Leather/g,"cn":"野性皮甲"},
{"en":/Full Leather/g,"cn":"连身皮甲"},
{"en":/Sun Leather/g,"cn":"日光皮甲"},
{"en":/Thief's Garb/g,"cn":"窃贼之装"},
{"en":/Eelskin Tunic/g,"cn":"鳗皮之衣"},
{"en":/Frontier Leather/g,"cn":"边戍皮甲"},
{"en":/Glorious Leather/g,"cn":"荣耀皮甲"},
{"en":/Coronal Leather/g,"cn":"光耀皮甲"},
{"en":/Cutthroat's Garb/g,"cn":"残杀者之装"},
{"en":/Sharkskin Tunic/g,"cn":"鲨皮之衣"},
{"en":/Destiny Leather/g,"cn":"命运皮甲"},
{"en":/Exquisite Leather/g,"cn":"精制皮甲"},
{"en":/Zodiac Leather/g,"cn":"星辰皮甲"},
{"en":/Assassin's Garb/g,"cn":"刺杀者之装"},
{"en":/Simple Robe/g,"cn":"简易之袍"},
{"en":/Silken Vest/g,"cn":"绸缎背心"},
{"en":/Scholar's Robe/g,"cn":"学者之袍"},
{"en":/Silken Garb/g,"cn":"丝绸之衣"},
{"en":/Mage's Vestment/g,"cn":"博学长衣"},
{"en":/Silk Robe/g,"cn":"丝质之袍"},
{"en":/Cabalist Regalia/g,"cn":"秘术法衣"},
{"en":/Sage's Robe/g,"cn":"贤者之袍"},
{"en":/Silken Wrap/g,"cn":"丝绒背心"},
{"en":/Conjurer's Vestment/g,"cn":"咒者长衣"},
{"en":/Spidersilk Robe/g,"cn":"蛛丝之袍"},
{"en":/Destroyer Regalia/g,"cn":"灭世法衣"},
{"en":/Savant's Robe/g,"cn":"智者之袍"},
{"en":/Necromancer Silks/g,"cn":"操灵者背心"},
{"en":/Occultist's Vestment/g,"cn":"秘术长衣"},
{"en":/Widowsilk Robe/g,"cn":"毒蛛丝之袍"},
{"en":/Vaal Regalia/g,"cn":"瓦尔法衣"},
{"en":/Scale Vest/g,"cn":"细鳞背心 "},
{"en":/Light Brigandine/g,"cn":"轻锁甲"},
{"en":/Scale Doublet/g,"cn":"合身鳞甲 "},
{"en":/Infantry Brigandine/g,"cn":"步兵锁甲 "},
{"en":/Full Scale Armour/g,"cn":"连身鳞甲"},
{"en":/Soldier's Brigandine/g,"cn":"战士锁甲"},
{"en":/Field Lamellar/g,"cn":"野战薄甲"},
{"en":/Wyrmscale Doublet/g,"cn":"龙鳞战甲"},
{"en":/Hussar Brigandine/g,"cn":"轻骑锁甲 "},
{"en":/Full Wyrmscale/g,"cn":"连身龙鳞战甲"},
{"en":/Commander's Brigandine/g,"cn":"指挥者锁甲"},
{"en":/Battle Lamellar/g,"cn":"争战鳞甲 "},
{"en":/Dragonscale Doublet/g,"cn":"龙鳞护甲 "},
{"en":/Desert Brigandine/g,"cn":"荒野锁铠"},
{"en":/Full Dragonscale/g,"cn":"连身龙鳞铠"},
{"en":/General's Brigandine/g,"cn":"将军铠甲"},
{"en":/Triumphant Lamellar/g,"cn":"胜利盔甲"},
{"en":/Chainmail Vest/g,"cn":"锁链背心"},
{"en":/Chainmail Tunic/g,"cn":"链甲外衣"},
{"en":/Ringmail Coat/g,"cn":"环甲外套"},
{"en":/Chainmail Doublet/g,"cn":"护体锁甲"},
{"en":/Full Ringmail/g,"cn":"连身环甲"},
{"en":/Full Chainmail/g,"cn":"连身锁甲"},
{"en":/Holy Chainmail/g,"cn":"圣语锁甲"},
{"en":/Latticed Ringmail/g,"cn":"精制环甲"},
{"en":/Crusader Chainmail/g,"cn":"圣战锁甲"},
{"en":/Ornate Ringmail/g,"cn":"华丽环甲"},
{"en":/Chain Hauberk/g,"cn":"锁子长甲"},
{"en":/Devout Chainmail/g,"cn":"虔诚链甲"},
{"en":/Loricated Ringmail/g,"cn":"覆体环甲"},
{"en":/Conquest Chainmail/g,"cn":"征战锁甲"},
{"en":/Elegant Ringmail/g,"cn":"权贵环甲"},
{"en":/Saint's Hauberk/g,"cn":"圣者链甲"},
{"en":/Saintly Chainmail/g,"cn":"圣洁锁甲"},
{"en":/Padded Vest/g,"cn":"薄衬衣"},
{"en":/Oiled Vest/g,"cn":"防水背心"},
{"en":/Padded Jacket/g,"cn":"长袖棉袄"},
{"en":/Oiled Coat/g,"cn":"防水外衣"},
{"en":/Scarlet Raiment/g,"cn":"炽红之衣"},
{"en":/Waxed Garb/g,"cn":"蜡封束衣"},
{"en":/Bone Armour/g,"cn":"骨制战甲"},
{"en":/Quilted Jacket/g,"cn":"菱纹外衣"},
{"en":/Sleek Coat/g,"cn":"滑布外套"},
{"en":/Crimson Raiment/g,"cn":"绯红之衣"},
{"en":/Lacquered Garb/g,"cn":"漆彩束衣"},
{"en":/Crypt Armour/g,"cn":"地穴战甲"},
{"en":/Sentinel Jacket/g,"cn":"哨兵之衣"},
{"en":/Varnished Coat/g,"cn":"映彩外套"},
{"en":/Blood Raiment/g,"cn":"血色之衣"},
{"en":/Sadist Garb/g,"cn":"狂虐者束衣"},
{"en":/Carnal Armour/g,"cn":"禁礼之甲"},
{"en":/Sacrificial Garb/g,"cn":"祭礼束衣"},
{"en":/Golden Mantle/g,"cn":"黄金战甲"},
{"en":/Iron Hat/g,"cn":"粗铁盔"},
{"en":/Cone Helmet/g,"cn":"锥顶盔"},
{"en":/Barbute Helmet/g,"cn":"轻骑盔"},
{"en":/Close Helmet/g,"cn":"护面盔"},
{"en":/Gladiator Helmet/g,"cn":"角斗者之盔"},
{"en":/Reaver Helmet/g,"cn":"掠夺者之盔"},
{"en":/Siege Helmet/g,"cn":"破城之盔"},
{"en":/Samite Helmet/g,"cn":"绣领之盔"},
{"en":/Ezomyte Burgonet/g,"cn":"艾兹麦坚盔"},
{"en":/Royal Burgonet/g,"cn":"皇室坚盔"},
{"en":/Eternal Burgonet/g,"cn":"永恒坚盔"},
{"en":/Leather Cap/g,"cn":"皮帽"},
{"en":/Tricorne/g,"cn":"三角帽"},
{"en":/Leather Hood/g,"cn":"革兜"},
{"en":/Wolf Pelt/g,"cn":"狼首皮盔"},
{"en":/Hunter Hood/g,"cn":"猎者之兜"},
{"en":/Noble Tricorne/g,"cn":"贵族三角帽"},
{"en":/Ursine Pelt/g,"cn":"熊首皮盔"},
{"en":/Silken Hood/g,"cn":"绸缎之兜"},
{"en":/Sinner Tricorne/g,"cn":"罪者之帽"},
{"en":/Lion Pelt/g,"cn":"狮首皮盔"},
{"en":/Vine Circlet/g,"cn":"藤蔓之冠"},
{"en":/Iron Circlet/g,"cn":"铁锻之冠"},
{"en":/Torture Cage/g,"cn":"刑罚头笼"},
{"en":/Tribal Circlet/g,"cn":"祭仪之冠"},
{"en":/Bone Circlet/g,"cn":"灵骨之冠"},
{"en":/Lunaris Circlet/g,"cn":"月影之冠"},
{"en":/Steel Circlet/g,"cn":"冷钢之冠"},
{"en":/Necromancer Circlet/g,"cn":"操灵者之冠"},
{"en":/Solaris Circlet/g,"cn":"日耀之冠"},
{"en":/Mind Cage/g,"cn":"灵能之笼"},
{"en":/Hubris Circlet/g,"cn":"灵主之环"},
{"en":/Battered Helm/g,"cn":"残破之盔"},
{"en":/Sallet/g,"cn":"轻铁护盔"},
{"en":/Visored Sallet/g,"cn":"清视护盔"},
{"en":/Gilded Sallet/g,"cn":"金面护盔"},
{"en":/Secutor Helm/g,"cn":"精兵之盔"},
{"en":/Fencer Helm/g,"cn":"击剑士之盔"},
{"en":/Lacquered Helmet/g,"cn":"漆彩之盔"},
{"en":/Fluted Bascinet/g,"cn":"全罩战盔"},
{"en":/Pig-Faced Bascinet/g,"cn":"猪面头盔"},
{"en":/Nightmare Bascinet/g,"cn":"梦魇战盔"},
{"en":/Rusted Coif/g,"cn":"锈铁链盔"},
{"en":/Soldier Helmet/g,"cn":"士兵之盔"},
{"en":/Great Helmet/g,"cn":"巨盔"},
{"en":/Crusader Helmet/g,"cn":"圣战之盔"},
{"en":/Aventail Helmet/g,"cn":"战意之盔"},
{"en":/Zealot Helmet/g,"cn":"热战之盔"},
{"en":/Great Crown/g,"cn":"强化巨盔"},
{"en":/Magistrate Crown/g,"cn":"行政者战冠"},
{"en":/Prophet Crown/g,"cn":"箴言战冠"},
{"en":/Praetor Crown/g,"cn":"领主战冠"},
{"en":/Scare Mask/g,"cn":"幽惧之面"},
{"en":/Plague Mask/g,"cn":"疫灾之面"},
{"en":/Iron Mask/g,"cn":"铁锻之面"},
{"en":/Festival Mask/g,"cn":"节庆之面"},
{"en":/Golden Mask/g,"cn":"黄金之面"},
{"en":/Raven Mask/g,"cn":"祸鸦之面"},
{"en":/Callous Mask/g,"cn":"无情之面"},
{"en":/Regicide Mask/g,"cn":"弒君之面"},
{"en":/Harlequin Mask/g,"cn":"鹰喙之面"},
{"en":/Vaal Mask/g,"cn":"瓦尔之面"},
{"en":/Deicide Mask/g,"cn":"弒神之面"},
{"en":/Golden Wreath/g,"cn":"金黄花环"},
{"en":/Bone Helmet/g,"cn":"唤骨头盔"},
{"en":/Splintered Tower Shield/g,"cn":"朽木塔盾"},
{"en":/Corroded Tower Shield/g,"cn":"斑驳塔盾"},
{"en":/Rawhide Tower Shield/g,"cn":"生皮塔盾"},
{"en":/Cedar Tower Shield/g,"cn":"松木塔盾"},
{"en":/Copper Tower Shield/g,"cn":"铜锻塔盾"},
{"en":/Reinforced Tower Shield/g,"cn":"强化塔盾"},
{"en":/Painted Tower Shield/g,"cn":"彩绘塔盾"},
{"en":/Buckskin Tower Shield/g,"cn":"鹿皮塔盾"},
{"en":/Mahogany Tower Shield/g,"cn":"桃木塔盾"},
{"en":/Bronze Tower Shield/g,"cn":"青铜塔盾"},
{"en":/Girded Tower Shield/g,"cn":"征战塔盾"},
{"en":/Crested Tower Shield/g,"cn":"荣冠塔盾"},
{"en":/Shagreen Tower Shield/g,"cn":"粗革塔盾"},
{"en":/Ebony Tower Shield/g,"cn":"乌木塔盾"},
{"en":/Ezomyte Tower Shield/g,"cn":"艾兹麦塔盾"},
{"en":/Colossal Tower Shield/g,"cn":"巨型塔盾"},
{"en":/Pinnacle Tower Shield/g,"cn":"坚毅塔盾"},
{"en":/Goathide Buckler/g,"cn":"羊皮轻盾"},
{"en":/Pine Buckler/g,"cn":"松木轻盾"},
{"en":/Painted Buckler/g,"cn":"彩绘轻盾"},
{"en":/Hammered Buckler/g,"cn":"铆钉轻盾"},
{"en":/War Buckler/g,"cn":"战争轻盾"},
{"en":/Gilded Buckler/g,"cn":"金面轻盾"},
{"en":/Oak Buckler/g,"cn":"橡木轻盾"},
{"en":/Enameled Buckler/g,"cn":"釉彩轻盾"},
{"en":/Corrugated Buckler/g,"cn":"波纹轻盾"},
{"en":/Battle Buckler/g,"cn":"斗者轻盾"},
{"en":/Golden Buckler/g,"cn":"金阳轻盾"},
{"en":/Ironwood Buckler/g,"cn":"钢木轻盾"},
{"en":/Lacquered Buckler/g,"cn":"漆彩轻盾"},
{"en":/Vaal Buckler/g,"cn":"瓦尔轻盾"},
{"en":/Crusader Buckler/g,"cn":"圣战轻盾"},
{"en":/Imperial Buckler/g,"cn":"帝国轻盾"},
{"en":/Twig Spirit Shield/g,"cn":"残枝魔盾"},
{"en":/Yew Spirit Shield/g,"cn":"紫衫魔盾"},
{"en":/Bone Spirit Shield/g,"cn":"骨制魔盾"},
{"en":/Tarnished Spirit Shield/g,"cn":"环形魔盾"},
{"en":/Jingling Spirit Shield/g,"cn":"灵相魔盾"},
{"en":/Brass Spirit Shield/g,"cn":"铜锻魔盾"},
{"en":/Walnut Spirit Shield/g,"cn":"桃木魔盾"},
{"en":/Ivory Spirit Shield/g,"cn":"象牙魔盾"},
{"en":/Ancient Spirit Shield/g,"cn":"远古魔盾"},
{"en":/Chiming Spirit Shield/g,"cn":"魂相魔盾"},
{"en":/Thorium Spirit Shield/g,"cn":"暗金魔盾"},
{"en":/Lacewood Spirit Shield/g,"cn":"软橡魔盾"},
{"en":/Fossilised Spirit Shield/g,"cn":"石化魔盾"},
{"en":/Vaal Spirit Shield/g,"cn":"瓦尔魔盾"},
{"en":/Harmonic Spirit Shield/g,"cn":"和谐魔盾"},
{"en":/Titanium Spirit Shield/g,"cn":"巨人魔盾"},
{"en":/Rotted Round Shield/g,"cn":"朽木圆盾"},
{"en":/Fir Round Shield/g,"cn":"杉木圆盾"},
{"en":/Studded Round Shield/g,"cn":"铆钉圆盾"},
{"en":/Scarlet Round Shield/g,"cn":"炽红圆盾"},
{"en":/Splendid Round Shield/g,"cn":"光辉圆盾"},
{"en":/Maple Round Shield/g,"cn":"枫木圆盾"},
{"en":/Spiked Round Shield/g,"cn":"尖刺圆盾"},
{"en":/Crimson Round Shield/g,"cn":"绯红圆盾"},
{"en":/Baroque Round Shield/g,"cn":"古代圆盾"},
{"en":/Teak Round Shield/g,"cn":"柚木圆盾"},
{"en":/Spiny Round Shield/g,"cn":"棘刺圆盾"},
{"en":/Cardinal Round Shield/g,"cn":"祭者圆盾"},
{"en":/Elegant Round Shield/g,"cn":"权贵圆盾"},
{"en":/Plank Kite Shield/g,"cn":"朽木鸢盾"},
{"en":/Linden Kite Shield/g,"cn":"椴木鸢盾"},
{"en":/Reinforced Kite Shield/g,"cn":"强化鸢盾"},
{"en":/Layered Kite Shield/g,"cn":"层板鸢盾"},
{"en":/Ceremonial Kite Shield/g,"cn":"祭仪鸢盾"},
{"en":/Etched Kite Shield/g,"cn":"刻文鸢盾"},
{"en":/Steel Kite Shield/g,"cn":"冷钢鸢盾"},
{"en":/Laminated Kite Shield/g,"cn":"合板鸢盾"},
{"en":/Angelic Kite Shield/g,"cn":"天使鸢盾"},
{"en":/Branded Kite Shield/g,"cn":"圣记鸢盾"},
{"en":/Champion Kite Shield/g,"cn":"斗士鸢盾"},
{"en":/Mosaic Kite Shield/g,"cn":"厚装鸢盾"},
{"en":/Archon Kite Shield/g,"cn":"威能鸢盾"},
{"en":/Spiked Bundle/g,"cn":"尖木刺盾"},
{"en":/Driftwood Spiked Shield/g,"cn":"朽木刺盾"},
{"en":/Alloyed Spiked Shield/g,"cn":"合金刺盾"},
{"en":/Burnished Spiked Shield/g,"cn":"冷芒刺盾"},
{"en":/Ornate Spiked Shield/g,"cn":"华丽刺盾"},
{"en":/Redwood Spiked Shield/g,"cn":"红木刺盾"},
{"en":/Compound Spiked Shield/g,"cn":"复合刺盾"},
{"en":/Polished Spiked Shield/g,"cn":"光辉刺盾"},
{"en":/Sovereign Spiked Shield/g,"cn":"王权刺盾"},
{"en":/Alder Spiked Shield/g,"cn":"桤木刺盾"},
{"en":/Ezomyte Spiked Shield/g,"cn":"艾兹麦刺盾"},
{"en":/Mirrored Spiked Shield/g,"cn":"钢镜刺盾"},
{"en":/Supreme Spiked Shield/g,"cn":"霸者刺盾"},
{"en":/Golden Flame/g,"cn":"黄金圣炎"},
{"en":/Paua Amulet/g,"cn":"海灵护身符"},
{"en":/Coral Amulet/g,"cn":"珊瑚护身符"},
{"en":/Amber Amulet/g,"cn":"琥珀护身符"},
{"en":/Jade Amulet/g,"cn":"翠玉护身符"},
{"en":/Lapis Amulet/g,"cn":"海玉护身符"},
{"en":/Gold Amulet/g,"cn":"帝金护身符"},
{"en":/Onyx Amulet/g,"cn":"黑曜护身符"},
{"en":/Turquoise Amulet/g,"cn":"青玉护身符"},
{"en":/Agate Amulet/g,"cn":"玛瑙护身符"},
{"en":/Citrine Amulet/g,"cn":"黄晶护身符"},
{"en":/Ruby Amulet/g,"cn":"血色护身符"},
{"en":/Jet Amulet/g,"cn":"杰特护身符"},
{"en":/Blue Pearl Amulet/g,"cn":"碧珠护身符"},
{"en":/Marble Amulet/g,"cn":"理石护身符"},
{"en":/Black Maw Talisman/g,"cn":"黑牙魔符"},
{"en":/Bonespire Talisman/g,"cn":"脊骨魔符"},
{"en":/Ashscale Talisman/g,"cn":"灰烬魔符"},
{"en":/Lone Antler Talisman/g,"cn":"孤角魔符"},
{"en":/Deep One Talisman/g,"cn":"深渊魔符"},
{"en":/Breakrib Talisman/g,"cn":"碎骨魔符"},
{"en":/Deadhand Talisman/g,"cn":"亡手魔符"},
{"en":/Undying Flesh Talisman/g,"cn":"不朽魔符"},
{"en":/Rot Head Talisman/g,"cn":"腐首魔符"},
{"en":/Mandible Talisman/g,"cn":"巨颚魔符"},
{"en":/Chrysalis Talisman/g,"cn":"虫蛹魔符"},
{"en":/Writhing Talisman/g,"cn":"狂癫魔符"},
{"en":/Hexclaw Talisman/g,"cn":"幻爪魔符"},
{"en":/Primal Skull Talisman/g,"cn":"皇骨魔符"},
{"en":/Wereclaw Talisman/g,"cn":"亡爪魔符"},
{"en":/Splitnewt Talisman/g,"cn":"断螈魔符"},
{"en":/Clutching Talisman/g,"cn":"咒箍魔符"},
{"en":/Avian Twins Talisman/g,"cn":"双子魔符"},
{"en":/Fangjaw Talisman/g,"cn":"齿鲨魔符"},
{"en":/Horned Talisman/g,"cn":"尖角魔符"},
{"en":/Spinefuse Talisman/g,"cn":"潜能魔符"},
{"en":/Three Rat Talisman/g,"cn":"三鼠魔符"},
{"en":/Monkey Twins Talisman/g,"cn":"双猴魔符"},
{"en":/Longtooth Talisman/g,"cn":"长牙魔符"},
{"en":/Rotfeather Talisman/g,"cn":"死羽魔符"},
{"en":/Monkey Paw Talisman/g,"cn":"猴掌魔符"},
{"en":/Three Hands Talisman/g,"cn":"三手魔符"},
{"en":/Greatwolf Talisman/g,"cn":"狼王魔符"},
{"en":/Golden Hoop/g,"cn":"金环"},
{"en":/Iron Ring/g,"cn":"锻铁戒指"},
{"en":/Coral Ring/g,"cn":"珊瑚戒指"},
{"en":/Paua Ring/g,"cn":"海灵戒指"},
{"en":/Gold Ring/g,"cn":"金光戒指"},
{"en":/Topaz Ring/g,"cn":"黄玉戒指"},
{"en":/Sapphire Ring/g,"cn":"蓝玉戒指"},
{"en":/Ruby Ring/g,"cn":"红玉戒指"},
{"en":/Prismatic Ring/g,"cn":"三相戒指"},
{"en":/Moonstone Ring/g,"cn":"月光石戒指"},
{"en":/Amethyst Ring/g,"cn":"紫晶戒指"},
{"en":/Diamond Ring/g,"cn":"宝钻戒指"},
{"en":/Two-Stone Ring/g,"cn":"双玉戒指"},
{"en":/Unset Ring/g,"cn":"潜能之戒"},
{"en":/Jet Ring/g,"cn":"杰特戒指"},
{"en":/Steel Ring/g,"cn":"钢铸戒指"},
{"en":/Opal Ring/g,"cn":"蛋白石戒指"},
{"en":/Breach Ring/g,"cn":"裂痕戒指"},
{"en":/Cured Quiver/g,"cn":"火焰箭袋"},
{"en":/Rugged Quiver/g,"cn":"冰晶箭袋"},
{"en":/Conductive Quiver/g,"cn":"电光箭袋"},
{"en":/Heavy Quiver/g,"cn":"重矢箭袋 "},
{"en":/Light Quiver/g,"cn":"轻巧箭袋"},
{"en":/Serrated Arrow Quiver/g,"cn":"锯齿箭袋"},
{"en":/Two-Point Arrow Quiver/g,"cn":"双锋箭袋"},
{"en":/Sharktooth Arrow Quiver/g,"cn":"鲨齿箭袋"},
{"en":/Blunt Arrow Quiver/g,"cn":"钝矢箭袋 "},
{"en":/Fire Arrow Quiver/g,"cn":"火灵箭袋"},
{"en":/Broadhead Arrow Quiver/g,"cn":"宽矢箭袋"},
{"en":/Penetrating Arrow Quiver/g,"cn":"穿射箭袋"},
{"en":/Spike-Point Arrow Quiver/g,"cn":"刺锋箭袋"},
{"en":/Serrated Arrow Quiver/g,"cn":"锯齿箭袋"},
{"en":/Rustic Sash/g,"cn":"素布腰带"},
{"en":/Chain Belt/g,"cn":"扣链腰带"},
{"en":/Leather Belt/g,"cn":"皮革腰带"},
{"en":/Heavy Belt/g,"cn":"重革腰带"},
{"en":/Cloth Belt/g,"cn":"饰布腰带"},
{"en":/Studded Belt/g,"cn":"扣钉腰带"},
{"en":/Vanguard Belt/g,"cn":"先锋腰带"},
{"en":/Crystal Belt/g,"cn":"水晶腰带"},
{"en":/Golden Obi/g,"cn":"金羽腰带"},
{"en":/Small Life Flask/g,"cn":"小型生命药剂"},
{"en":/Medium Life Flask/g,"cn":"中型生命药剂"},
{"en":/Large Life Flask/g,"cn":"大型生命药剂"},
{"en":/Greater Life Flask/g,"cn":"良质生命药剂"},
{"en":/Grand Life Flask/g,"cn":"优质生命药剂"},
{"en":/Giant Life Flask/g,"cn":"巨型生命药剂"},
{"en":/Colossal Life Flask/g,"cn":"高阶生命药剂"},
{"en":/Sacred Life Flask/g,"cn":"圣语生命药剂"},
{"en":/Hallowed Life Flask/g,"cn":"祝福生命药剂"},
{"en":/Sanctified Life Flask/g,"cn":"圣化生命药剂"},
{"en":/Divine Life Flask/g,"cn":"不朽生命药剂"},
{"en":/Eternal Life Flask/g,"cn":"永恒生命药剂"},
{"en":/Small Mana Flask/g,"cn":"小型魔力药剂"},
{"en":/Medium Mana Flask/g,"cn":"中型魔力药剂"},
{"en":/Large Mana Flask/g,"cn":"大型魔力药剂"},
{"en":/Greater Mana Flask/g,"cn":"良质魔力药剂"},
{"en":/Grand Mana Flask/g,"cn":"优质魔力药剂"},
{"en":/Giant Mana Flask/g,"cn":"巨型魔力药剂"},
{"en":/Colossal Mana Flask/g,"cn":"高阶魔力药剂"},
{"en":/Sacred Mana Flask/g,"cn":"圣语魔力药剂"},
{"en":/Hallowed Mana Flask/g,"cn":"祝福魔力药剂"},
{"en":/Sanctified Mana Flask/g,"cn":"圣化魔力药剂"},
{"en":/Divine Mana Flask/g,"cn":"不朽魔力药剂"},
{"en":/Eternal Mana Flask/g,"cn":"永恒魔力药剂"},
{"en":/Small Hybrid Flask/g,"cn":"小型复合药剂"},
{"en":/Medium Hybrid Flask/g,"cn":"中型复合药剂"},
{"en":/Large Hybrid Flask/g,"cn":"大型复合药剂"},
{"en":/Colossal Hybrid Flask/g,"cn":"高阶复合药剂"},
{"en":/Sacred Hybrid Flask/g,"cn":"圣语复合药剂 "},
{"en":/Hallowed Hybrid Flask/g,"cn":"祝福复合药剂"},
{"en":/Ruby Flask/g,"cn":"红玉药剂"},
{"en":/Sapphire Flask/g,"cn":"蓝玉药剂"},
{"en":/Topaz Flask/g,"cn":"黄玉药剂"},
{"en":/Granite Flask/g,"cn":"坚岩药剂"},
{"en":/Quicksilver Flask/g,"cn":"水银药剂"},
{"en":/Amethyst Flask/g,"cn":"紫晶药剂"},
{"en":/Quartz Flask/g,"cn":"石英药剂"},
{"en":/Jade Flask/g,"cn":"翠玉药剂"},
{"en":/Basalt Flask/g,"cn":"石化药剂"},
{"en":/Aquamarine Flask/g,"cn":"海蓝药剂"},
{"en":/Stibnite Flask/g,"cn":"迷雾药剂"},
{"en":/Sulphur Flask/g,"cn":"硫磺药剂"},
{"en":/Silver Flask/g,"cn":"真银药剂"},
{"en":/Bismuth Flask/g,"cn":"灰岩药剂"},
{"en":/Diamond Flask/g,"cn":"宝钻药剂"}	,
{"en":/Stygian Vise/g,"cn":"冥河腰帶"},
	{"en":/Crimson Jewel/g,"cn":"赤红珠宝"},
{"en":/Viridian Jewel/g,"cn":"翠绿珠宝"},
{"en":/Cobalt Jewel/g,"cn":"钴蓝珠宝"},
{"en":/Prismatic Jewel/g,"cn":"三相珠宝"},
{"en":/Murderous Eye Jewel/g,"cn":"杀戮之眼珠宝"},
{"en":/Searching Eye Jewel/g,"cn":"勘查之眼珠宝"},
{"en":/Hypnotic Eye Jewel/g,"cn":"催眠之眼珠宝"},
{"en":/Ghastly Eye Jewel/g,"cn":"极惧之眼珠宝"}
];

var baseJewelJson=[
{"en":/>Watcher's Eye/g,"cn":">看守之眼(Watcher's Eye)"},
{"en":/>The Long Winter/g,"cn":">凛冽久冬(The Long Winter)"},
{"en":/>The Golden Rule/g,"cn":">黄金守则(The Golden Rule)"},
{"en":/>Soul's Wick/g,"cn":">魂灵之芯(Soul's Wick)"},
{"en":/>Pure Talent/g,"cn":">纯才(Pure Talent)"},
{"en":/>Brawn/g,"cn":">筋骨强化(Brawn)"},
{"en":/>Inertia/g,"cn":">惯性(Inertia)"},
{"en":/>Vampire's Might/g,"cn":">吸血鬼的力量(Vampire's Might)"},
{"en":/>Survival Skills/g,"cn":">生存技巧(Survival Skills)"},
{"en":/>Inspired Learning/g,"cn":">求知的热情(Inspired Learning)"},
{"en":/>Martial Artistry/g,"cn":">武艺之相(Martial Artistry)"},
{"en":/>Spire of Stone/g,"cn":">石塔(Spire of Stone)"},
{"en":/>Mantra of Flames/g,"cn":">烈炎之兆(Mantra of Flames)"},
{"en":/>Combustibles/g,"cn":">燃尽(Combustibles)"},
{"en":/>The Naming Temporary/g,"cn":">暂名(The Naming Temporary)"},
{"en":/>Fragile Bloom/g,"cn":">脆弱的繁华(Fragile Bloom)"},
{"en":/>Rain of Splinters/g,"cn":">碎镞雨(Rain of Splinters)"},
{"en":/>Efficient Training/g,"cn":">充分训练(Efficient Training)"},
{"en":/>Atziri's Reign/g,"cn":">阿兹里之权(Atziri's Reign)"},
{"en":/>Blood Sacrifice/g,"cn":">血牺(Blood Sacrifice)"},
{"en":/>Warlord's Reach/g,"cn":">督军之力(Warlord's Reach)"},
{"en":/>Conqueror's Efficiency/g,"cn":">征服者的迅捷(Conqueror's Efficiency)"},
{"en":/>Ancient Waystones/g,"cn":">远古基石(Ancient Waystones)"},
{"en":/>Zerphi's Youth/g,"cn":">泽佛伊的青春(Zerphi's Youth)"},
{"en":/>Fragility/g,"cn":">虚弱(Fragility)"},
{"en":/>Fireborn/g,"cn":">炎域(Fireborn)"},
{"en":/>Energised Armour/g,"cn":">能量坚甲(Energised Armour)"},
{"en":/>Might in All Forms/g,"cn":">卓绝之力(Might in All Forms)"},
{"en":/>Izaro's Turmoil/g,"cn":">伊泽洛之乱(Izaro's Turmoil)"},
{"en":/>The Vigil/g,"cn":">监视守夜(The Vigil)"},
{"en":/>Rapid Expansion/g,"cn":">急速扩张(Rapid Expansion)"},
{"en":/>Shattered Chains/g,"cn":">破碎之鍊(Shattered Chains)"},
{"en":/>Weight of the Empire/g,"cn":">帝国重量(Weight of the Empire)"},
{"en":/>Emperor's Might/g,"cn":">帝王的霸权(Emperor's Might)"},
{"en":/>Grand Spectrum/g,"cn":">巨光谱(Grand Spectrum)"},
{"en":/>Coated Shrapnel/g,"cn":">榴星(Coated Shrapnel)"},
{"en":/>Underdog's Fury/g,"cn":">牺牲者怒息(Underdog's Fury)"},
{"en":/>Primordial Might/g,"cn":">先祖力量(Primordial Might)"},
{"en":/>The Red Dream/g,"cn":">赤影梦境(The Red Dream)"},
{"en":/>The Red Nightmare/g,"cn":">赤影梦魇(The Red Nightmare)"},
{"en":/>Winter Burial/g,"cn":">冬葬(Winter Burial)"},
{"en":/>Wildfire/g,"cn":">燐火(Wildfire)"},
{"en":/>Overwhelming Odds/g,"cn":">绝对压制(Overwhelming Odds)"},
{"en":/>Fluid Motion/g,"cn":">流畅行动(Fluid Motion)"},
{"en":/>Intuitive Leap/g,"cn":">直觉之跃(Intuitive Leap)"},
{"en":/>Lioneye's Fall/g,"cn":">狮眼的陨落(Lioneye's Fall)"},
{"en":/>Survival Instincts/g,"cn":">生存本能(Survival Instincts)"},
{"en":/>Cannibalistic Habits/g,"cn":">同族相残(Cannibalistic Habits)"},
{"en":/>Apparitions/g,"cn":">映像(Apparitions)"},
{"en":/>Hotfooted/g,"cn":">狂奔(Hotfooted)"},
{"en":/>Weight of Sin/g,"cn":">罪恶的重量(Weight of Sin)"},
{"en":/>Specialised/g,"cn":">熟稔(Specialised)"},
{"en":/>Miser of Misery/g,"cn":">悲惨赐予者(Miser of Misery)"},
{"en":/>Careful Planning/g,"cn":">审慎计划(Careful Planning)"},
{"en":/>Hidden Potential/g,"cn":">深藏的潜能(Hidden Potential)"},
{"en":/>Sacrificial Harvest/g,"cn":">原生祭仪(Sacrificial Harvest)"},
{"en":/>Self-Flagellation/g,"cn":">残虐之欢愉(Self-Flagellation)"},
{"en":/>Poacher's Aim/g,"cn":">盗猎者的准心(Poacher's Aim)"},
{"en":/>Conqueror's Longevity/g,"cn":">征服者的长生(Conqueror's Longevity)"},
{"en":/>Chill of Corruption/g,"cn":">腐化寒息(Chill of Corruption)"},
{"en":/>Hungry Abyss/g,"cn":">饥馑深渊(Hungry Abyss)"},
{"en":/>Pacifism/g,"cn":">和平主义(Pacifism)"},
{"en":/>Pugilist/g,"cn":">迅击者(Pugilist)"},
{"en":/>Cold Steel/g,"cn":">冷钢(Cold Steel)"},
{"en":/>Static Electricity/g,"cn":">静电之源(Static Electricity)"},
{"en":/>Volley Fire/g,"cn":">怒火齐发(Volley Fire)"},
{"en":/>Spirit Guards/g,"cn":">精神守护(Spirit Guards)"},
{"en":/>Pitch Darkness/g,"cn":">黯黑之调(Pitch Darkness)"},
{"en":/>Steel Spirit/g,"cn":">坚毅心灵(Steel Spirit)"},
{"en":/>Growing Agony/g,"cn":">茁壮苦痛(Growing Agony)"},
{"en":/>Cheap Construction/g,"cn":">廉价建设(Cheap Construction)"},
{"en":/>Hair Trigger/g,"cn":">发闸机关(Hair Trigger)"},
{"en":/>Emperor's Cunning/g,"cn":">帝王的诡计(Emperor's Cunning)"},
{"en":/>Primordial Eminence/g,"cn":">先祖卓越(Primordial Eminence)"},
{"en":/>The Green Dream/g,"cn":">青影梦境(The Green Dream)"},
{"en":/>The Green Nightmare/g,"cn":">青影梦魇(The Green Nightmare)"},
{"en":/>Sudden Ignition/g,"cn":">急遽点燃(Sudden Ignition)"},
{"en":/>Ring of Blades/g,"cn":">环形刃(Ring of Blades)"},
{"en":/>Fight for Survival/g,"cn":">存战(Fight for Survival)"},
{"en":/>Omen on the Winds/g,"cn":">乘风之兆(Omen on the Winds)"},
{"en":/>Might and Influence/g,"cn":">强权之势(Might and Influence)"},
{"en":/>Collateral Damage/g,"cn":">战殇(Collateral Damage)"},
{"en":/>Army of Bones/g,"cn":">枯骨军团(Army of Bones)"},
{"en":/>Eldritch Knowledge/g,"cn":">异能知识(Eldritch Knowledge)"},
{"en":/>Selfless Leadership/g,"cn":">无私领导(Selfless Leadership)"},
{"en":/>Survival Secrets/g,"cn":">生存秘技(Survival Secrets)"},
{"en":/>Fertile Mind/g,"cn":">丰富心灵(Fertile Mind)"},
{"en":/>Fortified Legion/g,"cn":">坚守军团(Fortified Legion)"},
{"en":/>Malicious Intent/g,"cn":">不善意图(Malicious Intent)"},
{"en":/>Clear Mind/g,"cn":">理智(Clear Mind)"},
{"en":/>Brute Force Solution/g,"cn":">蛮力冲撞(Brute Force Solution)"},
{"en":/>Vaal Sentencing/g,"cn":">瓦尔之诉(Vaal Sentencing)"},
{"en":/>Fevered Mind/g,"cn":">狂热之心(Fevered Mind)"},
{"en":/>Powerlessness/g,"cn":">无力(Powerlessness)"},
{"en":/>Assassin's Haste/g,"cn":">刺杀者迷影(Assassin's Haste)"},
{"en":/>Conqueror's Potency/g,"cn":">征服者的力量(Conqueror's Potency)"},
{"en":/>Mutated Growth/g,"cn":">堕落异体(Mutated Growth)"},
{"en":/>Corrupted Energy/g,"cn":">腐化能量(Corrupted Energy)"},
{"en":/>Brittle Barrier/g,"cn":">易碎屏障(Brittle Barrier)"},
{"en":/>Anatomical Knowledge/g,"cn":">真知灼见(Anatomical Knowledge)"},
{"en":/>Energy From Within/g,"cn":">潜能防护(Energy From Within)"},
{"en":/>Healthy Mind/g,"cn":">灵体转换(Healthy Mind)"},
{"en":/>Rolling Flames/g,"cn":">滚动烈焰(Rolling Flames)"},
{"en":/>Winter's Bounty/g,"cn":">冬季赏金(Winter's Bounty)"},
{"en":/>Spirited Response/g,"cn":">先祖回音(Spirited Response)"},
{"en":/>Dead Reckoning/g,"cn":">死亡清算(Dead Reckoning)"},
{"en":/>Reckless Defence/g,"cn":">鲁莽防御(Reckless Defence)"},
{"en":/>Unstable Payload/g,"cn":">不稳定承载(Unstable Payload)"},
{"en":/>Emperor's Wit/g,"cn":">帝王的智慧(Emperor's Wit)"},
{"en":/>Unending Hunger/g,"cn":">无尽渴望(Unending Hunger)"},
{"en":/>Primordial Harmony/g,"cn":">先祖和谐(Primordial Harmony)"},
{"en":/>The Blue Dream/g,"cn":">碧影梦境(The Blue Dream)"},
{"en":/>The Blue Nightmare/g,"cn":">碧影梦魇(The Blue Nightmare)"},
{"en":/>Violent Dead/g,"cn":">亡者之残(Violent Dead)"},
{"en":/>First Snow/g,"cn":">初雪(First Snow)"},
{"en":/>Frozen Trail/g,"cn":">迹冻(Frozen Trail)"},
{"en":/>Inevitability/g,"cn":">必然(Inevitability)"},
{"en":/>Emperor's Mastery/g,"cn":">帝王的纯熟(Emperor's Mastery)"},
{"en":/>The Anima Stone/g,"cn":">聚魂石(The Anima Stone)"},

];

var baseItemTypeJson=[
{"en":/Claw/g,"cn":"爪"},
{"en":/Dagger/g,"cn":"匕首"},
{"en":/Wand/g,"cn":"法杖"},
{"en":/One Handed Sword/g,"cn":"单手剑"},
{"en":/Thrusting One Handed Sword/g,"cn":"细剑"},
{"en":/One Handed Axe/g,"cn":"单手斧"},
{"en":/One Handed Mace/g,"cn":"单手锤"},
{"en":/Sceptre/g,"cn":"权杖"},
{"en":/Bow/g,"cn":"弓"},
{"en":/Stave/g,"cn":"长杖"},
{"en":/Two Handed Sword/g,"cn":"双手剑"},
{"en":/Two Handed Axe/g,"cn":"双手斧"},
{"en":/Two Handed Mace/g,"cn":"双手锤"},
{"en":/Fishing Rod/g,"cn":"鱼竿"}

];

