 var itemjson= [
{"en":/<span>Quality/g,"cn":"<span>品质"},
{"en":/<span>Physical Damage/g,"cn":"<span>物理伤害"},
{"en":/<span>Critical Strike Chance/g,"cn":"<span>暴击率"},
{"en":/<span>Attacks per Second/g,"cn":"<span>攻击速度"},
{"en":/<span>Weapon Range/g,"cn":"<span>武器范围"},
{"en":/<span>Mana Cost/g,"cn":"<span>武器范围"},
{"en":/<span>Mana Multiplier/g,"cn":"<span>武器范围"},
{"en":/<span>Elemental Damage/g,"cn":"<span>元素伤害"},
{"en":/                    Requires/g,"cn":"                    需求"},
{"en":/<span>Level/g,"cn":"<span>等级"},
{"en":/<span>Str/g,"cn":"<span>力量"},
{"en":/<span>Dex/g,"cn":"<span>敏捷"},
{"en":/<span>Int/g,"cn":"<span>智慧"},
{"en":/<span>Energy Shield/g,"cn":"<span>能量护盾"},
{"en":/<span>Evasion Rating/g,"cn":"<span>闪避"},
{"en":/<span>Armour/g,"cn":"<span>护甲"},
{"en":/<span class="lc">Mirrored/g,"cn":"<span class=\"lc\">已复制"},
{"en":/<span class="lc">Corrupted/g,"cn":"<span class=\"lc\">已污染"},
{"en":/Properties are doubled while in a Breach/g,"cn":"在裂痕中本装备词缀效果翻倍"},
{"en":/Has (\d+) Socket/g,"cn":"有 # 个插槽"},
{"en":/to Strength and Intelligence/g,"cn":"力量和智慧"},
{"en":/to Strength and Dexterity/g,"cn":"力量和敏捷"},
{"en":/to Dexterity and Intelligence/g,"cn":"敏捷和智慧"},
{"en":/of Fire Damage taken as Lightning Damage/g,"cn":"受到的火焰伤害转化为闪电伤害"},
{"en":/of Lightning Damage taken as Cold Damage/g,"cn":"受到的闪电伤害转化为冰冷伤害"},
{"en":/of Lightning Damage taken as Fire Damage/g,"cn":"受到的闪电伤害转化为火焰伤害"},
{"en":/of Cold Damage taken as Lightning Damage/g,"cn":"受到的冰冷伤害转化为闪电伤害"},
{"en":/of Cold Damage taken as Fire Damage/g,"cn":"受到的冰冷伤害转化为火焰伤害"},
{"en":/of Fire Damage taken as Cold Damage/g,"cn":"受到的火焰伤害转化为冰冷伤害"},
{"en":/(\d+)% increased Global Defences/g,"cn":"增加 #% 全域防御"},
{"en":/(\d+)% chance of Projectiles Piercing/g,"cn":"#% 投射物穿透几率"},
{"en":/(\d+)% additional Physical Damage Reduction/g,"cn":"#% 额外物理伤害减免"},
{"en":/(\d+)% increased Attack and Cast Speed/g,"cn":"增加 #% 攻击和施放速度"},
{"en":/(\d+)% chance to gain an Endurance Charge on Kill/g,"cn":"击杀有 #% 几率获得耐力球"},
{"en":/(\d+)% chance to gain a Power Charge on Kill/g,"cn":"击杀有 #% 几率获得暴击球"},
{"en":/(\d+)% chance to gain a Frenzy Charge on Kill/g,"cn":"击杀有 #% 几率获得狂怒球"},
{"en":/(\d+)% increased Area of Effect of Area Skills/g,"cn":"增加 #% 范围技能的范围效果"},
{"en":/(\d+)% increased Fish Bite Sensitivity/g,"cn":"增加 #% 鱼咬灵敏度"},
{"en":/(\d+)% increased Damage/g,"cn":"增加 #% 伤害"},
{"en":/(\d+)% chance to Freeze, Shock and Ignite/g,"cn":"#% 几率造成点燃，感电和冰冻"},
{"en":/Gain (\d+)% of Physical Damage as Extra Damage of a random Element/g,"cn":"获得 #% 物理伤害的额外1个随机元素伤害"},
{"en":/to maximum number of Zombies/gi,"cn":"最大僵尸数量"},
{"en":/(\d+)% increased Attack Damage/g,"cn":"增加 #% 攻击伤害"},
{"en":/to Armour and Evasion Rating/g,"cn":"护甲和闪避"},
{"en":/Adds (\d+) to (\d+) Physical Damage to Attacks with Bows/g,"cn":"弓攻击附加 # - # 物理伤害"},
{"en":/Adds (\d+) to (\d+) Fire Damage to Attacks with Bows/g,"cn":"弓攻击附加 # - # 火焰伤害"},
{"en":/(\d+)% chance of Arrows Piercing/g,"cn":"箭矢有 #% 穿透几率"},
{"en":/(\d+)% increased Dodge chance/g,"cn":"增加 #% 躲避几率"},
{"en":/(\d+)% chance to cause Bleeding on Hit/g,"cn":"击中有 #% 几率造成流血"},
{"en":/Damage Penetrates (\d+)% Elemental Resistance/g,"cn":"伤害穿透 #% 元素抗性"},
{"en":/Maximum Frenzy Charge/g,"cn":"最大狂怒球"},
{"en":/Maximum Power Charge/g,"cn":"最大暴击球"},
{"en":/Minions deal (\d+)% increased Damage/g,"cn":"增加 #% 召唤物伤害"},
{"en":/to Level of Vaal Gems in this item/g,"cn":"本物品上瓦尔宝石等级"},
{"en":/Physical Damage taken from Attacks/g,"cn":"从攻击受到物理伤害"},
{"en":/(\d+)% of Fire Damage Leeched as Life/g,"cn":"#% 火焰伤害偷取生命"},
{"en":/(\d+)% of Cold Damage Leeched as Life/g,"cn":"#% 冰冷伤害偷取生命"},
{"en":/(\d+)% of Lightning Damage Leeched as Life/g,"cn":"#% 闪电伤害偷取生命"},
{"en":/(\d+)% Chance to Cause Monsters to Flee/g,"cn":"#% 几率让敌人逃跑"},
{"en":/Adds (\d+)–(\d+) Chaos Damage to Attacks/g,"cn":"附加 # - # 混沌伤害到攻击"},
{"en":/Adds (\d+)–(\d+) Chaos Damage/g,"cn":"附加 # - # 混沌伤害"},
{"en":/(\d+)% Chance to Block Spells/g,"cn":"#% 几率格挡法术"},
{"en":/Culling Strike/g,"cn":"扑杀"},
{"en":/(\d+)% of Damage taken Gained as Mana when Hit/g,"cn":"被击中时获得 #% 所受伤害的魔力"},
{"en":/(\d+)% to all maximum Resistances/g,"cn":"# 最大抗性"},
{"en":/Enemies can have (\d+) additional Curse/g,"cn":"敌人可以收到额外 # 个诅咒"},
{"en":/(\d+)% chance to Avoid being Frozen/g,"cn":"#% 几率避免被冰冻"},
{"en":/(\d+)% chance to Avoid being Ignited/g,"cn":"#% 几率避免被点燃"},
{"en":/(\d+)% Chance to Dodge Attacks/g,"cn":"#% 几率躲避攻击"},
{"en":/Cannot be Knocked Back/g,"cn":"免疫击退"},
{"en":/to Level of Gems in this item/g,"cn":"物品上技能等级"},
{"en":/(\d+)% chance to Avoid being Shocked/g,"cn":"#% 几率避免被感电"},
{"en":/Enemies Cannot Leech Life From You/g,"cn":"敌人不能偷取你的生命"},
{"en":/When Hit, (\d+)% of Damage is taken from Mana before Life/g,"cn":"被击中时，#% 伤害优先从魔力扣除"},
{"en":/(\d+)% of Physical Damage Converted to Fire Damage/g,"cn":"受到的 #% 物理伤害转化为火焰伤害"},
{"en":/(\d+)% of Physical Damage Converted to Cold Damage/g,"cn":"受到的 #% 物理伤害转化为冰冷伤害"},
{"en":/(\d+)% of Physical Damage Converted to Lightning Damage/g,"cn":"受到的 #% 物理伤害转化为闪电伤害"},
{"en":/Adds an additional Arrow/g,"cn":"额外箭矢"},
{"en":/(\d+)% increased Radius of Area Skills/g,"cn":"增加 #% 范围技能的范围"},
{"en":/(\d+)% increased Skill Effect Duration/g,"cn":"增加 #% 技能持续时间"},
{"en":/Can set up to (\d+) additional trap/g,"cn":"可以放置额外 # 个陷阱"},
{"en":/Maximum Endurance Charge/g,"cn":"最大耐力球"},
{"en":/(\d+)% additional Chance to Block while Dual Wielding/g,"cn":"双持时增加 #% 格挡几率"},
{"en":/(\d+)% chance of Arrows Piercing/g,"cn":"#% 箭矢穿透几率"},
{"en":/(\d+)% chance of Projectiles Piercing/g,"cn":"#% 投射物穿透几率"},
{"en":/Curse Enemies with level (\d+) Temporal Chains on Hit/g,"cn":"击中时附加等级 # 的【时空锁链】"},
{"en":/Curse Enemies with level (\d+) Vulnerability on Hit/g,"cn":"击中时附加等级 # 的【脆弱】"},
{"en":/Curse Enemies with level (\d+) Elemental Weakness on Hit/g,"cn":"击中时附加等级 # 的【元素要害】"},
{"en":/Gems in this item are supported by level (\d+) Cast when Stunned/gi,"cn":"物品上的宝石被等级 # 的【晕眩时施放】辅助"},
{"en":/Gems in this item are supported by level (\d+) Cast On Crit/gi,"cn":"物品上的宝石被等级 # 的【暴击时施放】辅助"},
{"en":/Gems in this item are supported by level (\d+) Melee Splash/gi,"cn":"物品上的宝石被等级 # 的【近战伤害扩散】辅助"},
{"en":/Gems in this item are Supported by level (\d+) Added Fire Damage/gi,"cn":"物品上的宝石被等级 # 的【附加火焰伤害】辅助"},
{"en":/Gems in this item are supported by level (\d+) Stun/gi,"cn":"物品上的宝石被等级 # 的【击晕】辅助"},
{"en":/to Weapon range/g,"cn":"武器范围"},
{"en":/Skill Gems in this item get a (\d+)% Mana Multiplier/gi,"cn":"物品上的宝石有 #% 魔力消耗倍率"},
{"en":/Gems in this item are Supported by level (\d+) Elemental Proliferation/gi,"cn":"物品上的宝石被等级 # 的【元素扩散】辅助"},
{"en":/Gems in this item are supported by level (\d+) Additional Accuracy/gi,"cn":"物品上的宝石被等级 # 的【额外命中】辅助"},
{"en":/Gems in this item are supported by level (\d+) Multistrike/gi,"cn":"物品上的宝石被等级 # 的【多重打击】辅助"},
{"en":/Gems in this item are Supported by level (\d+) Increased Area of Effect/gi,"cn":"物品上的宝石被等级 # 的【范围增大】辅助"},
{"en":/Gems in this item are supported by level (\d+) Life Leech/gi,"cn":"物品上的宝石被等级 # 的【生命偷取】辅助"},
{"en":/Gems in this item are supported by level (\d+) Increased Critical Damage/gi,"cn":"物品上的宝石被等级 # 的【增加暴击伤害】辅助"},
{"en":/Gems in this item are supported by level (\d+) Fork/gi,"cn":"物品上的宝石被等级 # 的【分裂】辅助"},
{"en":/Gems in this item are supported by level (\d+) Weapon Elemental Damage/gi,"cn":"物品上的宝石被等级 # 的【武器元素伤害】辅助"},
{"en":/Gems in this item are Supported by level (\d+) Faster Casting/gi,"cn":"物品上的宝石被等级 # 的【快速施法】辅助"},
{"en":/Grants level (\d+) Purity of Elements Skill/g,"cn":"获得等级 # 的【元素净化】技能"},
{"en":/Grants level (\d+) Assassin's Mark Skill/g,"cn":"获得等级 # 的【刺客印记】技能"},
{"en":/Grants level (\d+) Purity of Fire Skill/g,"cn":"获得等级 # 的【火焰净化】技能"},
{"en":/Grants level (\d+) Purity of Ice Skill/g,"cn":"获得等级 # 的【冰霜净化】技能"},
{"en":/Grants level (\d+) Purity of Lightning Skill/g,"cn":"获得等级 # 的【闪电净化】技能"},
{"en":/Grants level (\d+) Wrath Skill/g,"cn":"获得等级 # 的【雷霆】技能"},
{"en":/Grants level (\d+) Hatred Skill/g,"cn":"获得等级 # 的【憎恨】技能"},
{"en":/Grants level (\d+) Anger Skill/g,"cn":"获得等级 # 的【愤怒】技能"},
{"en":/Grants level (\d+) Determination Skill/g,"cn":"获得等级 # 的【坚定】技能"},
{"en":/Grants level (\d+) Grace Skill/g,"cn":"优雅"},
{"en":/Grants level (\d+) Discipline Skill/g,"cn":"获得等级 # 的【纪律】技能"},
{"en":/Grants level (\d+) Projectile Weakness Skill/g,"cn":"获得等级 # 的【投射物要害】技能"},
{"en":/Grants level (\d+) Elemental Weakness Skill/g,"cn":"获得等级 # 的【元素要害】技能"},
{"en":/Grants level (\d+) Vulnerability Skill/g,"cn":"获得等级 # 的【脆弱】技能"},
{"en":/Grants level (\d+) Clarity Skill/g,"cn":"获得等级 # 的【清晰】技能"},
{"en":/Grants level (\d+) Frostbite Skill/g,"cn":"获得等级 # 的【冻伤】技能"},
{"en":/Grants level (\d+) Conductivity Skill/g,"cn":"获得等级 # 的【导电】技能"},
{"en":/Grants level (\d+) Temporal Chains Skill/g,"cn":"获得等级 # 的【时空锁链】技能"},
{"en":/Grants level (\d+) Haste Skill/g,"cn":"获得等级 # 的【迅捷】技能"},
{"en":/ Mana gained for each enemy hit by your Attacks/g,"cn":" 攻击击中回复魔力"},
{"en":/Grants level (\d+) Vitality Skill/g,"cn":"获得等级 # 的【活力】技能"},
{"en":/(\d+)% increased Quantity of Fish Caught/g,"cn":"增加 #% 鱼的数量"},
{"en":/(\d+)% increased Rarity of Fish Caught/g,"cn":"增加 #% 鱼的稀有度"},
{"en":/You can catch Corrupted Fish/g,"cn":"你可以捕获已污染的鱼"},
{"en":/(\d+)% additional Chance to receive a Critical Strike/g,"cn":"额外 #% 几率受到暴击"},
{"en":/(\d+)% increased Chaos Damage per equipped Corrupted Item/g,"cn":"装备每件已污染的物品增加 #% 混沌伤害"},
{"en":/(\d+)% increased Damage while Dead/g,"cn":"死亡时增加 #% 伤害"},
{"en":/(\d+)% increased Endurance Frenzy and Power Charge Duration/g,"cn":"增加 #% 耐力球 狂怒球和暴击球持续时间"},
{"en":/(\d+)% increased Life Leeched per second per equipped Corrupted Item/g,"cn":"装备每件已污染的物品增加 #% 生命偷取"},
{"en":/(\d+)% increased Mana Leeched per second per equipped Corrupted Item/g,"cn":"装备每件已污染的物品增加 #% 魔力偷取"},
{"en":/(\d+)% reduced Character Size/g,"cn":"减少 #% 角色体型"},
{"en":/(\d+)% reduced Chill Duration on You/g,"cn":"减少 #% 冰缓持续时间"},
{"en":/(\d+)% reduced Freeze Duration on You/g,"cn":"减少 #% 冰冻持续时间"},
{"en":/(\d+)% reduced Ignite Duration on You/g,"cn":"减少 #% 点燃持续时间"},
{"en":/(\d+)% reduced Shock Duration on You/g,"cn":"减少 #% 感电持续时间"},
{"en":/You are Immune to Silence/g,"cn":"免疫沉默"},
{"en":/(\d+)% increased Vaal Skill Damage/g,"cn":"增加 #% 瓦尔技能的伤害"}


];

var uniqueNameJson=[
{"en":/>Lycosidae/g,"cn":">狼蛛(Lycosidae)"},
{"en":/>Trolltimber Spire/g,"cn":">巫木(Trolltimber Spire)"},
{"en":/>Titucius' Span/g,"cn":">提图库斯的坚盾(Titucius' Span)"},
{"en":/>Redblade Banner/g,"cn":">红刃旗帜(Redblade Banner)"},
{"en":/>Chernobog's Pillar/g,"cn":">五芒屏障(Chernobog's Pillar)"},
{"en":/>Tukohama's Fortress/g,"cn":">图克玛哈堡垒(Tukohama's Fortress)"},
{"en":/>The Surrender/g,"cn":">降伏(The Surrender)"},
{"en":/>The Anticipation/g,"cn":">悬念(The Anticipation)"},
{"en":/>Ahn's Heritage/g,"cn":">汉恩的遗产(Ahn's Heritage)"},
{"en":/>Lioneye's Remorse/g,"cn":">狮眼的荣耀之盾(Lioneye's Remorse)"},
{"en":/>Remnant of Empires/g,"cn":">帝国的残壁(Remnant of Empires)"},
{"en":/>Crest of Perandus/g,"cn":">普兰德斯之徽(Crest of Perandus)"},
{"en":/>Kaltenhalt/g,"cn":">冰霜之镜(Kaltenhalt)"},
{"en":/>Kaltensoul/g,"cn":">冰霜之魂(Kaltensoul)"},
{"en":/>Chalice of Horrors/g,"cn":">恐惧之缶(Chalice of Horrors)"},
{"en":/>Thirst for Horrors/g,"cn":">颤栗之飢(Thirst for Horrors)"},
{"en":/>Mutewind Pennant/g,"cn":">哑风尖旗(Mutewind Pennant)"},
{"en":/>Great Old One's Ward/g,"cn":">邪神庇护(Great Old One's Ward)"},
{"en":/>Atziri's Mirror/g,"cn":">阿兹里之镜(Atziri's Mirror)"},
{"en":/>Thousand Teeth Temu/g,"cn":">千齿(Thousand Teeth Temu)"},
{"en":/>Death Rattle/g,"cn":">亡灵之音(Death Rattle)"},
{"en":/>Matua Tupuna/g,"cn":">远祖之颅(Matua Tupuna)"},
{"en":/>Brinerot Flag/g,"cn":">布琳洛特之旗(Brinerot Flag)"},
{"en":/>Light of Lunaris/g,"cn":">月影之耀(Light of Lunaris)"},
{"en":/>Sentari's Answer/g,"cn":">山特立的回应(Sentari's Answer)"},
{"en":/>Kongming's Stratagem/g,"cn":">孔明的神算(Kongming's Stratagem)"},
{"en":/>Esh's Mirror/g,"cn":">艾许之镜(Esh's Mirror)"},
{"en":/>Esh's Visage/g,"cn":">艾许之面(Esh's Visage)"},
{"en":/>Malachai's Loop/g,"cn":">轮回(Malachai's Loop)"},
{"en":/>Rathpith Globe/g,"cn":">献祭之心(Rathpith Globe)"},
{"en":/>Wheel of the Stormsail/g,"cn":">暴雨之舵(Wheel of the Stormsail)"},
{"en":/>The Deep One's Hide/g,"cn":">深渊绝壁(The Deep One's Hide)"},
{"en":/>Daresso's Courage/g,"cn":">德瑞索的勇者之盾(Daresso's Courage)"},
{"en":/>Springleaf/g,"cn":">新生之徽(Springleaf)"},
{"en":/>The Oak/g,"cn":">橡树(The Oak)"},
{"en":/>Alkem Eira/g,"cn":">神谕(Alkem Eira)"},
{"en":/>Santoni's Faith/g,"cn":">桑托尼的忠诚之心(Santoni's Faith)"},
{"en":/>Victario's Charity/g,"cn":">维多里奥的贡献(Victario's Charity)"},
{"en":/>Saffell's Frame/g,"cn":">萨费尔的智慧(Saffell's Frame)"},
{"en":/>Aegis Aurora/g,"cn":">幻芒圣盾(Aegis Aurora)"},
{"en":/>Rise of the Phoenix/g,"cn":">烈炎之翼(Rise of the Phoenix)"},
{"en":/>Prism Guardian/g,"cn":">元素的庇护(Prism Guardian)"},
{"en":/>Broken Faith/g,"cn":">破碎信念(Broken Faith)"},
{"en":/>Glitterdisc/g,"cn":">七彩碟(Glitterdisc)"},
{"en":/>Maligaro's Lens/g,"cn":">马雷葛萝的染血透镜(Maligaro's Lens)"},
{"en":/>Jaws of Agony/g,"cn":">苦痛狂鲨(Jaws of Agony)"},
{"en":/>Demigod's Beacon/g,"cn":">升华之灯(Demigod's Beacon)"},
{"en":/>Ezomyte Peak/g,"cn":">艾兹麦的荣光(Ezomyte Peak)"},
{"en":/>Tear of Entropy/g,"cn":">乱世之泪(Tear of Entropy)"},
{"en":/>Ezomyte Hold/g,"cn":">艾兹麦之握(Ezomyte Hold)"},
{"en":/>The Baron/g,"cn":">男爵(The Baron)"},
{"en":/>The Formless Flame/g,"cn":">无形火炬(The Formless Flame)"},
{"en":/>Hrimnor's Resolve/g,"cn":">雷姆诺的豪情(Hrimnor's Resolve)"},
{"en":/>Abyssus/g,"cn":">深渊之唤(Abyssus)"},
{"en":/>The Formless Inferno/g,"cn":">无形炼狱(The Formless Inferno)"},
{"en":/>Goldrim/g,"cn":">金缕帽(Goldrim)"},
{"en":/>Fairgraves' Tricorne/g,"cn":">费尔之帽(Fairgraves' Tricorne)"},
{"en":/>Heatshiver/g,"cn":">寒焰(Heatshiver)"},
{"en":/>Rat's Nest/g,"cn":">鼠巢(Rat's Nest)"},
{"en":/>Starkonja's Head/g,"cn":">斯塔空加之首(Starkonja's Head)"},
{"en":/>Alpha's Howl/g,"cn":">极地之嗥(Alpha's Howl)"},
{"en":/>Obscurantis/g,"cn":">朦胧诡面(Obscurantis)"},
{"en":/>Crown of Thorns/g,"cn":">刺棘之冠(Crown of Thorns)"},
{"en":/>Martyr's Crown/g,"cn":">烈士之冠(Martyr's Crown)"},
{"en":/>Asenath's Mark/g,"cn":">安赛娜丝的迅敏之冠(Asenath's Mark)"},
{"en":/>Doedre's Scorn/g,"cn":">德瑞的蔑视(Doedre's Scorn)"},
{"en":/>Chitus' Apex/g,"cn":">切特斯的威权(Chitus' Apex)"},
{"en":/>Rime Gaze/g,"cn":">酷寒的凝视(Rime Gaze)"},
{"en":/>Scold's Bridle/g,"cn":">禁语(Scold's Bridle)"},
{"en":/>Vizaru's Folly/g,"cn":">维札卢的不堪往事(Vizaru's Folly)"},
{"en":/>Ylfe Ban/g,"cn":">禁语(Ylfe Ban)"},
{"en":/>Crown of Eyes/g,"cn":">邪眼之冠(Crown of Eyes)"},
{"en":/>Ylfeban's Trickery/g,"cn":">伊芙班的诡计(Ylfeban's Trickery)"},
{"en":/>The Peregrine/g,"cn":">疾风的沉思(The Peregrine)"},
{"en":/>Deidbell/g,"cn":">丧钟(Deidbell)"},
{"en":/>Deidbellow/g,"cn":">丧吼(Deidbellow)"},
{"en":/>Skullhead/g,"cn":">光辉之颅(Skullhead)"},
{"en":/>Black Sun Crest/g,"cn":">黑阳之冠(Black Sun Crest)"},
{"en":/>The Bringer of Rain/g,"cn":">祭礼之雨(The Bringer of Rain)"},
{"en":/>Devoto's Devotion/g,"cn":">德沃托的信念之盔(Devoto's Devotion)"},
{"en":/>Honourhome/g,"cn":">私欲的光辉(Honourhome)"},
{"en":/>Veil of the Night/g,"cn":">夜幕(Veil of the Night)"},
{"en":/>Mindspiral/g,"cn":">灵漩(Mindspiral)"},
{"en":/>Kitava's Thirst/g,"cn":">奇塔弗之渴望(Kitava's Thirst)"},
{"en":/>Geofri's Crest/g,"cn":">吉尔菲的荣光(Geofri's Crest)"},
{"en":/>The Broken Crown/g,"cn":">缺角帝冠(The Broken Crown)"},
{"en":/>The Brine Crown/g,"cn":">海王冠冕(The Brine Crown)"},
{"en":/>Voll's Vision/g,"cn":">福尔的远见(Voll's Vision)"},
{"en":/>Malachai's Vision/g,"cn":">玛拉凯的远见(Malachai's Vision)"},
{"en":/>Malachai's Simula/g,"cn":">玛拉凯的祭具(Malachai's Simula)"},
{"en":/>Leer Cast/g,"cn":">共鸣之面(Leer Cast)"},
{"en":/>The Three Dragons/g,"cn":">三龙战纪(The Three Dragons)"},
{"en":/>The Gull/g,"cn":">鸥喙(The Gull)"},
{"en":/>Crown of the Pale King/g,"cn":">殒皇之冠(Crown of the Pale King)"},
{"en":/>Mind of the Council/g,"cn":">议会之心(Mind of the Council)"},
{"en":/>The Vertex/g,"cn":">谜容(The Vertex)"},
{"en":/>Heretic's Veil/g,"cn":">异教面纱(Heretic's Veil)"},
{"en":/>Demigod's Triumph/g,"cn":">升华之冠(Demigod's Triumph)"},
{"en":/>Bramblejack/g,"cn":">刺棘宝甲(Bramblejack)"},
{"en":/>Wall of Brambles/g,"cn":">荆棘之墙(Wall of Brambles)"},
{"en":/>Spiritskin/g,"cn":">精神之肤(Spiritskin)"},
{"en":/>TrapperBodyTempName/g,"cn":">TrapperBodyTempName(TrapperBodyTempName)"},
{"en":/>Skin of the Loyal/g,"cn":">忠诚之肤(Skin of the Loyal)"},
{"en":/>Solaris Lorica/g,"cn":">烈阳铠(Solaris Lorica)"},
{"en":/>Greed's Embrace/g,"cn":">贪婪之拥(Greed's Embrace)"},
{"en":/>Lioneye's Vision/g,"cn":">狮眼的视线(Lioneye's Vision)"},
{"en":/>Death's Oath/g,"cn":">冥使之体(Death's Oath)"},
{"en":/>The Brass Dome/g,"cn":">坚铜战罩(The Brass Dome)"},
{"en":/>Kaom's Heart/g,"cn":">冈姆的壮志(Kaom's Heart)"},
{"en":/>Briskwrap/g,"cn":">荒途(Briskwrap)"},
{"en":/>Ashrend/g,"cn":">拂烬(Ashrend)"},
{"en":/>Dewath's Hide/g,"cn":">德瓦斯的匿踪(Dewath's Hide)"},
{"en":/>Foxshade/g,"cn":">狐毛铠(Foxshade)"},
{"en":/>The Snowblind Grace/g,"cn":">雪盲恩惠(The Snowblind Grace)"},
{"en":/>Bronn's Lithe/g,"cn":">布隆的影衣(Bronn's Lithe)"},
{"en":/>The Rat Cage/g,"cn":">疫鼠囚笼(The Rat Cage)"},
{"en":/>Queen of the Forest/g,"cn":">森林之后(Queen of the Forest)"},
{"en":/>Kintsugi/g,"cn":">金缮(Kintsugi)"},
{"en":/>Hyrri's Ire/g,"cn":">西里的战衣(Hyrri's Ire)"},
{"en":/>The Perfect Form/g,"cn":">完美姿态(The Perfect Form)"},
{"en":/>Cospri's Will/g,"cn":">卡斯普里意志(Cospri's Will)"},
{"en":/>Thousand Ribbons/g,"cn":">千缕(Thousand Ribbons)"},
{"en":/>Skin of the Lords/g,"cn":">君主之肤(Skin of the Lords)"},
{"en":/>Cloak of Flame/g,"cn":">烈炎之袍(Cloak of Flame)"},
{"en":/>Zahndethus' Cassock/g,"cn":">札德图斯的圣衣(Zahndethus' Cassock)"},
{"en":/>The Covenant/g,"cn":">血誓(The Covenant)"},
{"en":/>Soul Mantle/g,"cn":">祖灵之约(Soul Mantle)"},
{"en":/>Cloak of Tawm'r Isley/g,"cn":">陶米儿艾斯理之袍(Cloak of Tawm'r Isley)"},
{"en":/>Vis Mortis/g,"cn":">兀鸣(Vis Mortis)"},
{"en":/>Shavronne's Wrappings/g,"cn":">薛朗的护身长袍(Shavronne's Wrappings)"},
{"en":/>Infernal Mantle/g,"cn":">炼狱之心(Infernal Mantle)"},
{"en":/>The Beast Fur Shawl/g,"cn":">兽毛披肩(The Beast Fur Shawl)"},
{"en":/>Viper's Scales/g,"cn":">毒蛇之度(Viper's Scales)"},
{"en":/>Gruthkul's Pelt/g,"cn":">葛鲁斯寇真皮(Gruthkul's Pelt)"},
{"en":/>Belly of the Beast/g,"cn":">兽腹(Belly of the Beast)"},
{"en":/>Lightning Coil/g,"cn":">雷语(Lightning Coil)"},
{"en":/>Daresso's Defiance/g,"cn":">德瑞索的卫衣(Daresso's Defiance)"},
{"en":/>Cherrubim's Maleficence/g,"cn":">薛鲁宾的恶作剧(Cherrubim's Maleficence)"},
{"en":/>Voll's Protector/g,"cn":">福尔的战铠(Voll's Protector)"},
{"en":/>Icetomb/g,"cn":">冰息(Icetomb)"},
{"en":/>Ambu's Charge/g,"cn":">安姆布的战甲(Ambu's Charge)"},
{"en":/>Lightbane Raiment/g,"cn":">魔道之衣(Lightbane Raiment)"},
{"en":/>Kingsguard/g,"cn":">皇家卫甲(Kingsguard)"},
{"en":/>Geofri's Sanctuary/g,"cn":">吉尔菲的圣殿(Geofri's Sanctuary)"},
{"en":/>Incandescent Heart/g,"cn":">烈炎之心(Incandescent Heart)"},
{"en":/>Cloak of Defiance/g,"cn":">卫道之袍(Cloak of Defiance)"},
{"en":/>Victario's Influence/g,"cn":">维多里奥之绝响(Victario's Influence)"},
{"en":/>Carcass Jack/g,"cn":">致命之体(Carcass Jack)"},
{"en":/>The Restless Ward/g,"cn":">无尽之卫(The Restless Ward)"},
{"en":/>Atziri's Splendour/g,"cn":">阿兹里的威权(Atziri's Splendour)"},
{"en":/>Demigod's Dominance/g,"cn":">升华统御(Demigod's Dominance)"},
{"en":/>Ghostmarch/g,"cn":">鬼行(Ghostmarch)"},
{"en":/>Rumblemarch/g,"cn":">奋勇进军(Rumblemarch)"},
{"en":/>Windscream/g,"cn":">恶风足迹(Windscream)"},
{"en":/>Redblade Tramplers/g,"cn":">红刃蹂躏靴(Redblade Tramplers)"},
{"en":/>The Infinite Pursuit/g,"cn":">无尽之距(The Infinite Pursuit)"},
{"en":/>Kaom's Roots/g,"cn":">冈姆的稳重之靴(Kaom's Roots)"},
{"en":/>The Red Trail/g,"cn":">赤红踪迹(The Red Trail)"},
{"en":/>Seven-League Step/g,"cn":">盟誓之迹(Seven-League Step)"},
{"en":/>Victario's Flight/g,"cn":">维多里奥的飞升(Victario's Flight)"},
{"en":/>Abberath's Hooves/g,"cn":">艾贝拉斯之蹄(Abberath's Hooves)"},
{"en":/>Deerstalker/g,"cn":">猎踪(Deerstalker)"},
{"en":/>Goldwyrm/g,"cn":">龙炎足迹(Goldwyrm)"},
{"en":/>The Blood Dance/g,"cn":">血影(The Blood Dance)"},
{"en":/>Three-step Assault/g,"cn":">三步突击(Three-step Assault)"},
{"en":/>Sin Trek/g,"cn":">敏锐思维(Sin Trek)"},
{"en":/>Garukhan's Flight/g,"cn":">卡洛翰之影(Garukhan's Flight)"},
{"en":/>Atziri's Step/g,"cn":">阿兹里的金履(Atziri's Step)"},
{"en":/>Wanderlust/g,"cn":">苦行之履(Wanderlust)"},
{"en":/>Wondertrap/g,"cn":">回光之迹(Wondertrap)"},
{"en":/>Bones of Ullr/g,"cn":">灵骸之履(Bones of Ullr)"},
{"en":/>Shavronne's Pace/g,"cn":">薛朗的秘术长靴(Shavronne's Pace)"},
{"en":/>Shavronne's Gambit/g,"cn":">薛朗的诡计(Shavronne's Gambit)"},
{"en":/>Rainbowstride/g,"cn":">虹幕(Rainbowstride)"},
{"en":/>Steppan Eard/g,"cn":">绝地魔履(Steppan Eard)"},
{"en":/>Skyforth/g,"cn":">空向(Skyforth)"},
{"en":/>Dusktoe/g,"cn":">迎暮(Dusktoe)"},
{"en":/>Lioneye's Paws/g,"cn":">狮眼的斗志(Lioneye's Paws)"},
{"en":/>Mutewind Whispersteps/g,"cn":">哑风轻步(Mutewind Whispersteps)"},
{"en":/>Darkray Vectors/g,"cn":">暗雷(Darkray Vectors)"},
{"en":/>Wake of Destruction/g,"cn":">覆灭之兆(Wake of Destruction)"},
{"en":/>Alberon's Warpath/g,"cn":">阿尔贝隆的征途(Alberon's Warpath)"},
{"en":/>Gang's Momentum/g,"cn":">刚勇(Gang's Momentum)"},
{"en":/>Death's Door/g,"cn":">死亡大门(Death's Door)"},
{"en":/>Nomic's Storm/g,"cn":">诺米克的风暴(Nomic's Storm)"},
{"en":/>Sundance/g,"cn":">日耀(Sundance)"},
{"en":/>Brinerot Whalers/g,"cn":">布琳洛特岸行者(Brinerot Whalers)"},
{"en":/>Voidwalker/g,"cn":">虚空行者(Voidwalker)"},
{"en":/>Demigod's Stride/g,"cn":">升华之途(Demigod's Stride)"},
{"en":/>Lochtonial Caress/g,"cn":">意识之缘(Lochtonial Caress)"},
{"en":/>Ironweld/g,"cn":">铁芒(Ironweld)"},
{"en":/>Meginord's Vise/g,"cn":">梅吉诺德的巨力腕甲(Meginord's Vise)"},
{"en":/>Winds of Change/g,"cn":">升华之风(Winds of Change)"},
{"en":/>Empire's Grasp/g,"cn":">帝国之掌(Empire's Grasp)"},
{"en":/>Atziri's Acuity/g,"cn":">阿兹里的捷思(Atziri's Acuity)"},
{"en":/>Doryani's Fist/g,"cn":">多里亚尼之拳(Doryani's Fist)"},
{"en":/>Veruso's Battering Rams/g,"cn":">维卢梭攻城槌(Veruso's Battering Rams)"},
{"en":/>Hrimsorrow/g,"cn":">冰冷之眼(Hrimsorrow)"},
{"en":/>Hrimburn/g,"cn":">李姆本(Hrimburn)"},
{"en":/>Maligaro's Virtuosity/g,"cn":">马雷葛萝的血染手套(Maligaro's Virtuosity)"},
{"en":/>Sadima's Touch/g,"cn":">猎宝者的护手(Sadima's Touch)"},
{"en":/>Doedre's Tenure/g,"cn":">德瑞的精神手套(Doedre's Tenure)"},
{"en":/>Asenath's Gentle Touch/g,"cn":">安赛娜丝的安抚之语(Asenath's Gentle Touch)"},
{"en":/>Voidbringer/g,"cn":">虚空之力(Voidbringer)"},
{"en":/>Grip of the Council/g,"cn":">议会之握(Grip of the Council)"},
{"en":/>Flesh and Spirit/g,"cn":">肉体与魂灵(Flesh and Spirit)"},
{"en":/>Slitherpinch/g,"cn":">苍蟒之鳞(Slitherpinch)"},
{"en":/>Vaal Caress/g,"cn":">瓦尔的灵手(Vaal Caress)"},
{"en":/>Aurseize/g,"cn":">富贵之运(Aurseize)"},
{"en":/>Deadman's Hand/g,"cn":">枯萎之手(Deadman's Hand)"},
{"en":/>Kalisa's Grace/g,"cn":">卡莉莎的优雅之影(Kalisa's Grace)"},
{"en":/>Arimagius' Honor/g,"cn":">志士的荣耀之心(Arimagius' Honor)"},
{"en":/>Wurmfist/g,"cn":">崩石(Wurmfist)"},
{"en":/>Haemophilia/g,"cn":">逆凝之血(Haemophilia)"},
{"en":/>Wyrmsign/g,"cn":">龙族印记(Wyrmsign)"},
{"en":/>Surgebinders/g,"cn":">浪涌缚者(Surgebinders)"},
{"en":/>Shackles of the Wretched/g,"cn":">悲运之缚(Shackles of the Wretched)"},
{"en":/>Southbound/g,"cn":">南方(Southbound)"},
{"en":/>Null and Void/g,"cn":">虚空(Null and Void)"},
{"en":/>Repentance/g,"cn":">悔悟之掌(Repentance)"},
{"en":/>Shaper's Touch/g,"cn":">塑者之触(Shaper's Touch)"},
{"en":/>Ondar's Clasp/g,"cn":">恩德的迅影(Ondar's Clasp)"},
{"en":/>Facebreaker/g,"cn":">毁面者(Facebreaker)"},
{"en":/>Shadows and Dust/g,"cn":">沙尘之影(Shadows and Dust)"},
{"en":/>Snakebite/g,"cn":">蝮吻(Snakebite)"},
{"en":/>Thunderfist/g,"cn":">轰天雷(Thunderfist)"},
{"en":/>Demigod's Touch/g,"cn":">升华之指(Demigod's Touch)"},
{"en":/>Lifesprig/g,"cn":">生机之记(Lifesprig)"},
{"en":/>Splinter of the Moon/g,"cn":">碎月(Splinter of the Moon)"},
{"en":/>Stormblast/g,"cn":">雷暴(Stormblast)"},
{"en":/>Abberath's Horn/g,"cn":">艾贝拉斯之角(Abberath's Horn)"},
{"en":/>Storm Prison/g,"cn":">禁锢暴风(Storm Prison)"},
{"en":/>Ashcaller/g,"cn":">灰烬行者(Ashcaller)"},
{"en":/>Reverberation Rod/g,"cn":">混响(Reverberation Rod)"},
{"en":/>Amplification Rod/g,"cn":">增幅杖(Amplification Rod)"},
{"en":/>Tulborn/g,"cn":">托沃崩(Tulborn)"},
{"en":/>Twyzel/g,"cn":">峡湾之星(Twyzel)"},
{"en":/>Shade of Solaris/g,"cn":">日耀之影(Shade of Solaris)"},
{"en":/>Midnight Bargain/g,"cn":">冥约(Midnight Bargain)"},
{"en":/>Eclipse Solaris/g,"cn":">宇蚀(Eclipse Solaris)"},
{"en":/>Obliteration/g,"cn":">抹灭(Obliteration)"},
{"en":/>Moonsorrow/g,"cn":">泣月(Moonsorrow)"},
{"en":/>Apep's Rage/g,"cn":">艾普之怒(Apep's Rage)"},
{"en":/>Piscator's Vigil/g,"cn":">皮斯卡托的慧眼(Piscator's Vigil)"},
{"en":/>Tulfall/g,"cn":">托沃卧(Tulfall)"},
{"en":/>Void Battery/g,"cn":">潜能魔棒(Void Battery)"},
{"en":/>Fragment of Eternity/g,"cn":">亘古之灵(Fragment of Eternity)"},
{"en":/>Celestial Fragment/g,"cn":">残星(Celestial Fragment)"},
{"en":/>Felltooth/g,"cn":">崩齿(Felltooth)"},
{"en":/>Goredrill/g,"cn":">血凿(Goredrill)"},
{"en":/>Bloodplay/g,"cn":">血谑(Bloodplay)"},
{"en":/>Ungil's Gauche/g,"cn":">恩吉尔的叉刃(Ungil's Gauche)"},
{"en":/>Mightflay/g,"cn":">力量猎刃(Mightflay)"},
{"en":/>Widowmaker/g,"cn":">寡妇(Widowmaker)"},
{"en":/>Heartbreaker/g,"cn":">裂心刃(Heartbreaker)"},
{"en":/>The Consuming Dark/g,"cn":">蚕食之闇(The Consuming Dark)"},
{"en":/>Arakaali's Fang/g,"cn":">亚拉卡力之牙(Arakaali's Fang)"},
{"en":/>Bino's Kitchen Knife/g,"cn":">比诺的厨刀(Bino's Kitchen Knife)"},
{"en":/>Mark of the Doubting Knight/g,"cn":">迷茫幻符(Mark of the Doubting Knight)"},
{"en":/>Divinarius/g,"cn":">戒律之影(Divinarius)"},
{"en":/>Last Resort/g,"cn":">终息(Last Resort)"},
{"en":/>Scar of Fate/g,"cn":">命运伤痕(Scar of Fate)"},
{"en":/>Leviathan Ivory/g,"cn":">神力之牙(Leviathan Ivory)"},
{"en":/>Wildslash/g,"cn":">野性狂爪(Wildslash)"},
{"en":/>Hand of Thought and Motion/g,"cn":">思动之手(Hand of Thought and Motion)"},
{"en":/>Al Dhih/g,"cn":">鬣犬之牙(Al Dhih)"},
{"en":/>Mortem Morsu/g,"cn":">噬魂之牙(Mortem Morsu)"},
{"en":/>Cybil's Paw/g,"cn":">希比尔的冰爪(Cybil's Paw)"},
{"en":/>Ornament of the East/g,"cn":">东之饰(Ornament of the East)"},
{"en":/>Advancing Fortress/g,"cn":">超越壁垒(Advancing Fortress)"},
{"en":/>Bloodseeker/g,"cn":">嗜血之爪(Bloodseeker)"},
{"en":/>Essentia Sanguis/g,"cn":">精华收割器(Essentia Sanguis)"},
{"en":/>Allure/g,"cn":">魅惑(Allure)"},
{"en":/>Izaro's Dilemma/g,"cn":">伊泽洛之谜(Izaro's Dilemma)"},
{"en":/>Touch of Anguish/g,"cn":">极度苦痛(Touch of Anguish)"},
{"en":/>Hand of Wisdom and Action/g,"cn":">智行之手(Hand of Wisdom and Action)"},
{"en":/>Rive/g,"cn":">裂隙(Rive)"},
{"en":/>The Scourge/g,"cn":">灾害(The Scourge)"},
{"en":/>Rust of Winter/g,"cn":">霜刃(Rust of Winter)"},
{"en":/>Boreal Shepherd/g,"cn":">牧者之音(Boreal Shepherd)"},
{"en":/>The Screaming Eagle/g,"cn":">鹰啸(The Screaming Eagle)"},
{"en":/>The Gryphon/g,"cn":">狮鹫(The Gryphon)"},
{"en":/>Dreadarc/g,"cn":">恐惧之镰(Dreadarc)"},
{"en":/>Relentless Fury/g,"cn":">无尽愤怒(Relentless Fury)"},
{"en":/>Moonbender's Wing/g,"cn":">月岚(Moonbender's Wing)"},
{"en":/>Soul Taker/g,"cn":">开膛斧(Soul Taker)"},
{"en":/>Jack, the Axe/g,"cn":">刽子手．杰克(Jack, the Axe)"},
{"en":/>Rigwald's Savagery/g,"cn":">野性瑞佛(Rigwald's Savagery)"},
{"en":/>Redbeak/g,"cn":">赤红短刃(Redbeak)"},
{"en":/>Blood of Summer/g,"cn":">炎夏之血(Blood of Summer)"},
{"en":/>Fairgraves' Bearing/g,"cn":">费尔之仪(Fairgraves' Bearing)"},
{"en":/>The Princess/g,"cn":">女爵(The Princess)"},
{"en":/>The Tempestuous Steel/g,"cn":">暴风之钢(The Tempestuous Steel)"},
{"en":/>The Goddess Scorned/g,"cn":">女神的怒炎(The Goddess Scorned)"},
{"en":/>Lakishu's Blade/g,"cn":">拉奇许之刃(Lakishu's Blade)"},
{"en":/>Ephemeral Edge/g,"cn":">影殒(Ephemeral Edge)"},
{"en":/>Severed in Sleep/g,"cn":">离异梦寐(Severed in Sleep)"},
{"en":/>United in Dream/g,"cn":">合流梦寐(United in Dream)"},
{"en":/>Innsbury Edge/g,"cn":">茵斯布雷之刃(Innsbury Edge)"},
{"en":/>Prismatic Eclipse/g,"cn":">虹耀之月(Prismatic Eclipse)"},
{"en":/>Ichimonji/g,"cn":">一文字(Ichimonji)"},
{"en":/>Scaeva/g,"cn":">食蚜(Scaeva)"},
{"en":/>Hyaon's Fury/g,"cn":">海昂的狂怒(Hyaon's Fury)"},
{"en":/>Rebuke of the Vaal/g,"cn":">瓦尔战刃(Rebuke of the Vaal)"},
{"en":/>Varunastra/g,"cn":">黑鲨(Varunastra)"},
{"en":/>Dreamfeather/g,"cn":">幻梦飞羽(Dreamfeather)"},
{"en":/>The Goddess Unleashed/g,"cn":">女神的束缚(The Goddess Unleashed)"},
{"en":/>Rigwald's Command/g,"cn":">瑞佛统帅(Rigwald's Command)"},
{"en":/>Razor of the Seventh Sun/g,"cn":">七日锋(Razor of the Seventh Sun)"},
{"en":/>The Goddess Bound/g,"cn":">女神的灵缚(The Goddess Bound)"},
{"en":/>Aurumvorax/g,"cn":">灵护(Aurumvorax)"},
{"en":/>Fidelitas' Spike/g,"cn":">费德利塔斯之锋(Fidelitas' Spike)"},
{"en":/>Ewar's Mirage/g,"cn":">伊沃幻像(Ewar's Mirage)"},
{"en":/>Chitus' Needle/g,"cn":">切特斯之针(Chitus' Needle)"},
{"en":/>Daresso's Passion/g,"cn":">德瑞索的热情(Daresso's Passion)"},
{"en":/>Cospri's Malice/g,"cn":">卡斯普里的怨恨(Cospri's Malice)"},
{"en":/>Ashes of the Sun/g,"cn":">烬杵(Ashes of the Sun)"},
{"en":/>Bartek's Finger/g,"cn":">巴特克的魔指(Bartek's Finger)"},
{"en":/>Gorebreaker/g,"cn":">血裂(Gorebreaker)"},
{"en":/>Brightbeak/g,"cn":">光耀之锤(Brightbeak)"},
{"en":/>Lavianga's Wisdom/g,"cn":">拉维安加的智慧(Lavianga's Wisdom)"},
{"en":/>Flesh-Eater/g,"cn":">血肉之嗜(Flesh-Eater)"},
{"en":/>Clayshaper/g,"cn":">塑泥者(Clayshaper)"},
{"en":/>Frostbreath/g,"cn":">霜息(Frostbreath)"},
{"en":/>Mjölner/g,"cn":">沉默之雷(Mjölner)"},
{"en":/>Cameria's Maul/g,"cn":">卡美利亚之锤(Cameria's Maul)"},
{"en":/>Callinellus Malleus/g,"cn":">坚定之刃(Callinellus Malleus)"},
{"en":/>Disjunction/g,"cn":">分裂析取(Disjunction)"},
{"en":/>Axiom Perpetuum/g,"cn":">历史公理(Axiom Perpetuum)"},
{"en":/>Spine of the First Claimant/g,"cn":">先驱之脊(Spine of the First Claimant)"},
{"en":/>Brutus' Lead Sprinkler/g,"cn":">布鲁特斯的刑具(Brutus' Lead Sprinkler)"},
{"en":/>The Dark Seer/g,"cn":">黯黑贤者(The Dark Seer)"},
{"en":/>Bitterdream/g,"cn":">苦梦(Bitterdream)"},
{"en":/>Nycta's Lantern/g,"cn":">奈可妲之灯(Nycta's Lantern)"},
{"en":/>The Supreme Truth/g,"cn":">无上箴言(The Supreme Truth)"},
{"en":/>Death's Hand/g,"cn":">死神之手(Death's Hand)"},
{"en":/>Singularity/g,"cn":">奇异(Singularity)"},
{"en":/>Doon Cuebiyari/g,"cn":">黑钢(Doon Cuebiyari)"},
{"en":/>Doryani's Catalyst/g,"cn":">多里亚尼的幻化之杖(Doryani's Catalyst)"},
{"en":/>Breath of the Council/g,"cn":">议会之息(Breath of the Council)"},
{"en":/>Mon'tregul's Grasp/g,"cn":">凋灵魔爪(Mon'tregul's Grasp)"},
{"en":/>Silverbranch/g,"cn":">幻银之弦(Silverbranch)"},
{"en":/>Relic of the Cycle/g,"cn":">轮回之记(Relic of the Cycle)"},
{"en":/>Silverbough/g,"cn":">银枝(Silverbough)"},
{"en":/>Quill Rain/g,"cn":">骤雨之弦(Quill Rain)"},
{"en":/>Storm Cloud/g,"cn":">暴雨之弦(Storm Cloud)"},
{"en":/>The Tempest/g,"cn":">暴风雨(The Tempest)"},
{"en":/>Roth's Reach/g,"cn":">萝丝之触(Roth's Reach)"},
{"en":/>Xoph's Inception/g,"cn":">索伏的始源(Xoph's Inception)"},
{"en":/>Doomfletch/g,"cn":">灭世(Doomfletch)"},
{"en":/>Doomfletch's Prism/g,"cn":">灭世之狱(Doomfletch's Prism)"},
{"en":/>Death's Harp/g,"cn":">冥使之琴(Death's Harp)"},
{"en":/>Iron Commander/g,"cn":">钢铁指挥(Iron Commander)"},
{"en":/>Death's Opus/g,"cn":">死亡之作(Death's Opus)"},
{"en":/>Infractem/g,"cn":">穿云(Infractem)"},
{"en":/>Xoph's Nurture/g,"cn":">索伏的爱抚(Xoph's Nurture)"},
{"en":/>Null's Inclination/g,"cn":">虚无之倾(Null's Inclination)"},
{"en":/>Chin Sol/g,"cn":">乱矢之弦(Chin Sol)"},
{"en":/>Voltaxic Rift/g,"cn":">魔暴之痕(Voltaxic Rift)"},
{"en":/>Reach of The Council/g,"cn":">议会之触(Reach of The Council)"},
{"en":/>Lioneye's Glare/g,"cn":">狮眼的战弓(Lioneye's Glare)"},
{"en":/>Windripper/g,"cn":">裂风(Windripper)"},
{"en":/>Nuro's Harp/g,"cn":">努罗的竖琴(Nuro's Harp)"},
{"en":/>Slivertongue/g,"cn":">裂舌(Slivertongue)"},
{"en":/>Darkscorn/g,"cn":">夜吟(Darkscorn)"},
{"en":/>Fencoil/g,"cn":">绿藤(Fencoil)"},
{"en":/>The Blood Thorn/g,"cn":">血棘(The Blood Thorn)"},
{"en":/>Vestige of Divinity/g,"cn":">庄重之杖(Vestige of Divinity)"},
{"en":/>Pillar of the Caged God/g,"cn":">囚神杵(Pillar of the Caged God)"},
{"en":/>Realmshaper/g,"cn":">创域(Realmshaper)"},
{"en":/>Realm Ender/g,"cn":">魂界终结(Realm Ender)"},
{"en":/>Dying Breath/g,"cn":">亡者之息(Dying Breath)"},
{"en":/>Xirgil's Crank/g,"cn":">舍吉的手柄(Xirgil's Crank)"},
{"en":/>The Stormheart/g,"cn":">风暴之眼(The Stormheart)"},
{"en":/>The Whispering Ice/g,"cn":">冰点低语(The Whispering Ice)"},
{"en":/>Tremor Rod/g,"cn":">颤抖之杖(Tremor Rod)"},
{"en":/>Sire of Shards/g,"cn":">破碎传承者(Sire of Shards)"},
{"en":/>Martyr of Innocence/g,"cn":">烈士之净(Martyr of Innocence)"},
{"en":/>Femurs of the Saints/g,"cn":">圣徒胫骨(Femurs of the Saints)"},
{"en":/>The Searing Touch/g,"cn":">炽炎之使(The Searing Touch)"},
{"en":/>Taryn's Shiver/g,"cn":">塔林的颤栗之语(Taryn's Shiver)"},
{"en":/>Duskdawn/g,"cn":">宵晓(Duskdawn)"},
{"en":/>Agnerod East/g,"cn":">东方雷霆圣杖(Agnerod East)"},
{"en":/>Agnerod North/g,"cn":">北方雷霆圣杖(Agnerod North)"},
{"en":/>Agnerod South/g,"cn":">南方雷霆圣杖(Agnerod South)"},
{"en":/>Agnerod West/g,"cn":">西方雷霆圣杖(Agnerod West)"},
{"en":/>Pledge of Hands/g,"cn":">誓约(Pledge of Hands)"},
{"en":/>Hegemony's Era/g,"cn":">霸权时代(Hegemony's Era)"},
{"en":/>Limbsplit/g,"cn":">断罪(Limbsplit)"},
{"en":/>The Cauteriser/g,"cn":">烧灼器(The Cauteriser)"},
{"en":/>Wideswing/g,"cn":">阔斩(Wideswing)"},
{"en":/>Reaper's Pursuit/g,"cn":">死神的取魂器(Reaper's Pursuit)"},
{"en":/>The Harvest/g,"cn":">收割者(The Harvest)"},
{"en":/>The Blood Reaper/g,"cn":">竭血之镰(The Blood Reaper)"},
{"en":/>Uul-Netol's Kiss/g,"cn":">乌尔尼多之吻(Uul-Netol's Kiss)"},
{"en":/>Ngamahu's Flame/g,"cn":">里特拿马乎(Ngamahu's Flame)"},
{"en":/>Kaom's Primacy/g,"cn":">冈姆的霸业(Kaom's Primacy)"},
{"en":/>Wings of Entropy/g,"cn":">乱世之翼(Wings of Entropy)"},
{"en":/>Atziri's Disfavour/g,"cn":">阿兹里的刑刃(Atziri's Disfavour)"},
{"en":/>Hezmana's Bloodlust/g,"cn":">嗜血黑兹玛娜(Hezmana's Bloodlust)"},
{"en":/>Uul-Netol's Embrace/g,"cn":">乌尔尼多的拥抱(Uul-Netol's Embrace)"},
{"en":/>Kingmaker/g,"cn":">王者之刃(Kingmaker)"},
{"en":/>Kitava's Feast/g,"cn":">奇塔弗之盛宴(Kitava's Feast)"},
{"en":/>Thunder of the Dawn/g,"cn":">曙雷(Thunder of the Dawn)"},
{"en":/>Shiversting/g,"cn":">寒光剑(Shiversting)"},
{"en":/>Edge of Madness/g,"cn":">疯狂边界(Edge of Madness)"},
{"en":/>Queen's Decree/g,"cn":">威严之刃(Queen's Decree)"},
{"en":/>Queen's Escape/g,"cn":">逃亡女王(Queen's Escape)"},
{"en":/>Rigwald's Charge/g,"cn":">瑞佛的奋战长剑(Rigwald's Charge)"},
{"en":/>Terminus Est/g,"cn":">行刑之刃(Terminus Est)"},
{"en":/>The Dancing Dervish/g,"cn":">狂舞德尔维希(The Dancing Dervish)"},
{"en":/>Hiltless/g,"cn":">长卷(Hiltless)"},
{"en":/>Kondo's Pride/g,"cn":">刚多的虚荣(Kondo's Pride)"},
{"en":/>Doomsower/g,"cn":">终末之始(Doomsower)"},
{"en":/>Oro's Sacrifice/g,"cn":">欧罗的贡品(Oro's Sacrifice)"},
{"en":/>Starforge/g,"cn":">核星(Starforge)"},
{"en":/>Hrimnor's Hymn/g,"cn":">雷姆诺的夺命乐具(Hrimnor's Hymn)"},
{"en":/>Hrimnor's Dirge/g,"cn":">雷姆诺的挽歌(Hrimnor's Dirge)"},
{"en":/>Quecholli/g,"cn":">重击之锤(Quecholli)"},
{"en":/>Geofri's Baptism/g,"cn":">吉尔菲的净罪之锤(Geofri's Baptism)"},
{"en":/>Chober Chaber/g,"cn":">忠诚之锤(Chober Chaber)"},
{"en":/>Trypanon/g,"cn":">裂颅(Trypanon)"},
{"en":/>Jorrhast's Blacksteel/g,"cn":">乔赫黑钢(Jorrhast's Blacksteel)"},
{"en":/>Voidhome/g,"cn":">逝空之锤(Voidhome)"},
{"en":/>Marohi Erqi/g,"cn":">尔奇的巨灵之锤(Marohi Erqi)"},
{"en":/>Brain Rattler/g,"cn":">脑乱者(Brain Rattler)"},
{"en":/>Tidebreaker/g,"cn":">破浪者(Tidebreaker)"},
{"en":/>Kongor's Undying Rage/g,"cn":">康戈的战炎(Kongor's Undying Rage)"},
{"en":/>Song of the Sirens/g,"cn":">海妖魅曲(Song of the Sirens)"},
{"en":/>Reefbane/g,"cn":">灾祸之礁(Reefbane)"},
{"en":/>Dyadus/g,"cn":">龙凤吟(Dyadus)"},
{"en":/>Demigod's Eye/g,"cn":">升华之眼(Demigod's Eye)"},
{"en":/>Blackheart/g,"cn":">幽暗之语(Blackheart)"},
{"en":/>Le Heup of All/g,"cn":">英灵宝环(Le Heup of All)"},
{"en":/>Band of the Victor/g,"cn":">胜利之环(Band of the Victor)"},
{"en":/>Voidheart/g,"cn":">虚空心灵(Voidheart)"},
{"en":/>The Warden's Brand/g,"cn":">狱使之印(The Warden's Brand)"},
{"en":/>Kaom's Sign/g,"cn":">冈姆的远见(Kaom's Sign)"},
{"en":/>Bloodboil/g,"cn":">沸血(Bloodboil)"},
{"en":/>Sibyl's Lament/g,"cn":">希比尔之叹(Sibyl's Lament)"},
{"en":/>Kaom's Way/g,"cn":">冈姆之路(Kaom's Way)"},
{"en":/>Doedre's Damning/g,"cn":">德瑞的魔具(Doedre's Damning)"},
{"en":/>Perandus Signet/g,"cn":">普兰德斯之记(Perandus Signet)"},
{"en":/>Praxis/g,"cn":">普拉克斯(Praxis)"},
{"en":/>Andvarius/g,"cn":">贪欲之记(Andvarius)"},
{"en":/>Ventor's Gamble/g,"cn":">赌神芬多(Ventor's Gamble)"},
{"en":/>Kikazaru/g,"cn":">基加萨鲁(Kikazaru)"},
{"en":/>Valako's Sign/g,"cn":">瓦拉库之印(Valako's Sign)"},
{"en":/>Dream Fragments/g,"cn":">梦语之痕(Dream Fragments)"},
{"en":/>Pyre/g,"cn":">燃焰(Pyre)"},
{"en":/>Tasalio's Sign/g,"cn":">塔萨里之印(Tasalio's Sign)"},
{"en":/>Snakepit/g,"cn":">蛇巢(Snakepit)"},
{"en":/>Mokou's Embrace/g,"cn":">莫考之拥(Mokou's Embrace)"},
{"en":/>Ngamahu's Sign/g,"cn":">拿玛乎之印(Ngamahu's Sign)"},
{"en":/>Emberwake/g,"cn":">余烬之痕(Emberwake)"},
{"en":/>Lori's Lantern/g,"cn":">罗里的幸运之灯(Lori's Lantern)"},
{"en":/>The Taming/g,"cn":">元素之章(The Taming)"},
{"en":/>Thief's Torment/g,"cn":">窃罪(Thief's Torment)"},
{"en":/>Shavronne's Revelation/g,"cn":">薛朗的启示之环(Shavronne's Revelation)"},
{"en":/>Timeclasp/g,"cn":">时光之握(Timeclasp)"},
{"en":/>Heartbound Loop/g,"cn":">结魂之环(Heartbound Loop)"},
{"en":/>Valyrium/g,"cn":">战日(Valyrium)"},
{"en":/>Death Rush/g,"cn":">亡者呼唤(Death Rush)"},
{"en":/>Ming's Heart/g,"cn":">明恩的慧心(Ming's Heart)"},
{"en":/>Gifts from Above/g,"cn":">神赐(Gifts from Above)"},
{"en":/>Romira's Banquet/g,"cn":">罗米拉的潜力之环(Romira's Banquet)"},
{"en":/>Berek's Grip/g,"cn":">贝雷克的冰与雷之曲(Berek's Grip)"},
{"en":/>Berek's Pass/g,"cn":">贝雷克的冰与火之歌(Berek's Pass)"},
{"en":/>Berek's Respite/g,"cn":">贝雷克的火与雷之乐(Berek's Respite)"},
{"en":/>Call of the Brotherhood/g,"cn":">意志呼唤(Call of the Brotherhood)"},
{"en":/>Rigwald's Crest/g,"cn":">瑞佛之冠(Rigwald's Crest)"},
{"en":/>Voideye/g,"cn":">虚空慧眼(Voideye)"},
{"en":/>Malachai's Artifice/g,"cn":">玛拉凯的巧技(Malachai's Artifice)"},
{"en":/>Brinerot Mark/g,"cn":">布琳洛特印记(Brinerot Mark)"},
{"en":/>Redblade Band/g,"cn":">红刃之环(Redblade Band)"},
{"en":/>Mutewind Seal/g,"cn":">哑风封印(Mutewind Seal)"},
{"en":/>The Pariah/g,"cn":">草民(The Pariah)"},
{"en":/>Essence Worm/g,"cn":">菁华蠕虫(Essence Worm)"},
{"en":/>Angler's Plait/g,"cn":">渔夫之辫(Angler's Plait)"},
{"en":/>Atziri's Foible/g,"cn":">阿兹里圣徽(Atziri's Foible)"},
{"en":/>Sidhebreath/g,"cn":">魔灵之符(Sidhebreath)"},
{"en":/>The Learning Stone/g,"cn":">学习之石(The Learning Stone)"},
{"en":/>Duskwing/g,"cn":">黄昏之翼(Duskwing)"},
{"en":/>Araku Tiki/g,"cn":">隐灵之符(Araku Tiki)"},
{"en":/>Bloodgrip/g,"cn":">鲜血支配(Bloodgrip)"},
{"en":/>Ngamahu Tiki/g,"cn":">拿玛乎蒂基(Ngamahu Tiki)"},
{"en":/>The Anvil/g,"cn":">信念之砧(The Anvil)"},
{"en":/>Blood of Corruption/g,"cn":">堕落之血(Blood of Corruption)"},
{"en":/>Xoph's Heart/g,"cn":">索伏之心(Xoph's Heart)"},
{"en":/>Xoph's Blood/g,"cn":">索伏之血(Xoph's Blood)"},
{"en":/>Karui Ward/g,"cn":">卡鲁的战徽(Karui Ward)"},
{"en":/>Rashkaldor's Patience/g,"cn":">拉什卡德的耐心(Rashkaldor's Patience)"},
{"en":/>Karui Charge/g,"cn":">卡鲁充能(Karui Charge)"},
{"en":/>The Halcyon/g,"cn":">太平(The Halcyon)"},
{"en":/>The Pandemonius/g,"cn":">群魔殿(The Pandemonius)"},
{"en":/>Marylene's Fallacy/g,"cn":">玛莉琳的护体之符(Marylene's Fallacy)"},
{"en":/>Stone of Lazhwar/g,"cn":">拉兹瓦的灵石(Stone of Lazhwar)"},
{"en":/>Tear of Purity/g,"cn":">纯净之泪(Tear of Purity)"},
{"en":/>Talisman of the Victor/g,"cn":">胜者护符(Talisman of the Victor)"},
{"en":/>The Rathorn/g,"cn":">咒荆(The Rathorn)"},
{"en":/>Voice of the Storm/g,"cn":">暴风之言(Voice of the Storm)"},
{"en":/>Choir of the Storm/g,"cn":">暴风之语(Choir of the Storm)"},
{"en":/>Demigod's Presence/g,"cn":">升华之印(Demigod's Presence)"},
{"en":/>The Ignomon/g,"cn":">烈阳徽记(The Ignomon)"},
{"en":/>Winterheart/g,"cn":">冬之心(Winterheart)"},
{"en":/>Frost Unbroken/g,"cn":">不灭冰晶(Frost Unbroken)"},
{"en":/>The Ascetic/g,"cn":">苦行(The Ascetic)"},
{"en":/>Bisco's Collar/g,"cn":">毕斯寇的项圈(Bisco's Collar)"},
{"en":/>Astramentis/g,"cn":">均衡之符(Astramentis)"},
{"en":/>Carnage Heart/g,"cn":">屠戮之心(Carnage Heart)"},
{"en":/>Eye of Chayula/g,"cn":">寻宝者的心眼(Eye of Chayula)"},
{"en":/>Hinekora's Sight/g,"cn":">悉妮蔻拉之眼(Hinekora's Sight)"},
{"en":/>Presence of Chayula/g,"cn":">夏乌拉之印(Presence of Chayula)"},
{"en":/>Victario's Acuity/g,"cn":">维多里奥的捷思(Victario's Acuity)"},
{"en":/>Ungil's Harmony/g,"cn":">恩吉尔的和谐(Ungil's Harmony)"},
{"en":/>Warped Timepiece/g,"cn":">时空扭曲(Warped Timepiece)"},
{"en":/>Voll's Devotion/g,"cn":">福尔的忠诚之符(Voll's Devotion)"},
{"en":/>Shaper's Seed/g,"cn":">塑型者之籽(Shaper's Seed)"},
{"en":/>The Aylardex/g,"cn":">艾拉黛丝(The Aylardex)"},
{"en":/>Extractor Mentis/g,"cn":">心灵抽取(Extractor Mentis)"},
{"en":/>Daresso's Salute/g,"cn":">德瑞索的战礼(Daresso's Salute)"},
{"en":/>Eye of Innocence/g,"cn":">无罪之眼(Eye of Innocence)"},
{"en":/>Star of Wraeclast/g,"cn":">瓦尔克拉斯之星(Star of Wraeclast)"},
{"en":/>Night's Hold/g,"cn":">夜守(Night's Hold)"},
{"en":/>Rigwald's Curse/g,"cn":">瑞佛诅咒(Rigwald's Curse)"},
{"en":/>Blightwell/g,"cn":">枯井(Blightwell)"},
{"en":/>Natural Hierarchy/g,"cn":">自然组织(Natural Hierarchy)"},
{"en":/>Eyes of the Greatwolf/g,"cn":">巨狼之眼(Eyes of the Greatwolf)"},
{"en":/>Prismweave/g,"cn":">幻彩菱织(Prismweave)"},
{"en":/>Chains of Time/g,"cn":">时空之链(Chains of Time)"},
{"en":/>Feastbind/g,"cn":">盛宴之结(Feastbind)"},
{"en":/>Faminebind/g,"cn":">饥荒之结(Faminebind)"},
{"en":/>The Retch/g,"cn":">呕吐(The Retch)"},
{"en":/>Bated Breath/g,"cn":">凝息(Bated Breath)"},
{"en":/>Maligaro's Restraint/g,"cn":">马雷葛萝的染血之环(Maligaro's Restraint)"},
{"en":/>Ascent From Flesh/g,"cn":">血躯升华(Ascent From Flesh)"},
{"en":/>Headhunter/g,"cn":">猎首(Headhunter)"},
{"en":/>Immortal Flesh/g,"cn":">永生(Immortal Flesh)"},
{"en":/>Wurm's Molt/g,"cn":">龙蜕之带(Wurm's Molt)"},
{"en":/>Umbilicus Immortalis/g,"cn":">不朽系命(Umbilicus Immortalis)"},
{"en":/>Doryani's Invitation/g,"cn":">多里亚尼之约(Doryani's Invitation)"},
{"en":/>Meginord's Girdle/g,"cn":">梅吉诺德的力量泉源(Meginord's Girdle)"},
{"en":/>Belt of the Deceiver/g,"cn":">狡徒束腰(Belt of the Deceiver)"},
{"en":/>Dyadian Dawn/g,"cn":">戴亚迪安的晨曦(Dyadian Dawn)"},
{"en":/>Bisco's Leash/g,"cn":">毕斯寇系带(Bisco's Leash)"},
{"en":/>Perandus Blazon/g,"cn":">普兰德斯之印(Perandus Blazon)"},
{"en":/>Sunblast/g,"cn":">日炎(Sunblast)"},
{"en":/>Soulthirst/g,"cn":">嗜魂(Soulthirst)"},
{"en":/>The Magnate/g,"cn":">坚毅之环(The Magnate)"},
{"en":/>Ryslatha's Coil/g,"cn":">瑞斯拉萨之缠(Ryslatha's Coil)"},
{"en":/>Perseverance/g,"cn":">恒毅意志(Perseverance)"},
{"en":/>Auxium/g,"cn":">奥术之符(Auxium)"},
{"en":/>Demigod's Bounty/g,"cn":">升华珍宝(Demigod's Bounty)"},
{"en":/>Blood of the Karui/g,"cn":">卡鲁之血(Blood of the Karui)"},
{"en":/>Doedre's Elixir/g,"cn":">德瑞的妙药(Doedre's Elixir)"},
{"en":/>Zerphi's Last Breath/g,"cn":">泽佛伊的终息(Zerphi's Last Breath)"},
{"en":/>Lavianga's Spirit/g,"cn":">拉维安加之泉(Lavianga's Spirit)"},
{"en":/>Divination Distillate/g,"cn":">宝视精华(Divination Distillate)"},
{"en":/>The Writhing Jar/g,"cn":">扭曲之罐(The Writhing Jar)"},
{"en":/>Coruscating Elixir/g,"cn":">闪耀精华(Coruscating Elixir)"},
{"en":/>Dying Sun/g,"cn":">灭日(Dying Sun)"},
{"en":/>Taste of Hate/g,"cn":">恨意(Taste of Hate)"},
{"en":/>Vessel of Vinktar/g,"cn":">维克塔血器(Vessel of Vinktar)"},
{"en":/>Rumi's Concoction/g,"cn":">鲁米的灵药(Rumi's Concoction)"},
{"en":/>Lion's Roar/g,"cn":">狮吼精华(Lion's Roar)"},
{"en":/>Rotgut/g,"cn":">伤胃酒(Rotgut)"},
{"en":/>Atziri's Promise/g,"cn":">阿兹里的诺言(Atziri's Promise)"},
{"en":/>Forbidden Taste/g,"cn":">禁果(Forbidden Taste)"},
{"en":/>Witchfire Brew/g,"cn":">巫火秘酿(Witchfire Brew)"},
{"en":/>Sin's Rebirth/g,"cn":">再生的罪恶(Sin's Rebirth)"},
{"en":/>The Sorrow of the Divine/g,"cn":">神圣哀悼(The Sorrow of the Divine)"},
{"en":/>The Overflowing Chalice/g,"cn":">满溢圣杯(The Overflowing Chalice)"},
{"en":/>Kiara's Determination/g,"cn":">奇亚拉的决心(Kiara's Determination)"},
{"en":/>The Wise Oak/g,"cn":">哲栎(The Wise Oak)"},
{"en":/>Blackgleam/g,"cn":">黑炎之芒(Blackgleam)"},
{"en":/>The Signal Fire/g,"cn":">狼烟(The Signal Fire)"},
{"en":/>Broadstroke/g,"cn":">疾袭之锋(Broadstroke)"},
{"en":/>Craghead/g,"cn":">岩头(Craghead)"},
{"en":/>Slivers of Providence/g,"cn":">白银恩典(Slivers of Providence)"},
{"en":/>Cragfall/g,"cn":">落石(Cragfall)"},
{"en":/>Asphyxia's Wrath/g,"cn":">冰灵之吼(Asphyxia's Wrath)"},
{"en":/>Rigwald's Quills/g,"cn":">瑞佛之羽(Rigwald's Quills)"},
{"en":/>Skirmish/g,"cn":">小会战(Skirmish)"},
{"en":/>Hyrri's Bite/g,"cn":">西里的嗜血之矢(Hyrri's Bite)"},
{"en":/>Maloney's Nightfall/g,"cn":">马洛尼的暮光(Maloney's Nightfall)"},
{"en":/>Rearguard/g,"cn":">寒锋之卫(Rearguard)"},
{"en":/>Drillneck/g,"cn":">穿心(Drillneck)"},
{"en":/>Soul Strike/g,"cn":">灵魂打击(Soul Strike)"},
{"en":/>Saemus' Gift/g,"cn":">谢默斯的赠礼(Saemus' Gift)"}
];



var baseItemJson=[
{"en":/Nailed Fist/g,"cn":"拳钉"},
{"en":/Sharktooth Claw/g,"cn":"鲨颚爪"},
{"en":/Awl/g,"cn":"凿钉"},
{"en":/Cat's Paw/g,"cn":"猫爪刃"},
{"en":/Blinder/g,"cn":"袭眼钩"},
{"en":/Timeworn Claw/g,"cn":"远古战爪"},
{"en":/Sparkling Claw/g,"cn":"眩目爪刃"},
{"en":/Fright Claw/g,"cn":"恐惧之爪"},
{"en":/Double Claw/g,"cn":"双刃爪"},
{"en":/Thresher Claw/g,"cn":"撕裂尖爪"},
{"en":/Gouger/g,"cn":"穿体凿"},
{"en":/Tiger's Paw/g,"cn":"虎爪刃"},
{"en":/Gut Ripper/g,"cn":"裂脏钩"},
{"en":/Prehistoric Claw/g,"cn":"史前战爪"},
{"en":/Noble Claw/g,"cn":"贵族战爪"},
{"en":/Eagle Claw/g,"cn":"鹰爪刃"},
{"en":/Twin Claw/g,"cn":"重刃爪"},
{"en":/Great White Claw/g,"cn":"白灵之爪"},
{"en":/Throat Stabber/g,"cn":"刺喉刃"},
{"en":/Hellion's Paw/g,"cn":"魔爪刃"},
{"en":/Eye Gouger/g,"cn":"刺眼钩"},
{"en":/Vaal Claw/g,"cn":"瓦尔战爪"},
{"en":/Imperial Claw/g,"cn":"帝国战爪"},
{"en":/Terror Claw/g,"cn":"恐惧之牙"},
{"en":/Gemini Claw/g,"cn":"双子战爪"},
{"en":/Glass Shank/g,"cn":"玻璃利片"},
{"en":/Skinning Knife/g,"cn":"剥皮刀"},
{"en":/Carving Knife/g,"cn":"刻骨刀"},
{"en":/Stiletto/g,"cn":"锐利刺匕"},
{"en":/Boot Knife/g,"cn":"窃者短刃"},
{"en":/Copper Kris/g,"cn":"铜锻波刃"},
{"en":/Skean/g,"cn":"双刃匕"},
{"en":/Imp Dagger/g,"cn":"魔性之刃"},
{"en":/Prong Dagger/g,"cn":"尖耙短匕"},
{"en":/Flaying Knife/g,"cn":"残体利刃"},
{"en":/Butcher Knife/g,"cn":"屠兽利刃"},
{"en":/Poignard/g,"cn":"夺命刺"},
{"en":/Boot Blade/g,"cn":"窃者短匕"},
{"en":/Golden Kris/g,"cn":"金光波刃"},
{"en":/Royal Skean/g,"cn":"皇家短匕"},
{"en":/Fiend Dagger/g,"cn":"兽血短匕"},
{"en":/Trisula/g,"cn":"三叉短匕"},
{"en":/Gutting Knife/g,"cn":"重伤短刀"},
{"en":/Slaughter Knife/g,"cn":"猎者之刃"},
{"en":/Ambusher/g,"cn":"伏击刺刃"},
{"en":/Ezomyte Dagger/g,"cn":"艾兹麦之匕"},
{"en":/Platinum Kris/g,"cn":"白金波刃"},
{"en":/Imperial Skean/g,"cn":"帝国短匕"},
{"en":/Demon Dagger/g,"cn":"魔灵短匕"},
{"en":/Sai/g,"cn":"战叉"},
{"en":/Driftwood Wand/g,"cn":"朽木法杖"},
{"en":/Goat's Horn/g,"cn":"羊角法杖"},
{"en":/Carved Wand/g,"cn":"粗纹法杖"},
{"en":/Quartz Wand/g,"cn":"石英法杖"},
{"en":/Spiraled Wand/g,"cn":"螺纹法杖"},
{"en":/Sage Wand/g,"cn":"贤者法杖"},
{"en":/Pagan Wand/g,"cn":"异教法杖"},
{"en":/Faun's Horn/g,"cn":"兽角法杖"},
{"en":/Engraved Wand/g,"cn":"符文法杖"},
{"en":/Crystal Wand/g,"cn":"水晶法杖"},
{"en":/Serpent Wand/g,"cn":"蛇眼法杖"},
{"en":/Omen Wand/g,"cn":"灵兆法杖"},
{"en":/Heathen Wand/g,"cn":"异徒法杖"},
{"en":/Demon's Horn/g,"cn":"魔角法杖"},
{"en":/Imbued Wand/g,"cn":"魔性法杖"},
{"en":/Opal Wand/g,"cn":"灵石法杖"},
{"en":/Tornado Wand/g,"cn":"狂风法杖"},
{"en":/Prophecy Wand/g,"cn":"箴言法杖"},
{"en":/Profane Wand/g,"cn":"亵渎法杖"},
{"en":/Rusted Sword/g,"cn":"锈剑"},
{"en":/Copper Sword/g,"cn":"青铜短剑"},
{"en":/Sabre/g,"cn":"旧军刀"},
{"en":/Broad Sword/g,"cn":"阔剑"},
{"en":/War Sword/g,"cn":"征战之剑"},
{"en":/Ancient Sword/g,"cn":"远古之剑"},
{"en":/Elegant Sword/g,"cn":"贵族之剑"},
{"en":/Dusk Blade/g,"cn":"暮色之刃"},
{"en":/Hook Sword/g,"cn":"钩爪剑"},
{"en":/Variscite Blade/g,"cn":"碧铜短剑"},
{"en":/Cutlass/g,"cn":"军用长刃"},
{"en":/Baselard/g,"cn":"冷光长剑"},
{"en":/Battle Sword/g,"cn":"士兵长剑"},
{"en":/Elder Sword/g,"cn":"智者长剑"},
{"en":/Graceful Sword/g,"cn":"权贵之剑"},
{"en":/Twilight Blade/g,"cn":"暮光长剑"},
{"en":/Grappler/g,"cn":"捕捉者"},
{"en":/Gemstone Sword/g,"cn":"宝石之剑"},
{"en":/Corsair Sword/g,"cn":"海贼长刀"},
{"en":/Gladius/g,"cn":"斗士长剑"},
{"en":/Legion Sword/g,"cn":"军团长剑"},
{"en":/Vaal Blade/g,"cn":"瓦尔军刃"},
{"en":/Eternal Sword/g,"cn":"永恒之剑"},
{"en":/Midnight Blade/g,"cn":"夜语长剑"},
{"en":/Tiger Hook/g,"cn":"虎钩"},
{"en":/Rusted Spike/g,"cn":"锈刺剑"},
{"en":/Whalebone Rapier/g,"cn":"鲸骨细刃"},
{"en":/Battered Foil/g,"cn":"钝刃细剑"},
{"en":/Basket Rapier/g,"cn":"练武者细剑"},
{"en":/Jagged Foil/g,"cn":"锯状薄刃"},
{"en":/Antique Rapier/g,"cn":"古代细剑"},
{"en":/Elegant Foil/g,"cn":"贵族细剑"},
{"en":/Thorn Rapier/g,"cn":"棘刺细剑"},
{"en":/Smallsword/g,"cn":"小剑"},
{"en":/Wyrmbone Rapier/g,"cn":"龙骨细剑"},
{"en":/Burnished Foil/g,"cn":"冷芒刺剑"},
{"en":/Estoc/g,"cn":"穿甲刺剑"},
{"en":/Serrated Foil/g,"cn":"锯齿细剑"},
{"en":/Primeval Rapier/g,"cn":"古典刺剑"},
{"en":/Fancy Foil/g,"cn":"华丽细剑"},
{"en":/Apex Rapier/g,"cn":"锐锋细剑"},
{"en":/Courtesan Sword/g,"cn":"花魁之剑"},
{"en":/Dragonbone Rapier/g,"cn":"龙骨细剑"},
{"en":/Tempered Foil/g,"cn":"强化细剑"},
{"en":/Pecoraro/g,"cn":"寒光刺剑"},
{"en":/Spiraled Foil/g,"cn":"螺纹细剑"},
{"en":/Vaal Rapier/g,"cn":"瓦尔细剑"},
{"en":/Jewelled Foil/g,"cn":"宝饰细剑"},
{"en":/Harpy Rapier/g,"cn":"魔喙细剑"},
{"en":/Dragoon Sword/g,"cn":"骑兵军刀"},
{"en":/Rusted Hatchet/g,"cn":"锈斧"},
{"en":/Jade Hatchet/g,"cn":"碎玉斧"},
{"en":/Boarding Axe/g,"cn":"万用手斧"},
{"en":/Cleaver/g,"cn":"切割者"},
{"en":/Broad Axe/g,"cn":"阔斧"},
{"en":/Arming Axe/g,"cn":"长柄斧"},
{"en":/Decorative Axe/g,"cn":"富贵之斧"},
{"en":/Spectral Axe/g,"cn":"幽魂之斧"},
{"en":/Etched Hatchet/g,"cn":"蚀刻战斧"},
{"en":/Jasper Axe/g,"cn":"灵玉斧"},
{"en":/Tomahawk/g,"cn":"征战之斧"},
{"en":/Wrist Chopper/g,"cn":"断腕之刃"},
{"en":/War Axe/g,"cn":"行军斧"},
{"en":/Chest Splitter/g,"cn":"开膛利刃"},
{"en":/Ceremonial Axe/g,"cn":"血仪之斧"},
{"en":/Wraith Axe/g,"cn":"凶灵之斧"},
{"en":/Engraved Hatchet/g,"cn":"雕文战斧"},
{"en":/Karui Axe/g,"cn":"卡鲁古斧"},
{"en":/Siege Axe/g,"cn":"破城斧"},
{"en":/Reaver Axe/g,"cn":"残暴之斧"},
{"en":/Butcher Axe/g,"cn":"屠戮之斧"},
{"en":/Vaal Hatchet/g,"cn":"瓦尔战斧"},
{"en":/Royal Axe/g,"cn":"皇家之斧"},
{"en":/Infernal Axe/g,"cn":"狱火之刃"},
{"en":/Runic Hatchet/g,"cn":"密文之斧"},
{"en":/Driftwood Club/g,"cn":"朽木之棒"},
{"en":/Tribal Club/g,"cn":"祭仪之杵"},
{"en":/Spiked Club/g,"cn":"钝钉木棒"},
{"en":/Stone Hammer/g,"cn":"石锤"},
{"en":/War Hammer/g,"cn":"战锤"},
{"en":/Bladed Mace/g,"cn":"多刃锤"},
{"en":/Ceremonial Mace/g,"cn":"祭礼之锤"},
{"en":/Dream Mace/g,"cn":"梦境之锤"},
{"en":/Wyrm Mace/g,"cn":"古龙之锤"},
{"en":/Petrified Club/g,"cn":"坚石木棒"},
{"en":/Barbed Club/g,"cn":"锐刺木棒"},
{"en":/Rock Breaker/g,"cn":"破岩锤"},
{"en":/Battle Hammer/g,"cn":"强化战锤"},
{"en":/Flanged Mace/g,"cn":"护体之锤"},
{"en":/Ornate Mace/g,"cn":"华丽之锤"},
{"en":/Phantom Mace/g,"cn":"幻象之锤"},
{"en":/Dragon Mace/g,"cn":"龙之锤"},
{"en":/Ancestral Club/g,"cn":"祖灵之杵"},
{"en":/Tenderizer/g,"cn":"裂肉之锤"},
{"en":/Gavel/g,"cn":"坚锤"},
{"en":/Legion Hammer/g,"cn":"军团之锤"},
{"en":/Pernarch/g,"cn":"锋刃重锤"},
{"en":/Auric Mace/g,"cn":"圣约之锤"},
{"en":/Nightmare Mace/g,"cn":"梦魇之锤"},
{"en":/Behemoth Mace/g,"cn":"巴哈姆特"},
{"en":/Driftwood Sceptre/g,"cn":"朽木权杖"},
{"en":/Darkwood Sceptre/g,"cn":"乌木权杖"},
{"en":/Bronze Sceptre/g,"cn":"铜锻权杖"},
{"en":/Quartz Sceptre/g,"cn":"石英权杖"},
{"en":/Iron Sceptre/g,"cn":"冷铁权杖"},
{"en":/Ochre Sceptre/g,"cn":"赤色权杖"},
{"en":/Ritual Sceptre/g,"cn":"祭仪权杖"},
{"en":/Shadow Sceptre/g,"cn":"影语权杖"},
{"en":/Horned Sceptre/g,"cn":"犄角权杖"},
{"en":/Grinning Fetish/g,"cn":"远古之祭"},
{"en":/Sekhem/g,"cn":"威能权杖"},
{"en":/Crystal Sceptre/g,"cn":"水晶权杖"},
{"en":/Lead Sceptre/g,"cn":"铅铸权杖"},
{"en":/Blood Sceptre/g,"cn":"血色权杖"},
{"en":/Royal Sceptre/g,"cn":"皇家权杖"},
{"en":/Abyssal Sceptre/g,"cn":"深渊权杖"},
{"en":/Stag Sceptre/g,"cn":"灵鹿权杖"},
{"en":/Karui Sceptre/g,"cn":"卡鲁权杖"},
{"en":/Tyrant's Sekhem/g,"cn":"暴君之统"},
{"en":/Opal Sceptre/g,"cn":"灵石权杖"},
{"en":/Platinum Sceptre/g,"cn":"白金权杖"},
{"en":/Vaal Sceptre/g,"cn":"瓦尔权杖"},
{"en":/Carnal Sceptre/g,"cn":"禁礼权杖"},
{"en":/Void Sceptre/g,"cn":"虚影权杖"},
{"en":/Sambar Sceptre/g,"cn":"恶魔权杖"},
{"en":/Crude Bow/g,"cn":"粗制弓"},
{"en":/Short Bow/g,"cn":"短弓"},
{"en":/Long Bow/g,"cn":"长弓"},
{"en":/Composite Bow/g,"cn":"合成弓"},
{"en":/Recurve Bow/g,"cn":"反曲弓"},
{"en":/Bone Bow/g,"cn":"骨制弓"},
{"en":/Royal Bow/g,"cn":"皇家猎弓"},
{"en":/Death Bow/g,"cn":"死亡之弓"},
{"en":/Reflex Bow/g,"cn":"反射弓"},
{"en":/Grove Bow/g,"cn":"丛林猎弓"},
{"en":/Decurve Bow/g,"cn":"直弓"},
{"en":/Compound Bow/g,"cn":"复合弓"},
{"en":/Sniper Bow/g,"cn":"狙杀弓"},
{"en":/Ivory Bow/g,"cn":"象牙弓"},
{"en":/Highborn Bow/g,"cn":"贵族之弓"},
{"en":/Decimation Bow/g,"cn":"猎魂之弓"},
{"en":/Steelwood Bow/g,"cn":"钢木之弓"},
{"en":/Thicket Bow/g,"cn":"林野猎弓"},
{"en":/Citadel Bow/g,"cn":"城塞战弓"},
{"en":/Ranger Bow/g,"cn":"漫游之弓"},
{"en":/Assassin Bow/g,"cn":"暗杀弓"},
{"en":/Spine Bow/g,"cn":"脊弓"},
{"en":/Imperial Bow/g,"cn":"帝国之弓"},
{"en":/Harbinger Bow/g,"cn":"先驱者之弓"},
{"en":/Maraketh Bow/g,"cn":"马拉克斯弓"},
{"en":/Gnarled Branch/g,"cn":"朽木之干"},
{"en":/Primitive Staff/g,"cn":"粗制长杖"},
{"en":/Long Staff/g,"cn":"长杖"},
{"en":/Iron Staff/g,"cn":"铁锻长杖"},
{"en":/Coiled Staff/g,"cn":"强化长杖"},
{"en":/Royal Staff/g,"cn":"皇家长杖"},
{"en":/Vile Staff/g,"cn":"毒牙长杖"},
{"en":/Crescent Staff/g,"cn":"新月长杖"},
{"en":/Woodful Staff/g,"cn":"坚木长杖"},
{"en":/Quarterstaff/g,"cn":"细柄长杖"},
{"en":/Military Staff/g,"cn":"军用长杖"},
{"en":/Serpentine Staff/g,"cn":"蛇纹长杖"},
{"en":/Highborn Staff/g,"cn":"贵族长杖"},
{"en":/Foul Staff/g,"cn":"恶灵长杖"},
{"en":/Moon Staff/g,"cn":"月神长杖"},
{"en":/Primordial Staff/g,"cn":"史典长杖"},
{"en":/Lathi/g,"cn":"武术长杖"},
{"en":/Ezomyte Staff/g,"cn":"艾兹麦长杖"},
{"en":/Maelstr%C3%B6m Staff/g,"cn":"风暴长杖"},
{"en":/Imperial Staff/g,"cn":"帝国长杖"},
{"en":/Judgement Staff/g,"cn":"审判长杖"},
{"en":/Eclipse Staff/g,"cn":"月蚀长杖"},
{"en":/Corroded Blade/g,"cn":"锈斑巨剑"},
{"en":/Longsword/g,"cn":"大剑"},
{"en":/Bastard Sword/g,"cn":"重剑"},
{"en":/Two-Handed Sword/g,"cn":"双手剑"},
{"en":/Etched Greatsword/g,"cn":"术雕巨剑"},
{"en":/Ornate Sword/g,"cn":"名贵巨剑"},
{"en":/Spectral Sword/g,"cn":"幽魂巨剑"},
{"en":/Curved Blade/g,"cn":"弯刃"},
{"en":/Butcher Sword/g,"cn":"杀戮巨剑"},
{"en":/Footman Sword/g,"cn":"士兵巨剑"},
{"en":/Highland Blade/g,"cn":"高山重刃"},
{"en":/Engraved Greatsword/g,"cn":"符文巨剑"},
{"en":/Tiger Sword/g,"cn":"虎牙巨剑"},
{"en":/Wraith Sword/g,"cn":"凶灵巨剑"},
{"en":/Lithe Blade/g,"cn":"细刃"},
{"en":/Headman's Sword/g,"cn":"行刑巨剑"},
{"en":/Reaver Sword/g,"cn":"残暴巨剑"},
{"en":/Ezomyte Blade/g,"cn":"艾兹麦巨剑"},
{"en":/Vaal Greatsword/g,"cn":"瓦尔巨剑"},
{"en":/Lion Sword/g,"cn":"狮爪巨剑"},
{"en":/Infernal Sword/g,"cn":"狱炎重剑"},
{"en":/Exquisite Blade/g,"cn":"精致之刃"},
{"en":/Stone Axe/g,"cn":"石斧"},
{"en":/Jade Chopper/g,"cn":"碎玉大斧"},
{"en":/Woodsplitter/g,"cn":"柴斧"},
{"en":/Poleaxe/g,"cn":"巨战斧"},
{"en":/Double Axe/g,"cn":"双刃巨斧"},
{"en":/Gilded Axe/g,"cn":"金柄之斧"},
{"en":/Shadow Axe/g,"cn":"幽影巨斧"},
{"en":/Jasper Chopper/g,"cn":"灵玉巨斧"},
{"en":/Dagger Axe/g,"cn":"匕斧"},
{"en":/Timber Axe/g,"cn":"裂木巨斧"},
{"en":/Headsman Axe/g,"cn":"行刑巨斧"},
{"en":/Labrys/g,"cn":"双影巨斧"},
{"en":/Noble Axe/g,"cn":"权贵巨斧"},
{"en":/Abyssal Axe/g,"cn":"深渊巨斧"},
{"en":/Talon Axe/g,"cn":"猛禽爪斧"},
{"en":/Karui Chopper/g,"cn":"卡鲁巨斧"},
{"en":/Sundering Axe/g,"cn":"裂甲巨斧"},
{"en":/Ezomyte Axe/g,"cn":"艾兹麦巨斧"},
{"en":/Vaal Axe/g,"cn":"瓦尔巨斧"},
{"en":/Despot Axe/g,"cn":"霸主巨斧"},
{"en":/Void Axe/g,"cn":"虚影巨斧"},
{"en":/Fleshripper/g,"cn":"裂肉者"},
{"en":/Driftwood Maul/g,"cn":"朽木巨锤"},
{"en":/Tribal Maul/g,"cn":"祭仪巨锤"},
{"en":/Mallet/g,"cn":"千斤锤"},
{"en":/Sledgehammer/g,"cn":"冷铁重锤"},
{"en":/Jagged Maul/g,"cn":"狼牙重锤"},
{"en":/Brass Maul/g,"cn":"铜影巨锤"},
{"en":/Fright Maul/g,"cn":"恐惧重锤"},
{"en":/Morning Star/g,"cn":"晨星"},
{"en":/Totemic Maul/g,"cn":"图腾巨锤"},
{"en":/Great Mallet/g,"cn":"刚猛巨锤"},
{"en":/Steelhead/g,"cn":"沉钢重锤"},
{"en":/Spiny Maul/g,"cn":"凶刺巨锤"},
{"en":/Plated Maul/g,"cn":"华丽重锤"},
{"en":/Dread Maul/g,"cn":"威权巨锤"},
{"en":/Solar Maul/g,"cn":"日光锤"},
{"en":/Karui Maul/g,"cn":"卡鲁重锤"},
{"en":/Colossus Mallet/g,"cn":"巨型重锤"},
{"en":/Piledriver/g,"cn":"扫荡者"},
{"en":/Meatgrinder/g,"cn":"戮魂重锤"},
{"en":/Imperial Maul/g,"cn":"帝国重锤"},
{"en":/Terror Maul/g,"cn":"惧灵重锤"},
{"en":/Coronal Maul/g,"cn":"花冠重锤"},
{"en":/Iron Gauntlets/g,"cn":"铁锻护手"},
{"en":/Plated Gauntlets/g,"cn":"坚铁护手"},
{"en":/Bronze Gauntlets/g,"cn":"青铜护手"},
{"en":/Steel Gauntlets/g,"cn":"冷钢护手"},
{"en":/Antique Gauntlets/g,"cn":"古钢护手"},
{"en":/Ancient Gauntlets/g,"cn":"远古护手"},
{"en":/Goliath Gauntlets/g,"cn":"巨灵护手"},
{"en":/Vaal Gauntlets/g,"cn":"瓦尔护手"},
{"en":/Titan Gauntlets/g,"cn":"巨人护手"},
{"en":/Rawhide Gloves/g,"cn":"生皮手套"},
{"en":/Goathide Gloves/g,"cn":"羊皮手套"},
{"en":/Deerskin Gloves/g,"cn":"鹿皮手套"},
{"en":/Nubuck Gloves/g,"cn":"砂影手套"},
{"en":/Eelskin Gloves/g,"cn":"鳗皮手套"},
{"en":/Sharkskin Gloves/g,"cn":"鲨皮手套"},
{"en":/Shagreen Gloves/g,"cn":"粗革手套"},
{"en":/Stealth Gloves/g,"cn":"匿踪手套"},
{"en":/Slink Gloves/g,"cn":"迷踪手套"},
{"en":/Wool Gloves/g,"cn":"羊毛手套"},
{"en":/Velvet Gloves/g,"cn":"丝绒手套"},
{"en":/Silk Gloves/g,"cn":"丝绸手套"},
{"en":/Embroidered Gloves/g,"cn":"刺绣手套"},
{"en":/Satin Gloves/g,"cn":"缎布手套"},
{"en":/Samite Gloves/g,"cn":"绣布手套"},
{"en":/Conjurer Gloves/g,"cn":"咒者手套"},
{"en":/Arcanist Gloves/g,"cn":"秘术手套"},
{"en":/Sorcerer Gloves/g,"cn":"术士手套"},
{"en":/Fishscale Gauntlets/g,"cn":"鱼鳞手套"},
{"en":/Ironscale Gauntlets/g,"cn":"铁影手套"},
{"en":/Bronzescale Gauntlets/g,"cn":"铜影手套"},
{"en":/Steelscale Gauntlets/g,"cn":"钢影护手"},
{"en":/Serpentscale Gauntlets/g,"cn":"蛇鳞手套"},
{"en":/Wyrmscale Gauntlets/g,"cn":"蝮鳞手套"},
{"en":/Hydrascale Gauntlets/g,"cn":"火蝮鳞手套"},
{"en":/Dragonscale Gauntlets/g,"cn":"龙鳞手套"},
{"en":/Chain Gloves/g,"cn":"链甲手套"},
{"en":/Ringmail Gloves/g,"cn":"环甲手套"},
{"en":/Mesh Gloves/g,"cn":"网眼手套"},
{"en":/Riveted Gloves/g,"cn":"仪式手套"},
{"en":/Zealot Gloves/g,"cn":"狂热者手套"},
{"en":/Soldier Gloves/g,"cn":"战士手套"},
{"en":/Legion Gloves/g,"cn":"军团手套"},
{"en":/Crusader Gloves/g,"cn":"圣战手套"},
{"en":/Wrapped Mitts/g,"cn":"裹趾护手"},
{"en":/Strapped Mitts/g,"cn":"扣环护手"},
{"en":/Clasped Mitts/g,"cn":"环带护手"},
{"en":/Trapper Mitts/g,"cn":"猎人护手"},
{"en":/Ambush Mitts/g,"cn":"伏击护手"},
{"en":/Carnal Mitts/g,"cn":"禁礼护手"},
{"en":/Assassin's Mitts/g,"cn":"刺杀者护手"},
{"en":/Murder Mitts/g,"cn":"暗杀者护手"},
{"en":/Golden Bracers/g,"cn":"黄金臂甲"},
{"en":/Spiked Gloves/g,"cn":"釦钉手套"},
{"en":/Gripped Gloves/g,"cn":"擒拿手套"},
{"en":/Fingerless Silk Gloves/g,"cn":"魔指手套"},
{"en":/Iron Greaves/g,"cn":"铁锻胫甲"},
{"en":/Steel Greaves/g,"cn":"冷钢胫甲"},
{"en":/Plated Greaves/g,"cn":"坚铁胫甲"},
{"en":/Reinforced Greaves/g,"cn":"强化胫甲"},
{"en":/Antique Greaves/g,"cn":"古钢胫甲"},
{"en":/Ancient Greaves/g,"cn":"远古胫甲"},
{"en":/Goliath Greaves/g,"cn":"巨灵胫甲"},
{"en":/Vaal Greaves/g,"cn":"瓦尔胫甲"},
{"en":/Titan Greaves/g,"cn":"巨人胫甲"},
{"en":/Kaom's Greaves/g,"cn":"冈姆胫甲"},
{"en":/Rawhide Boots/g,"cn":"生皮短靴"},
{"en":/Goathide Boots/g,"cn":"羊皮短靴"},
{"en":/Deerskin Boots/g,"cn":"鹿皮短靴"},
{"en":/Nubuck Boots/g,"cn":"砂影短靴"},
{"en":/Eelskin Boots/g,"cn":"鳗皮短靴"},
{"en":/Sharkskin Boots/g,"cn":"鲨皮短靴"},
{"en":/Shagreen Boots/g,"cn":"粗革短靴"},
{"en":/Stealth Boots/g,"cn":"匿踪短靴"},
{"en":/Slink Boots/g,"cn":"迷踪短靴"},
{"en":/Wool Shoes/g,"cn":"羊毛之鞋"},
{"en":/Velvet Slippers/g,"cn":"丝绒便鞋"},
{"en":/Silk Slippers/g,"cn":"丝绸便鞋"},
{"en":/Scholar Boots/g,"cn":"学者长靴"},
{"en":/Satin Slippers/g,"cn":"缎布便鞋"},
{"en":/Samite Slippers/g,"cn":"绣布便鞋"},
{"en":/Conjurer Boots/g,"cn":"咒者长靴"},
{"en":/Arcanist Slippers/g,"cn":"秘术便鞋"},
{"en":/Sorcerer Boots/g,"cn":"术士长靴"},
{"en":/Leatherscale Boots/g,"cn":"粗鳞皮靴"},
{"en":/Ironscale Boots/g,"cn":"铁影长靴"},
{"en":/Bronzescale Boots/g,"cn":"铜影长靴"},
{"en":/Steelscale Boots/g,"cn":"钢影长靴"},
{"en":/Serpentscale Boots/g,"cn":"蛇鳞长靴"},
{"en":/Wyrmscale Boots/g,"cn":"地蝮鳞长靴"},
{"en":/Hydrascale Boots/g,"cn":"火蝮鳞长靴"},
{"en":/Dragonscale Boots/g,"cn":"龙鳞长靴"},
{"en":/Chain Boots/g,"cn":"链甲长靴 "},
{"en":/Ringmail Boots/g,"cn":"环甲筒靴"},
{"en":/Mesh Boots/g,"cn":"网眼长靴"},
{"en":/Riveted Boots/g,"cn":"仪式短靴 "},
{"en":/Zealot Boots/g,"cn":"狂热者长靴"},
{"en":/Soldier Boots/g,"cn":"战士之靴"},
{"en":/Legion Boots/g,"cn":"军团长靴"},
{"en":/Crusader Boots/g,"cn":"圣战长靴 "},
{"en":/Wrapped Boots/g,"cn":"裹趾凉鞋 "},
{"en":/Strapped Boots/g,"cn":"扣环短靴"},
{"en":/Clasped Boots/g,"cn":"环带长靴"},
{"en":/Shackled Boots/g,"cn":"缚足长靴"},
{"en":/Trapper Boots/g,"cn":"猎人之靴"},
{"en":/Ambush Boots/g,"cn":"伏击之靴"},
{"en":/Carnal Boots/g,"cn":"禁礼之靴"},
{"en":/Assassin's Boots/g,"cn":"刺杀者之靴"},
{"en":/Murder Boots/g,"cn":"暗杀者长靴"},
{"en":/Golden Caligae/g,"cn":"黄金缠鞋"},
{"en":/Avian Slippers/g,"cn":"飞羽便鞋"},
{"en":/Two-Toned Boots/g,"cn":"异色鞋"},
{"en":/Plate Vest/g,"cn":"铁制背心"},
{"en":/Chestplate/g,"cn":"胸甲"},
{"en":/Copper Plate/g,"cn":"铜锻板甲"},
{"en":/War Plate/g,"cn":"战争之铠"},
{"en":/Full Plate/g,"cn":"连身铠甲"},
{"en":/Arena Plate/g,"cn":"斗者之铠"},
{"en":/Lordly Plate/g,"cn":"领主护铠"},
{"en":/Bronze Plate/g,"cn":"青铜铠甲"},
{"en":/Battle Plate/g,"cn":"战铠"},
{"en":/Sun Plate/g,"cn":"日光之铠"},
{"en":/Colosseum Plate/g,"cn":"决斗之铠"},
{"en":/Majestic Plate/g,"cn":"庄严之铠"},
{"en":/Golden Plate/g,"cn":"金耀之铠"},
{"en":/Crusader Plate/g,"cn":"征战重铠"},
{"en":/Astral Plate/g,"cn":"星芒战铠"},
{"en":/Gladiator Plate/g,"cn":"角斗重铠"},
{"en":/Glorious Plate/g,"cn":"荣耀战铠"},
{"en":/Kaom's Plate/g,"cn":"冈姆的重铠"},
{"en":/Shabby Jerkin/g,"cn":"破旧外套"},
{"en":/Strapped Leather/g,"cn":"扣环皮甲"},
{"en":/Buckskin Tunic/g,"cn":"鹿皮外套"},
{"en":/Wild Leather/g,"cn":"野性皮甲"},
{"en":/Full Leather/g,"cn":"连身皮甲"},
{"en":/Sun Leather/g,"cn":"日光皮甲"},
{"en":/Thief's Garb/g,"cn":"窃贼之装"},
{"en":/Eelskin Tunic/g,"cn":"鳗皮之衣"},
{"en":/Frontier Leather/g,"cn":"边戍皮甲"},
{"en":/Glorious Leather/g,"cn":"荣耀皮甲"},
{"en":/Coronal Leather/g,"cn":"光耀皮甲"},
{"en":/Cutthroat's Garb/g,"cn":"残杀者之装"},
{"en":/Sharkskin Tunic/g,"cn":"鲨皮之衣"},
{"en":/Destiny Leather/g,"cn":"命运皮甲"},
{"en":/Exquisite Leather/g,"cn":"精制皮甲"},
{"en":/Zodiac Leather/g,"cn":"星辰皮甲"},
{"en":/Assassin's Garb/g,"cn":"刺杀者之装"},
{"en":/Simple Robe/g,"cn":"简易之袍"},
{"en":/Silken Vest/g,"cn":"绸缎背心"},
{"en":/Scholar's Robe/g,"cn":"学者之袍"},
{"en":/Silken Garb/g,"cn":"丝绸之衣"},
{"en":/Mage's Vestment/g,"cn":"博学长衣"},
{"en":/Silk Robe/g,"cn":"丝质之袍"},
{"en":/Cabalist Regalia/g,"cn":"秘术法衣"},
{"en":/Sage's Robe/g,"cn":"贤者之袍"},
{"en":/Silken Wrap/g,"cn":"丝绒背心"},
{"en":/Conjurer's Vestment/g,"cn":"咒者长衣"},
{"en":/Spidersilk Robe/g,"cn":"蛛丝之袍"},
{"en":/Destroyer Regalia/g,"cn":"灭世法衣"},
{"en":/Savant's Robe/g,"cn":"智者之袍"},
{"en":/Necromancer Silks/g,"cn":"操灵者背心"},
{"en":/Occultist's Vestment/g,"cn":"秘术长衣"},
{"en":/Widowsilk Robe/g,"cn":"毒蛛丝之袍"},
{"en":/Vaal Regalia/g,"cn":"瓦尔法衣"},
{"en":/Scale Vest/g,"cn":"细鳞背心 "},
{"en":/Light Brigandine/g,"cn":"轻锁甲"},
{"en":/Scale Doublet/g,"cn":"合身鳞甲 "},
{"en":/Infantry Brigandine/g,"cn":"步兵锁甲 "},
{"en":/Full Scale Armour/g,"cn":"连身鳞甲"},
{"en":/Soldier's Brigandine/g,"cn":"战士锁甲"},
{"en":/Field Lamellar/g,"cn":"野战薄甲"},
{"en":/Wyrmscale Doublet/g,"cn":"龙鳞战甲"},
{"en":/Hussar Brigandine/g,"cn":"轻骑锁甲 "},
{"en":/Full Wyrmscale/g,"cn":"连身龙鳞战甲"},
{"en":/Commander's Brigandine/g,"cn":"指挥者锁甲"},
{"en":/Battle Lamellar/g,"cn":"争战鳞甲 "},
{"en":/Dragonscale Doublet/g,"cn":"龙鳞护甲 "},
{"en":/Desert Brigandine/g,"cn":"荒野锁铠"},
{"en":/Full Dragonscale/g,"cn":"连身龙鳞铠"},
{"en":/General's Brigandine/g,"cn":"将军铠甲"},
{"en":/Triumphant Lamellar/g,"cn":"胜利盔甲"},
{"en":/Chainmail Vest/g,"cn":"锁链背心"},
{"en":/Chainmail Tunic/g,"cn":"链甲外衣"},
{"en":/Ringmail Coat/g,"cn":"环甲外套"},
{"en":/Chainmail Doublet/g,"cn":"护体锁甲"},
{"en":/Full Ringmail/g,"cn":"连身环甲"},
{"en":/Full Chainmail/g,"cn":"连身锁甲"},
{"en":/Holy Chainmail/g,"cn":"圣语锁甲"},
{"en":/Latticed Ringmail/g,"cn":"精制环甲"},
{"en":/Crusader Chainmail/g,"cn":"圣战锁甲"},
{"en":/Ornate Ringmail/g,"cn":"华丽环甲"},
{"en":/Chain Hauberk/g,"cn":"锁子长甲"},
{"en":/Devout Chainmail/g,"cn":"虔诚链甲"},
{"en":/Loricated Ringmail/g,"cn":"覆体环甲"},
{"en":/Conquest Chainmail/g,"cn":"征战锁甲"},
{"en":/Elegant Ringmail/g,"cn":"权贵环甲"},
{"en":/Saint's Hauberk/g,"cn":"圣者链甲"},
{"en":/Saintly Chainmail/g,"cn":"圣洁锁甲"},
{"en":/Padded Vest/g,"cn":"薄衬衣"},
{"en":/Oiled Vest/g,"cn":"防水背心"},
{"en":/Padded Jacket/g,"cn":"长袖棉袄"},
{"en":/Oiled Coat/g,"cn":"防水外衣"},
{"en":/Scarlet Raiment/g,"cn":"炽红之衣"},
{"en":/Waxed Garb/g,"cn":"蜡封束衣"},
{"en":/Bone Armour/g,"cn":"骨制战甲"},
{"en":/Quilted Jacket/g,"cn":"菱纹外衣"},
{"en":/Sleek Coat/g,"cn":"滑布外套"},
{"en":/Crimson Raiment/g,"cn":"绯红之衣"},
{"en":/Lacquered Garb/g,"cn":"漆彩束衣"},
{"en":/Crypt Armour/g,"cn":"地穴战甲"},
{"en":/Sentinel Jacket/g,"cn":"哨兵之衣"},
{"en":/Varnished Coat/g,"cn":"映彩外套"},
{"en":/Blood Raiment/g,"cn":"血色之衣"},
{"en":/Sadist Garb/g,"cn":"狂虐者束衣"},
{"en":/Carnal Armour/g,"cn":"禁礼之甲"},
{"en":/Sacrificial Garb/g,"cn":"祭礼束衣"},
{"en":/Golden Mantle/g,"cn":"黄金战甲"},
{"en":/Iron Hat/g,"cn":"粗铁盔"},
{"en":/Cone Helmet/g,"cn":"锥顶盔"},
{"en":/Barbute Helmet/g,"cn":"轻骑盔"},
{"en":/Close Helmet/g,"cn":"护面盔"},
{"en":/Gladiator Helmet/g,"cn":"角斗者之盔"},
{"en":/Reaver Helmet/g,"cn":"掠夺者之盔"},
{"en":/Siege Helmet/g,"cn":"破城之盔"},
{"en":/Samite Helmet/g,"cn":"绣领之盔"},
{"en":/Ezomyte Burgonet/g,"cn":"艾兹麦坚盔"},
{"en":/Royal Burgonet/g,"cn":"皇室坚盔"},
{"en":/Eternal Burgonet/g,"cn":"永恒坚盔"},
{"en":/Leather Cap/g,"cn":"皮帽"},
{"en":/Tricorne/g,"cn":"三角帽"},
{"en":/Leather Hood/g,"cn":"革兜"},
{"en":/Wolf Pelt/g,"cn":"狼首皮盔"},
{"en":/Hunter Hood/g,"cn":"猎者之兜"},
{"en":/Noble Tricorne/g,"cn":"贵族三角帽"},
{"en":/Ursine Pelt/g,"cn":"熊首皮盔"},
{"en":/Silken Hood/g,"cn":"绸缎之兜"},
{"en":/Sinner Tricorne/g,"cn":"罪者之帽"},
{"en":/Lion Pelt/g,"cn":"狮首皮盔"},
{"en":/Vine Circlet/g,"cn":"藤蔓之冠"},
{"en":/Iron Circlet/g,"cn":"铁锻之冠"},
{"en":/Torture Cage/g,"cn":"刑罚头笼"},
{"en":/Tribal Circlet/g,"cn":"祭仪之冠"},
{"en":/Bone Circlet/g,"cn":"灵骨之冠"},
{"en":/Lunaris Circlet/g,"cn":"月影之冠"},
{"en":/Steel Circlet/g,"cn":"冷钢之冠"},
{"en":/Necromancer Circlet/g,"cn":"操灵者之冠"},
{"en":/Solaris Circlet/g,"cn":"日耀之冠"},
{"en":/Mind Cage/g,"cn":"灵能之笼"},
{"en":/Hubris Circlet/g,"cn":"灵主之环"},
{"en":/Battered Helm/g,"cn":"残破之盔"},
{"en":/Sallet/g,"cn":"轻铁护盔"},
{"en":/Visored Sallet/g,"cn":"清视护盔"},
{"en":/Gilded Sallet/g,"cn":"金面护盔"},
{"en":/Secutor Helm/g,"cn":"精兵之盔"},
{"en":/Fencer Helm/g,"cn":"击剑士之盔"},
{"en":/Lacquered Helmet/g,"cn":"漆彩之盔"},
{"en":/Fluted Bascinet/g,"cn":"全罩战盔"},
{"en":/Pig-Faced Bascinet/g,"cn":"猪面头盔"},
{"en":/Nightmare Bascinet/g,"cn":"梦魇战盔"},
{"en":/Rusted Coif/g,"cn":"锈铁链盔"},
{"en":/Soldier Helmet/g,"cn":"士兵之盔"},
{"en":/Great Helmet/g,"cn":"巨盔"},
{"en":/Crusader Helmet/g,"cn":"圣战之盔"},
{"en":/Aventail Helmet/g,"cn":"战意之盔"},
{"en":/Zealot Helmet/g,"cn":"热战之盔"},
{"en":/Great Crown/g,"cn":"强化巨盔"},
{"en":/Magistrate Crown/g,"cn":"行政者战冠"},
{"en":/Prophet Crown/g,"cn":"箴言战冠"},
{"en":/Praetor Crown/g,"cn":"领主战冠"},
{"en":/Scare Mask/g,"cn":"幽惧之面"},
{"en":/Plague Mask/g,"cn":"疫灾之面"},
{"en":/Iron Mask/g,"cn":"铁锻之面"},
{"en":/Festival Mask/g,"cn":"节庆之面"},
{"en":/Golden Mask/g,"cn":"黄金之面"},
{"en":/Raven Mask/g,"cn":"祸鸦之面"},
{"en":/Callous Mask/g,"cn":"无情之面"},
{"en":/Regicide Mask/g,"cn":"弒君之面"},
{"en":/Harlequin Mask/g,"cn":"鹰喙之面"},
{"en":/Vaal Mask/g,"cn":"瓦尔之面"},
{"en":/Deicide Mask/g,"cn":"弒神之面"},
{"en":/Golden Wreath/g,"cn":"金黄花环"},
{"en":/Bone Helmet/g,"cn":"唤骨头盔"},
{"en":/Splintered Tower Shield/g,"cn":"朽木塔盾"},
{"en":/Corroded Tower Shield/g,"cn":"斑驳塔盾"},
{"en":/Rawhide Tower Shield/g,"cn":"生皮塔盾"},
{"en":/Cedar Tower Shield/g,"cn":"松木塔盾"},
{"en":/Copper Tower Shield/g,"cn":"铜锻塔盾"},
{"en":/Reinforced Tower Shield/g,"cn":"强化塔盾"},
{"en":/Painted Tower Shield/g,"cn":"彩绘塔盾"},
{"en":/Buckskin Tower Shield/g,"cn":"鹿皮塔盾"},
{"en":/Mahogany Tower Shield/g,"cn":"桃木塔盾"},
{"en":/Bronze Tower Shield/g,"cn":"青铜塔盾"},
{"en":/Girded Tower Shield/g,"cn":"征战塔盾"},
{"en":/Crested Tower Shield/g,"cn":"荣冠塔盾"},
{"en":/Shagreen Tower Shield/g,"cn":"粗革塔盾"},
{"en":/Ebony Tower Shield/g,"cn":"乌木塔盾"},
{"en":/Ezomyte Tower Shield/g,"cn":"艾兹麦塔盾"},
{"en":/Colossal Tower Shield/g,"cn":"巨型塔盾"},
{"en":/Pinnacle Tower Shield/g,"cn":"坚毅塔盾"},
{"en":/Goathide Buckler/g,"cn":"羊皮轻盾"},
{"en":/Pine Buckler/g,"cn":"松木轻盾"},
{"en":/Painted Buckler/g,"cn":"彩绘轻盾"},
{"en":/Hammered Buckler/g,"cn":"铆钉轻盾"},
{"en":/War Buckler/g,"cn":"战争轻盾"},
{"en":/Gilded Buckler/g,"cn":"金面轻盾"},
{"en":/Oak Buckler/g,"cn":"橡木轻盾"},
{"en":/Enameled Buckler/g,"cn":"釉彩轻盾"},
{"en":/Corrugated Buckler/g,"cn":"波纹轻盾"},
{"en":/Battle Buckler/g,"cn":"斗者轻盾"},
{"en":/Golden Buckler/g,"cn":"金阳轻盾"},
{"en":/Ironwood Buckler/g,"cn":"钢木轻盾"},
{"en":/Lacquered Buckler/g,"cn":"漆彩轻盾"},
{"en":/Vaal Buckler/g,"cn":"瓦尔轻盾"},
{"en":/Crusader Buckler/g,"cn":"圣战轻盾"},
{"en":/Imperial Buckler/g,"cn":"帝国轻盾"},
{"en":/Twig Spirit Shield/g,"cn":"残枝魔盾"},
{"en":/Yew Spirit Shield/g,"cn":"紫衫魔盾"},
{"en":/Bone Spirit Shield/g,"cn":"骨制魔盾"},
{"en":/Tarnished Spirit Shield/g,"cn":"环形魔盾"},
{"en":/Jingling Spirit Shield/g,"cn":"灵相魔盾"},
{"en":/Brass Spirit Shield/g,"cn":"铜锻魔盾"},
{"en":/Walnut Spirit Shield/g,"cn":"桃木魔盾"},
{"en":/Ivory Spirit Shield/g,"cn":"象牙魔盾"},
{"en":/Ancient Spirit Shield/g,"cn":"远古魔盾"},
{"en":/Chiming Spirit Shield/g,"cn":"魂相魔盾"},
{"en":/Thorium Spirit Shield/g,"cn":"暗金魔盾"},
{"en":/Lacewood Spirit Shield/g,"cn":"软橡魔盾"},
{"en":/Fossilised Spirit Shield/g,"cn":"石化魔盾"},
{"en":/Vaal Spirit Shield/g,"cn":"瓦尔魔盾"},
{"en":/Harmonic Spirit Shield/g,"cn":"和谐魔盾"},
{"en":/Titanium Spirit Shield/g,"cn":"巨人魔盾"},
{"en":/Rotted Round Shield/g,"cn":"朽木圆盾"},
{"en":/Fir Round Shield/g,"cn":"杉木圆盾"},
{"en":/Studded Round Shield/g,"cn":"铆钉圆盾"},
{"en":/Scarlet Round Shield/g,"cn":"炽红圆盾"},
{"en":/Splendid Round Shield/g,"cn":"光辉圆盾"},
{"en":/Maple Round Shield/g,"cn":"枫木圆盾"},
{"en":/Spiked Round Shield/g,"cn":"尖刺圆盾"},
{"en":/Crimson Round Shield/g,"cn":"绯红圆盾"},
{"en":/Baroque Round Shield/g,"cn":"古代圆盾"},
{"en":/Teak Round Shield/g,"cn":"柚木圆盾"},
{"en":/Spiny Round Shield/g,"cn":"棘刺圆盾"},
{"en":/Cardinal Round Shield/g,"cn":"祭者圆盾"},
{"en":/Elegant Round Shield/g,"cn":"权贵圆盾"},
{"en":/Plank Kite Shield/g,"cn":"朽木鸢盾"},
{"en":/Linden Kite Shield/g,"cn":"椴木鸢盾"},
{"en":/Reinforced Kite Shield/g,"cn":"强化鸢盾"},
{"en":/Layered Kite Shield/g,"cn":"层板鸢盾"},
{"en":/Ceremonial Kite Shield/g,"cn":"祭仪鸢盾"},
{"en":/Etched Kite Shield/g,"cn":"刻文鸢盾"},
{"en":/Steel Kite Shield/g,"cn":"冷钢鸢盾"},
{"en":/Laminated Kite Shield/g,"cn":"合板鸢盾"},
{"en":/Angelic Kite Shield/g,"cn":"天使鸢盾"},
{"en":/Branded Kite Shield/g,"cn":"圣记鸢盾"},
{"en":/Champion Kite Shield/g,"cn":"斗士鸢盾"},
{"en":/Mosaic Kite Shield/g,"cn":"厚装鸢盾"},
{"en":/Archon Kite Shield/g,"cn":"威能鸢盾"},
{"en":/Spiked Bundle/g,"cn":"尖木刺盾"},
{"en":/Driftwood Spiked Shield/g,"cn":"朽木刺盾"},
{"en":/Alloyed Spiked Shield/g,"cn":"合金刺盾"},
{"en":/Burnished Spiked Shield/g,"cn":"冷芒刺盾"},
{"en":/Ornate Spiked Shield/g,"cn":"华丽刺盾"},
{"en":/Redwood Spiked Shield/g,"cn":"红木刺盾"},
{"en":/Compound Spiked Shield/g,"cn":"复合刺盾"},
{"en":/Polished Spiked Shield/g,"cn":"光辉刺盾"},
{"en":/Sovereign Spiked Shield/g,"cn":"王权刺盾"},
{"en":/Alder Spiked Shield/g,"cn":"桤木刺盾"},
{"en":/Ezomyte Spiked Shield/g,"cn":"艾兹麦刺盾"},
{"en":/Mirrored Spiked Shield/g,"cn":"钢镜刺盾"},
{"en":/Supreme Spiked Shield/g,"cn":"霸者刺盾"},
{"en":/Golden Flame/g,"cn":"黄金圣炎"},
{"en":/Paua Amulet/g,"cn":"海灵护身符"},
{"en":/Coral Amulet/g,"cn":"珊瑚护身符"},
{"en":/Amber Amulet/g,"cn":"琥珀护身符"},
{"en":/Jade Amulet/g,"cn":"翠玉护身符"},
{"en":/Lapis Amulet/g,"cn":"海玉护身符"},
{"en":/Gold Amulet/g,"cn":"帝金护身符"},
{"en":/Onyx Amulet/g,"cn":"黑曜护身符"},
{"en":/Turquoise Amulet/g,"cn":"青玉护身符"},
{"en":/Agate Amulet/g,"cn":"玛瑙护身符"},
{"en":/Citrine Amulet/g,"cn":"黄晶护身符"},
{"en":/Ruby Amulet/g,"cn":"血色护身符"},
{"en":/Jet Amulet/g,"cn":"杰特护身符"},
{"en":/Blue Pearl Amulet/g,"cn":"碧珠护身符"},
{"en":/Marble Amulet/g,"cn":"理石护身符"},
{"en":/Black Maw Talisman/g,"cn":"黑牙魔符"},
{"en":/Bonespire Talisman/g,"cn":"脊骨魔符"},
{"en":/Ashscale Talisman/g,"cn":"灰烬魔符"},
{"en":/Lone Antler Talisman/g,"cn":"孤角魔符"},
{"en":/Deep One Talisman/g,"cn":"深渊魔符"},
{"en":/Breakrib Talisman/g,"cn":"碎骨魔符"},
{"en":/Deadhand Talisman/g,"cn":"亡手魔符"},
{"en":/Undying Flesh Talisman/g,"cn":"不朽魔符"},
{"en":/Rot Head Talisman/g,"cn":"腐首魔符"},
{"en":/Mandible Talisman/g,"cn":"巨颚魔符"},
{"en":/Chrysalis Talisman/g,"cn":"虫蛹魔符"},
{"en":/Writhing Talisman/g,"cn":"狂癫魔符"},
{"en":/Hexclaw Talisman/g,"cn":"幻爪魔符"},
{"en":/Primal Skull Talisman/g,"cn":"皇骨魔符"},
{"en":/Wereclaw Talisman/g,"cn":"亡爪魔符"},
{"en":/Splitnewt Talisman/g,"cn":"断螈魔符"},
{"en":/Clutching Talisman/g,"cn":"咒箍魔符"},
{"en":/Avian Twins Talisman/g,"cn":"双子魔符"},
{"en":/Fangjaw Talisman/g,"cn":"齿鲨魔符"},
{"en":/Horned Talisman/g,"cn":"尖角魔符"},
{"en":/Spinefuse Talisman/g,"cn":"潜能魔符"},
{"en":/Three Rat Talisman/g,"cn":"三鼠魔符"},
{"en":/Monkey Twins Talisman/g,"cn":"双猴魔符"},
{"en":/Longtooth Talisman/g,"cn":"长牙魔符"},
{"en":/Rotfeather Talisman/g,"cn":"死羽魔符"},
{"en":/Monkey Paw Talisman/g,"cn":"猴掌魔符"},
{"en":/Three Hands Talisman/g,"cn":"三手魔符"},
{"en":/Greatwolf Talisman/g,"cn":"狼王魔符"},
{"en":/Golden Hoop/g,"cn":"金环"},
{"en":/Iron Ring/g,"cn":"锻铁戒指"},
{"en":/Coral Ring/g,"cn":"珊瑚戒指"},
{"en":/Paua Ring/g,"cn":"海灵戒指"},
{"en":/Gold Ring/g,"cn":"金光戒指"},
{"en":/Topaz Ring/g,"cn":"黄玉戒指"},
{"en":/Sapphire Ring/g,"cn":"蓝玉戒指"},
{"en":/Ruby Ring/g,"cn":"红玉戒指"},
{"en":/Prismatic Ring/g,"cn":"三相戒指"},
{"en":/Moonstone Ring/g,"cn":"月光石戒指"},
{"en":/Amethyst Ring/g,"cn":"紫晶戒指"},
{"en":/Diamond Ring/g,"cn":"宝钻戒指"},
{"en":/Two-Stone Ring/g,"cn":"双玉戒指"},
{"en":/Unset Ring/g,"cn":"潜能之戒"},
{"en":/Jet Ring/g,"cn":"杰特戒指"},
{"en":/Steel Ring/g,"cn":"钢铸戒指"},
{"en":/Opal Ring/g,"cn":"蛋白石戒指"},
{"en":/Breach Ring/g,"cn":"裂痕戒指"},
{"en":/Cured Quiver/g,"cn":"火焰箭袋"},
{"en":/Rugged Quiver/g,"cn":"冰晶箭袋"},
{"en":/Conductive Quiver/g,"cn":"电光箭袋"},
{"en":/Heavy Quiver/g,"cn":"重矢箭袋 "},
{"en":/Light Quiver/g,"cn":"轻巧箭袋"},
{"en":/Serrated Arrow Quiver/g,"cn":"锯齿箭袋"},
{"en":/Two-Point Arrow Quiver/g,"cn":"双锋箭袋"},
{"en":/Sharktooth Arrow Quiver/g,"cn":"鲨齿箭袋"},
{"en":/Blunt Arrow Quiver/g,"cn":"钝矢箭袋 "},
{"en":/Fire Arrow Quiver/g,"cn":"火灵箭袋"},
{"en":/Broadhead Arrow Quiver/g,"cn":"宽矢箭袋"},
{"en":/Penetrating Arrow Quiver/g,"cn":"穿射箭袋"},
{"en":/Spike-Point Arrow Quiver/g,"cn":"刺锋箭袋"},
{"en":/Serrated Arrow Quiver/g,"cn":"锯齿箭袋"},
{"en":/Rustic Sash/g,"cn":"素布腰带"},
{"en":/Chain Belt/g,"cn":"扣链腰带"},
{"en":/Leather Belt/g,"cn":"皮革腰带"},
{"en":/Heavy Belt/g,"cn":"重革腰带"},
{"en":/Cloth Belt/g,"cn":"饰布腰带"},
{"en":/Studded Belt/g,"cn":"扣钉腰带"},
{"en":/Vanguard Belt/g,"cn":"先锋腰带"},
{"en":/Crystal Belt/g,"cn":"水晶腰带"},
{"en":/Golden Obi/g,"cn":"金羽腰带"},
{"en":/Small Life Flask/g,"cn":"小型生命药剂"},
{"en":/Medium Life Flask/g,"cn":"中型生命药剂"},
{"en":/Large Life Flask/g,"cn":"大型生命药剂"},
{"en":/Greater Life Flask/g,"cn":"良质生命药剂"},
{"en":/Grand Life Flask/g,"cn":"优质生命药剂"},
{"en":/Giant Life Flask/g,"cn":"巨型生命药剂"},
{"en":/Colossal Life Flask/g,"cn":"高阶生命药剂"},
{"en":/Sacred Life Flask/g,"cn":"圣语生命药剂"},
{"en":/Hallowed Life Flask/g,"cn":"祝福生命药剂"},
{"en":/Sanctified Life Flask/g,"cn":"圣化生命药剂"},
{"en":/Divine Life Flask/g,"cn":"不朽生命药剂"},
{"en":/Eternal Life Flask/g,"cn":"永恒生命药剂"},
{"en":/Small Mana Flask/g,"cn":"小型魔力药剂"},
{"en":/Medium Mana Flask/g,"cn":"中型魔力药剂"},
{"en":/Large Mana Flask/g,"cn":"大型魔力药剂"},
{"en":/Greater Mana Flask/g,"cn":"良质魔力药剂"},
{"en":/Grand Mana Flask/g,"cn":"优质魔力药剂"},
{"en":/Giant Mana Flask/g,"cn":"巨型魔力药剂"},
{"en":/Colossal Mana Flask/g,"cn":"高阶魔力药剂"},
{"en":/Sacred Mana Flask/g,"cn":"圣语魔力药剂"},
{"en":/Hallowed Mana Flask/g,"cn":"祝福魔力药剂"},
{"en":/Sanctified Mana Flask/g,"cn":"圣化魔力药剂"},
{"en":/Divine Mana Flask/g,"cn":"不朽魔力药剂"},
{"en":/Eternal Mana Flask/g,"cn":"永恒魔力药剂"},
{"en":/Small Hybrid Flask/g,"cn":"小型复合药剂"},
{"en":/Medium Hybrid Flask/g,"cn":"中型复合药剂"},
{"en":/Large Hybrid Flask/g,"cn":"大型复合药剂"},
{"en":/Colossal Hybrid Flask/g,"cn":"高阶复合药剂"},
{"en":/Sacred Hybrid Flask/g,"cn":"圣语复合药剂 "},
{"en":/Hallowed Hybrid Flask/g,"cn":"祝福复合药剂"},
{"en":/Ruby Flask/g,"cn":"红玉药剂"},
{"en":/Sapphire Flask/g,"cn":"蓝玉药剂"},
{"en":/Topaz Flask/g,"cn":"黄玉药剂"},
{"en":/Granite Flask/g,"cn":"坚岩药剂"},
{"en":/Quicksilver Flask/g,"cn":"水银药剂"},
{"en":/Amethyst Flask/g,"cn":"紫晶药剂"},
{"en":/Quartz Flask/g,"cn":"石英药剂"},
{"en":/Jade Flask/g,"cn":"翠玉药剂"},
{"en":/Basalt Flask/g,"cn":"石化药剂"},
{"en":/Aquamarine Flask/g,"cn":"海蓝药剂"},
{"en":/Stibnite Flask/g,"cn":"迷雾药剂"},
{"en":/Sulphur Flask/g,"cn":"硫磺药剂"},
{"en":/Silver Flask/g,"cn":"真银药剂"},
{"en":/Bismuth Flask/g,"cn":"灰岩药剂"},
{"en":/Diamond Flask/g,"cn":"宝钻药剂"}

];

var baseJewelJson=[

{"en":/>Brawn/g,"cn":">筋骨强化(Brawn)"},
{"en":/>Inertia/g,"cn":">惯性(Inertia)"},
{"en":/>Vampire's Might/g,"cn":">吸血鬼的力量(Vampire's Might)"},
{"en":/>Survival Skills/g,"cn":">生存技巧(Survival Skills)"},
{"en":/>Inspired Learning/g,"cn":">求知的热情(Inspired Learning)"},
{"en":/>Martial Artistry/g,"cn":">武艺之相(Martial Artistry)"},
{"en":/>Spire of Stone/g,"cn":">石塔(Spire of Stone)"},
{"en":/>Mantra of Flames/g,"cn":">烈炎之兆(Mantra of Flames)"},
{"en":/>Combustibles/g,"cn":">燃尽(Combustibles)"},
{"en":/>The Naming Temporary/g,"cn":">暂名(The Naming Temporary)"},
{"en":/>Fragile Bloom/g,"cn":">脆弱的繁华(Fragile Bloom)"},
{"en":/>Rain of Splinters/g,"cn":">碎镞雨(Rain of Splinters)"},
{"en":/>Efficient Training/g,"cn":">充分训练(Efficient Training)"},
{"en":/>Atziri's Reign/g,"cn":">阿兹里之权(Atziri's Reign)"},
{"en":/>Blood Sacrifice/g,"cn":">血牺(Blood Sacrifice)"},
{"en":/>Warlord's Reach/g,"cn":">督军之力(Warlord's Reach)"},
{"en":/>Conqueror's Efficiency/g,"cn":">征服者的迅捷(Conqueror's Efficiency)"},
{"en":/>Ancient Waystones/g,"cn":">远古基石(Ancient Waystones)"},
{"en":/>Zerphi's Youth/g,"cn":">泽佛伊的青春(Zerphi's Youth)"},
{"en":/>Fragility/g,"cn":">虚弱(Fragility)"},
{"en":/>Fireborn/g,"cn":">炎域(Fireborn)"},
{"en":/>Energised Armour/g,"cn":">能量坚甲(Energised Armour)"},
{"en":/>Might in All Forms/g,"cn":">卓绝之力(Might in All Forms)"},
{"en":/>Izaro's Turmoil/g,"cn":">伊泽洛之乱(Izaro's Turmoil)"},
{"en":/>The Vigil/g,"cn":">监视守夜(The Vigil)"},
{"en":/>Rapid Expansion/g,"cn":">急速扩张(Rapid Expansion)"},
{"en":/>Shattered Chains/g,"cn":">破碎之鍊(Shattered Chains)"},
{"en":/>Weight of the Empire/g,"cn":">帝国重量(Weight of the Empire)"},
{"en":/>Emperor's Might/g,"cn":">帝王的霸权(Emperor's Might)"},
{"en":/>Grand Spectrum/g,"cn":">巨光谱(Grand Spectrum)"},
{"en":/>Coated Shrapnel/g,"cn":">榴星(Coated Shrapnel)"},
{"en":/>Underdog's Fury/g,"cn":">牺牲者怒息(Underdog's Fury)"},
{"en":/>Primordial Might/g,"cn":">先祖力量(Primordial Might)"},
{"en":/>The Red Dream/g,"cn":">赤影梦境(The Red Dream)"},
{"en":/>The Red Nightmare/g,"cn":">赤影梦魇(The Red Nightmare)"},
{"en":/>Winter Burial/g,"cn":">冬葬(Winter Burial)"},
{"en":/>Wildfire/g,"cn":">燐火(Wildfire)"},
{"en":/>Overwhelming Odds/g,"cn":">绝对压制(Overwhelming Odds)"},
{"en":/>Fluid Motion/g,"cn":">流畅行动(Fluid Motion)"},
{"en":/>Intuitive Leap/g,"cn":">直觉之跃(Intuitive Leap)"},
{"en":/>Lioneye's Fall/g,"cn":">狮眼的陨落(Lioneye's Fall)"},
{"en":/>Survival Instincts/g,"cn":">生存本能(Survival Instincts)"},
{"en":/>Cannibalistic Habits/g,"cn":">同族相残(Cannibalistic Habits)"},
{"en":/>Apparitions/g,"cn":">映像(Apparitions)"},
{"en":/>Hotfooted/g,"cn":">狂奔(Hotfooted)"},
{"en":/>Weight of Sin/g,"cn":">罪恶的重量(Weight of Sin)"},
{"en":/>Specialised/g,"cn":">熟稔(Specialised)"},
{"en":/>Miser of Misery/g,"cn":">悲惨赐予者(Miser of Misery)"},
{"en":/>Careful Planning/g,"cn":">审慎计划(Careful Planning)"},
{"en":/>Hidden Potential/g,"cn":">深藏的潜能(Hidden Potential)"},
{"en":/>Sacrificial Harvest/g,"cn":">原生祭仪(Sacrificial Harvest)"},
{"en":/>Self-Flagellation/g,"cn":">残虐之欢愉(Self-Flagellation)"},
{"en":/>Poacher's Aim/g,"cn":">盗猎者的准心(Poacher's Aim)"},
{"en":/>Conqueror's Longevity/g,"cn":">征服者的长生(Conqueror's Longevity)"},
{"en":/>Chill of Corruption/g,"cn":">腐化寒息(Chill of Corruption)"},
{"en":/>Hungry Abyss/g,"cn":">饥馑深渊(Hungry Abyss)"},
{"en":/>Pacifism/g,"cn":">和平主义(Pacifism)"},
{"en":/>Pugilist/g,"cn":">迅击者(Pugilist)"},
{"en":/>Cold Steel/g,"cn":">冷钢(Cold Steel)"},
{"en":/>Static Electricity/g,"cn":">静电之源(Static Electricity)"},
{"en":/>Volley Fire/g,"cn":">怒火齐发(Volley Fire)"},
{"en":/>Spirit Guards/g,"cn":">精神守护(Spirit Guards)"},
{"en":/>Pitch Darkness/g,"cn":">黯黑之调(Pitch Darkness)"},
{"en":/>Steel Spirit/g,"cn":">坚毅心灵(Steel Spirit)"},
{"en":/>Growing Agony/g,"cn":">茁壮苦痛(Growing Agony)"},
{"en":/>Cheap Construction/g,"cn":">廉价建设(Cheap Construction)"},
{"en":/>Hair Trigger/g,"cn":">发闸机关(Hair Trigger)"},
{"en":/>Emperor's Cunning/g,"cn":">帝王的诡计(Emperor's Cunning)"},
{"en":/>Primordial Eminence/g,"cn":">先祖卓越(Primordial Eminence)"},
{"en":/>The Green Dream/g,"cn":">青影梦境(The Green Dream)"},
{"en":/>The Green Nightmare/g,"cn":">青影梦魇(The Green Nightmare)"},
{"en":/>Sudden Ignition/g,"cn":">急遽点燃(Sudden Ignition)"},
{"en":/>Ring of Blades/g,"cn":">环形刃(Ring of Blades)"},
{"en":/>Fight for Survival/g,"cn":">存战(Fight for Survival)"},
{"en":/>Omen on the Winds/g,"cn":">乘风之兆(Omen on the Winds)"},
{"en":/>Might and Influence/g,"cn":">强权之势(Might and Influence)"},
{"en":/>Collateral Damage/g,"cn":">战殇(Collateral Damage)"},
{"en":/>Army of Bones/g,"cn":">枯骨军团(Army of Bones)"},
{"en":/>Eldritch Knowledge/g,"cn":">异能知识(Eldritch Knowledge)"},
{"en":/>Selfless Leadership/g,"cn":">无私领导(Selfless Leadership)"},
{"en":/>Survival Secrets/g,"cn":">生存秘技(Survival Secrets)"},
{"en":/>Fertile Mind/g,"cn":">丰富心灵(Fertile Mind)"},
{"en":/>Fortified Legion/g,"cn":">坚守军团(Fortified Legion)"},
{"en":/>Malicious Intent/g,"cn":">不善意图(Malicious Intent)"},
{"en":/>Clear Mind/g,"cn":">理智(Clear Mind)"},
{"en":/>Brute Force Solution/g,"cn":">蛮力冲撞(Brute Force Solution)"},
{"en":/>Vaal Sentencing/g,"cn":">瓦尔之诉(Vaal Sentencing)"},
{"en":/>Fevered Mind/g,"cn":">狂热之心(Fevered Mind)"},
{"en":/>Powerlessness/g,"cn":">无力(Powerlessness)"},
{"en":/>Assassin's Haste/g,"cn":">刺杀者迷影(Assassin's Haste)"},
{"en":/>Conqueror's Potency/g,"cn":">征服者的力量(Conqueror's Potency)"},
{"en":/>Mutated Growth/g,"cn":">堕落异体(Mutated Growth)"},
{"en":/>Corrupted Energy/g,"cn":">腐化能量(Corrupted Energy)"},
{"en":/>Brittle Barrier/g,"cn":">易碎屏障(Brittle Barrier)"},
{"en":/>Anatomical Knowledge/g,"cn":">真知灼见(Anatomical Knowledge)"},
{"en":/>Energy From Within/g,"cn":">潜能防护(Energy From Within)"},
{"en":/>Healthy Mind/g,"cn":">灵体转换(Healthy Mind)"},
{"en":/>Rolling Flames/g,"cn":">滚动烈焰(Rolling Flames)"},
{"en":/>Winter's Bounty/g,"cn":">冬季赏金(Winter's Bounty)"},
{"en":/>Spirited Response/g,"cn":">先祖回音(Spirited Response)"},
{"en":/>Dead Reckoning/g,"cn":">死亡清算(Dead Reckoning)"},
{"en":/>Reckless Defence/g,"cn":">鲁莽防御(Reckless Defence)"},
{"en":/>Unstable Payload/g,"cn":">不稳定承载(Unstable Payload)"},
{"en":/>Emperor's Wit/g,"cn":">帝王的智慧(Emperor's Wit)"},
{"en":/>Unending Hunger/g,"cn":">无尽渴望(Unending Hunger)"},
{"en":/>Primordial Harmony/g,"cn":">先祖和谐(Primordial Harmony)"},
{"en":/>The Blue Dream/g,"cn":">碧影梦境(The Blue Dream)"},
{"en":/>The Blue Nightmare/g,"cn":">碧影梦魇(The Blue Nightmare)"},
{"en":/>Violent Dead/g,"cn":">亡者之残(Violent Dead)"},
{"en":/>First Snow/g,"cn":">初雪(First Snow)"},
{"en":/>Frozen Trail/g,"cn":">迹冻(Frozen Trail)"},
{"en":/>Inevitability/g,"cn":">必然(Inevitability)"},
{"en":/>Emperor's Mastery/g,"cn":">帝王的纯熟(Emperor's Mastery)"},
{"en":/>The Anima Stone/g,"cn":">聚魂石(The Anima Stone)"},
{"en":/Crimson Jewel/g,"cn":"赤红珠宝"},
{"en":/Viridian Jewel/g,"cn":"翠绿珠宝"},
{"en":/Cobalt Jewel/g,"cn":"钴蓝珠宝"},
{"en":/Prismatic Jewel/g,"cn":"三相珠宝"}
];

var baseItemTypeJson=[
{"en":/Claw/g,"cn":"爪"},
{"en":/Dagger/g,"cn":"匕首"},
{"en":/Wand/g,"cn":"法杖"},
{"en":/One Handed Sword/g,"cn":"单手剑"},
{"en":/Thrusting One Handed Sword/g,"cn":"细剑"},
{"en":/One Handed Axe/g,"cn":"单手斧"},
{"en":/One Handed Mace/g,"cn":"单手锤"},
{"en":/Sceptre/g,"cn":"权杖"},
{"en":/Bow/g,"cn":"弓"},
{"en":/Stave/g,"cn":"长杖"},
{"en":/Two Handed Sword/g,"cn":"双手剑"},
{"en":/Two Handed Axe/g,"cn":"双手斧"},
{"en":/Two Handed Mace/g,"cn":"双手锤"},
{"en":/Fishing Rod/g,"cn":"鱼竿"},
{"en":/Glove/g,"cn":"手套"},
{"en":/Boot/g,"cn":"鞋子"},
{"en":/Body Armour/g,"cn":"胸甲"},
{"en":/Helmet/g,"cn":"头盔"},
{"en":/Shield/g,"cn":"盾"},
{"en":/Amulet/g,"cn":"护身符"},
{"en":/Ring/g,"cn":"戒指"},
{"en":/Quiver/g,"cn":"箭袋"},
{"en":/Belt/g,"cn":"腰带"}
];

