var jewelsJson=[
{"en":/(\d+)% increased Physical Damage with Wands/g,"cn":"法杖攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Spell Damage while wielding a Staff/g,"cn":"持长杖时增加 #% 法术伤害"},
{"en":/(\d+)% increased Spell Damage while dual Wielding/g,"cn":"双持时增加 #% 法术伤害"},
{"en":/(\d+)% increased Spell Damage while holding a Shield/g,"cn":"持盾时增加 #% 法术伤害"},
{"en":/(\d+)% increased Trap Damage/g,"cn":"增加 #% 陷阱伤害"},
{"en":/(\d+)% increased Mine Damage/g,"cn":"增加 #% 地雷伤害"},
{"en":/(\d+)% increased Minion Damage/g,"cn":"增加 #% 召唤物伤害"},
{"en":/(\d+)% increased Attack Speed with Wands/g,"cn":"法杖攻击增加 #% 攻击速度"},
{"en":/(\d+)% increased Cast Speed while Dual Wielding/g,"cn":"双持时增加 #% 施放速度"},
{"en":/(\d+)% increased Attack Speed while Dual Wielding/g,"cn":"双持时增加 #% 攻击速度"},
{"en":/(\d+)% increased Attack Speed while holding a Shield/g,"cn":"持盾时增加 #% 攻击速度"},
{"en":/(\d+)% increased Cast Speed while holding a Shield/g,"cn":"持盾时增加 #% 施放速度"},
{"en":/(\d+)% increased Cast Speed while wielding a Staff/g,"cn":"持长杖时增加 #% 施放速度"},
{"en":/(\d+)% increased Trap Throwing Speed/g,"cn":"增加 #% 陷阱投掷速度"},
{"en":/(\d+)% increased Mine Laying Speed/g,"cn":"增加 #% 地雷放置速度"},
{"en":/(\d+)% increased Cast Speed with Fire Skills/g,"cn":"增加 #% 火焰技能的施放速度"},
{"en":/(\d+)% increased Cast Speed with Cold Skills/g,"cn":"增加 #% 冰冷技能的施放速度"},
{"en":/(\d+)% increased Cast Speed with Lightning Skills/g,"cn":"增加 #% 闪电技能的施放速度"},
{"en":/(\d+)% increased Mana Regeneration Rate/g,"cn":"增加 #% 每秒魔力回复"},
{"en":/(\d+)% increased Critical Strike Chance with Fire Skills/g,"cn":"增加 #% 火焰技能的暴击率"},
{"en":/(\d+)% increased Critical Strike Chance with Cold Skills/g,"cn":"增加 #% 冰冷技能的暴击率"},
{"en":/(\d+)% increased Critical Strike Chance with Lightning Skills/g,"cn":"增加 #% 闪电技能的暴击率"},
{"en":/to Critical Strike Multiplier with Fire Skills/g,"cn":"增加 #% 火焰技能的暴击加成"},
{"en":/to Critical Strike Multiplier with Cold Skills/g,"cn":"增加 #% 冰冷技能的暴击加成"},
{"en":/to Critical Strike Multiplier with Lightning Skills/g,"cn":"增加 #% 闪电技能的暴击加成"},
{"en":/(\d+)% additional Block Chance while Dual Wielding/g,"cn":"#% 格挡率双持时"},
{"en":/(\d+)% additional Block Chance with Shields/g,"cn":"#% 格挡率持盾时"},
{"en":/(\d+)% additional Block Chance with Staves/g,"cn":"#% 格挡率持长杖时"},
{"en":/(\d+)% additional Chance to Block Spells while Dual Wielding/g,"cn":"#% 法术格挡率双持时"},
{"en":/(\d+)% additional Chance to Block Spells with Shields/g,"cn":"#% 法术格挡率持盾时"},
{"en":/(\d+)% additional Chance to Block Spells with Staves/g,"cn":"#% 法术格挡率持长杖时"},
{"en":/(\d+)% faster start of Energy Shield Recharge/g,"cn":"比平常快 #% 开始回复能量护盾"},
{"en":/(\d+)% increased Energy Shield Recharge Rate/g,"cn":"增加 #% 能量护盾回复速度"},
{"en":/Minions have (\d+)% increased maximum Life/g,"cn":"召唤物增加 #% 最大生命"},
{"en":/(\d+)% increased Totem Damage/g,"cn":"增加 #% 图腾伤害"},
{"en":/(\d+)% increased Totem Life/g,"cn":"增加 #% 图腾生命"},
{"en":/(\d+)% increased Projectile Damage/g,"cn":"增加 #% 投射物伤害"},
{"en":/(\d+)% increased Damage over Time/g,"cn":"增加 #% 持续伤害"},
{"en":/(\d+)% increased Area Damage/g,"cn":"增加 #% 范围伤害"},
{"en":/(\d+)% increased Projectile Speed/g,"cn":"增加 #% 投射物速度"},
{"en":/(\d+) Energy Shield gained for each Enemy hit by your Attacks/g,"cn":"# 攻击命中回复能量护盾"},
{"en":/(\d+)% increased Rarity of Items found/g,"cn":"增加 #% 物品稀有度"},
{"en":/(\d+)% increased Global Critical Strike Chance/g,"cn":"增加 #% 全域暴击率"},
{"en":/to Global Critical Strike Multiplier/g,"cn":"全域暴击加成"},
{"en":/(\d+)% increased Critical Strike Chance for Spells/g,"cn":"增加 #% 法术暴击率"},
{"en":/(\d+)% increased Critical Strike Chance with Elemental Skills/g,"cn":"增加 #% 元素技能暴击率"},
{"en":/to Critical Strike Multiplier for Spells/g,"cn":"法术暴击加成"},
{"en":/to Critical Strike Multiplier with Elemental Skills/g,"cn":"元素技能的法术暴击加成"},
{"en":/(\d+)% increased Stun Duration on Enemies/g,"cn":"增加 #% 敌人的晕眩时间"},
{"en":/(\d+)% increased Stun Recovery/g,"cn":"增加 #% 晕眩回复"},
{"en":/(\d+)% reduced Mana Cost of Skills/g,"cn":"减少 #% 技能的魔力消耗"},
{"en":/(\d+)% chance to Knock Enemies Back on hit/g,"cn":"击中时有 #% 几率击退敌人"},
{"en":/(\d+)% increased Freeze Duration on Enemies, (\d+)% chance to Freeze/g,"cn":"增加 #% 敌人的冰冻持续时间"},
{"en":/(\d+)% increased Shock Duration on Enemies, (\d+)% chance to Shock/g,"cn":"增加 #% 敌人的感电持续时间"},
{"en":/(\d+)% increased Ignite Duration on Enemies, (\d+)% chance to Ignite/g,"cn":"增加 #% 敌人的点燃持续时间"},
{"en":/Minions have (\d+)% Chance to Block/g,"cn":"增加召唤物 #% 格挡率"},
{"en":/Minions have (\d+)% to all Elemental Resistances/g,"cn":"增加 #% 召唤物元素抗性"},
{"en":/Totems gain (\d+)% to all Elemental Resistances/g,"cn":"增加 #% 图腾元素抗性"},
{"en":/(\d+)% increased Physical Damage with Maces/g,"cn":"锤类攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage with Axes/g,"cn":"斧类攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage with Swords/g,"cn":"剑类攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage with Staves/g,"cn":"长杖攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage with One Handed Melee Weapons/g,"cn":"单手近战武器攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage with Two Handed Melee Weapons/g,"cn":"双手近战武器攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage while Dual Wielding/g,"cn":"双持攻击时增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage while holding a Shield/g,"cn":"持盾时增加 #% 物理伤害"},
{"en":/(\d+)% increased Attack Speed with Maces/g,"cn":"锤类攻击增加 #% 攻击速度"},
{"en":/(\d+)% increased Attack Speed with Axes/g,"cn":"斧类攻击增加 #% 攻击速度"},
{"en":/(\d+)% increased Attack Speed with Swords/g,"cn":"剑类攻击增加 #% 攻击速度"},
{"en":/(\d+)% increased Attack Speed with Staves/g,"cn":"长杖攻击增加 #% 攻击速度"},
{"en":/(\d+)% increased Attack Speed with One Handed Melee Weapons/g,"cn":"单手近战攻击增加 #% 攻击速度"},
{"en":/(\d+)% increased Attack Speed with Two Handed Melee Weapons/g,"cn":"双手近战攻击增加 #% 攻击速度"},
{"en":/(\d+)% of Physical Attack Damage Leeched as Life/g,"cn":"#% 物理攻击伤害偷取生命"},
{"en":/(\d+)% increased Armour/g,"cn":"增加 #% 护甲"},
{"en":/(\d+)% increased Critical Strike Chance with One Handed Melee Weapons/g,"cn":"单手近战武器攻击增加 #% 暴击率"},
{"en":/(\d+)% increased Critical Strike Chance with Two Handed Melee Weapons/g,"cn":"双手近战武器攻击增加 #% 暴击率"},
{"en":/(\d+)% increased Critical Strike Chance while Dual Wielding/g,"cn":"双持时攻击增加 #% 武器暴击率"},
{"en":/to Critical Strike Multiplier with One Handed Melee Weapons/g,"cn":"暴击加成·单手近战武器攻击"},
{"en":/to Critical Strike Multiplier with Two Handed Melee Weapons/g,"cn":"暴击加成·双手近战武器攻击"},
{"en":/to Critical Strike Multiplier while Dual Wielding/g,"cn":"暴击加成·双持时"},
{"en":/(\d+)% increased Melee Damage/g,"cn":"增加 #% 近战伤害"},
{"en":/(\d+) Life gained for each Enemy hit by your Attacks/g,"cn":"# 攻击命中回复生命"},
{"en":/(\d+)% increased Melee Critical Strike Chance/g,"cn":"增加 #% 近战暴击率"},
{"en":/to Melee Critical Strike Multiplier/g,"cn":"近战暴击加成"},
{"en":/(\d+)% increased Burn Duration on Enemies/g,"cn":"增加 #% 敌人燃烧持续时间"},
{"en":/(\d+)% increased Physical Damage with Bows/g,"cn":"弓类攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage with Claws/g,"cn":"爪类武器攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Physical Damage with Daggers/g,"cn":"匕首攻击增加 #% 物理伤害"},
{"en":/(\d+)% increased Melee Physical Damage while holding a Shield/g,"cn":"持盾时增加 #% 近战物理伤害"},
{"en":/(\d+)% increased Attack Speed with Bows/g,"cn":"弓类攻击增加 #% 攻击速度"},
{"en":/(\d+)% increased Attack Speed with Claws/g,"cn":"爪类攻击增加 #% 攻击速度"},
{"en":/(\d+)% increased Attack Speed with Daggers/g,"cn":"匕首攻击增加 #% 攻击速度"},
{"en":/(\d+)% of Physical Attack Damage Leeched as Mana/g,"cn":"#% 物理攻击伤害偷取魔力"},
{"en":/(\d+)% increased Evasion Rating/g,"cn":"增加 #% 闪避"},
{"en":/(\d+) Mana gained for each Enemy hit by your Attacks/g,"cn":"# 攻击命中回复魔力"},
{"en":/(\d+)% increased Accuracy Rating/g,"cn":"增加 #% 命中"},
{"en":/to Critical Strike Chance with Elemental Skills/g,"cn":"增加 #% 元素技能暴击几率"}
];