var uniqueNameJson=[

{"en":/Gluttony/g,"cn":"暴食 皮革腰带"},
{"en":/Corona Solaris/g,"cn":"日耀之冠 水晶法杖"},
{"en":/Reach of the Council/g,"cn":"议会之触 脊弓"},

{"en":/Combat Focus/g,"cn":"专精作战 钴蓝珠宝"},
{"en":/Combat Focus/g,"cn":"专精作战 翠绿珠宝"},
{"en":/Combat Focus/g,"cn":"专精作战 赤红珠宝"},
{"en":/Zeel's Amplifier/g,"cn":"萨尔的扬音 光辉刺盾"},
{"en":/Unyielding Flame/g,"cn":"不屈恶火 威能鸢盾"},
{"en":/Transcendent Spirit/g,"cn":"超凡之灵 翠绿珠宝"},
{"en":/Transcendent Mind/g,"cn":"超凡之意 钴蓝珠宝"},
{"en":/Transcendent Flesh/g,"cn":"超凡之体 赤红珠宝"},
{"en":/Tempered Spirit/g,"cn":"冶炼之灵 翠绿珠宝"},
{"en":/Tempered Mind/g,"cn":"冶炼之意 钴蓝珠宝"},
{"en":/Tempered Flesh/g,"cn":"冶炼之体 赤红珠宝"},
{"en":/String of Servitude/g,"cn":"奴役之索 重革腰带"},
{"en":/Story of the Vaal/g,"cn":"瓦尔之序 碧铜短剑"},
{"en":/Soul Ripper/g,"cn":"碎魂者 石英药剂"},
{"en":/Soul Catcher/g,"cn":"追魂者 石英药剂"},
{"en":/Slavedriver's Hand/g,"cn":"奴役之手 伏击护手"},
{"en":/Sinvicta's Mettle/g,"cn":"勇气之魄 艾兹麦巨斧"},
{"en":/Shadowstitch/g,"cn":"缝影 祭礼束衣"},
{"en":/Sacrificial Heart/g,"cn":"献祭之心 海灵护身符"},
{"en":/Omeyocan/g,"cn":"欧门悠根 禁礼之靴"},
{"en":/Mask of the Stitched Demon/g,"cn":"恶缝之面 行政者战冠"},
{"en":/Mask of the Spirit Drinker/g,"cn":"魂饮化面 圣战之盔"},
{"en":/Fate of the Vaal/g,"cn":"瓦尔之命 宝石之剑"},
{"en":/Earendel's Embrace/g,"cn":"伊尔多恩的拥抱 远古之祭"},
{"en":/Dance of the Offered/g,"cn":"奉献之舞 缚足长靴"},
{"en":/Coward's Legacy/g,"cn":"懦夫的遗产 扣链腰带"},
{"en":/Coward's Chains/g,"cn":"懦夫的锁链 扣链腰带"},
{"en":/Architect's Hand/g,"cn":"构筑之手 扣环护手"},
{"en":/Apep's Supremacy/g,"cn":"艾普霸权 瓦尔魔盾"},
{"en":/Apep's Slumber/g,"cn":"艾普之眠 远古魔盾"},
{"en":/Zerphi's Heart/g,"cn":"泽佛伊之心 海灵护身符"},
{"en":/Caer Blaidd, Wolfpack's Den/g,"cn":"塞尔.布雷德狼穴 地底之河"},
{"en":/Asenath's Gentle Touch/g,"cn":"安赛娜丝的安抚之语 丝绸手套"},
{"en":/Mark of the Doubting Knight/g,"cn":"迷茫幻符 白金波刃"},
{"en":/Spine of the First Claimant/g,"cn":"先驱之脊 冷铁短杖"},
{"en":/Cherrubim's Maleficence/g,"cn":"薛鲁宾的恶作剧 胜利盔甲"},
{"en":/Maligaro's Virtuosity/g,"cn":"马雷格罗的玫红手套 鹿皮手套"},
{"en":/Shavronne's Revelation/g,"cn":"薛朗的启示之环 月光石戒指"},
{"en":/Hand of Thought and Motion/g,"cn":"思动之手 袭眼钩"},
{"en":/Hand of Wisdom and Action/g,"cn":"智行之手 帝国战爪"},
{"en":/Brutus' Lead Sprinkler/g,"cn":"布鲁特斯的刑具 祭仪短杖"},
{"en":/Rashkaldor's Patience/g,"cn":"拉什卡德的耐心 翠玉护身符"},
{"en":/Maligaro's Restraint/g,"cn":"马雷格罗的染血之环 扣链腰带"},
{"en":/Mark of the Red Covenant/g,"cn":"红契符印 祭仪之冠"},
{"en":/Shavronne's Wrappings/g,"cn":"薛朗的护身长袍 秘术长衣"},
{"en":/Shackles of the Wretched/g,"cn":"悲运之缚 链甲手套"},
{"en":/Zerphi's Last Breath/g,"cn":"泽佛伊的终息 优质魔力药剂"},
{"en":/The Sorrow of the Divine/g,"cn":"神圣哀悼 硫磺药剂"},
{"en":/Conqueror's Efficiency/g,"cn":"征服者的迅捷 赤红珠宝"},
{"en":/Inpulsa's Broken Heart/g,"cn":"速度之力 狂虐者束衣"},
{"en":/Ralakesh's Impatience/g,"cn":"拉克斯的渴望 仪式短靴"},
{"en":/Shroud of the Lightless/g,"cn":"泯光寿衣 禁礼之甲"},
{"en":/Victario's Influence/g,"cn":"维多里奥之绝响 漆彩束衣"},
{"en":/Brinerot Whalers/g,"cn":"布琳洛特-加龙省岸行者 猎人之靴"},
{"en":/Veruso's Battering Rams/g,"cn":"陨落之环 巨人护手"},
{"en":/Razor of the Seventh Sun/g,"cn":"七日锋 夜语长剑"},
{"en":/Doryani's Catalyst/g,"cn":"多里亚尼的幻化之杖 瓦尔短杖"},
{"en":/Call of the Brotherhood/g,"cn":"意志呼唤 双玉戒指"},
{"en":/Marylene's Fallacy/g,"cn":"玛莉琳的护体之符 海玉护身符"},
{"en":/Talisman of the Victor/g,"cn":"胜者护符 海玉护身符"},
{"en":/Divination Distillate/g,"cn":"宝视精华 大型复合药剂"},
{"en":/The Overflowing Chalice/g,"cn":"高洁圣杯 硫磺药剂"},
{"en":/Kiara's Determination/g,"cn":"奇亚拉的决心 真银药剂"},
{"en":/Conqueror's Longevity/g,"cn":"征服者的长生 翠绿珠宝"},
{"en":/Malachai's Awakening/g,"cn":"玛拉凯之觉醒 铁锻之面"},
{"en":/Coralito's Signature/g,"cn":"克拉里多之名 宝钻药剂"},
{"en":/Wheel of the Stormsail/g,"cn":"暴雨之舵 朽木圆盾"},
{"en":/Crown of the Pale King/g,"cn":"殒皇之冠 弑君之面"},
{"en":/Zahndethus' Cassock/g,"cn":"札德图斯的圣衣 贤者之袍"},
{"en":/Cloak of Tawm'r Isley/g,"cn":"塔温的披风 智者之袍"},
{"en":/UniqueDagger6/g,"cn":"UniqueDagger6 玻璃利片"},
{"en":/The Goddess Unleashed/g,"cn":"女神的束缚 永恒之剑"},
{"en":/Martyr of Innocence/g,"cn":"纯净之神的祭品 贵族长杖"},
{"en":/Uul-Netol's Embrace/g,"cn":"乌尔尼多的拥抱 瓦尔巨斧"},
{"en":/Kongor's Undying Rage/g,"cn":"康戈的战炎 惧灵重锤"},
{"en":/Maligaro's Cruelty/g,"cn":"马雷格罗的残酷 青玉护身符"},
{"en":/Doryani's Invitation/g,"cn":"多里亚尼之约 重革腰带"},
{"en":/Meginord's Girdle/g,"cn":"梅吉诺德的力量泉源 重革腰带"},
{"en":/The Fracturing Spinner/g,"cn":"爆裂之射 钝矢箭袋"},
{"en":/UniqueJewel1b/g,"cn":"UniqueJewel1b 钴蓝珠宝"},
{"en":/Atziri's Reflection/g,"cn":"阿兹里的反击 金阳轻盾"},
{"en":/Doedre's Malevolence/g,"cn":"德瑞的恶念 丝绒手套"},
{"en":/Geofri's Devotion/g,"cn":"吉尔菲的奉献之锤 铜影巨锤"},
{"en":/Tukohama's Fortress/g,"cn":"图克玛哈堡垒 乌木塔盾"},
{"en":/Kongming's Stratagem/g,"cn":"孔明的神算 象牙魔盾"},
{"en":/Daresso's Courage/g,"cn":"德瑞索的勇者之盾 古代圆盾"},
{"en":/Victario's Charity/g,"cn":"维多里奥的贡献 合板鸢盾"},
{"en":/Devoto's Devotion/g,"cn":"德沃托的信念之盔 梦魇战盔"},
{"en":/The Tempest's Binding/g,"cn":"风暴拘束 无情之面"},
{"en":/Daresso's Defiance/g,"cn":"德瑞索的卫衣 连身龙鳞铠"},
{"en":/Mutewind Whispersteps/g,"cn":"哑风轻步 蛇鳞长靴"},
{"en":/Bino's Kitchen Knife/g,"cn":"比诺的厨刀 猎者之刃"},
{"en":/The Tempestuous Steel/g,"cn":"暴风之钢 征战之剑"},
{"en":/The Rippling Thoughts/g,"cn":"秘法君临 军团长剑"},
{"en":/Breath of the Council/g,"cn":"议会之息 禁礼短杖"},
{"en":/Hezmana's Bloodlust/g,"cn":"嗜血黑兹玛娜 瓦尔巨斧"},
{"en":/Jorrhast's Blacksteel/g,"cn":"乔赫黑钢 沉钢重锤"},
{"en":/Malachai's Artifice/g,"cn":"玛拉凯的巧技 潜能之戒"},
{"en":/Presence of Chayula/g,"cn":"夏乌拉之印 黑曜护身符"},
{"en":/Victario's Acuity/g,"cn":"维多里奥的捷思 青玉护身符"},
{"en":/Star of Wraeclast/g,"cn":"瓦尔克拉斯之星 血色护身符"},
{"en":/Eyes of the Greatwolf/g,"cn":"巨狼之眼 狼王魔符"},
{"en":/Lavianga's Spirit/g,"cn":"拉维安加之泉 圣化魔力药剂"},
{"en":/Slivers of Providence/g,"cn":"白银恩典 锯齿箭袋"},
{"en":/Maloney's Nightfall/g,"cn":"马洛尼的暮光 钝矢箭袋"},
{"en":/Conqueror's Potency/g,"cn":"征服者的力量 钴蓝珠宝"},
{"en":/Oba's Cursed Trove/g,"cn":"欧霸的咒怨宝库 古拷刑室"},
{"en":/Wraeclast Pantheon/g,"cn":"瓦尔克拉斯神殿 奇术秘殿"},
{"en":/Asenath's Chant/g,"cn":"安赛娜丝的优雅之歌 铁锻之冠"},
{"en":/Craiceann's Carapace/g,"cn":"深海魔甲 金耀之铠"},
{"en":/Cane of Unravelling/g,"cn":"阐释之杖 艾兹麦长杖"},
{"en":/Dialla's Malefaction/g,"cn":"无悔之爱 贤者之袍"},
{"en":/Lioneye's Remorse/g,"cn":"狮眼的荣耀之盾 坚毅塔盾"},
{"en":/Great Old One's Ward/g,"cn":"邪神庇护 波纹轻盾"},
{"en":/The Unshattered Will/g,"cn":"不屈之志 威能鸢盾"},
{"en":/Maligaro's Lens/g,"cn":"马雷格罗的染血透镜 复合刺盾"},
{"en":/The Formless Inferno/g,"cn":"无形炼狱 皇室坚盔"},
{"en":/Ylfeban's Trickery/g,"cn":"伊芙班的诡计 灵主之环"},
{"en":/Prospero's Vault/g,"cn":"普洛斯彼罗的宝库 铁制背心"},
{"en":/Geofri's Sanctuary/g,"cn":"吉尔菲的圣殿 权贵环甲"},
{"en":/Atziri's Splendour/g,"cn":"阿兹里的威权 祭礼束衣"},
{"en":/The Infinite Pursuit/g,"cn":"无尽之距 巨灵胫甲"},
{"en":/Victario's Flight/g,"cn":"维多里奥的飞升 羊皮短靴"},
{"en":/Alberon's Warpath/g,"cn":"阿尔贝隆的征途 战士之靴"},
{"en":/Meginord's Vise/g,"cn":"梅吉诺德的巨力腕甲 冷钢护手"},
{"en":/Volkuur's Guidance/g,"cn":"福库尔的手 狂热者手套"},
{"en":/Fragment of Eternity/g,"cn":"亘古之灵 玻璃利片"},
{"en":/The Goddess Scorned/g,"cn":"女神的怒炎 贵族之剑"},
{"en":/Pillar of the Caged God/g,"cn":"囚神杵 长杖"},
{"en":/Femurs of the Saints/g,"cn":"圣徒胫骨 史典长杖"},
{"en":/Atziri's Disfavour/g,"cn":"阿兹里的刑刃 瓦尔巨斧"},
{"en":/The Dancing Dervish/g,"cn":"禅意苦行僧 残暴巨剑"},
{"en":/Geofri's Baptism/g,"cn":"吉尔菲的净罪之锤 铜影巨锤"},
{"en":/Romira's Banquet/g,"cn":"罗米拉的潜力之环 宝钻戒指"},
{"en":/Berek's Respite/g,"cn":"贝雷克的火与雷之乐 双玉戒指"},
{"en":/Blood of Corruption/g,"cn":"堕落之血 琥珀护身符"},
{"en":/Umbilicus Immortalis/g,"cn":"不朽系命 皮革腰带"},
{"en":/Belt of the Deceiver/g,"cn":"狡徒束腰 重革腰带"},
{"en":/Blood of the Karui/g,"cn":"卡鲁之血 圣化生命药剂"},
{"en":/Weight of the Empire/g,"cn":"帝国重量 赤红珠宝"},
{"en":/Cannibalistic Habits/g,"cn":"同族相残 翠绿珠宝"},
{"en":/Might and Influence/g,"cn":"蛮力与影响 翠绿珠宝"},
{"en":/Brute Force Solution/g,"cn":"蛮力冲撞 钴蓝珠宝"},
{"en":/Anatomical Knowledge/g,"cn":"真知灼见 钴蓝珠宝"},
{"en":/Vaults of Atziri/g,"cn":"阿兹里的秘宝库 瓦尔金字塔"},
{"en":/The Putrid Cloister/g,"cn":"幽秘博物馆 古博物馆"},
{"en":/Hall of Grandmasters/g,"cn":"元帅殿堂 月色回廊"},
{"en":/Craiceann's Chitin/g,"cn":"深海魔角 行政者战冠"},
{"en":/Craiceann's Pincers/g,"cn":"深海魔钳 巨人护手"},
{"en":/Fenumus' Spinnerets/g,"cn":"暗夜刺足 暗影之靴"},
{"en":/Mark of the Shaper/g,"cn":"塑界之印 蛋白石戒指"},
{"en":/Blasphemer's Grasp/g,"cn":"亵渎者之握 暗影护手"},
{"en":/Remnant of Empires/g,"cn":"帝国的残壁 羊皮轻盾"},
{"en":/Crest of Perandus/g,"cn":"普兰德斯之徽 松木轻盾"},
{"en":/Brinerot Flag/g,"cn":"布琳洛特-加龙省之旗 环形魔盾"},
{"en":/The Deep One's Hide/g,"cn":"深渊绝壁 铆钉圆盾"},
{"en":/Santoni's Faith/g,"cn":"桑托尼的忠诚之心 椴木鸢盾"},
{"en":/Rise of the Phoenix/g,"cn":"烈炎之翼 厚装鸢盾"},
{"en":/Hrimnor's Resolve/g,"cn":"雷姆诺的豪情 绣领之盔"},
{"en":/Fairgraves' Tricorne/g,"cn":"费尔之帽 三角帽"},
{"en":/Asenath's Mark/g,"cn":"安赛娜丝的迅敏之冠 铁锻之冠"},
{"en":/Eber's Unification/g,"cn":"希伯的霸权 灵主之环"},
{"en":/The Bringer of Rain/g,"cn":"祭礼之雨 梦魇战盔"},
{"en":/Malachai's Vision/g,"cn":"玛拉凯的远见 领主战冠"},
{"en":/Malachai's Simula/g,"cn":"玛拉凯的祭具 铁锻之面"},
{"en":/Mind of the Council/g,"cn":"智者之秘 鹰喙之面"},
{"en":/The Snowblind Grace/g,"cn":"雪盲恩惠 光耀皮甲"},
{"en":/Queen of the Forest/g,"cn":"森林之后 命运皮甲"},
{"en":/The Coming Calamity/g,"cn":"灵魂甲胄 灭世法衣"},
{"en":/The Beast Fur Shawl/g,"cn":"兽毛披肩 瓦尔法衣"},
{"en":/Demigod's Dominance/g,"cn":"升华统御 黄金战甲"},
{"en":/Redblade Tramplers/g,"cn":"红刃蹂躏靴 远古胫甲"},
{"en":/Garukhan's Flight/g,"cn":"盖卢坎的飞升 匿踪短靴"},
{"en":/Shavronne's Pace/g,"cn":"薛朗的秘术长靴 学者长靴"},
{"en":/Shavronne's Gambit/g,"cn":"薛朗的诡计 学者长靴"},
{"en":/Wake of Destruction/g,"cn":"覆灭之兆 网眼长靴"},
{"en":/Grip of the Council/g,"cn":"议会之握 秘术手套"},
{"en":/Arimagius' Honor/g,"cn":"志士的荣耀之心 钢影护手"},
{"en":/Piscator's Vigil/g,"cn":"皮斯卡托的慧眼 狂风法杖"},
{"en":/Fidelitas' Spike/g,"cn":"费德利塔斯之锋 锯状薄刃"},
{"en":/Daresso's Passion/g,"cn":"德瑞索的热情 穿甲刺剑"},
{"en":/Callinellus Malleus/g,"cn":"坚定之刃 圣约之锤"},
{"en":/Vestige of Divinity/g,"cn":"庄重之杖 朽木之干"},
{"en":/Rigwald's Charge/g,"cn":"瑞佛的奋战长剑 高山重刃"},
{"en":/Brinerot Mark/g,"cn":"布琳洛特-加龙省印记 潜能之戒"},
{"en":/The Learning Stone/g,"cn":"学习之石 海灵护身符"},
{"en":/Stone of Lazhwar/g,"cn":"拉兹瓦的灵石 海玉护身符"},
{"en":/Voice of the Storm/g,"cn":"暴风之言 海玉护身符"},
{"en":/Choir of the Storm/g,"cn":"暴风之语 海玉护身符"},
{"en":/Demigod's Presence/g,"cn":"升华之印 帝金护身符"},
{"en":/Hinekora's Sight/g,"cn":"辛格拉的凝视 黑曜护身符"},
{"en":/Voll's Devotion/g,"cn":"福尔的忠诚之符 玛瑙护身符"},
{"en":/Daresso's Salute/g,"cn":"德瑞索的战礼 黄晶护身符"},
{"en":/The Flow Untethered/g,"cn":"流逝之时 饰布腰带"},
{"en":/Sacrificial Harvest/g,"cn":"原生祭仪 翠绿珠宝"},
{"en":/Chill of Corruption/g,"cn":"腐化寒息 翠绿珠宝"},
{"en":/Primordial Eminence/g,"cn":"起源卓越 翠绿珠宝"},
{"en":/The Green Nightmare/g,"cn":"青影梦魇 翠绿珠宝"},
{"en":/Fight for Survival/g,"cn":"为生存而战 翠绿珠宝"},
{"en":/Selfless Leadership/g,"cn":"无私领导 钴蓝珠宝"},
{"en":/The Coward's Trial/g,"cn":"懦者的试验 寂静陵墓"},
{"en":/The Vinktar Square/g,"cn":"维克塔广场 奇术之庭"},
{"en":/Chains of Command/g,"cn":"将军的复生 圣洁锁甲"},
{"en":/Cameria's Avarice/g,"cn":"卡美利亚之贪婪 坚锤"},
{"en":/Craiceann's Tracks/g,"cn":"深海魔足 巨灵胫甲"},
{"en":/Kalisa's Grace/g,"cn":"卡莉莎的优雅之影 绣布手套"},
{"en":/Yoke of Suffering/g,"cn":"苦难羁绊 黑曜护身符"},
{"en":/Chernobog's Pillar/g,"cn":"五芒屏障 乌木塔盾"},
{"en":/Chalice of Horrors/g,"cn":"恐惧之缶 战争轻盾"},
{"en":/Thirst for Horrors/g,"cn":"颤栗之饥 战争轻盾"},
{"en":/Sentari's Answer/g,"cn":"山特立的回应 铜锻魔盾"},
{"en":/The Formless Flame/g,"cn":"无形火炬 破城之盔"},
{"en":/Starkonja's Head/g,"cn":"斯塔空加之首 绸缎之兜"},
{"en":/Vizaru's Folly/g,"cn":"维札卢的不堪往事 灵能之笼"},
{"en":/Yriel's Fostering/g,"cn":"伊瑞的精通 精制皮甲"},
{"en":/Belly of the Beast/g,"cn":"兽腹 连身龙鳞战甲"},
{"en":/Incandescent Heart/g,"cn":"烈炎之心 圣洁锁甲"},
{"en":/Doedre's Tenure/g,"cn":"德瑞的精神手套 丝绒手套"},
{"en":/Kalisa's Grace/g,"cn":"卡莉莎的优雅之影 钢影护手"},
{"en":/Splinter of the Moon/g,"cn":"碎月 朽木法杖"},
{"en":/The Consuming Dark/g,"cn":"蚕食之闇 兽血短匕"},
{"en":/Ornament of the East/g,"cn":"东之饰 裂脏钩"},
{"en":/Rigwald's Savagery/g,"cn":"野性瑞佛 皇家之斧"},
{"en":/Rebuke of the Vaal/g,"cn":"瓦尔战刃 瓦尔军刃"},
{"en":/The Goddess Bound/g,"cn":"女神的灵缚 鲸骨细刃"},
{"en":/Lavianga's Wisdom/g,"cn":"拉维安加的智慧 战锤"},
{"en":/Mon'tregul's Grasp/g,"cn":"凋灵魔爪 虚影短杖"},
{"en":/Doomfletch's Prism/g,"cn":"灭世之狱 皇家猎弓"},
{"en":/Null's Inclination/g,"cn":"虚无之倾 漫游之弓"},
{"en":/Reach of The Council/g,"cn":"议会之触 脊弓"},
{"en":/The Whispering Ice/g,"cn":"冰点低语 毒牙长杖"},
{"en":/Reaper's Pursuit/g,"cn":"死神的取魂器 幽影巨斧"},
{"en":/Uul-Netol's Kiss/g,"cn":"乌尔尼多之吻 双影巨斧"},
{"en":/Hrimnor's Hymn/g,"cn":"雷姆诺的夺命凶器 冷铁重锤"},
{"en":/Band of the Victor/g,"cn":"胜利之环 锻铁戒指"},
{"en":/The Warden's Brand/g,"cn":"守卫之铭 锻铁戒指"},
{"en":/Ungil's Harmony/g,"cn":"恩吉尔的和谐 青玉护身符"},
{"en":/Ryslatha's Coil/g,"cn":"瑞斯拉萨的线圈 扣钉腰带"},
{"en":/Doedre's Elixir/g,"cn":"德瑞的妙药 良质魔力药剂"},
{"en":/The Writhing Jar/g,"cn":"扭曲之罐 祝福复合药剂"},
{"en":/Coruscating Elixir/g,"cn":"闪耀精华 红玉药剂"},
{"en":/Vessel of Vinktar/g,"cn":"维克塔血器 黄玉药剂"},
{"en":/Rumi's Concoction/g,"cn":"鲁米的灵药 坚岩药剂"},
{"en":/Atziri's Promise/g,"cn":"阿兹里的诺言 紫晶药剂"},
{"en":/Inspired Learning/g,"cn":"求知的热情 赤红珠宝"},
{"en":/The Naming Temporary/g,"cn":"暂名 赤红珠宝"},
{"en":/Efficient Training/g,"cn":"充分训练 赤红珠宝"},
{"en":/Might in All Forms/g,"cn":"卓绝之力 赤红珠宝"},
{"en":/Survival Instincts/g,"cn":"生存本能 翠绿珠宝"},
{"en":/Self-Flagellation/g,"cn":"残虐之欢愉 翠绿珠宝"},
{"en":/Static Electricity/g,"cn":"静电之源 翠绿珠宝"},
{"en":/Cheap Construction/g,"cn":"廉价建设 翠绿珠宝"},
{"en":/Emperor's Cunning/g,"cn":"帝王的诡计 翠绿珠宝"},
{"en":/Eldritch Knowledge/g,"cn":"异能知识 钴蓝珠宝"},
{"en":/Energy From Within/g,"cn":"潜能防护 钴蓝珠宝"},
{"en":/Primordial Harmony/g,"cn":"起源和谐 钴蓝珠宝"},
{"en":/The Blue Nightmare/g,"cn":"碧影梦魇 钴蓝珠宝"},
{"en":/Hazardous Research/g,"cn":"危险研究 钴蓝珠宝"},
{"en":/Emperor's Mastery/g,"cn":"帝王的纯熟 三相珠宝"},
{"en":/Maelström of Chaos/g,"cn":"混沌之渊 滨海山丘"},
{"en":/Untainted Paradise/g,"cn":"纯净乐园 晴空幽岛"},
{"en":/Acton's Nightmare/g,"cn":"轮回的梦魇 密草神殿"},
{"en":/The Perandus Manor/g,"cn":"普兰德斯庄园 古堡"},
{"en":/Mark of the Elder/g,"cn":"裂界之印 合金戒指"},
{"en":/Might of the Meek/g,"cn":"温柔之力 赤红珠宝"},
{"en":/Saqawal's Talons/g,"cn":"苍空之爪 火蝮鳞长靴"},
{"en":/Malachai's Mark/g,"cn":"马拉凯之记 暗影者护手"},
{"en":/Titucius' Span/g,"cn":"提图库斯的坚盾 强化塔盾"},
{"en":/Thousand Teeth Temu/g,"cn":"千齿 瓦尔轻盾"},
{"en":/Saffell's Frame/g,"cn":"萨费尔的智慧 圣记鸢盾"},
{"en":/Kitava's Thirst/g,"cn":"奇塔弗之渴望 热战之盔"},
{"en":/The Three Dragons/g,"cn":"三龙战纪 黄金之面"},
{"en":/Demigod's Triumph/g,"cn":"升华之冠 金黄花环"},
{"en":/Skin of the Loyal/g,"cn":"忠诚之肤 简易之袍"},
{"en":/Lioneye's Vision/g,"cn":"狮眼的视线 征战重铠"},
{"en":/Skin of the Lords/g,"cn":"君主之肤 简易之袍"},
{"en":/Voll's Protector/g,"cn":"福尔的战铠 圣语锁甲"},
{"en":/Lightbane Raiment/g,"cn":"魔道之衣 华丽环甲"},
{"en":/Cloak of Defiance/g,"cn":"卫道之袍 漆彩束衣"},
{"en":/The Restless Ward/g,"cn":"无尽之卫 禁礼之甲"},
{"en":/Seven-League Step/g,"cn":"盟誓之迹 生皮短靴"},
{"en":/Three-step Assault/g,"cn":"强袭者 粗革短靴"},
{"en":/Lochtonial Caress/g,"cn":"意识之缘 铁锻护手"},
{"en":/Atziri's Acuity/g,"cn":"阿兹里的捷思 瓦尔护手"},
{"en":/Flesh and Spirit/g,"cn":"肉体与魂灵 铁影手套"},
{"en":/Abberath's Horn/g,"cn":"艾贝拉斯之角 羊角法杖"},
{"en":/Arakaali's Fang/g,"cn":"阿拉卡力之牙 兽血短匕"},
{"en":/Advancing Fortress/g,"cn":"超越壁垒 裂脏钩"},
{"en":/Essentia Sanguis/g,"cn":"精华收割器 瓦尔战爪"},
{"en":/Fairgraves' Bearing/g,"cn":"费尔之仪 锈剑"},
{"en":/Prismatic Eclipse/g,"cn":"虹耀之月 暮光长剑"},
{"en":/Rigwald's Command/g,"cn":"瑞佛统帅 夜语长剑"},
{"en":/Cospri's Malice/g,"cn":"卡斯普里怨恨 宝饰细剑"},
{"en":/Bartek's Finger/g,"cn":"巴特克的魔指 朽木之棒"},
{"en":/The Supreme Truth/g,"cn":"无上箴言 水晶短杖"},
{"en":/Relic of the Cycle/g,"cn":"轮回之记 粗制弓"},
{"en":/The Searing Touch/g,"cn":"炽炎之使 武术长杖"},
{"en":/Taryn's Shiver/g,"cn":"塔林的颤栗之语 风暴长杖"},
{"en":/The Enmity Divine/g,"cn":"圣恶之喻 帝国长杖"},
{"en":/Ngamahu's Flame/g,"cn":"努葛玛呼之耀 深渊巨斧"},
{"en":/Thunder of the Dawn/g,"cn":"曙雷 锈斑巨剑"},
{"en":/Hrimnor's Dirge/g,"cn":"雷姆诺的挽歌 冷铁重锤"},
{"en":/Doedre's Damning/g,"cn":"德瑞的魔具 海灵戒指"},
{"en":/Perandus Signet/g,"cn":"普兰德斯之记 海灵戒指"},
{"en":/Lori's Lantern/g,"cn":"罗里的幸运之灯 三相戒指"},
{"en":/Berek's Grip/g,"cn":"贝雷克的冰与雷之曲 双玉戒指"},
{"en":/Berek's Pass/g,"cn":"贝雷克的冰与火之歌 双玉戒指"},
{"en":/Atziri's Foible/g,"cn":"阿兹里圣徽 海灵护身符"},
{"en":/Bisco's Collar/g,"cn":"比斯克的项圈 帝金护身符"},
{"en":/Eye of Chayula/g,"cn":"寻宝者的心眼 黑曜护身符"},
{"en":/Warped Timepiece/g,"cn":"时空扭曲 青玉护身符"},
{"en":/Extractor Mentis/g,"cn":"心灵抽取 玛瑙护身符"},
{"en":/Eye of Innocence/g,"cn":"无罪之眼 黄晶护身符"},
{"en":/Natural Hierarchy/g,"cn":"自然组织 死羽魔符"},
{"en":/Perandus Blazon/g,"cn":"普兰德斯之印 饰布腰带"},
{"en":/Vampire's Might/g,"cn":"吸血鬼的力量 赤红珠宝"},
{"en":/Ancient Waystones/g,"cn":"远古基石 赤红珠宝"},
{"en":/The Red Nightmare/g,"cn":"赤影梦魇 赤红珠宝"},
{"en":/Hidden Potential/g,"cn":"深藏的潜能 翠绿珠宝"},
{"en":/Omen on the Winds/g,"cn":"风之启示 翠绿珠宝"},
{"en":/Collateral Damage/g,"cn":"附带伤害 翠绿珠宝"},
{"en":/Straight and True/g,"cn":"直理之述 翠绿珠宝"},
{"en":/Spirited Response/g,"cn":"先祖回音 钴蓝珠宝"},
{"en":/Unstable Payload/g,"cn":"不稳定承载 钴蓝珠宝"},
{"en":/Whakawairua Tuahu/g,"cn":"禁闭祭坛 致命岩滩"},
{"en":/Farrul's Pounce/g,"cn":"大地之握 火蝮鳞手套"},
{"en":/Fenumus' Shroud/g,"cn":"暗夜弑衣 毒蛛丝之袍"},
{"en":/Fenumus' Toxins/g,"cn":"暗夜毒牙 操灵者之冠"},
{"en":/Darkness Enthroned/g,"cn":"夜临 深渊腰带"},
{"en":/Mutewind Pennant/g,"cn":"哑风尖旗 釉彩轻盾"},
{"en":/Atziri's Mirror/g,"cn":"阿兹里之镜 金阳轻盾"},
{"en":/Light of Lunaris/g,"cn":"月影之耀 灵相魔盾"},
{"en":/Demigod's Beacon/g,"cn":"升华之灯 黄金圣炎"},
{"en":/Geofri's Crest/g,"cn":"吉尔菲的荣光 强化巨盔"},
{"en":/The Broken Crown/g,"cn":"缺角帝冠 箴言战冠"},
{"en":/Speaker's Wreath/g,"cn":"众生指引 箴言战冠"},
{"en":/Wall of Brambles/g,"cn":"荆棘之墙 铁制背心"},
{"en":/The Perfect Form/g,"cn":"完美姿态 星辰皮甲"},
{"en":/Infernal Mantle/g,"cn":"炼狱之心 毒蛛丝之袍"},
{"en":/Inya's Epiphany/g,"cn":"茵雅的启蒙 秘术便鞋"},
{"en":/Demigod's Stride/g,"cn":"升华之途 黄金缠鞋"},
{"en":/Doryani's Fist/g,"cn":"多里亚尼之拳 瓦尔护手"},
{"en":/Sadima's Touch/g,"cn":"猎宝者的护手 羊毛手套"},
{"en":/Shadows and Dust/g,"cn":"沙尘之影 环带护手"},
{"en":/Amplification Rod/g,"cn":"增幅杖 螺纹法杖"},
{"en":/Shade of Solaris/g,"cn":"日耀之影 贤者法杖"},
{"en":/Celestial Fragment/g,"cn":"残星 玻璃利片"},
{"en":/Ungil's Gauche/g,"cn":"恩吉尔的叉刃 窃者短刃"},
{"en":/Izaro's Dilemma/g,"cn":"伊泽洛之谜 帝国战爪"},
{"en":/Touch of Anguish/g,"cn":"痛苦之触 帝国战爪"},
{"en":/The Screaming Eagle/g,"cn":"鹰啸 碎玉斧"},
{"en":/Lakishu's Blade/g,"cn":"拉奇许之刃 贵族之剑"},
{"en":/Severed in Sleep/g,"cn":"离异梦寐 军用长刃"},
{"en":/Galla's Riposte/g,"cn":"加拉的突刺刃 锈刺剑"},
{"en":/Nycta's Lantern/g,"cn":"奈可妲之灯 水晶短杖"},
{"en":/Xoph's Inception/g,"cn":"索伏的始源 骨制弓"},
{"en":/Lioneye's Glare/g,"cn":"狮眼的战弓 帝国之弓"},
{"en":/The Blood Reaper/g,"cn":"竭血之镰 行刑巨斧"},
{"en":/Wings of Entropy/g,"cn":"乱世之翼 裂甲巨斧"},
{"en":/Kitava's Feast/g,"cn":"奇塔弗之盛宴 虚影巨斧"},
{"en":/Oro's Sacrifice/g,"cn":"欧罗的贡品 狱炎重剑"},
{"en":/Song of the Sirens/g,"cn":"海妖魅曲 鱼竿"},
{"en":/Ngamahu's Sign/g,"cn":"努葛玛呼之印 红玉戒指"},
{"en":/Heartbound Loop/g,"cn":"结魂之环 月光石戒指"},
{"en":/Ascent From Flesh/g,"cn":"变节者 扣链腰带"},
{"en":/Demigod's Bounty/g,"cn":"升华珍宝 金羽腰带"},
{"en":/Asphyxia's Wrath/g,"cn":"冰灵之吼 双锋箭袋"},
{"en":/Rigwald's Quills/g,"cn":"瑞佛之羽 双锋箭袋"},
{"en":/Martial Artistry/g,"cn":"武艺之相 赤红珠宝"},
{"en":/Mantra of Flames/g,"cn":"烈炎之兆 赤红珠宝"},
{"en":/Rain of Splinters/g,"cn":"碎镞雨 赤红珠宝"},
{"en":/Zerphi's Youth/g,"cn":"泽佛伊的青春 赤红珠宝"},
{"en":/Energised Armour/g,"cn":"能量坚甲 赤红珠宝"},
{"en":/Izaro's Turmoil/g,"cn":"伊泽洛之乱 赤红珠宝"},
{"en":/Shattered Chains/g,"cn":"破碎之炼 赤红珠宝"},
{"en":/Emperor's Might/g,"cn":"帝王的霸权 赤红珠宝"},
{"en":/Primordial Might/g,"cn":"起源力量 赤红珠宝"},
{"en":/Overwhelming Odds/g,"cn":"压倒性 赤红珠宝"},
{"en":/Miser of Misery/g,"cn":"悲惨赐予者 翠绿珠宝"},
{"en":/Careful Planning/g,"cn":"审慎计划 翠绿珠宝"},
{"en":/Survival Secrets/g,"cn":"生存秘技 钴蓝珠宝"},
{"en":/Fortified Legion/g,"cn":"坚守军团 钴蓝珠宝"},
{"en":/Malicious Intent/g,"cn":"不善意图 钴蓝珠宝"},
{"en":/Assassin's Haste/g,"cn":"暗影之影 钴蓝珠宝"},
{"en":/Corrupted Energy/g,"cn":"腐化能量 钴蓝珠宝"},
{"en":/Reckless Defence/g,"cn":"鲁莽防御 钴蓝珠宝"},
{"en":/Poorjoy's Asylum/g,"cn":"沉沦之间 夺魂之殿"},
{"en":/Gorgon's Gaze/g,"cn":"葛尔贡的凝视 弑君之面"},
{"en":/Panquetzaliztli/g,"cn":"巨击之锤 狼牙重锤"},
{"en":/Saqawal's Flock/g,"cn":"苍空之翎 绸缎之兜"},
{"en":/Saqawal's Winds/g,"cn":"苍空之翼 战士手套"},
{"en":/The Dancing Duo/g,"cn":"杀孽戒刀 残暴巨剑"},
{"en":/Ahn's Contempt/g,"cn":"汉恩的蔑视 领主战冠"},
{"en":/Beltimber Blade/g,"cn":"芯木腰刀 永恒之剑"},
{"en":/The Golden Rule/g,"cn":"黄金法则 翠绿珠宝"},
{"en":/The Hungry Loop/g,"cn":"饥饿之环 潜能之戒"},
{"en":/The Long Winter/g,"cn":"凛冽寒冬 钴蓝珠宝"},
{"en":/Trolltimber Spire/g,"cn":"巫木 松木塔盾"},
{"en":/Redblade Banner/g,"cn":"红刃旗帜 彩绘塔盾"},
{"en":/The Anticipation/g,"cn":"悬念 艾兹麦塔盾"},
{"en":/Ahn's Heritage/g,"cn":"汉恩的遗产 巨型塔盾"},
{"en":/Prism Guardian/g,"cn":"元素的庇护 威能鸢盾"},
{"en":/Crown of Thorns/g,"cn":"刺棘之冠 藤蔓之冠"},
{"en":/Doedre's Scorn/g,"cn":"德瑞的蔑视 月影之冠"},
{"en":/Chitus' Apex/g,"cn":"切特斯的威权 操灵者之冠"},
{"en":/Black Sun Crest/g,"cn":"黑阳之冠 漆彩之盔"},
{"en":/The Brine Crown/g,"cn":"海王冠冕 箴言战冠"},
{"en":/Greed's Embrace/g,"cn":"贪婪之拥 金耀之铠"},
{"en":/Dewath's Hide/g,"cn":"德瓦斯的匿踪 鹿皮外套"},
{"en":/Cospri's Will/g,"cn":"卡斯普里意志 暗影之装"},
{"en":/Gruthkul's Pelt/g,"cn":"欺诈獠牙 龙鳞战甲"},
{"en":/Ambu's Charge/g,"cn":"安姆布的战甲 圣战锁甲"},
{"en":/Kaom's Roots/g,"cn":"冈姆的稳重之靴 巨人胫甲"},
{"en":/Abberath's Hooves/g,"cn":"地动 羊皮短靴"},
{"en":/Atziri's Step/g,"cn":"阿兹里的金履 迷踪短靴"},
{"en":/Lioneye's Paws/g,"cn":"狮眼的斗志 铜影长靴"},
{"en":/Nomic's Storm/g,"cn":"诺米克的风暴 扣环短靴"},
{"en":/Winds of Change/g,"cn":"升华之风 远古护手"},
{"en":/Demigod's Touch/g,"cn":"升华之指 黄金臂甲"},
{"en":/Reverberation Rod/g,"cn":"混响 螺纹法杖"},
{"en":/Relentless Fury/g,"cn":"无尽愤怒 富贵之斧"},
{"en":/Moonbender's Wing/g,"cn":"月岚 征战之斧"},
{"en":/Jack, the Axe/g,"cn":"刽子手.杰克 瓦尔战斧"},
{"en":/United in Dream/g,"cn":"合流梦寐 军用长刃"},
{"en":/Innsbury Edge/g,"cn":"英斯贝理之极 智者长剑"},
{"en":/Chitus' Needle/g,"cn":"切特斯之针 贵族细剑"},
{"en":/Axiom Perpetuum/g,"cn":"历史公理 铜锻短杖"},
{"en":/Xoph's Nurture/g,"cn":"索伏的爱抚 城塞战弓"},
{"en":/Xirgil's Crank/g,"cn":"舍吉的手柄 强化长杖"},
{"en":/Sire of Shards/g,"cn":"破碎传承者 蛇纹长杖"},
{"en":/Agnerod North/g,"cn":"北方雷霆圣杖 帝国长杖"},
{"en":/Agnerod South/g,"cn":"南方雷霆圣杖 帝国长杖"},
{"en":/Kaom's Primacy/g,"cn":"冈姆的霸业 卡鲁巨斧"},
{"en":/Edge of Madness/g,"cn":"疯狂边界 术雕巨剑"},
{"en":/Kondo's Pride/g,"cn":"刚多的虚荣 艾兹麦巨剑"},
{"en":/Sibyl's Lament/g,"cn":"希比尔之叹 珊瑚戒指"},
{"en":/Ventor's Gamble/g,"cn":"赌神芬多 金光戒指"},
{"en":/Dream Fragments/g,"cn":"梦语之痕 蓝玉戒指"},
{"en":/Tasalio's Sign/g,"cn":"塔萨里之印 蓝玉戒指"},
{"en":/Mokou's Embrace/g,"cn":"莫考之拥 红玉戒指"},
{"en":/Rigwald's Crest/g,"cn":"瑞佛之冠 双玉戒指"},
{"en":/Ngamahu Tiki/g,"cn":"努葛玛呼之像 珊瑚护身符"},
{"en":/The Pandemonius/g,"cn":"群魔殿 翠玉护身符"},
{"en":/Tear of Purity/g,"cn":"纯净之泪 海玉护身符"},
{"en":/Frost Unbroken/g,"cn":"不灭冰晶 帝金护身符"},
{"en":/Shaper's Seed/g,"cn":"塑界者之籽 玛瑙护身符"},
{"en":/Rigwald's Curse/g,"cn":"瑞佛诅咒 亡爪魔符"},
{"en":/Dyadian Dawn/g,"cn":"戴亚迪安的晨曦 重革腰带"},
{"en":/Bisco's Leash/g,"cn":"比斯克的缰绳 重革腰带"},
{"en":/Hyrri's Bite/g,"cn":"西里的嗜血之矢 鲨齿箭袋"},
{"en":/Survival Skills/g,"cn":"生存技巧 赤红珠宝"},
{"en":/Atziri's Reign/g,"cn":"阿兹里之权 赤红珠宝"},
{"en":/Warlord's Reach/g,"cn":"督军之力 赤红珠宝"},
{"en":/Rapid Expansion/g,"cn":"急速扩张 赤红珠宝"},
{"en":/Underdog's Fury/g,"cn":"逆行之怒 赤红珠宝"},
{"en":/Lioneye's Fall/g,"cn":"狮眼的陨落 翠绿珠宝"},
{"en":/Poacher's Aim/g,"cn":"盗猎者的准心 翠绿珠宝"},
{"en":/The Green Dream/g,"cn":"青影梦境 翠绿珠宝"},
{"en":/Sudden Ignition/g,"cn":"突然点火 翠绿珠宝"},
{"en":/Vaal Sentencing/g,"cn":"瓦尔之诉 钴蓝珠宝"},
{"en":/Brittle Barrier/g,"cn":"易碎屏障 钴蓝珠宝"},
{"en":/Winter's Bounty/g,"cn":"冬季赏金 钴蓝珠宝"},
{"en":/Unending Hunger/g,"cn":"无尽渴望 钴蓝珠宝"},
{"en":/Boundless Grasp/g,"cn":"无边紧握 钴蓝珠宝"},
{"en":/Hallowed Ground/g,"cn":"魔诅之域 堕影墓场"},
{"en":/Olmec's Sanctum/g,"cn":"远古之印 黑石陵墓"},
{"en":/Death and Taxes/g,"cn":"亡者之财 魔影墓场"},
{"en":/Farrul's Chase/g,"cn":"大地之痕 迷踪短靴"},
{"en":/Fenumus' Weave/g,"cn":"暗夜织礼 禁礼护手"},
{"en":/Hyrri's Demise/g,"cn":"西里之逝 鲨齿箭袋"},
{"en":/Saqawal's Nest/g,"cn":"苍空之巢 血色之衣"},
{"en":/Bubonic Trail/g,"cn":"鼠疫之源 暗影者长靴"},
{"en":/Cyclopean Coil/g,"cn":"巨岩指套 皮革腰带"},
{"en":/Doedre's Skin/g,"cn":"德瑞之肤 毒蛛丝之袍"},
{"en":/Grelwood Shank/g,"cn":"韧木曲刃 永恒之剑"},
{"en":/Invictus Solaris/g,"cn":"耀日 威能鸢盾"},
{"en":/Magna Eclipsis/g,"cn":"坚毅之食 坚毅塔盾"},
{"en":/The Poet's Pen/g,"cn":"诗人之笔 粗纹法杖"},
{"en":/Rathpith Globe/g,"cn":"献祭之心 巨人魔盾"},
{"en":/Tear of Entropy/g,"cn":"乱世之泪 粗铁盔"},
{"en":/Ahn's Contempt/g,"cn":"汉恩的蔑视 粗铁盔"},
{"en":/Martyr's Crown/g,"cn":"烈士之冠 藤蔓之冠"},
{"en":/The Peregrine/g,"cn":"疾风的沉思 清视护盔"},
{"en":/Voll's Vision/g,"cn":"福尔的远见 领主战冠"},
{"en":/Heretic's Veil/g,"cn":"异教面纱 弑神之面"},
{"en":/The Brass Dome/g,"cn":"巨铜之顶 角斗重铠"},
{"en":/Bronn's Lithe/g,"cn":"布隆的影衣 死神之装"},
{"en":/Thousand Ribbons/g,"cn":"千缎 简易之袍"},
{"en":/Cloak of Flame/g,"cn":"烈炎之袍 学者之袍"},
{"en":/Viper's Scales/g,"cn":"毒蛇之度 连身鳞甲"},
{"en":/Empire's Grasp/g,"cn":"帝国之掌 巨灵护手"},
{"en":/Deadman's Hand/g,"cn":"枯萎之手 钢影护手"},
{"en":/Shaper's Touch/g,"cn":"塑界之触 圣战手套"},
{"en":/Ondar's Clasp/g,"cn":"恩德的迅影 裹趾护手"},
{"en":/Midnight Bargain/g,"cn":"冥约 符文法杖"},
{"en":/Ashes of the Sun/g,"cn":"烬杵 朽木之棒"},
{"en":/Cameria's Maul/g,"cn":"卡美利亚之锤 坚锤"},
{"en":/Iron Commander/g,"cn":"钢铁指挥 死亡之弓"},
{"en":/Borrowed Power/g,"cn":"力量借贷 朽木之干"},
{"en":/The Stormheart/g,"cn":"风暴之眼 皇家长杖"},
{"en":/Agnerod East/g,"cn":"东方雷霆圣杖 帝国长杖"},
{"en":/Agnerod West/g,"cn":"西方雷霆圣杖 帝国长杖"},
{"en":/Hegemony's Era/g,"cn":"霸权时代 审判长杖"},
{"en":/Queen's Decree/g,"cn":"威严之刃 名贵巨剑"},
{"en":/Queen's Escape/g,"cn":"逃亡女王 名贵巨剑"},
{"en":/Marohi Erqi/g,"cn":"尔奇的巨灵之锤 卡鲁重锤"},
{"en":/Le Heup of All/g,"cn":"英灵宝环 锻铁戒指"},
{"en":/Valako's Sign/g,"cn":"瓦拉库之印 黄玉戒指"},
{"en":/Gifts from Above/g,"cn":"神赐 宝钻戒指"},
{"en":/Angler's Plait/g,"cn":"渔夫之辫 潜能之戒"},
{"en":/Carnage Heart/g,"cn":"屠戮之心 黑曜护身符"},
{"en":/Chains of Time/g,"cn":"时空之链 素布腰带"},
{"en":/Witchfire Brew/g,"cn":"巫酿之水 迷雾药剂"},
{"en":/Sin's Rebirth/g,"cn":"再生的罪恶 迷雾药剂"},
{"en":/Fragile Bloom/g,"cn":"脆弱的繁华 赤红珠宝"},
{"en":/Grand Spectrum/g,"cn":"聚光之石 赤红珠宝"},
{"en":/Grand Spectrum/g,"cn":"聚光之石 翠绿珠宝"},
{"en":/Grand Spectrum/g,"cn":"聚光之石 钴蓝珠宝"},
{"en":/Intuitive Leap/g,"cn":"直觉之跃 翠绿珠宝"},
{"en":/Weight of Sin/g,"cn":"罪恶的重量 翠绿珠宝"},
{"en":/Pitch Darkness/g,"cn":"黯黑之调 翠绿珠宝"},
{"en":/Ring of Blades/g,"cn":"利刃戒指 翠绿珠宝"},
{"en":/Mutated Growth/g,"cn":"堕落异体 钴蓝珠宝"},
{"en":/Rolling Flames/g,"cn":"滚动烈焰 钴蓝珠宝"},
{"en":/Dead Reckoning/g,"cn":"死亡清算 钴蓝珠宝"},
{"en":/Emperor's Wit/g,"cn":"帝王的智慧 钴蓝珠宝"},
{"en":/The Blue Dream/g,"cn":"碧影梦境 钴蓝珠宝"},
{"en":/The Anima Stone/g,"cn":"聚魂石 三相珠宝"},
{"en":/Cagan's Map/g,"cn":"卡甘的奥秘之地 寂静陵墓"},
{"en":/The Beachhead/g,"cn":"降临之地 先驱者地图"},
{"en":/Crystal Vault/g,"cn":"水晶墓穴 精制环甲"},
{"en":/Disintegrator/g,"cn":"裂世轮回 风暴长杖"},
{"en":/Farrul's Bite/g,"cn":"大地之牙 鹰喙之面"},
{"en":/Fox's Fortune/g,"cn":"狐运强铠 野性皮甲"},
{"en":/The Stormwall/g,"cn":"风暴坚壁 皇家长杖"},
{"en":/The Tactician/g,"cn":"谋士之环 扣钉腰带"},
{"en":/Voidfletcher/g,"cn":"虚空制箭者 穿射箭袋"},
{"en":/Leper's Alms/g,"cn":"临死的施舍 钢镜刺盾"},
{"en":/Lightpoacher/g,"cn":"光明偷猎者 强化巨盔"},
{"en":/Watcher's Eye/g,"cn":"守望之眼 三相珠宝"},
{"en":/The Signal Fire/g,"cn":"狼烟 火灵箭袋"},
{"en":/Malachai's Loop/g,"cn":"轮回 和谐魔盾"},
{"en":/Jaws of Agony/g,"cn":"苦痛狂鲨 霸者刺盾"},
{"en":/Ezomyte Peak/g,"cn":"艾兹麦的荣光 粗铁盔"},
{"en":/Crown of Eyes/g,"cn":"邪眼之冠 灵主之环"},
{"en":/Veil of the Night/g,"cn":"夜幕 巨盔"},
{"en":/Solaris Lorica/g,"cn":"烈阳铠 铜锻板甲"},
{"en":/Kaom's Heart/g,"cn":"冈姆的壮志 荣耀战铠"},
{"en":/Tinkerskin/g,"cn":"钟表匠的华服 狂虐者束衣"},
{"en":/The Red Trail/g,"cn":"赤红踪迹 巨人胫甲"},
{"en":/The Blood Dance/g,"cn":"血影 鲨皮短靴"},
{"en":/Bones of Ullr/g,"cn":"灵骸之履 丝绸便鞋"},
{"en":/Darkray Vectors/g,"cn":"暗雷 龙鳞长靴"},
{"en":/Eclipse Solaris/g,"cn":"宇蚀 水晶法杖"},
{"en":/Leviathan Ivory/g,"cn":"神力之牙 拳钉"},
{"en":/Cybil's Paw/g,"cn":"希比尔的冰爪 撕裂尖爪"},
{"en":/Boreal Shepherd/g,"cn":"牧者之音 锈斧"},
{"en":/Blood of Summer/g,"cn":"炎夏之血 锈剑"},
{"en":/Hyaon's Fury/g,"cn":"海昂的狂怒 军团长剑"},
{"en":/Ewar's Mirage/g,"cn":"伊沃幻像 古代细剑"},
{"en":/The Dark Seer/g,"cn":"黯黑贤者 影语短杖"},
{"en":/Nuro's Harp/g,"cn":"努罗的竖琴 先驱者之弓"},
{"en":/Slivertongue/g,"cn":"白银之舌 先驱者之弓"},
{"en":/The Blood Thorn/g,"cn":"血棘 朽木之干"},
{"en":/Pledge of Hands/g,"cn":"誓约 审判长杖"},
{"en":/Chober Chaber/g,"cn":"忠诚之锤 刚猛巨锤"},
{"en":/Gang's Momentum/g,"cn":"刚勇 军团长靴"},
{"en":/Thief's Torment/g,"cn":"窃罪 三相戒指"},
{"en":/Ming's Heart/g,"cn":"明恩的慧心 紫晶戒指"},
{"en":/Redblade Band/g,"cn":"红刃之环 潜能之戒"},
{"en":/Mutewind Seal/g,"cn":"哑风封印 潜能之戒"},
{"en":/Xoph's Heart/g,"cn":"索伏之心 琥珀护身符"},
{"en":/Xoph's Blood/g,"cn":"索伏之血 琥珀护身符"},
{"en":/Karui Charge/g,"cn":"卡鲁充能 翠玉护身符"},
{"en":/The Aylardex/g,"cn":"埃拉黛丝 玛瑙护身符"},
{"en":/Forbidden Taste/g,"cn":"禁果 石英药剂"},
{"en":/The Wise Oak/g,"cn":"聪明的欧克 灰岩药剂"},
{"en":/The Signal Fire/g,"cn":"狼烟 火焰箭袋"},
{"en":/Blood Sacrifice/g,"cn":"血牺 赤红珠宝"},
{"en":/Coated Shrapnel/g,"cn":"榴星 赤红珠宝"},
{"en":/The Red Dream/g,"cn":"赤影梦境 赤红珠宝"},
{"en":/Spirit Guards/g,"cn":"精神守护 翠绿珠宝"},
{"en":/Growing Agony/g,"cn":"茁壮苦痛 翠绿珠宝"},
{"en":/Violent Dead/g,"cn":"暴力的死者 钴蓝珠宝"},
{"en":/Inevitability/g,"cn":"不可避免 钴蓝珠宝"},
{"en":/Spreading Rot/g,"cn":"腐烂扩散 钴蓝珠宝"},
{"en":/Farrul's Fur/g,"cn":"大地之护 胜利盔甲"},
{"en":/Sanguine Gambol/g,"cn":"雀跃 剥皮刀"},
{"en":/The Effigon/g,"cn":"耀阳徽记 帝金护身符"},
{"en":/Ahn's Might/g,"cn":"汉恩的力量 夜语长剑"},
{"en":/Hopeshredder/g,"cn":"破灭之希 漫游之弓"},
{"en":/Memory Vault/g,"cn":"记忆囚笼 领主战冠"},
{"en":/Stormcharger/g,"cn":"风暴骑士 坚铁胫甲"},
{"en":/The Surrender/g,"cn":"降伏 艾兹麦塔盾"},
{"en":/Death Rattle/g,"cn":"亡灵之音 残枝魔盾"},
{"en":/Matua Tupuna/g,"cn":"远祖之颅 环形魔盾"},
{"en":/Esh's Mirror/g,"cn":"艾许之镜 暗金魔盾"},
{"en":/Esh's Visage/g,"cn":"艾许之面 瓦尔魔盾"},
{"en":/Aegis Aurora/g,"cn":"幻芒圣盾 斗士鸢盾"},
{"en":/Broken Faith/g,"cn":"破碎信念 威能鸢盾"},
{"en":/Ezomyte Hold/g,"cn":"艾兹麦之握 粗铁盔"},
{"en":/Alpha's Howl/g,"cn":"极地之眼 罪者之帽"},
{"en":/Scold's Bridle/g,"cn":"禁语 灵能之笼"},
{"en":/Death's Oath/g,"cn":"冥使之体 星芒战铠"},
{"en":/The Rat Cage/g,"cn":"疫鼠囚笼 鲨皮之衣"},
{"en":/Hyrri's Ire/g,"cn":"西里的战衣 星辰皮甲"},
{"en":/Lightning Coil/g,"cn":"雷语 荒野锁铠"},
{"en":/Carcass Jack/g,"cn":"致命之体 映彩外套"},
{"en":/Steppan Eard/g,"cn":"绝地魔履 术士长靴"},
{"en":/Death's Door/g,"cn":"死亡大门 圣战长靴"},
{"en":/Slitherpinch/g,"cn":"苍蟒之鳞 铜影手套"},
{"en":/Vaal Caress/g,"cn":"瓦尔的灵手 铜影手套"},
{"en":/Surgebinders/g,"cn":"浪涌缚者 龙鳞手套"},
{"en":/Storm Prison/g,"cn":"禁锢暴风 粗纹法杖"},
{"en":/Void Battery/g,"cn":"潜能魔棒 箴言法杖"},
{"en":/Mortem Morsu/g,"cn":"噬魂之牙 恐惧之爪"},
{"en":/The Wasp Nest/g,"cn":"蜂巢涌动 刺喉刃"},
{"en":/Ephemeral Edge/g,"cn":"影殒 暮色之刃"},
{"en":/Dreamfeather/g,"cn":"幻梦飞羽 永恒之剑"},
{"en":/Ahn's Might/g,"cn":"汉恩的力量 夜语长剑"},
{"en":/Death's Hand/g,"cn":"死神之手 卡鲁短杖"},
{"en":/Doon Cuebiyari/g,"cn":"黑钢 瓦尔短杖"},
{"en":/Death's Harp/g,"cn":"冥使之琴 死亡之弓"},
{"en":/Death's Opus/g,"cn":"死亡之作 死亡之弓"},
{"en":/Dying Breath/g,"cn":"幽魂之息 铁锻长杖"},
{"en":/Debeon's Dirge/g,"cn":"战歌 霸主巨斧"},
{"en":/Terminus Est/g,"cn":"行刑之刃 虎牙巨剑"},
{"en":/Brain Rattler/g,"cn":"脑乱者 戮魂重锤"},
{"en":/Tidebreaker/g,"cn":"局势逆转者 帝国重锤"},
{"en":/Kaom's Sign/g,"cn":"冈姆的远见 珊瑚戒指"},
{"en":/Essence Worm/g,"cn":"菁华蠕虫 潜能之戒"},
{"en":/Sidhebreath/g,"cn":"魔灵之符 海灵护身符"},
{"en":/Karui Ward/g,"cn":"卡鲁的战徽 翠玉护身符"},
{"en":/The Ignomon/g,"cn":"烈阳徽记 帝金护身符"},
{"en":/Astramentis/g,"cn":"均衡之符 黑曜护身符"},
{"en":/Immortal Flesh/g,"cn":"永生 皮革腰带"},
{"en":/Perseverance/g,"cn":"恒毅意志 先锋腰带"},
{"en":/Saemus' Gift/g,"cn":"勇者之礼 刺锋箭袋"},
{"en":/Spire of Stone/g,"cn":"石塔 赤红珠宝"},
{"en":/Fluid Motion/g,"cn":"流畅行动 翠绿珠宝"},
{"en":/Hungry Abyss/g,"cn":"饥馑深渊 翠绿珠宝"},
{"en":/Steel Spirit/g,"cn":"坚毅心灵 翠绿珠宝"},
{"en":/Hair Trigger/g,"cn":"发闸机关 翠绿珠宝"},
{"en":/Fertile Mind/g,"cn":"丰富心灵 钴蓝珠宝"},
{"en":/Fevered Mind/g,"cn":"狂热之心 钴蓝珠宝"},
{"en":/Healthy Mind/g,"cn":"灵体转换 钴蓝珠宝"},
{"en":/Frozen Trail/g,"cn":"冰冻痕迹 钴蓝珠宝"},
{"en":/Winterweave/g,"cn":"冬日之织 珊瑚戒指"},
{"en":/Soul's Wick/g,"cn":"灵魂之芯 钴蓝珠宝"},
{"en":/Tabula Rasa/g,"cn":"无尽之衣 简易之袍"},
{"en":/Honourhome/g,"cn":"私欲的光辉 士兵之盔"},
{"en":/Bramblejack/g,"cn":"刺棘宝甲 铁制背心"},
{"en":/Soul Mantle/g,"cn":"祖灵之约 蛛丝之袍"},
{"en":/Rumblemarch/g,"cn":"不羁之行 铁锻胫甲"},
{"en":/Rainbowstride/g,"cn":"虹幕 咒者长靴"},
{"en":/Voidwalker/g,"cn":"虚空行者 暗影者长靴"},
{"en":/Voidbringer/g,"cn":"虚空之力 咒者手套"},
{"en":/Allelopathy/g,"cn":"相生相克 术士手套"},
{"en":/The Embalmer/g,"cn":"入殓师 禁礼护手"},
{"en":/Thunderfist/g,"cn":"轰天雷 暗影者护手"},
{"en":/Apep's Rage/g,"cn":"艾普之怒 灵石法杖"},
{"en":/Heartbreaker/g,"cn":"裂心刃 皇家短匕"},
{"en":/Flesh-Eater/g,"cn":"血肉之嗜 梦境之锤"},
{"en":/Disjunction/g,"cn":"分裂析取 朽木短杖"},
{"en":/Silverbranch/g,"cn":"幻银之弦 粗制弓"},
{"en":/Roth's Reach/g,"cn":"萝丝之触 反曲弓"},
{"en":/Voltaxic Rift/g,"cn":"魔暴之痕 脊弓"},
{"en":/Realm Ender/g,"cn":"魂界终结 铁锻长杖"},
{"en":/The Cauteriser/g,"cn":"烧灼器 柴斧"},
{"en":/Null and Void/g,"cn":"虚空 军团手套"},
{"en":/Demigod's Eye/g,"cn":"升华之眼 金环"},
{"en":/Araku Tiki/g,"cn":"隐灵之符 珊瑚护身符"},
{"en":/Winterheart/g,"cn":"冬之心 帝金护身符"},
{"en":/Wurm's Molt/g,"cn":"龙蜕之带 皮革腰带"},
{"en":/Soul Tether/g,"cn":"灵魂羁绊 饰布腰带"},
{"en":/The Magnate/g,"cn":"坚毅之环 扣钉腰带"},
{"en":/Taste of Hate/g,"cn":"恨意 蓝玉药剂"},
{"en":/Lion's Roar/g,"cn":"狮吼精华 坚岩药剂"},
{"en":/Broadstroke/g,"cn":"疾袭之锋 重矢箭袋"},
{"en":/Soul Strike/g,"cn":"灵魂打击 刺锋箭袋"},
{"en":/Winter Burial/g,"cn":"冬葬 赤红珠宝"},
{"en":/Volley Fire/g,"cn":"怒火齐发 翠绿珠宝"},
{"en":/Choking Ash/g,"cn":"窒息之烬 翠绿珠宝"},
{"en":/Powerlessness/g,"cn":"无力 钴蓝珠宝"},
{"en":/Duskblight/g,"cn":"恐怖巨镰 铁影长靴"},
{"en":/Stormfire/g,"cn":"风暴之炎 蛋白石戒指"},
{"en":/Timetwist/g,"cn":"时空扭曲 月光石戒指"},
{"en":/Giantsbane/g,"cn":"巨灵灾星 青铜护手"},
{"en":/Gloomfang/g,"cn":"昏暗之牙 碧珠护身符"},
{"en":/Iron Heart/g,"cn":"钢铁之心 征战重铠"},
{"en":/White Wind/g,"cn":"白净之风 帝国短匕"},
{"en":/Wraithlord/g,"cn":"幽冥灵王 灵骨之冠"},
{"en":/Blackgleam/g,"cn":"黑炎之芒 火灵箭袋"},
{"en":/Kaltenhalt/g,"cn":"冰霜之镜 彩绘轻盾"},
{"en":/Kaltensoul/g,"cn":"冰霜之魂 彩绘轻盾"},
{"en":/Springleaf/g,"cn":"新生之徽 朽木鸢盾"},
{"en":/Glitterdisc/g,"cn":"七彩碟 冷芒刺盾"},
{"en":/Obscurantis/g,"cn":"厌食者 狮首皮盔"},
{"en":/Rime Gaze/g,"cn":"酷寒的凝视 灵能之笼"},
{"en":/Spiritskin/g,"cn":"精灵皮肤 权贵环甲"},
{"en":/The Covenant/g,"cn":"血誓 蛛丝之袍"},
{"en":/Kingsguard/g,"cn":"皇家卫甲 征战锁甲"},
{"en":/Dendrobate/g,"cn":"箭丽毒蛙 哨兵之衣"},
{"en":/Windscream/g,"cn":"恶风足迹 强化胫甲"},
{"en":/Wanderlust/g,"cn":"苦行之履 羊毛之鞋"},
{"en":/Wondertrap/g,"cn":"回光之迹 丝绒便鞋"},
{"en":/Hrimsorrow/g,"cn":"冰冷之眼 羊皮手套"},
{"en":/Haemophilia/g,"cn":"血友病 蛇鳞手套"},
{"en":/Repentance/g,"cn":"悔悟之掌 圣战手套"},
{"en":/Facebreaker/g,"cn":"毁面者 扣环护手"},
{"en":/Obliteration/g,"cn":"抹灭 魔角法杖"},
{"en":/Divinarius/g,"cn":"戒律之影 帝国短匕"},
{"en":/Scar of Fate/g,"cn":"命运伤痕 拳钉"},
{"en":/Bloodseeker/g,"cn":"嗜血之爪 魔爪刃"},
{"en":/Rust of Winter/g,"cn":"霜刃 锈斧"},
{"en":/Pagan Geis/g,"cn":"异宗之镜 朽木短杖"},
{"en":/Tremor Rod/g,"cn":"颤抖之杖 军用长杖"},
{"en":/The Harvest/g,"cn":"收割者 灵玉巨斧"},
{"en":/Blackheart/g,"cn":"幽暗之语 锻铁戒指"},
{"en":/Kaom's Way/g,"cn":"冈姆之路 珊瑚戒指"},
{"en":/The Taming/g,"cn":"元素之章 三相戒指"},
{"en":/Timeclasp/g,"cn":"时光之握 月光石戒指"},
{"en":/Death Rush/g,"cn":"亡者呼唤 紫晶戒指"},
{"en":/Bloodgrip/g,"cn":"鲜血支配 珊瑚护身符"},
{"en":/The Anvil/g,"cn":"信念之砧 琥珀护身符"},
{"en":/The Halcyon/g,"cn":"太平 翠玉护身符"},
{"en":/The Rathorn/g,"cn":"咒荆 海玉护身符"},
{"en":/The Ascetic/g,"cn":"苦行 帝金护身符"},
{"en":/Night's Hold/g,"cn":"夜守 黑牙魔符"},
{"en":/Prismweave/g,"cn":"幻彩菱织 素布腰带"},
{"en":/Faminebind/g,"cn":"饥荒之结 素布腰带"},
{"en":/Bated Breath/g,"cn":"凝息 扣链腰带"},
{"en":/Blackgleam/g,"cn":"黑炎之芒 火焰箭袋"},
{"en":/Combustibles/g,"cn":"燃尽 赤红珠宝"},
{"en":/Loreweave/g,"cn":"满溢之甲 权贵环甲"},
{"en":/Dreadsurge/g,"cn":"恐惧利刃 切割者"},
{"en":/Greedtrap/g,"cn":"贪婪之诱 丝绒便鞋"},
{"en":/The Nomad/g,"cn":"游牧之环 扣钉腰带"},
{"en":/Bloodbond/g,"cn":"血脉相连 骨制战甲"},
{"en":/Impresence/g,"cn":"隐逝 黑曜护身符"},
{"en":/Oni-Goroshi/g,"cn":"鬼弑 查兰之剑"},
{"en":/Pure Talent/g,"cn":"纯才 翠绿珠宝"},
{"en":/Shimmeron/g,"cn":"低伏暗光 狂风法杖"},
{"en":/Vix Lunaris/g,"cn":"影月 祭者圆盾"},
{"en":/Skullhead/g,"cn":"光辉之颅 精兵之盔"},
{"en":/Leer Cast/g,"cn":"共鸣之面 节庆之面"},
{"en":/Vis Mortis/g,"cn":"兀鸣 操灵者背心"},
{"en":/Deerstalker/g,"cn":"猎踪 鹿皮短靴"},
{"en":/Lifesprig/g,"cn":"生机之记 朽木法杖"},
{"en":/Ashcaller/g,"cn":"灰烬行者 石英法杖"},
{"en":/Bloodletter/g,"cn":"血书 玻璃利片"},
{"en":/Mightflay/g,"cn":"力量猎刃 残体利刃"},
{"en":/The Scourge/g,"cn":"灾害 恐惧之牙"},
{"en":/The Princess/g,"cn":"女爵 旧军刀"},
{"en":/Aurumvorax/g,"cn":"灵护 练武者细剑"},
{"en":/Gorebreaker/g,"cn":"血裂 钝钉木棒"},
{"en":/Frostbreath/g,"cn":"霜息 华丽之锤"},
{"en":/Bitterdream/g,"cn":"苦梦 影语短杖"},
{"en":/Singularity/g,"cn":"奇异 白金短杖"},
{"en":/Storm Cloud/g,"cn":"暴雨之弦 长弓"},
{"en":/Realmshaper/g,"cn":"创域 铁锻长杖"},
{"en":/Kingmaker/g,"cn":"王者之刃 霸主巨斧"},
{"en":/Doomsower/g,"cn":"终末之始 狮爪巨剑"},
{"en":/Quecholli/g,"cn":"重击之锤 狼牙重锤"},
{"en":/Voidheart/g,"cn":"虚空心灵 锻铁戒指"},
{"en":/Andvarius/g,"cn":"贪欲之记 金光戒指"},
{"en":/Emberwake/g,"cn":"余烬之痕 红玉戒指"},
{"en":/Feastbind/g,"cn":"盛宴之结 素布腰带"},
{"en":/Rearguard/g,"cn":"寒锋之卫 宽矢箭袋"},
{"en":/The Vigil/g,"cn":"监视守夜 赤红珠宝"},
{"en":/Apparitions/g,"cn":"映像 翠绿珠宝"},
{"en":/Specialised/g,"cn":"熟稔 翠绿珠宝"},
{"en":/From Dust/g,"cn":"尘土归来 钴蓝珠宝"},
{"en":/BlackGuardz/g,"cn":"乌卫 激战柱廊"},
{"en":/Voidforge/g,"cn":"裂空者 狱炎重剑"},
{"en":/Wildwrap/g,"cn":"荒野之绕 扣环皮甲"},
{"en":/Windshriek/g,"cn":"风哮 强化胫甲"},
{"en":/Balefire/g,"cn":"灾难之光 灵石短杖"},
{"en":/Nebuloch/g,"cn":"尼布洛克 梦魇之锤"},
{"en":/Vulconus/g,"cn":"火神锻台 魔灵短匕"},
{"en":/Alkem Eira/g,"cn":"神谕 椴木鸢盾"},
{"en":/Abyssus/g,"cn":"深渊之唤 艾兹麦坚盔"},
{"en":/Rat's Nest/g,"cn":"鼠巢 熊首皮盔"},
{"en":/Deidbellow/g,"cn":"丧吼 金面护盔"},
{"en":/Mindspiral/g,"cn":"灵漩 战意之盔"},
{"en":/The Vertex/g,"cn":"谜容 瓦尔之面"},
{"en":/Kintsugi/g,"cn":"金珏之缮 精制皮甲"},
{"en":/Ghostmarch/g,"cn":"鬼行 铁锻胫甲"},
{"en":/Goldwyrm/g,"cn":"龙炎足迹 砂影短靴"},
{"en":/Sin Trek/g,"cn":"敏锐思维 匿踪短靴"},
{"en":/Aurseize/g,"cn":"富贵之运 钢影护手"},
{"en":/Wyrmsign/g,"cn":"龙族印记 蝮鳞手套"},
{"en":/Southbound/g,"cn":"南方 战士手套"},
{"en":/Stormblast/g,"cn":"雷暴 朽木法杖"},
{"en":/Moonsorrow/g,"cn":"泣月 魔性法杖"},
{"en":/Widowmaker/g,"cn":"寡妇 窃者短匕"},
{"en":/The Gryphon/g,"cn":"狮鹫 碎玉斧"},
{"en":/Soul Taker/g,"cn":"开膛斧 破城斧"},
{"en":/Ichimonji/g,"cn":"一文字 海贼长刀"},
{"en":/Varunastra/g,"cn":"黑鲨 瓦尔军刃"},
{"en":/Brightbeak/g,"cn":"光耀之锤 战锤"},
{"en":/Clayshaper/g,"cn":"塑泥者 破岩锤"},
{"en":/Silverbough/g,"cn":"银枝 粗制弓"},
{"en":/Quill Rain/g,"cn":"骤雨之弦 短弓"},
{"en":/The Tempest/g,"cn":"暴风雨 长弓"},
{"en":/Doomfletch/g,"cn":"灭世 皇家猎弓"},
{"en":/Windripper/g,"cn":"裂风 帝国之弓"},
{"en":/Darkscorn/g,"cn":"夜吟 马拉克斯弓"},
{"en":/Shiversting/g,"cn":"寒光剑 重剑"},
{"en":/Starforge/g,"cn":"塑星者 狱炎重剑"},
{"en":/Voidhome/g,"cn":"逝空之锤 威权巨锤"},
{"en":/Kikazaru/g,"cn":"基加萨鲁 黄玉戒指"},
{"en":/Valyrium/g,"cn":"女武神 月光石戒指"},
{"en":/The Pariah/g,"cn":"草民 潜能之戒"},
{"en":/Blightwell/g,"cn":"枯井 咒箍魔符"},
{"en":/Headhunter/g,"cn":"猎首 皮革腰带"},
{"en":/Soulthirst/g,"cn":"嗜魂 饰布腰带"},
{"en":/Pacifism/g,"cn":"和平主义 翠绿珠宝"},
{"en":/Cold Steel/g,"cn":"冷钢 翠绿珠宝"},
{"en":/Clear Mind/g,"cn":"理智 钴蓝珠宝"},
{"en":/First Snow/g,"cn":"首秀 钴蓝珠宝"},
{"en":/Dreadbeak/g,"cn":"恐惧之喙 锈剑"},
{"en":/Indigon/g,"cn":"靛蓝之冠 灵主之环"},
{"en":/Mirebough/g,"cn":"魔藤 朽木之干"},
{"en":/The Rack/g,"cn":"绞刑架 朽木塔盾"},
{"en":/Lycosidae/g,"cn":"狼蛛 生皮塔盾"},
{"en":/Briskwrap/g,"cn":"荒途 扣环皮甲"},
{"en":/Foxshade/g,"cn":"狐毛铠 野性皮甲"},
{"en":/Hrimburn/g,"cn":"李姆本 羊皮手套"},
{"en":/Snakebite/g,"cn":"蝮吻 暗影护手"},
{"en":/Felltooth/g,"cn":"崩齿 玻璃利片"},
{"en":/Bloodplay/g,"cn":"血谑 锐利刺匕"},
{"en":/Taproot/g,"cn":"砥砺深根 伏击刺刃"},
{"en":/Last Resort/g,"cn":"终息 拳钉"},
{"en":/Wildslash/g,"cn":"野性狂爪 凿钉"},
{"en":/Al Dhih/g,"cn":"鬣犬之牙 远古战爪"},
{"en":/Dreadarc/g,"cn":"恐惧之镰 切割者"},
{"en":/Infractem/g,"cn":"穿云 猎魂之弓"},
{"en":/Chin Sol/g,"cn":"乱矢之弦 暗影弓"},
{"en":/Bloodboil/g,"cn":"沸血 珊瑚戒指"},
{"en":/Voideye/g,"cn":"虚空慧眼 潜能之戒"},
{"en":/Duskwing/g,"cn":"暗翼 海灵护身符"},
{"en":/The Retch/g,"cn":"呕吐 素布腰带"},
{"en":/Dying Sun/g,"cn":"逝日 红玉药剂"},
{"en":/Skirmish/g,"cn":"小会战 双锋箭袋"},
{"en":/Drillneck/g,"cn":"穿心 穿射箭袋"},
{"en":/Fragility/g,"cn":"脆弱 赤红珠宝"},
{"en":/Hotfooted/g,"cn":"狂奔 翠绿珠宝"},
{"en":/Pugilist/g,"cn":"迅击者 翠绿珠宝"},
{"en":/To Dust/g,"cn":"尘埃落定 钴蓝珠宝"},
{"en":/Frostferno/g,"cn":"冰狱 革兜"},
{"en":/Sunspite/g,"cn":"日怨 环带长靴"},
{"en":/Arborix/g,"cn":"阿伯瑞斯 暗影弓"},
{"en":/Oskarm/g,"cn":"欧斯卡姆 砂影手套"},
{"en":/Tombfist/g,"cn":"陵拳 钢影护手"},
{"en":/The Baron/g,"cn":"男爵 护面盔"},
{"en":/Heatshiver/g,"cn":"寒焰 革兜"},
{"en":/Ylfe Ban/g,"cn":"禁语 灵能之笼"},
{"en":/Deidbell/g,"cn":"丧钟 金面护盔"},
{"en":/The Gull/g,"cn":"鸥喙 祸鸦之面"},
{"en":/Skyforth/g,"cn":"空向 术士长靴"},
{"en":/Sundance/g,"cn":"日耀 环带长靴"},
{"en":/Ironweld/g,"cn":"铁芒 铁锻护手"},
{"en":/Wurmfist/g,"cn":"崩石 钢影护手"},
{"en":/Tulborn/g,"cn":"托沃崩 螺纹法杖"},
{"en":/Twyzel/g,"cn":"峡湾之星 贤者法杖"},
{"en":/Tulfall/g,"cn":"托沃卧 狂风法杖"},
{"en":/Goredrill/g,"cn":"血凿 剥皮刀"},
{"en":/Duskdawn/g,"cn":"宵晓 风暴长杖"},
{"en":/Wideswing/g,"cn":"阔斩 巨战斧"},
{"en":/Hiltless/g,"cn":"无击 残暴巨剑"},
{"en":/Trypanon/g,"cn":"裂颅 刚猛巨锤"},
{"en":/Reefbane/g,"cn":"灾祸之礁 鱼竿"},
{"en":/Praxis/g,"cn":"普拉克斯 海灵戒指"},
{"en":/Snakepit/g,"cn":"蛇穴 蓝玉戒指"},
{"en":/Sunblast/g,"cn":"日炎 饰布腰带"},
{"en":/Auxium/g,"cn":"奥术之符 水晶腰带"},
{"en":/Craghead/g,"cn":"岩头 锯齿箭袋"},
{"en":/Cragfall/g,"cn":"落石 锯齿箭袋"},
{"en":/Fireborn/g,"cn":"炎域 赤红珠宝"},
{"en":/Wildfire/g,"cn":"野火 赤红珠宝"},
{"en":/The Oak/g,"cn":"橡树 朽木鸢盾"},
{"en":/Ashrend/g,"cn":"拂烬 鹿皮外套"},
{"en":/Icetomb/g,"cn":"冰息 精制环甲"},
{"en":/Dusktoe/g,"cn":"迎暮 铁影长靴"},
{"en":/Redbeak/g,"cn":"赤红短刃 锈剑"},
{"en":/Mjölner/g,"cn":"沉默之雷 坚锤"},
{"en":/Fencoil/g,"cn":"绿藤 朽木之干"},
{"en":/Limbsplit/g,"cn":"断罪 柴斧"},
{"en":/Mordhau/g,"cn":"魔器 锈斑巨剑"},
{"en":/Dyadus/g,"cn":"龙凤吟 狱火之刃"},
{"en":/Rotgut/g,"cn":"伤胃酒 水银药剂"},
{"en":/Brawn/g,"cn":"筋骨强化 赤红珠宝"},
{"en":/Inertia/g,"cn":"惯性 赤红珠宝"},
{"en":/Mao Kun/g,"cn":"贼窝 危机海礁"},
{"en":/Augyre/g,"cn":"占星 虚影短杖"},
{"en":/Goldrim/g,"cn":"金缕帽 皮帽"},
{"en":/Allure/g,"cn":"魅惑 瓦尔战爪"},
{"en":/Scaeva/g,"cn":"食蚜 斗士长剑"},
{"en":/Rive/g,"cn":"裂隙 恐惧之牙"},
{"en":/Pyre/g,"cn":"燃焰 蓝玉戒指"},
];